Automattic/vip-go-mu-plugins

search/includes/classes/class-search.php

Enable mirrored queries for a small subset of queries, for testing purposes.
1. Sandbox site
1. View a few category pages
1. Ensure mirrored queries are recorded

Mirror the main taxonomy query on subset of sites

---

files/class-wp-filesystem-vip.php

This should handle the special case where $file_path *is* WP_CONTENT_DIR/$subfolder without a trailing slash. One notable case is when `true !== VIP_GO_ENV` and wp cli is making checks against `get_transport_for_path` for a plugin installation to `WP_CONTENT_DIR/upgrade` (without a trailing slash).
Example:
1. In a local environment with a fresh WP install (eg. v5.4.1) ...
1. git clone this patched repo into mu-plugins 
1. run a plugin install via WPCLI (e.g. `wp plugin install classic-editor`)
```
PHP Warning:  The `/var/www/my-cool-site/wp-content/upgrade` file cannot be managed by the `Automattic\VIP\Files\WP_Filesystem_VIP` class. Writes are only allowed for the `/tmp/` and …
```

Return true if subfolder path is missing trailing slash

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

For running a generic ES query (by $type) against VIP Search.
This will be used to provide 3rd party plugins (like es-wp-query) the ability to query ES directly without needing to worry about the internals of VIP Search.
This is a simple wrapper around the EP Indexable of $type, to hide the implementation details.
1. In code, run a query (need ES query) - `Automattic\VIP\Search\Search::instance()->query_es( 'post', $es_args );
1. Verify response is as expected

Add Search::query_es() helper

---

vip-helpers/vip-stats.php

Due to the way `stats_get_csv` method works, it introduces a read and update operation on each request.
When called frequently this results in a DB write each request, WP.com has added a caching layer to this function, so the cache values mirror that, as per: https://vip-svn.wordpress.com/plugins/vip-helper-stats-wpcom.php L180
- visit a site calling `wpcom_vip_get_post_pageviews`
- first page load will result in a DB read and write
- visit same page a second time with the PR added and the write should no longer occur

Add caching layer to stats

---

wp-cli/alloptions.php

Adds help line to remind how to disable autoload quickly.
1. Apply patch
2. See output in `wp vip alloptions find`

Add helper info for un-autoloading given option

---

README.md

In setting up the repository on my local environment and attempting to get the tests to pass, I thought that the README could use some additional information on git submodules.  I also refactored some of the ordering of the information so that it would flow better with a typical setup.
The goal is to get folks up and running and contributing faster.
View the `README.md` file and move through the information in order to achieve a fully installed repository, with all submodules, and unit tests passing.

docs: update readme with information on cloning submodules

---

README.md

The command provided in the readme `make lint` doesn't exist.
This change provides the correct npm based command.
In `master` run `make lint` and see the error message about not makefile.
In `correct-linting-command` see the correct documentation on running `npm run phplint`

fix: provide correct linting command

---

vip-helpers/vip-utils.php

Increase timeouts for POST requests since the flat 5s timeout causes some problems with ElasticPress and related WP-CLI commands.
1. Attempt to use `vip_safe_wp_remote_request` with a timeout over 5s. You should be limited to 5s and receive a `_doing_it_wrong`.
3. Attempt a POST request via `vip_safe_wp_remote_request` with a 15s timeout. You shouldn't get any warnings or have any issues.
4. Attempt a POST request via `vip_safe_wp_remote_request` with a 20s timeout. You should get a `doing_it_wrong` and have the timeout set to 15s.
5.  Attempt a POST request via `vip_safe_wp_remote_request` with a 30s timeout through WP-CLI. You shouldn't get any warnings or have any issues.
6.  Attempt a POST …

Increase vip_safe_wp_remote_request timeouts

---

vip-helpers/vip-caching.php

Add support for local development servers that do not have `$_SERVER['DOCUMENT_URI']` defined.
Fixes #976.
_Needs actual testing._
1. Create a setup where `$_SERVER['DOCUMENT_URI']` is undefined.
2. Check that function does what it was still meant to, once PR is applied.

wpcom_vip_maybe_skip_old_slug_redirect(): Improve compatibility with local setups

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Depends on: https://github.com/Automattic/vip-go-mu-plugins/pull/1608
Use the new timeout limits to increase the timeouts for bulk Elasticsearch operations.
1. Pull down PR.
2. `echo` the timeout before the return in `get_http_timeout_for_query`.
3. Run `wp vip-search health validate-counts`, should be 2.
4. Run `wp elasticpress index`, should be 30.
5. Revert `echo` change.

Increase timeouts for bulk ES operations

---

vip-cache-manager/vip-cache-manager.php

Group purge requests in batches of `CACHE_PURGE_BATCH_SIZE` and send the
batched purge requests to the `purge-batch` endpoint.
Batched requests are used only if the `PURGE_BATCH_SERVER_URL` constant
is defined in `wp-config.php`, otherwise the code falls back to the old
approach of sending individual requests to the `purge` endpoint.
When batched requests are supported, the number of URLs that can be
purged is increased to 4000, while it remains 100 in the fallback case.
1. Define `PURGE_BATCH_SERVER_URL` in your sandbox and point to a local HTTP server that dumps the body of the request.
2. Set the purge server type constant on you sandbox to `mangle`.
3. Edit a post on the test site and observe the output of …

Group purge requests in batches and send them to the `purge-batch` endpoint

---

vip-helpers/vip-utils.php

The `is_proxied_request()` checks whether the `A8C_PROXIED_REQUEST` constant is defined, before checking it is `=== true`.
The `is_proxied_automattician()` only checked whether the constant was truthy. It did not check if the constant was defined.
It makes sense for `is_proxied_automattician()` (the purpose of which is to check for both a proxied request AND that the currently logged-in user appears to be an Automattician) to use `is_proxied_request()` internally.
Note, that technically this slightly tightens the behaviour, from allowing a truthy definition (like `'a string'` or `1`) to requiring it to be a boolean `true`.
The constant may be defined in secret file as true, but [falls back](https://github.com/Automattic/vip-go-mu-plugins/blob/4511c412617032b71e820f7adc997c9358c35905/000-vi …

is_proxied_automattician: Check constant exists

---

000-vip-init.php

Require the `VIP_Encloseme_Cleanup` class and then call the `init()` method to get things going.
1. Checkout PR
1. Sandbox a site and copy changed files
1. Edit config file to include `define( 'ENABLE_VIP_ENCLOSEME_CLEANUP_ENV', true );`
1. Ensure `vip_encloseme_cleanup_hook` is in the list of events

Wire up the `_encloseme` meta cleanup class

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Add/increment a stat when a query is rate limited.
2. Run StatsD locally
3. Add somewhere it will run `define( 'VIP_STATSD_HOST', 'docker.for.mac.localhost' );`
4. Add somewhere it will run `define( 'VIP_STATSD_PORT', 8125 );`
5. Change `private static $max_query_count = 50000 + 1;` to `private static $max_query_count = 1;`
6. Run a search with QM/Debug Bar open for ElasticPress.
7. Keep refreshing the page while watching the queries.
8. Roughly half shouldn't go through ElasticPress.
9. Watch StatsD output - should include metrics for both the global stats, then metrics the site id and index name in them

Increment stat in statsd when query is ratelimited

---

search/includes/classes/class-queue.php
tests/search/includes/classes/test-class-queue.php

Add a gauge to keep track of queue size as it's processed.
1. Open wp shell and execute 2 and 3:
2. ` \Automattic\VIP\Search\Search::instance()->init();`
3. ` \Automattic\VIP\Search\Search::instance()->queue->schema->prepare_table();`
1. Pull down PR.
2. Open wp shell and execute 3 and 4:
3. ` \Automattic\VIP\Search\Search::instance()->init();`
4. ` \Automattic\VIP\Search\Search::instance()->queue->count_jobs( 'all', 'all' );`
5. Insert a number of rows into `wp_vip_search_index_queue`(make sure some have the 'post' object type) and …

Add queue size stat to statsd after processing a batch

---

000-vip-init.php

Brings over the latest changes from es-wp-query (fix for post_type in VIP Search mapping and fixing total records count in ES 7)
Offload a query with `es => true` and make sure it still works.

Update es-wp-query subtree

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

This issue was initially because of a bug that resulted in hanging when search strings were longer than a certain length.
That's been resolved, but we should still limit search string lengths. 
1. Search with a string longer than 255. It shouldn't be truncated.
3. Search with a string longer than 255. It should be truncated to 255 in general and also in ElasticPress query monitor/debug bar.

Truncate search strings to a reasonable length

---

search/includes/classes/class-search.php

Having multiple commands for search management doesn't make a lot of sense. 
Since the ElasticPress dashboard is also hidden, it makes sense to just alias the commands to vip-search.
1. Pull down PR.
2. `wp` shouldn't list elasticpress as a command.
3. `wp vip-search` should list all former elasticpress commands in addition to vip-search specific commands.

Alias elasticpress commands to vip-search

---

search/includes/classes/class-search.php

Our automatic query mirroring for testing es-wp-query has a bug in that it offloads search queries that also have a taxonomy component. Since search queries will always differ somewhat, we can't reliably validate the results and they should be omitted.
1. Apply PR
1. Run a taxonomy query on a site with offloading enabled (like `?s&tag=something`)
1. Everything should work fine

Only mirror tax query if it's also not a search query

---

search/includes/classes/class-search.php

Expands the list of sites that are mirroring taxonomy queries, for testing.
1. Checkout PR
1. On one of the listed sites, visit some taxonomy pages - `/category/something` and make sure everything looks good

Expand list of sites with mirrored tax queries

---

search/includes/classes/class-cache.php
search/includes/classes/class-search.php
tests/search/includes/classes/test-class-cache.php

To better handle and tweak any potential cache improvements it was decided to introduce `Automattic\VIP\Search\Cache` class. Currently, it doesn't do much except the Advanced Post Cache compatibility. 
That is, it disables APC for any EP-enabled query. APC disabling is pretty much a copy-pasta from es-wp-query adapters.
1. Add a breakpoint or a good old `exit('here')` in`Advanced_Post_Cache::posts_request` (advanced-post-cache/advanced-post-cache.php:109)
1. Load the test site with `?s=hello`
1. Verify that breakpoint/exit doesn't fire for the search query.
1. Verify that breakpoint/exit fires for any non-search query.

Stub Cache class, implement Advanced Post Cache compatibility.

---

tests/search/includes/classes/test-class-cache.php

Broken tests were committed to master. Just a minor issue involving global state.
1. `~$ ./bin/phpunit-docker.sh`
2. Tests will fail.
3. Pull down PR.
4. `./bin/phpunit-docker.sh`
5. Tests will pass.

Set proper global states for Automattic\VIP\Search\Cache_Test

---

logstash/class-logger.php

Currently, logs captured with `\Automattic\VIP\Logstash\Logger::log2logstash()` function within CLI containers don't get delivered to Elasticsearch Vip Go debug index. This happens due to CLI containers not yet running their tasks within a chroot. 
To fix that, the logs file could be forced to be placed within the `/chroot` directory. 
Thanks to @darthhexx for explaining this and providing a solution.
1. Make sure the `VIP_GO_ENV` is set to `true`.
1. Make sure you have the chroot implemented and `/chroot/tmp/` directory exists. 
1. Enter WP shell `wp shell` and run `\Automattic\VIP\Logstash\Logger::log2logstash(['severity' => 'info', 'feature' => 'test', 'message' => 'hello']);`
1. Confirm the …

Enable logs delivery to Elasticsearch debug index for CLI containers

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

So we can consistently check if query integration is enabled at all from multiple places.
This takes the logic from the filter, puts it in a new static function `is_query_integration_enabled()`, then updates the filter to instead use it.
The tests diff is pretty messy b/c the existing code got moved around.
No change in behavior is expected. Worth noting that I pulled out the code that was preventing query skipping when `vip_search_mirrored` was set on the WP_Query - that was old unused code from when we were trying to use EP for the query offloading via `ep_integrate`, and is no longer needed.
- n/a This change has relevant documentation additions / …

Split the ep_skip_query_integration filter into a reusable function

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Need a way to not index all post meta due to field count restrictions. An allow list set by the user seems to be a good way to about it so that only the meta they actually need are included.
2. `/bin/phpunit-docker.sh tests/search/test-class-search.php`
-----
1. Pull down PR.
2. Modify the post meta allow list via the`vip_search_post_meta_allow_list` filter in code.
3. Index posts using those meta and some others.
4. Query the freshly indexed posts and check that the only post meta indexed were the ones indicated in the allow list.
------
1. Pull down PR.
2. Set `FILES_CLIENT_SITE_ID` to one of the values in `Search::DISABLE_POST_META_ALLOW_LIST`
3. Index posts with any meta.
4. Query the …

Add allow list for indexing post meta

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Modifies how we load es-wp-query so that we only load it if query integration or query mirroring are enabled. This lets us enable Search on sites that are still using es-wp-query with other adapters, to get content indexed and evaluated before disabling the other adapter.
This refactors the es-wp-query loading logic into a standalone function with tests.
1. Run some regular queries, like `?s=test` (should not break anything)
1. With query mirroring and integration disabled, try offloading a WP_Query with `'es' => true` in the args...it should not hit ES
1. …

Only load es wp query when needed

---

search/includes/classes/class-cache.php
search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

To decrease alerting noise we should only alert when an index inconsistency persists across at least two intervals.

Only send inconsistency alert in IRC in case it spans over two healthchecks.

---

a8c-files.php

If the home_url is `https://...` and the site loads on `http://...`, we offload to Photon erroneously. The goal here is just to ensure that the image is indeed hosted on this site, so a simple host match should suffice.

Fixes filtering the photon domain with a scheme mismatch

---

000-vip-init.php
plugin-fixes.php

By default the WC log location is in the uploads directory, which is copied to the Files Service on VIP Go. The Files Service is not an appropriate location for logs because files are public and each new log line creates a new copy of the previous file along with the new line. We'll need to follow up with a way to clean up these files at end up in the /tmp directory.

Prevent Woocommerce logs from being written to the Files Service

---

security.php

We should return 403 for failed XMLRPC login attempts and 429 after the rate limit kicks in. By default the response codes is 200 in both of these situations. Using the proper codes will make it easier to limit abuse at various levels of the stack.
I tested by attempting to login via xmlrpc with the wrong username and password. The first attempts get the 403 response code. The 429 code correctly comes in after the rate limit has been exceeded. I haven't seen any issues with headers already being sent.
I also tested the regular login page just to make sure there were no new issues there and it still works as expected.

Return error codes for failed login attempts

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

The new `vip_search_post_taxonomies_allow_list` filter is a more convenient way to define which taxonomies are allowed to be indexed for a post. Compared to `ep_sync_taxonomies`, which is an array of taxonomy objects, the new filter is an array of taxonomy names, which is easier to add/remove from (no traversing the list to see if a taxonomy is or isn't already included).
1. Implement `vip_search_taxonomies_allow_list`- `add_filter( 'vip_search_taxonomies_allow_list, function( $taxonomies ) { return array( 'category' ); } );`
1. Index some content (can just edit a post)
1. Check that post in the index (`\ElasticPress\Indexables::factory()->get( 'post' )->get( $post_id )` - that document should …

Add vip_search_post_taxonomies_allow_list filter

---

alloptions-limit.php
search/includes/classes/class-search.php

Add OpsGenie Alerts for AllOptions! 😄
I tried testing this on my sandbox but there was a problem with this:
https://github.com/Automattic/vip-go-mu-plugins/blob/9c293f8325d1b4d51a15e947591e6cae4cc67a68/lib/utils/class-alerts.php#L280
The `is_int` check wasn't passing because it was a string.  
If I bypass that, I get this error (I removed the URL, IP_ADDRESS and PORT):
```
[12-Jun-2020 22:42:21 UTC] Warning: vip_safe_wp_remote_request: Blog ID 1: Requesting http://{IP_ADDRESS}:{PORT}/v1.0/alerts with method POST and a timeout of 1 failed. Result: O:8:"WP_Error":2:{s:6:"errors";a:1:{s:19:"http_request_failed";a:1:{i:0;s:78:"cURL error 7: Failed to connect to {IP_ADDRESS} port {PORT}: Connection …
```

Add opsgenie alerts for AllOptions

---

lib/class-vip-encloseme-cleanup.php

Add an additional IRC alert notification for when the cleanup job has ended a round of meta deletions.
1. Upload to sandboxed site
1. Add `define( 'ENABLE_VIP_ENCLOSEME_CLEANUP_ENV', true);` to `vip-config.php`
1. Ensure that the cleanup job is in the list of cron events.

Add ending IRC notification for encloseme cleanup

---

package.json
search/es-wp-query/adapters/vip-search.php

Our adapter for es-wp-query has some new fixes for term names and meta values.
This also adds a convenience `npm run update-subtrees` command b/c the actual command to update the subtree is tedious to remember/type.
1. Just do some basic searches. If you _really_ want, you can offload a WP_Query and specify `category_name` or a meta value, but nothing is relying on this yet and I've confirmed that stuff works.

Update es-wp-query subtree to latest

---

lib/class-vip-encloseme-cleanup.php

Reduce the interval between jobs from 20 minutes to 10 minutes.
During testing, we've found that 10000 post meta gets deleted in just about 1 minute so setting the interval to 20 minutes appears a little overkill.
1. Upload changed files to a sandboxed site
1. ensure `define( 'ENABLE_VIP_ENCLOSEME_CLEANUP_ENV', true );` is in `vip-config.php`
1. Ensure job is in events list and interval is set to 10 minutes

Reduce _encloseme meta cleanup interval time

---

lib/class-vip-encloseme-cleanup.php

Adds a random jitter element to stagger the cleanup start timing to prevent seeing a cascade of alerts when we add a new batch of sites to the cleanup list.
1. Upload changes to sandboxed site
1. ensure `define( 'ENABLE_VIP_ENCLOSEME_CLEANUP_ENV', true );` is in `vip-config.php`
1. ensure that the `vip_encloseme_cleanup_hook` action is scheduled to start between 1 to 10 minutes from "now"

Add random stagger to _encloseme meta cleanup start time

---

search/includes/classes/class-queue.php
search/includes/classes/class-queuewaittimejob.php
search/includes/classes/class-search.php

Added a stat to get the average time jobs have been sitting in the queue.
3. Add somewhere it will run `define( 'VIP_SEARCH_ENABLE_ASYNC_INDEXING', true );`
4. Apply PR.
5. Populate `wp_vip_search_index_queue` with rows with different `queued_time`s.
6. Execute: `SELECT FLOOR( AVG( TIMESTAMPDIFF( SECOND, queued_time, NOW() ) ) ) AS average_wait_time FROM wp_vip_search_index_queue WHERE 1`
7. `wp cron event schedule vip_config_sync_cron`
8. `wp cron event run vip_config_sync_cron`
9. Compare StatsD output for the gauge(should be something …

Add stat tracking for queue wait times

---

search/includes/classes/class-fieldcountgaugejob.php
search/includes/classes/class-search.php

Need to keep track of field counts in Elasticsearch so we can add an alert if someone exceeds it.
Added a custom interval so it can be adjusted easily. Chose to update each day right now as it shouldn't change too frequently with the post meta allow list for indexing in place.
- N/A This change has relevant unit tests (if applicable). _Don't see anything unit test would be able to test right now aside from invalid indexables, which is already tested to death_
3. Apply PR.
4. Get value of `\Automattic\VIP\Config\Sync::CRON_EVENT_NAME`, …

Added statsd gauge for post index current field count

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Previously, later filters (such as from client code) would override our code that prevented checks from running during indexing. We're not actually _disabling_ checking entirely, just temporarily skipping while indexing is happening, so this code path should not be filterable.
Tricky to test...need to think about that.

Fix index healthchecks during indexing

---

search/includes/classes/class-search.php
search/includes/classes/class-versioning.php
search/includes/classes/commands/class-versioncommand.php
tests/search/includes/classes/test-class-versioning.php
tests/search/test-class-search.php

CLI commands to manage index versions. There are 5 new commands added:
```
wp vip-search index-versions list <type>
wp vip-search index-versions add <type>
wp vip-search index-versions get <type> <version_number>
wp vip-search index-versions activate <type> <version_number>
wp vip-search index-versions get-active <type>
```
Not yet implemented is anything related to actually pulling data from the ES index itself (if it exists, doc counts, etc) or removing index versions, which can be part of a future PR.
1. First, ensure you're starting off with no indexes present, to represent existing production sites - `wp option delete vip_search_index_versions`
1. Then list them:
```
wp vip-search index-versions list post …
```

Add Search versioning CLI commands

---

search/includes/classes/class-search.php
search/includes/classes/class-versioning.php
search/includes/classes/commands/class-corecommand.php

Adds support for index versioning to the `wp vip-search index` command.
1. Add a new index version - `wp vip-search index-versions add post`
1. Build that new index - `wp vip-search index --setup --indexables=post --version=<new_version_number>`
1. Switch to the new index - `wp vip-search index-versions activate post <new_version_number>`
1. Try some searches - should get the same results as on the old index, but requests go to the new one
1. Try switching back to the previous version - `wp vip-search index-versions activate post <previous_version_number>`
1. Everything should work fine

Search: Add version support to index CLI command

---

search/includes/classes/class-queue.php

Since the testing period on async indexing is over, it should be on by default.

Async indexing now enabled by default

---

search/includes/classes/class-queue.php
search/includes/classes/queue/class-cron.php

The queue sweeper cron wasn't being registered properly and wasn't running.
Once it was running, it was apparent the stats were off.

Fix queue sweeper cron and stats

---

search/includes/classes/class-queue.php

StatsD::increment only increases by one. Need to use StatsD::update_stats directly to increase a stat by a different amount.

Use update_stats directly

---

jetpack.php

Upgrade Jetpack to 8.7.0.1
1. Visit Jetpack Dashboard and ensure version is reported as 8.7.0.1
1. Run `wp plugin list` and verify JP is 8.7.0.1
1. Test various site functionality (posting, reading) to ensure no issues

Upgrade to Jetpack 8.7

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Depends upon https://github.com/Automattic/ElasticPress/pull/44
Since the post meta allow list has been added, posts should not be re-indexed if meta not on that list are changed.
1. `./bin/phpunit-docker.sh tests/search/test-class-search.php`
------
1. Apply PR. Ensure https://github.com/Automattic/ElasticPress/pull/44 is applied as well.
2. Ensure VIP Search in enabled and you have a properly consistent index.
3. Add some post meta to a post that isn't on the allow list. The post should not have been re-indexed
4. Change the value of that meta. The post should not have been re-indexed.
5. Delete the meta. The post should not have been re-indexed.
6. Add some post meta to a post that is on the allow list. The …

Reindex post if post meta is in allow list

---

search/includes/classes/class-dashboard.php

Per docs for `remove_menu_page()`, menu changes should be done on the admin_menu hook:
> This function should be called on the admin_menu action hook. Calling it elsewhere might cause issues: either the function is not defined or the global $menu variable used but this function is not yet declared.
Example:
1. Go to `wp-admin`
1. Note that the EP submenu item still doesn't render

Search: Switch to admin_menu hook for altering menu

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

There was at least one instance where 'es' GET argument conflicted with client code, this PR should eliminate that by changing the argument to more specific `vip_search_enabled`
- [NA] This change has relevant documentation additions / updates (if applicable).
1. Make sure query integration is not enabled either via the constant or the option.
1. Go to a site, pass `?vip_search_enabled=true&s={SEARCH_TERM}`
1. Verify in QM that the query is offloaded

Search: update query integration argument from 'es' to 'vip_search_enabled' to eliminate the chances of conflicts with client code

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Structure of HA endpoint hostnames is changing slightly, so need to adapt our regex accordingly.
Tests FTW
Small change with test coverage, so manual testing is not necessarily needed (and doesn't really work locally because we don't have the right hostname formats).

Search: Support new HA endpoint structure in stat names

---

.circleci/config.yml

Simplify the build by removing the `sid` repo and using `default-mysql-client`. Props @seanosh and @jblz 
Just let tests run on Circle :)

Fix broken CircleCI tests

---

tests/test-cache-ttl-manager-rest.php

WP 5.5 adds a `_doing_it_wrong()` warning when `permission_callback` is missing from `register_rest_route()`.
See https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/.
1. Run tests using WP nightly, with WP_DEBUG enabled. See an error triggered.
2. Pull the fix, and re-run tests.

Add permission_callback to test-cache-ttl-manager-rest.php

---

tests/test-vip-mail.php

This test was breaking against the WordPress nightly build. Just updated the regex test to handle more line ending types.

Look for all line ending types in mail test for checking tracking

---

.circleci/config.yml
bin/download-wp-tests.sh
bin/install-wp-tests.sh

We don't currently test against nightly. Probably a good idea to do so though.
1. Install circleci cli locally
2. Run both of the added jobs via the circleci cli(e.g.: `circleci local execute --job php73-build-singlesite-nightly`)
3. Everything should run normally and all tests should complete successfully.

Add nightly builds for CI tests

---

.gitignore
query-monitor/output/Headers.php
query-monitor/output/Html.php
query-monitor/output/headers/overview.php
query-monitor/output/headers/php_errors.php
query-monitor/output/headers/redirects.php
query-monitor/output/html/admin.php
query-monitor/output/html/assets.php
query-monitor/output/html/caps.php
query-monitor/output/html/conditionals.php
query-monitor/output/html/db_callers.php
query-monitor/output/html/db_components.php
query-monitor/output/html/db_dupes.php
query-monitor/output/html/db_queries.php
query-monitor/output/html/debug_bar.php
query-monitor/output/html/environment.php
query-monitor/output/html/hooks.php
query-monitor/output/html/http.php
query-monitor/output/html/languages.php
query-monitor/output/html/logger.php
query-monitor/output/html/overview.php
query-monitor/output/html/php_errors.php
query-monitor/output/html/request.php
query-monitor/output/html/theme.php
query-monitor/output/html/timing.php
query-monitor/output/html/transients.php

In #1683, the Query Monitor plugin was changed from being a git submodule to a standard set of files. The version of the plugin was not changed.
However, the `output` directory was missing from #1683, due to a rule in the `.gitignore` file.
This PR adds an exception to that rule for the `query-monitor/output` directory, and adds the missing directory itself.
Without this fix, the original report (#1683) says that "Query Monitor has no output ( admin ) or a critical error is thrown ( front-end )."
This didn't show-up at the time of the merge three days ago, as (fortunately) there was [no deploy](https://github.com/Automattic/vip-go-mu-plugins/pull/1683#issuecomment-663731121).
Fixes #1684.
1. Compare …

QM: Re-add previously ignored output directory

---

files/class-api-cache.php
tests/files/test-vip-filesystem-api-cache.php

The current file service API cache uses the file base name as the cache key but this causes problem when a file is uploaded with the same name but on a different path. Functions like `file_exist` will return `true` even though the file is on a different path.
1. Upload changes to a sandboxed site
1. `wp --allow-root shell`
1. Upload a new file: `file_put_contents( 'vip://wp-content/uploads/path1/test.txt', 'test' );`
1. `file_exist( 'vip://wp-content/uploads/path2/test.txt' );`
1. Verify that `file_exist` call returns `false`.

Use full file path for file service caching

---

search/includes/classes/class-versioning.php
search/includes/classes/commands/class-versioncommand.php

Previously, adding a new index version only registered it with VIP Search - it didn't actually create it in Elasticsearch until you ran the `index` command. This changes that behavior so that the index (with mapping) is created when the new version is registered.
This will simplify things and prevent user error/confusion. It also ensures the index is there so we can start syncing changes to it immediately without causing problems.
A full indexing is still required - content is not automatically indexed.
1. Make sure you are running https://github.com/Automattic/vip-go-mu-dev/pull/34 and have rebuilt the env (`lando rebuild --yes`) to expose ES to your local machine.
1. `curl …

Search: Create the new index in ES when a version is registered

---

.circleci/config.yml
package.json

We currently have several lint commands, primarily 1 for checking PHP syntax, and another for checking PHPCS rules for the diff. This combines those into an easier-to-type single command - `npm run lint`.
- n/a This change works and has been tested on a Go sandbox.
1. `npm run lint` - should run both `./bin/php-lint.sh` and `npm run phpcs:changed:remote`

Add unified lint command

---

search/includes/classes/class-queue.php
search/includes/classes/class-versioning.php
search/includes/classes/queue/class-cron.php

Reduce the number of statsd calls by not repeatedly incrementing add to queue stats by 1. Instead, increment by the number added to the queue so it's always only 1 call.
1. Use https://github.com/Automattic/vip-go-mu-dev
2. Apply PR.
3. `~$ lando logs -f` to see statsd output
4. `~$ lando wp shell`
5. `\Automattic\VIP\Search\Search::instance()->queue->record_added_to_queue_stat(3000, 'post');`
6. Added to queue stat should be add up to 3000 in statsd output.
7. `\Automattic\VIP\Search\Search::instance()->queue->queue_objects( array( 0, 1, 2, 3, 4, 5) );`
8. Added to queue stat should add up to 6.
9. `~$ lando wp vip-search queue stress-test`
10. Added to queue stat should add up to the number outputted(e.g.: …

Reduce add to queue stat usage

---

search/includes/classes/class-health-job.php
search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php
tests/search/includes/classes/test-class-healthjob.php

Now that index versioning is supported, we need to monitor the consistency of the various versions. This PR adds version support to `wp vip-search health validate-counts` and the cron job that monitors counts.
1. Make sure you have at least an additional index version (`lando wp vip-search index-versions list post`)
1. Run `lando wp vip-search health validate-counts` - if there are no inconsistencies, there is no difference
1. Introduce an inconsistency by adding a new version (but not running the index command for it) - `lando wp vip-search index-versions add post`
1. `lando wp vip-search health validate-counts` …

Search: Add version support to document count validation job and command

---

search/includes/classes/commands/class-corecommand.php

Fix for an undeclared $search variable which is needed for the EP network mode check.
1. Execute `wp vip-search index --network-wide --version=2 --indexables=post`, it will fail with a PHP error
1. Execute the same command again, it will show the expected error message

Fix undeclared variable

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php
vip-helpers/vip-caching.php
vip-helpers/vip-wp-cli.php

Improve memory management for the command `wp vip-search health validate-contents`.
On very large sites with hundreds of thousands of documents, this command would take increasingly amounts of memory (e.g, around 4 GB for 100k documents). This is mostly due to non-flushing cache and logs, so this PR tackles them:
- Disable Elasticpress query log
- Disable WP DB query log
- Flush WP object cache after every validation block
n/a This change has relevant unit tests (if applicable).
n/a This change has relevant documentation additions / updates (if applicable).
1. Check out this PR
1. Check out the required PR for ElasticPress submodule: https://github.com/Automattic/ElasticPress/pull/48
1. Run `wp vip-search …

Search: Improve memory management for validate_contents

---

000-vip-init.php

Sitemap changes are causing issues in WordPress 5.5. 
We'll turn them off globally for now.

Disable core sitemap xml

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

The protected meta allow list from ElasticPress should be overridden to use our post meta allow list for ease-of-use.
1. Apply PR.
2. `lando test tests/search/test-class-search.php`

Override ep prepare meta allowed protected keys

---

tests/vip-helpers/test-wpcom-vip-set-image-quality-for-url.php
vip-helpers/vip-media.php

PHPCompatibility flagged the original instance of the code as:
> The "result" parameter for function parse_str() is missing. Passing this parameter is no longer optional. The optional nature of the parameter is deprecated since PHP 7.2 (PHPCompatibility.FunctionUse.OptionalToRequiredFunctionParameters.parse_str_resultSoftRequired)
As per the `parse_str()` [documentation](php.net/manual/en/function.parse-str.php), "using this function without the result parameter is highly DISCOURAGED and DEPRECATED as of PHP 7.2."
To ensure that the fix didn't change the behaviour, I wrote a bunch of unit tests before making the change, and then made the change, and the unit tests still passed.
As an aside, the unit tests revealed some non-ideal values being returned, to which I've left comments on the …

Fix parse_str() missing parameter deprecation

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Added post field for compatibility.
1. Apply PR.
2. Replace `add_filter( 'ep_prepare_meta_allowed_protected_keys', array( $this, 'filter__ep_prepare_meta_allowed_protected_keys' ), PHP_INT_MAX, 2 );` with `add_filter( 'ep_prepare_meta_allowed_protected_keys', array( $this, 'filter__ep_prepare_meta_allowed_protected_keys' ), PHP_INT_MAX );`
3. `lando test lando test tests/search/test-class-search.php`
4. It should error.
5. Reset to PR changes.
6. `lando test lando test tests/search/test-class-search.php`
7. It should not error.

Reenable ep post meta filter override

---

search/includes/classes/commands/class-healthcommand.php

Support `--network-wide` parameter for `vip-search health validate-counts` commands. If the parameter is provided, these commands will show the stats for all sites of the network, instead of only the main site.
This is not compatible with `--version`, as every subsite can have a different index version.
1. Execute on a multisite site: `wp vip-search health validate-counts --network-side`
1. Ensure stats for all subsites are shown

Search: Support --network-wide in validate-counts commands

---

files/class-api-client.php
files/class-vip-filesystem-stream-wrapper.php

It was highlighted that there's potential for the files stats to be inaccurate when uploading files due to PHP's built in file stat cache. We had a call to `clearstatcache()` added but that really only affected new files. This ensures that the stat cache is cleared for _every_ upload.
Not really sure how to effectively test this but I basically sandboxed a site and ensured that files are uploaded properly to the file service.

Move `clearstatcache` call into the client class

---

000-vip-init.php
lib/feature/class-feature.php

Enables the comment type batch jobs for 10% of sites. We'll ramp this up over time.
1.  Ensure dev env is on 5.5
1. Edit mu-plugins/lib/feature/class-feature.php to set the `comment_type_update_cron` percentage to 1 (to ensure it runs)
1. `lando wp option delete finished_updating_comment_type` to reset the cron job
1. Visit a wp-admin page
1. `lando wp cron-control events list | grep wp_update_comment_type_batch` - should report that the cron job is scheduled
1. Let that cron job run
1. Edit mu-plugins/lib/feature/class-feature.php to set the …

Enable comment type cron job for percentage

---

000-vip-init.php

VIP sites should not be staging in Jetpack by default.

Don't set sites as staging in Jetpack regardless of env type

---

lib/feature/class-feature.php

Increases number of sites running the comment type update batch job to 75%

Bump comment type job percentage to 75%

---

search/includes/classes/class-search.php

Once we go over Elasticsearch 7.5, admin notices about being over the compatible version will show.
We should hide these since we should never be above the version we support since we control the full stack.
1. Open wp-admin in Lando. You should see the above compat admin notice.
2. Apply PR.
3. The notice should no longer appear.

Disable above compat admin notice for EP

---

000-vip-init.php
lib/feature/class-feature.php

Have ramped up to 75%, so now going to 100% by removing all the disabling code
Since this just removes the block (ramping up to 100% of sites, from 75%), this has all been tested before, but still should poke around the site to ensure no errors are reported.

Enable comment type update cron job for all sites

---

001-core/privacy.php

WordPress 5.4 changed how privacy exports managed the post meta data for generated ZIP files.  This was done in https://core.trac.wordpress.org/changeset/48127 and it broke VIP Go's overrides.
This PR should bring the VIP Go functionality up to date with the changes in the core functionality.
Example:
1. Visit a site's export `/wp-admin/export-personal-data.php` on a WP 5.4 or higher install
1. Try to export data, and see it fails.
1. Patch
1. Try again and see if a ZIP is downloaded.

Updates VIP GO Privacy Exports for 5.4

---

lib/feature/class-feature.php
tests/lib/feature/test-class-feature.php

The `FILES_CLIENT_SITE_ID` constant is not necessarily defined, such as in custom local dev environments, so can't use it directly...needs to be wrapped.
Fixes #1730
1. Remove any reference to `define( 'FILES_CLIENT_SITE_ID', ... )` anywhere
1. Run a check in the theme's functions.php - `\Automattic\VIP\Feature::is_enabled( 'foo' )` - this should not throw any undefined constant warnings

Features: Use a site_id() function instead of defaulting to FILES_CLIENT_SITE_ID

---

files/class-api-client.php
tests/files/test-api-client.php

We store the path in the cache without the leading slash but the API returns the path with it. We need to remove the leading slash, otherwise the cache doesn't get cleared and we end up with stale data (e.g. filesize is incorrect).
1. `wp shell`
1. `file_put_contents( 'vip://wp-content/uploads/yay1.txt', 'hello' )`
1. `filesize( 'vip://wp-content/uploads/yay1.txt' )` <= should return `5`; without the fix, returns `0`.

Fix file stats cache reset on upload

---

search/includes/classes/class-search.php
search/includes/classes/commands/class-corecommand.php
search/includes/classes/commands/class-versioncommand.php

Currently, it's too easy to destroy an index inadvertently. E.g. a bad copy-paste with `--setup` flag does not require confirmation. Same with `put-mapping`.
To address that we're introducing `CoreCommand::confirm_destructive_operation()`, which prints a nice prompt for those types of operations.
If `--skip-confirm` is passed, no prompt will be displayed/

Search: implement a confirmation prompt before executing destructive CLI commands

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php

Currently, the only way to address index inconsistencies is to re-index the content. Re-indexing also doesn't resolve the issue where something is in the indexed, but the object was deleted in a way that our hooks didn't catch.
This PR addresses that by introducing a new static method Health::reconcile_diff which addresses a batch on inconsistencies (either add to the index queue or delete from the index.
By default, try to correct the inconsistencies, but allow to skip that step via `--do-not-heal` flag.
Here's how it looks:
First run:
```
$ wp vip-search health validate-contents
Validating posts 1 - 500...❌
Warning: Inconsistencies found!
Reconciling the differences!
type,id,issue
post,1,extra_in_index
```
Second run:
```
$ wp vip-search health validate-contents 
Validating posts 1 - …
```

Search: Add Health::reconcile_diff method to allow for the correction of index inconsistencies.

---

000-vip-init.php

WordPress 5.5.1 [won't allow to set custom environment types](https://make.wordpress.org/core/2020/08/27/wordpress-environment-types/), so our previous code to set it matching the VIP environment name won't work.
This PR recovers a previous implementation ( #1703 ) where we map "production" and "develop" VIP environments to "production" and "development" environment types, assigning the "staging" type to any other.
1. Execute `wp_get_environment_type()` in a wp shell
1. For production sites it should return "production", for develop sites it should return "development", and for the rest "staging"

Adjust environment type to the ones allowed in WP 5.5.1

---

.gitmodules

checkout the `Automattic/Cron-Control` with https instead of ssh.  This is consistent with all other submodules, and has the advantage of checkout without github login.
Tested with `git submodule update --recursive --init --jobs 8` on a newly cloned repo and it successfully checkout all submodules.

checkout Cron-Control submodule over https

---

search/includes/classes/commands/class-healthcommand.php

This isn't a useable command, it's just a helper function, so marking it as `private` so WP-CLI doesn't register it.
1. `lando wp help vip-search health` - should print `render_contents_diff` as a subcommand
1. `lando wp help vip-search health` - should _not_ print `render_contents_diff` as a subcommand
1. `lando wp vip-search health validate-contents` - just to make sure the command still works as expected

Search: Set render_contents_diff function to private so it isn't registered as a command

---

search/includes/classes/class-versioning.php
search/includes/classes/commands/class-versioncommand.php
tests/search/includes/classes/test-class-versioning.php

This makes the previous index alias functionality live by normalizing the index version on internal functions that use it along with the `wp vip-search index-versions` CLI commands.
Once this is merged, we can add `--network-wide` support to the `index-version` commands, and we'll be able to manage versions on multisites easily.
1. Make sure your site has a few index versions - `lando wp vip-search index-versions add post` (make sure you have 3)
1. Now activate the next version: `lando wp vip-search index-versions activate post next` - it should succeed
1. `lando wp vip-search index-versions list post` should now show the new version as active
1. Switch back to the previous version ``lando wp …

Search: Hook up index version aliases to functions and CLI commands

---

search/includes/classes/class-search.php
search/includes/classes/commands/class-documentcommand.php

Adds WP CLI command to get a specific document. This helps us debug VIP search functionality.
```
wp vip-search documents get post 1
```
Example:
1. `lando wp vip-search documents get post 1`
1. Verify a document is returned
1. Add a new post and get it's ID
1. `lando wp vip-search documents get post <new-post-id>`
1. Verify a document populated by the new data is returned.

Adds WP CLI command to get a specific document

---

performance/do-pings.php

The new (pending) version of Cron Control utilizes the `pre_*` hooks to hook into cron, allowing for a much cleaner way to move cron to its own table. When that plugin is active, we hook on `pre_schedule_event` which short-circuits the schedule_event function before we disable do_pings.
Here we're disabling on both pre_schedule_event as well as schedule_event for backwards compatibility.

Disable do_pings on sites that use `pre_schedule_event`

---

vip-helpers/vip-stats.php

Fixes #1755 - sets the default `$end_date` to the site's local date.
1. Follow steps to reproduce the issue described in #1755.
1. Run `wpcom_vip_top_posts_array(1)` between midnight UTC and midnight in the site's local time.
1. Verify a non-empty array is returned.

Pass local date to wpcom_vip_top_posts_array()

---

performance/do-pings.php

Fixes the disabling of do_pings via pre_schedule_event. The new filter
takes an extra argument, so we can't use the exact same function. Here
we're wrapping the disable_pings function in a helper to normalize
the arguments.
Example:
1. Ensure cron-control-next is enabled on the test site
1. Publish a new post
1. Confirm do_pings event was not scheduled
The easiest way I've found to verify this is to dump the values to the error log with something like `error_log( var_export( $event, true ) )`.
cron-control-next is important because that's where we're using the pre_schedule_event filter.

Disable do_pings via pre_schedule_event

---

search/includes/classes/class-versioning.php
search/includes/classes/commands/class-corecommand.php
search/includes/classes/commands/class-versioncommand.php

Adds `--network-wide` support to the `wp vip-search index-versions` `add` and `activate` commands, for working with index versions on multisites. This lets us create a new index version, index the content, then activate it across all subsites.
```
wp vip-search index-versions add post --network-wide
wp vip-search index --network-wide --version=next --indexables=post
wp vip-search index-versions activate post next --network-wide
```
There are other commands that don't yet support `--network-wide` (`delete`, `get`, `list`, `get-active`), but those are lower priority so I don't want to hold up this PR for them.
This makes a change to how index versions are stored - instead of using a site-wide option on multisites in network mode, each index version list is stored per-site, in regular blog …

Search: Add --network-wide support to index version commands

---

search/es-wp-query/adapters/vip-search.php

Use `post_title.raw` rather than `post_title.` 
Since `fielddata` is off by default for text fields making sorting, aggregations, scripting, etc... on `post_title` not possible due to various issues that would present. 
The `raw` keyword field is an easy workaround for that issue and still lets `post_title` be used properly as an inverted index.
1. Add to themes functions.php:
```
add_action( 'pre_get_posts', function( $q ) { 
$q->set( 'es', true );
} );
```
2. Visit `http://vip-go-dev.lndo.site/wp-admin/edit.php` or equivalent.
3. You will get no results and an Elasticsearch error.
4. Apply PR.
5. Visit `http://vip-go-dev.lndo.site/wp-admin/edit.php` or equivalent.
6. It will load as you'd expect.

Update es-wp-query to latest Automattic/es-wp-query

---

search/includes/classes/class-search.php

There are a few other behaviour-affecting querystring values that customers and Automatticians can use, and they all use hyphens.
For consistency with them, and a general understanding that hyphens are more frequently used in URLs than underscores anyway, this change updates the `vip_search_enabled` querystring key to `vip-search-enabled`.
The GitHub search didn't reveal any other files using it, so I'm not sure if there are any tests for this querystring feature.
Unknown.
I noticed that the QS value is not checked; the presence of the key is enough to enable the ES queries, so if someone did `vip-search-enabled=false` (as might be reasonably expected given the `=true` part of the docs), then they would get an …

Search: Change vip_search_enabled QS to use dashes

---

001-core/privacy.php
tests/001-core/test-privacy.php

On the login page, display a link to the Automattic Privacy Policy page so users better understand what information we collect, use, and share, and what choices they have with respect to that information.
It hooks in to core's Privacy Policy page feature. If a customer has a privacy policy page set, we do not display the Automattic one. If a customer does not, we fall back to the Automattic one.
Note that this is currently disabled by default so no changes are expected to ViP sites on deploy. To enable for a site, we can add:
```
add_filter( 'vip_show_login_privacy_policy', '__return_true' );
```
If a customer would prefer never to show ours:
```
add_filter( 'vip_show_login_privacy_policy', '__return_false', PHP_INT_MAX );
```
Please make sure the items below have been covered before …

Add link to VIP (Automattic) Privacy Policy on the login page

---

search/includes/classes/class-search.php

This particular site was included in meta allow bypass list as an interim measure. This should not be needed anymore. 

Search: remove 2341 from meta allow bypass list

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Currently, we just silently not load our bundled `es-wp-query` or another adapter is loaded. This allows us to fail gracefully, but, on the flip side, it may lead to not-that-obvious bugs, where a different adapter is loaded and the queries just don't return correct results. 
This PR adds `_doing_ot_wrong` notices for the scenarios described, so it's easier to spot during debugging and developing.
1. Activate a version of `es-wp-query` via Plugins UI or `wp plugin activate`
1. Open Query Monitor and verify a notice about already loaded es-wp-query is present.
1. De-activate `es-wp-query` and verify that the notice is gone.

Add notices when trying to load es-wp-query or vip-search adapter, but either another copy of es-wp-query or a different adapter is loaded

---

logstash/class-logger.php
search/includes/classes/class-search.php

Detect errors (HTTP code error + error section in the response) and warnings (HTTP header) in Elasticsearch responses and log them to logstash, so they get more visibility and we don't depend on someone looking at Elasticsearch logs.
1. Enforce some error/warning in Elasticsearch queries (e.g., adding `orderby` on some text field, or adding `'_source' => [ 'exclude' => 'meta.*' ]`.
1. In the local dev environment it should appear in `debug.log`. In a sandbox it should appear in logstash under features `vip_search_query_error` or `vip_search_es_warning`

Log Elasticsearch warnings and errors

---

search/includes/classes/class-search.php

In #1770 we added logging for `Warning` headers in Elasticsearch responses. It turns out that if there are several of them, then `wp_remote_retrieve_headers()` will return an array with all of them instead of a string. This PR adds support for that case.
1. Run `wp vip-search index-versions add post` (which triggers several warnings, at least in the local dev environment)
1. Verify that all warnings are shown, and there are no errors about array->string conversion

Support multiple Warning headers on Elasticsearch responses

---

lib/class-apc-cache-interceptor.php

Offloading the subsite information in the network admin has the side effect of showing stale data after clicking save on a site. (i.e. from /wp-admin/network/site-info.php?id=<id>). The form still saves properly and if you refresh the page, you see the correct thing. It's kind of suboptimal though.
To counteract that, we're disabling apcu for these keys when you're in the network admin. That way, you still get the data directly from memcached in the screen when you could be updating this data, but in all other cases, you get the apcu offloaded data.
Example:
1. Go to wp-admin > My Sites > Network Admin -> Sites
1. Click Edit on a site record
1. …

APC Cache Interceptor: Don't offload subsite information in network admin

---

search/docs/versioning.md
search/includes/classes/commands/class-versioncommand.php

There are still four vip-search commands that don't support `--network-wide` parameter (get, get-active, list, delete). This PR addresses them.
1. Create a multisite testing site
1. Add a couple of index versions with `vip-search index-versions add post --network-wide`
1. Run `vip-search index-versions get post active --network-wide` and verify that the active version is returned for all sites
1. Run `vip-search index-versions list post --network-wide` and verify that all index versions are returned for all sites

Add --network-wide support for pending search commands

---

security.php

Allow client sites to customize the login limit thresholds
1. Checkout this PR
1. Filter `wpcom_vip_ip_login_threshold` to return `0`
1. Confirm trying to login gets the rate limited error message
1. Filter `wpcom_vip_ip_username_login_threshold` to return `0`
1. Confirm trying to login gets the rate limited error message
1. Remove filters
1. Confirm trying to login gets no rate limited error message
You can also experiment with various other values to show that a given username is rate limited, but other usernames from the same IP have a different rate limit.

Add login limit threshold filters

---

.circleci/config.yml

Speeding up git checkout for circleCI jobs. 
EDIT: turns out avoiding to use CircleCI to use it's default git+ssh, but installing one locally is way faster.
Check core tests jobs in circle CI

Speeding up git checkout for circleCI jobs

---

.huskyrc.json

The pre-push hook was previously firing `npm run phpcs:changed:local`, which only checks against non-committed changes. 
Since the pre-push hook is for checking what you're trying to push(which are committed changes) this is incorrect.

Switched to use npm run phpcs:changed:remote

---

search/includes/classes/class-queue.php

Previously the arguments for a WP_Error were incorrect. Due to the way sprintf works, the code was perfectly valid but would only ever error with `Indexable not found for type invalid-indexable` rather than display the actual indexable slug that failed to be found.
The arguments have been corrected.
1. `lando wp shell`
2. Execute `\Automattic\VIP\Search\Search::instance()->queue->get_index_version_number_from_options( 'fake-slug-ae34f' );`
3. You should see a WP Error with `Indexable not found for for type invalid-indexable` for a code with no message.
4. Exit the shell.
5. Apply PR.
6. Execute `\Automattic\VIP\Search\Search::instance()->queue->get_index_version_number_from_options( 'fake-slug-ae34f' );`
7. You …

Fix arguments for WP_Error invalid-indexable for queue

---

search/includes/classes/class-queue.php
search/includes/classes/class-versioning.php
tests/search/includes/classes/test-class-queue.php

Presently, deleting an index version doesn't stop the queued job from continuing to be processed. This is pretty inefficient, so we should just delete all jobs for the indexable slug / index version that was deleted.
1. Apply PR
2. `lando test --stop-on-failure tests/search/includes/classes/test-class-queue.php`
----------------------
1. Populate the `wp_vip_search_index_queue` table with various jobs with different index versions.
2. Apply PR.
3. `lando wp shell`
4. Execute `\Automattic\VIP\Search\Search::instance()->queue->delete_jobs_for_index_version( <indexable slug>, <index version> );
5. Verify that all the jobs that should be removed are gone and no others.

Clear queue of related jobs on index version delete

---

search/includes/classes/class-queue.php

Presently there's no handling for if the index version has been deleted before the jobs are processed from the queue.
They should not be re-indexed and they should not count towards index rate limiting.
1. Apply PR.
2. Schedule a process jobs cron job for the queue that contains a list of valid IDs with a non-existent index version number.
3. Run the cron job.
4. There should be no warnings or errors from the process and the index rate limiting count shouldn't increase.

Skip indexing job from queue if index version not found

---

search/includes/classes/commands/class-versioncommand.php

WP Errors  when adding an index version couldn't be handled because `$result` doesn't exist.
Switched `$result` to `$new_version` to make it work.
1. Make the `add_version` function return a WP_Error.
2. Execute `lando wp vip-search index-versions add post`
3. You'll get a fatal error without the output of the underlying WP_Error. The logs will point you to `$result->get_error_message()`.
4. Apply PR.
5. Execute `lando wp vip-search index-versions add post`
6. The WP_Error will be handled properly and the error will be printed to the terminal properly.

Replace $result with $new_version since $result doesn't exist

---

jetpack.php

Prepare the PR to roll out the new default Jetpack version
* Make sure you dont have pinned Jetpack version - VIP_JETPACK_PINNED_VERSION
* Check Jetpeck version
* change the code to the pr
* See the jetpack version is updated

Jetpack 9.0 as new default

---

search/includes/classes/class-queuewaittimejob.php
search/includes/classes/class-search.php
tests/search/test-class-search.php

Sends an alert to cantina channel if the indexing queue gets stale.
Couldn't figure that out:(

Search: implement stale queue alerts

---

search/includes/classes/commands/class-corecommand.php

This PR combines several performance improvements when doing bulk indexing:
- Implement ID ranges instead of relying on OFFSET when doing pagination. OFFSET gets progressively slower on larger datasets, using ID ranges provides consistent and fast results.
- Term preparation refactoring
- date_18in usage improvements (reduce the number of total calls)
https://github.com/Automattic/ElasticPress/pull/66

Search: Update ElasticPress submodule to f0ffd49

---

search/includes/classes/class-queue.php
search/includes/classes/class-search.php
search/includes/classes/class-versioning.php
tests/search/test-class-search.php

We have fade out per site metrics due to the high volume of keys needed. 
This should be merged after https://github.com/Automattic/vip-go-mu-plugins/pull/1811 (to avoid conflicts)
This is removal of some stats recording, so basically checking indexing, posts changes and such works on vip-search enabled site.

search-statsd: cleanup per site metrics

---

search/includes/classes/class-queue.php
tests/search/includes/classes/test-class-queue.php

`scheduled` jobs are those that have been sent to a cron job, but jobs can also get stuck `running` if they are picked up but never completed (like when process is interrupted), so we need to check for both.
- n/a This change has relevant documentation a`dditions / updates (if applicable).
There is test coverage, so manual testing not strictly necessary. But could be done like this:
1. Insert a row into the `wp_vip_search_index_queue` table with a status of `running` and a `scheduled_time` in the distant past
1. Let the sweeper cron job run
1. Ensure the job has now been processed

Search: Consider stuck `running` jobs as deadlocked too

---

search/es-wp-query/adapters/vip-search.php

We were mapping the user_nicename field incorrectly - @rebeccahum has fixed this in https://github.com/Automattic/es-wp-query/pull/10
- N/A This change has relevant unit tests (if applicable).
- N/A This change has relevant documentation additions / updates (if applicable).
1. Offload an author page main query to ES
1. Ensure results are returned

Search: Update es-wp-query subtree with fix for user_nicename field

---

search/includes/classes/class-search.php
search/includes/classes/commands/class-corecommand.php
search/includes/classes/commands/class-healthcommand.php

This is not exactly a memory leak, it's just a log of all Elasticsearch queries that ElasticPress stores for debugging purposes. If not explicitly defined with `EP_QUERY_LOG`, it gets automatically enabled when `WP_DEBUG` is set to true.
But for long executing CLI commands it doesn't make sense to store this log even if debugging is enabled, as it takes a lot of memory and it's not being used for anything.
1. Check out master
1. Try to index a big site on a Go sandbox (WP_DEBUG will be set to true, don't enforce it to false). It will leak memory
1. Check out this PR.
1. Index the same site again. It won't leak any memory (unless it's a problem with the site code)

Solve a memory leak in ElasticPress when WP_DEBUG is enabled

---

.circleci/config.yml

Composer 2 was released recently and has some issues with the version of our PHPCS scripts. The installer version fails. Bumping up to a newer version then causes OOM errors, which needs investigation before we re-enable.
CI should should pass tests again.

Downgrade to Composer v1

---

lib/class-apc-cache-interceptor.php

The array and string offset access syntax using curly braces is deprecated as of PHP 7.4
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.array-string-access-curly-brace
This will begin throwing a fatal error in PHP 8
https://github.com/php/php-src/blob/107962208a19d8b6dc1a190cb25fc37614411e71/UPGRADING#L198

Remove curly braces syntax for array access

---

akismet.php
akismet/akismet.php
akismet/changelog.txt
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/stats.php

> Release Date – 22 October 2020
>
> Show the “Set up your Akismet account” banner on the comments admin screen, where it’s relevant to mention if Akismet hasn’t been configured.
> Don’t use wp_blacklist_check when the new wp_check_comment_disallowed_list function is available.
https://wordpress.org/plugins/akismet/

Akismet 4.1.7

---

.circleci/config.yml
composer.json
composer.lock

Which supports both Composer 1 and 2.
Fixes this:
```
Problem 1
- dealerdirect/phpcodesniffer-composer-installer is locked to version v0.6.2 and an update of this package was not requested.
- dealerdirect/phpcodesniffer-composer-installer v0.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```
See https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/119
Previously #1829

Bump phpcodesniffer-composer-installer to 0.7

---

phpcs.xml.dist

`.git/*` is a regular expresion so . matches anything. In my case whne I
have all the code under git/repo it would exclude the whole repo.
1. clone repo to `git` folder
1. run `npm run phpcs`
1. see all the errors (files not being ignored)

Fix phpcs exclusion missconfiguration

---

.circleci/config.yml
README.md
bin/utils.sh

Looking into new core test failure:
```
in ests/phpunit/tests/xmlrpc/wp/newComment.php
Cannot modify header information - headers already sent by (output started at /tmp/wordpress-develop/tests/phpunit/includes/bootstrap.php:122)
```
Our code adds a header on login failure, but the test isn't setup to work with headers (or http requests in general). The authentication fails even without our plugin and is expected in the test. So I am adding that test class to ignored ones. 
Check the circleCI build pipelines

Fix Failing core tests

---

vip-plugins/vip-plugins.php

This PR is backwards compatible and will continue to use `meta->plugin_url` if `permalink` is unavailable.
For this PR to work properly, `permalink` value must be added to response that comes from wpvip.com REST API (handled by a separate PR for that site).

vip-plugins: link to post->permalink instead of post->meta->plugin_url

---

vip-plugins/vip-plugins.php

WordPress VIP doesn't have an approved list of plugins, and therefore no Featured Plugins.
It does, however, have a list of [Featured Partners](http://wpvip.com/partners), so this PR updates the title in the admin page shown in all customer WPVIP sites to reflect that.

vip-plugins: "VIP Featured Plugins" -> "VIP Featured Partners"

---

search/includes/classes/class-health-job.php

Health checks happen way too frequently at present. Doubling the interval between event should help with that.
1. Check current interval time for `vip_search_healthcheck_interval`. It should be 30 minutes.
2. Apply PR
3. Check interval time for `vip_search_healthcheck_interval`. It should be an hour.

Adjust health check cron interval to 1 hour

---

search/includes/classes/commands/class-corecommand.php

Currently the `--skip-confirm` flag is broken for indexing. This PR fixes that.
1. Execute `wp vip-search index --skip-confirm`
2. It will error something like `Error: Parameter errors: unknown --skip-confirm parameter`
3. Apply PR.
4. Execute `wp vip-search index --skip-confirm`
5. It shouldn't error.

Unset skip-confirm before passing to EP for indexing

---

jetpack.php
vip-helpers/vip-caching.php

As described in #1859, in Jetpack 9.1 the instagram oembed cache has been deprecated. As we are adding a filter to enable this cache, it results in a warning when Jetpack 9.1 or above is in use.
This PR solves this by checking the Jetpack version before adding the filter. It had to be moved out from `vip-helpers/vip-cache.php`, as Jetpack was still not loaded, so we couldn't check the Jetpack version there. Instead, it's now directly in the mu-plugins Jetpack loader.
1. Ensure that the warning no longer appears if you are using Jetpack 9.1
1. If you pin Jetpack to an older version (e.g. 9.0), the filter is correctly applied.

Avoid a warning on Jetpack 9.1 when enabling instagram cache

---

admin-notice/js/script.js

Previously the hook was on `DOMNodeRemoved` which cause some other operations (e.g. page unloading) to fire it even if the button was not clicked.
1. Create a notice
1. Navigate to wp-admin
1. Refresh few times
1. Notice is still there
1. Dismiss Notice
1. Refresh few times
1. Notice is gone

Dissmiss Notice Event by Onclick

---

query-monitor.php
query-monitor/assets/query-monitor.js
query-monitor/classes/Activation.php
query-monitor/classes/Backtrace.php
query-monitor/classes/Hook.php
query-monitor/classes/Util.php
query-monitor/collectors/environment.php
query-monitor/dispatchers/Html.php
query-monitor/output/html/logger.php
query-monitor/query-monitor.php
query-monitor/readme.txt

Uprade query monitor 3.6.4->3.6.5.
1. Make sure query monitor still works
1. Check version of `query-monitor` using wp-cli `wp plugin list`

Uprade query monitor 3.6.4->3.6.5.

---

query-monitor.php

We want to see reports in Query Monitor even if results of shutdown actions. Thic change moves the dispatching of the QM as a last step in shutdown action as opose to first one so that we can cover more.
1. Add this code somewhere ("vip-config.php" should work):
```
function test_qm() {
do_action( 'qm/debug', 'This happened!' );
}
add_action( 'shutdown', 'test_qm', 5 );
```
1. See there is no log in query monitor:
1. Apply PR
1. Reload and see there is the log

Changes the priority of QM shutdown to cover more operations

---

wp-cli.php

If a site is created via WP-CLI with `wp_insert_site()`, `Automattic\VIP\WP_CLI\maybe_toggle_is_ssl()` will call `get_option()` before the database is created, causing the `siteurl` option to be cached blank.
This fix adds a simple `wp_is_site_initialized()` check to `Automattic\VIP\WP_CLI\init_is_ssl_toggle_for_multisite()` so that we won't toggle the SSL if the site isn't initialized yet.
Found this while testing @trepmal's fancy Blog Duplicator plugin :D
Example:
1. Write a WP-CLI comand to create a new site via `wp_insert_site()` and dump `site_url()` immediately afterwards and it should be blank.
1. Create a new site, dump `site_url()` and …

Fixes siteurl cache corruption with wp_insert_site

---

jetpack.php

Publish Jetpack 9.2 to all VIP Go sites, by setting it as the default version
1. Go to the Jetpack dashboard in wp-admin
1. Ensure it works and version 9.2 is active

Set Jetpack 9.2 as the default version

---

jetpack.php

As there are still VIP Go sites running on WordPress <5.5, they are failing to load Jetpack 9.2, as it's only compatible with newer WordPress versions.
With this change, we ensure that sites running older WP versions are using Jetpack 9.1 instead of 9.2.
Once they are upgraded to a newer WordPress version, they will immediately start using Jetpack 9.2.
1. Set up a sandbox/dev env with WordPress 5.4.2
1. Ensure that Jetpack works and version 9.1 is loaded
1. Go back to WordPress 5.5
1. Ensure that Jetpack 9.2 is loaded

Ensure that a proper Jetpack version is loaded depending on WordPress version

---

search/includes/classes/class-search.php

When there's a problem with the HTTP connection to ElasticSearch, we are masking it with a fallback error that prevents the actual error (e.g, a curl error) to be logged.
This branch removes that fallback error, and also creates a new logstash feature (`vip_search_http_error`) to log all those connection errors.
1. Just before the call to `vip_safe_wp_remote_request` in `class-search.php`, add a line to create a bad ES query. E.g: `$args['body'] = '{';`
1. Run a search on the testing site. The usual logstash error should appear in the log (including `error_type` and `root_cause` in the extra field)
1. Replace that added line for another one to provoke a HTTP error. E.g: `$query['url'] = 'http://10.0.0.1/';`
1. Run a search again. The new logstash error, including the cURL …

Improve logging for failed HTTP requests to ElasticSearch

---

.github/PULL_REQUEST_TEMPLATE.md

Deleting a whole bunch of text from the PR template is tedious. So I moved them all into comments.
Further, we're starting to look at process improvements and one of the whoppers is to have a sweet change log. So I've added both a Change Log Description(for everyone) and a task for adding a draft change log post to our change log(for Automatticians).

Switched instructions to be in comments and added changelog tasks.

---

README-PUBLIC.md
README.md
cache/README.md
gutenberg-ramp.php
lib/proxy/ip-forward.php
phpdoc.dist.xml
rest-api/vip-endpoints.php
shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php
vip-cache-manager/ttl-manager.php
vip-dashboard.php
vip-helpers/vip-caching.php
vip-helpers/vip-deprecated.php
vip-helpers/vip-newrelic.php
vip-helpers/vip-permastructs.php
vip-helpers/vip-utils.php
vip-jetpack/jetpack-mandatory.php
vip-rest-api.php
vip-support.php

There have been several changes recently that have not been reflected in the URLs in this repo.
- Much documentation now lives at https://docs.wpvip.com
- Main marketing site has changed from vip.wordpress.com to wpvip.com
- Branding has changed from "WordPress.com VIP" to "WordPress VIP".
This change updates each instance as needed.
Some URL references have been deleted where it makes sense, and an instance around the "Powered By WordPress.com VIP" has been left as that has wider implications that are being handled elsewhere.
Updated old documentation URLs, and WordPress.com VIP references, in code comments and some customer-facing strings.
Each old `vip.wordpress.com` references was manually tested to see …

Update old domains and WordPress.com references

---

vip-cache-manager/vip-cache-manager.php

It seems like yesterdays merge introduced a syntax error.
- Fix syntax error
https://github.com/Automattic/vip-go-mu-plugins/pull/1915
Running any test reports the issue e.g.: 
`./bin/phpunit-docker.sh tests/search/includes/classes/test-class-versioning.php`

Fix syntax error

---

search/includes/classes/class-queue.php
search/includes/classes/class-search.php
tests/search/includes/classes/test-class-queue.php
tests/search/test-class-search.php

We need a way to know if VIP Search is currently rate limited or not on specific sites when debugging. By logging to logstash when rate limiting kicks off and knowing how long rate limiting lasts, it makes debugging much easier since you don't need to guess.
To assist with debugging VIP Search related issues, we need an easy way to determine if rate limiting is currently in effect for queries or indexing operations. The easiest way to accomplish this right now is by logging when rate limiting starts to logstash.
https://github.com/Automattic/vip-go-mu-plugins/pull/1916
1. Apply PR.
2. Trigger rate limiting.
3. Check for appropriate logstash-related behaviour.

Log to logstash when VIP Search ratelimiting starts.

---

000-debug/logger.php

* Switches func_get_args to spread operator
* Ignores debug_backtrace warning
Details bellow vvv
The warnings were already reviewed previously and deemed false positive in this case.
However, we updated the implementation here to silence/resolve the warnings.
Add folowing code after logger was loaded (e.g. `debug.php`):
```
foreach( [1,2] as $ix) {
lo("foo", "bar");
}
```
Running any request/CLI (e.g. `wp post list`) should then print `foo` and `bar` (only once as we are using lo - log once in the example).
Note:
In vip-dev environment, you might need to set a constant (as logs are not printed in prod environments):
```
define('WPCOM_SANDBOXED', true);
```

Clears PHPCompatibility phpcs warnings

---

vip-cache-manager/vip-cache-manager.php

The length of the stat key is limited to `32` characters. Our keys included `vip-go-cache-manager-` prefix, which is `21` characters long, leading to stats keys truncation. 
This PR removes `go-` and `manager-` from the prefix so that keys become `vip-cache-action`, `vip-cache-url-purge-status`, and `vip-cache-url-purge-by-site`.
Additionally, introduces `vip-cache-action=dashboard-site-purge` stat.
We have updated stats keys allowing us to better track usage for Cache Manager functionality.
https://github.com/Automattic/vip-go-mu-plugins/pull/1922
1. Check out PR on a sandbox
1. Click 'Purge Page Cache' in Dashboard
1. Verify that 'dashboard-site-purge' is tracked now

Cache Manager: update stats keys, track dashboard purge action

---

000-vip-init.php
config/class-site-details-index.php
tests/config/test-site-details-index.php

Add more fields to the site details. Namely:
- Jetpack information (version, active status, Jetpack id, active modules)
- VIP Search status (enabled, query integration)
- Site url (useful mostly for multisite installations)
- Plugin path (in some situations, easier to handle than the plugin name)
We keep working in the Site Details functionality, that will allow us to have up to date details about sites, such as the list of plugins and their versions, whether VIP Search is enabled, Jetpack connection status...
This adds some more fields, namely the information about Jetpack (version, active status, Jetpack id, active modules). In the future, all these will be stored and be accessible to run actions on them. E.g, easily find all sites that have a certain old Jetpack version that needs …

Add new fields to the site details data

---

config/class-site-details-index.php
config/class-sync.php

We have recently found some situations where having Site Details already available would be very useful. The final implementation will still take some time, but in the meantime we would benefit of Site Details data being stored somewhere, even if it's not the final place.
This PR recovers a couple of commits from the original PR by @brandon-m-skinner - [commit1](https://github.com/Automattic/vip-go-mu-plugins/pull/1768/commits/63beab34d2df1997d3e62cd0835841bcec87b618#) [commit2](https://github.com/Automattic/vip-go-mu-plugins/pull/1768/commits/1143ba1659a733f98a39fd281f70eafb7f55f192).
Code was originally removed then because with `log2logstash` most of the relevant site details would be stored as a JSON string the `extra` field of the `vip-debug` index, which would have prevented the …

Temporarily store site details data in logstash

---

lib/wpcom-error-handler/wpcom-error-handler.php

Same as bellow
The warnings were already reviewed previously and deemed false positive in this case.
However, we updated the implementation here to silence/resolve the warnings.
* Add a fatal error to somewhere in mu-plugins e.g. -  `this_is_not_a_function();`
* Call `wp user list` see the error with `Fatal Error` prefix (added among other things by this handler)

Clears PHPCompatibility phpcs warnings wpcom-error-handler

---

logstash/class-logger.php
query-monitor.php

log2logstash runs fastcgi_finish_request during it's shutdown hook function. Doing this before query monitor is finished results in no query monitor panels getting loaded.
log2logstash runs fastcgi_finish_request during its shutdown hook function. Doing this before query monitor is finished causes query monitor to not load any panels.
https://github.com/Automattic/vip-go-mu-plugins/pull/1927
1. On the latest master using vip-go-mu-dev, run `./vip-init.sh --destroy`.
2. When the site is back up and running, login to wp-admin.
3.  Check the query monitor UI and notice how no panels load.
4. Apply PR.
5. Query monitor UI should have panels again.

Adjusted shutdown priorities for query monitor dispatch and log2logstash

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

We have some flakiness in Search unit tests due to using `time()` in two or more occurrences and comparing them. To move toward a more consistent testing experience, it makes sense to be able to set fixed timestamps in the functionality.
Adding the ability to set fixed timestamps in VIP Search is handy for creating consistent and reliable automated tests.
https://github.com/Automattic/vip-go-mu-plugins/pull/this-pr
1. Apply PR.
2. `./bin/phpunit-docker.sh tests/search/test-class-search.php --filter test__maybe_alert_for_prolonged_query_limiting`

Added ability to set fixed timestamps in Search for testing

---

vip-jetpack/vip-jetpack.php

Jetpack Sync checksums are about to be released to improve Jetpack Sync reliability. Checksum calculation is a potentially costly operation and may affect stability on very large datasets. This PR aims to account for the worst-case scenario by introducing the killswitch that would prevent the Checksum calculation from running.
A proactive change aimed for mitigation of potential performance degradation when calculating Jetpack Sync Checksums on very large datasets.
https://github.com/Automattic/vip-go-mu-plugins/pull/1938
1. Apply the PR
2. define `VIP_DISABLE_JETPACK_SYNC_CHECKSUM` constant with the value of `true` in `vip-config.php` 
3. `wp shell`
4. Call the checksum logic: 
```$rs = new …
```

Add pre_option_jetpack_sync_settings_checksum_disable filter to allow for a killswitch for Jetpack Checksum functionality

---

jetpack.php

Release Jetpack 9.3 to all sites (except pinned ones and sites with WordPress <5.5)
We upgraded all unpinned sites to Jetpack 9.3. More details about this release in the lobby post.
1. Ensure it's using Jetpack version 9.3

Set Jetpack 9.3 as the default for all sites

---

config/class-sync.php

Site Details generation is using a temporary solution while we decide the final approach. Because of this, we decided to reduce the interval of generation to 4 hours instead of 30 minutes, using a random number. The problem is that it's not predictable at all, and we need to search in the last 24 hours to obtain all results (and some sites might not have generated anything in that period).
This PR increases the frequency to match the cron execution period (30 minutes). More than the frequency itself, the most important part is that we can know for sure that every site generates the details document predictably, so the search query can be reduced a lot (around one hour).
The amount of documents to be stored in logstash keeps being low enough (less than half a million per day) to not …

Increase frequency of Site Details generation

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

When an ElasticSearch query fails or it returns a warning, Include the full original query in the message sent to logstash.
When a VIP Search query fails, it gets logged to Logstash so we can investigate the problems. Now we are also logging the full query sent to ElasticSearch and the PHP backtrace, so we can have much more detailed information about the root cause.

Include the original ElasticSearch query and backtrace when logging errors

---

bin/add-jetpack-subtree.sh
bin/update-jetpack-subtree.sh

New production Jetpack releases will be published in [Automattic/jetpack-production](https://github.com/Automattic/jetpack-production). This PR updates the helper scripts to manage Jetpack subtrees to reflect the new repo.
Jetpack releases are now being published in a [new repository](https://github.com/Automattic/jetpack-production). We have updated the helper scripts we use to add new Jetpack versions to `vip-go-mu-plugins` to reflect the correct repository.
1. Run `bin/add-jetpack-subtree.sh test 9.3.2`
1. Ensure that a new `jetpack-test` subtree is created from the new `jetpack-production`

Use the new jetpack-production repository for Jetpack subtrees

---

bin/github-changelog.php

I first tried to have Github label => changelog tag mapping in the code, which works fine. But then I thought it is a way more flexible if we can maintain that in Github directly. So the automation is looking for `ChangelogID: <ID>` in the label description that we don't really use for anything else.
You can change it here:
https://github.com/Automattic/vip-go-mu-plugins/labels?page=2&sort=name-asc
I also added `[Tag] Jetpack` and `[Tag] Search` as examples.
We updated changelog automation to support tags. Some Github labels will automatically be converted to the changelog tags.
CircleCI thingie so no real testing.

adds tag support

---

bin/github-changelog.php

This change makes it easier for us to detect if/when the changelog automation fails to create a draft post.

Fails circleCI pipeline on failure

---

jetpack.php

Set Jetpack 9.4 as the default version, so it gets rolled out to all VIP Go sites (except those that are pinned)
We have rolled out Jetpack 9.4 to all VIP Go sites (except those that are pinned to a specific version).
You can find [here](https://github.com/Automattic/jetpack-production/releases/tag/9.4) the list of changes in this version.
1. Ensure the version 9.4 is loaded

Set Jetpack 9.4 as the default version

---

tests/test-vip-jetpack.php
vip-jetpack/vip-jetpack.php

Outbound SSL is always available on VIP so we can skip the HTTP requests that JP makes to determine this (since JP has to work on many different hosting providers).
props @emrikol for the idea + code
Since Jetpack works across many different hosting providers (some which may not support HTTPS / SSL), it attempts to detect support by making an HTTPS request to WordPress.com, which is then cached for 1 day. On VIP, SSL is always supported so we can skip this check by filtering the transient used to store the result.
2. In `wp shell`, run `Jetpack::permit_ssl()` - this should return `1`
3. `wp transient get …

Always filter the jetpack_https_test transient to 1

---

tests/admin-notice/test-admin-notice.php
tests/bootstrap.php
tests/test-vip-jetpack.php
tests/vip-helpers/test-wpcom-vip-load-plugin.php
vip-jetpack/vip-jetpack.php

This fixes an issue with excessive HTTP requests due to a bug in Jetpack. This is a temporary (ish) filter - once the upstream Jetpack fix is in all of the versions VIP supports, this can be removed
Props @kraftbj for the code.
Adds another filter to reduce requests from Jetpack made to detect HTTPS / SSL support.
1. In `wp shell`, run:
2. `Jetpack_Options::delete_option( 'fallback_no_verify_ssl_certs' )` (to be sure it doesn't exist)
3. `Jetpack_Options::get_option( 'fallback_no_verify_ssl_certs' )` - this should return `0` (_not_ `false`)
4. `Jetpack_Options::get_option( 'id' )` - this should return the cache site id (_not_ `0` - option is unaffected)

Filter the fallback_no_verify_ssl_certs Jetpack Option to 0

---

files/acl/restrict-unpublished-files.php
tests/files/acl/test-pre-wp-utils.php
tests/files/acl/test-restrict-unpublished-files.php

Those need to be stripped out as well since the files paths are stored in postmeta without it.
We've added a fix that properly handles files with a subsite path (e.g. `/wp-content/uploads/sites/4/2021/01/unpublished.jpg`) with our Private Files feature. We now strip the `sites/:id` portion of the path before forwarding the request to WordPress.
See unit tests.

Properly handle file paths with `sites/:id`

---

files/acl/acl.php
tests/files/acl/test-acl.php

Even if the file is public, send a value of false to avoid traps when we hit an error
To harden the feature and avoid unexpected issues when the ACL endpoint may hit an error (e.g. fatal), we now will always send the X-Private header when the endpoint successfully processes the file. This way, we can differentiate between successful and unsuccessful requests and handle them appropriately upstream.
Covered by unit tests.

Private Files: Always send X-Private header

---

files/acl/acl.php
files/acl/endpoint-check-file-acl.php
tests/files/acl/test-acl.php

In a multisite install, we support running mixed private and public sites. To harden our ACL endpoint and prevent accidentally leaking private files via public sites, we now restrict access to files on the same subsite.
So, `example.com` (main site) can access `example.com/wp-content/uploads/2021/02/donuts.jpg`. But it cannot access `example.com/wp-content/uploads/sites/2/2021/02/icecream.jpg` since that file is managed by Site ID 2.
Similarly, `example.com/en/` (subsite) can access `example.com/en/wp-content/uploads/sites/2/2021/02/icecream.jpg` but not `example.com/wp-content/uploads/2021/02/donuts.jpg`.
In a multisite install, we support running mixed private and public sites. To harden our ACL endpoint and prevent accidentally leaking private files via public sites, we now restrict …

Private Files: Restrict cross-site file access

---

001-core.php

Passing a query string like this will cause the below php error: `http://vip-go-dev.lndo.site/?name[]=test`
> PHP Warning:  trim() expects parameter 1 to be string, array given in /app/wp/wp-includes/class-wp-query.php on line 779
Furthermore, because WP then interprets these as single post or single page queries - it will end up with a main query that looks like this - which is notably limitless:
```
SELECT wp_posts.*
FROM wp_posts
WHERE 1=1
AND wp_posts.post_type = 'post'
ORDER BY wp_posts.post_date DESC
```
With the intention being that it would also have a `AND wp_posts.post_name = 'test'` clause  if you visited `http://vip-go-dev.lndo.site/?name[]=test` for example - but this is left out when a non-string is passed.
Passing a query string like …

Prevent invalid core query args

---

files/acl/acl.php
files/acl/restrict-unpublished-files.php
tests/files/acl/test-acl.php
tests/files/acl/test-restrict-unpublished-files.php

When a post is updated, we should purge all children attachments. This allows us to propagate changes more quickly to the edges, and also allows us to cache public files for much longer which has performance benefits.
When the Restrict Unpublished Files module is enabled, a post update will now automatically purge the URLs for any child attachments for that post. This allows us to quickly propagate visibility changes and also cache public files for much longer, which has several performance benefits.
1. Add constant: `define( 'VIP_FILES_ACL_ENABLED', true );
1. `wp option set …

Private Files: PURGE attachment URLs on post update

---

tests/search/includes/classes/test-class-health.php
tests/search/includes/classes/test-class-versioningcleanupjob.php

Update ElasticPress to latest from Automattic/ElasticPress#develop.
The latest includes changes to how mappings are built - it breaks out the generation from the API requests to make it reusable.
See https://github.com/Automattic/ElasticPress/pull/78
See https://github.com/Automattic/ElasticPress/pull/79
This version of ElasticPress contains changes to how mappings are built - it breaks out the generation from the API requests to make it reusable.
2. On a test site, run `wp vip-search put-mappings` (this will delete your indexes!)
3. Check the …

Update ElasticPress to latest

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

This adds a sanitization step to the logging of failed ES queries to ensure nothing sensitive is logged.
Adds a sanitization step to the generated EP query to prevent sensitive info from being logged.
2. Just before the call to vip_safe_wp_remote_request in class-search.php, add a line to create a bad ES query. E.g: $args['body'] = '{';
3. For a local dev install do the following. For a VIP sandbox, check the php logs
4. Make sure you have `define( 'WP_DEBUG_LOG', true );` in vip-config.php
4. Run a query - http://vip-go-dev.lndo.site/?s=test
5. Check wp-content/debug.log in your environment
6. There should be an …

Search: Sanitize EP query for error logging

---

search/includes/classes/queue/class-cron.php

The admin_init and wp_loaded (WP CLI only) hooks are plenty to ensure the job is scheduled. WP CLI gets executed every 60 seconds via cron, so this will run regularly and does not need to add overhead to REST requests
Changed how a VIP Search cron job is scheduled - previously it was hooked into `rest_api_init` along with 2 other hooks, but this is unnecessary overhead as the job will be scheduled reliably via WP CLI (which runs regularly via cron).
1. Not too much needed here as this only removes a hook. If desired, can manually unschedule the event then run a CLI command …

Remove unnecessary hook on rest_api_init to schedule Search cron job

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php

Apart from checking the input, I removed the defaults arguments on the function level, as those were never used and were only misleading (we always send all of the arguments).
Removes minor warning from `wp vip-search health validate-contents` when some parameters are not set. The correct default values are set both before and after this change.
1. Running `lando wp vip-search health validate-contents` Gives you:
```
Notice: Undefined index: last_post_id in /wp/wp-content/mu-plugins/search/includes/classes/commands/class-healthcommand.php on line 271 [$ /usr/local/bin/wp vip-search health validate-contents] [Automattic\VIP\Search\Commands\HealthCommand->validate_contents(), …
```

Adds argument validations

---

blogpublic-notice.php

The new notice that your non-production site might be indexable by search engines throws a warning in CI and likely other places outside VIP Go where VIP_GO_APP_ENVIRONMENT isn't defined.
This PR wraps the usage of VIP_GO_APP_ENVIRONMENT in a defined check to avoid the warning and future error.
We wrapped the usage of VIP_GO_APP_ENVIRONMENT in a defined check so it won't throw warnings anymore.
1. Run anything without VIP_GO_APP_ENVIRONMENT defined.
2. Note the undefined constant warning.
3. Apply the PR.
4. Do 1 again.
5. There shouldn't be an undefined constant warning anymore.

Wrap blog public notices use of VIP_GO_APP_ENVIRONMENT in a defined check

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

We changed the loading order for VIP Search a little while back. This was done because we needed ElasticPress to correctly check if the protected content feature was enabled or not so we could add attachments as a default indexable post type under the right circumstances.
This seemed fine, but apparently broke the ElasticPress debug bar panel when it's loaded into debug bar. If it was loaded into query monitor it worked as expected. It also worked fine if WP_DEBUG or WP_EP_DEBUG or EP_QUERY_LOG were true in the config.
This PR moves the all important defining of WP_EP_DEBUG when debug bar or query monitor are enabled to before dependencies are loaded. Thereby having the constant set appropriately for when ElasticPress is instantiated.
Fixed an issue where the ElasticPress debug bar panel …

Move WP_EP_DEBUG defining and EP debug bar panel loading to before dependencies are loaded

---

a8c-files.php

Presently if you pass in an invalid URL to the A8C_Files::purge_file_cache function  you could end up attempting to return an undefined variable. By moving the declaration of `$requests` a bit higher, it will just return an empty array instead.
It used to be possible to return an undefined variable in A8C_File::purge_file_cache. The function has been made more defensive and as such this is no longer possible.
1. Make `A8C_File::purge_file_cache` public.
2. Call it with a bad url in `wp shell`.
3. You'll get a undefined variable notice.
4. Apply PR.
5. Call `A8C_File::purge_file_cache` with a bad url in `wp shell`.
6. It should return an empty array.

Move requests variable definition higher in A8C_Files::purge_file_cache to prevent returning undefined variable

---

lib/class-vip-request-block.php

Right now, if we want to block on something more custom than what's included in this class, we'd need to copy the functionality of `VIP_Request_Block::block_and_log()` into `vip-config.php`
Changing this to public could allow us to use the functionality without duplicating code.
Example:
```
if ( isset( $_SERVER['REQUEST_URI'] ) && '/autodiscover/autodiscover.xml' === $_SERVER['REQUEST_URI'] ) {
VIP_Request_Block::block_and_log( '/autodiscover/autodiscover.xml', 'REQUEST_URI' );
}
```
Of course, we could just add a `request_uri()` function for this _specific_ example, but switching to `public` could allow for more options (` false === strpos()`?) and allow us to iterate quicker via `vip-config.php` than requesting new updates to the `VIP_Request_Block` class.
Previously if we wanted to …

Switch `VIP_Request_Block::block_and_log()` to public visibility

---

async-publish-actions.php
stats.php
tests/test-async-publish-actions.php

Prevents a large number of cron jobs from being registered, unless they are truly needed.
This PR includes 3 steps:
1) Track the usage of this feature, to better help make future decisions.
2) Remove the two "default" offloads.
3) Only register the cron job when the hooks are being used.
For 2, by removing the two default offloads - the [track_publish_post()](https://github.com/Automattic/vip-go-mu-plugins/blob/82308873535a775d263daa3f2cc24a36d8774ccd/stats.php#L24) and [_publish_post_hook()](https://github.com/WordPress/WordPress/blob/c6c1ef3c32ee4bfdc86a7dc2290604aee3bc3de8/wp-includes/post.php#L7289) logic will now happen synchronously when a post is published, the effects of which quite minimal here. One additional note is that `track_publish_post()` would have technically only have …

Update async publish actions

---

vip-jetpack/connection-pilot/bin/partner-provision.sh
vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

1) By checking against `hashed_site_url`, we can better ensure there won't be a mixup due to search/replaces & migrations/data syncs.
2) Log "last connection info" every time when possible.
3) Only attempt to register the cron job in admin/cron (prevent every FE request from triggering).
4) Remove deprecated `Jetpack_Client::wpcom_json_api_request_as_blog` call. Was deprecated in JP 7.5, and supposed to be removed in 8.1 (but still there).
5) Refresh bash script from JP source. We still need to override though ([more info](https://github.com/Automattic/vip-go-mu-plugins/pull/986#issuecomment-784730476)).
In preparation for the rollout for improved Jetpack connection monitoring, the following notable changes have been made:
- Hash and save the existing site_url in the healtcheck so it can …

Refresh Jetpack Connection Pilot (A Space Odyssey)

---

lib/feature/class-feature.php

The original intent of the PR was to enable Jetpack Connection Pilot for 25% of the websites, during that work we also decided to add some documentation in the code.
- Add usage examples
- Add PHPDoc for $feature_percentages
- Register `jetpack-cxn-pilot' and 0.25
We've also discussed potentially adding an API for feature registration and/or changing the visibility for $feature_percentages to `protected` to better signal the intent - we want to keep the feature definition central and prevent any other code from modifying the value. but that needs some additional thought
Jetpack Connection Pilot is an internal system that allows us to better monitor the state of Jetpack connections and quickly address any issues.
Minor updates to our internal library that we use for partial rollouts of new …

Feature lib updates: add usage examples, some basic PHP Doc and enable Jetpack connection Pilot

---

jetpack.php

Set Jetpack 9.5 as the default version, so it gets rolled out to all VIP Go sites (except those that are pinned)
We have rolled out Jetpack 9.5 to all VIP Go sites (except those that are pinned to a specific version).
You can find [here](https://github.com/Automattic/jetpack-production/releases/tag/9.5) the list of changes in this version.
1. Ensure the enabled version is 9.5
1. Ensure everything else keeps working

Set Jetpack 9.5 as the default version for all VIP sites

---

jetpack-start/wp-cli-provision.php

Due to some deprecations/updates in Jetpack 9.5 jetpack-start needs some refresh.
Updates deprecated functions calls to their modern counterparts from Jetpack 9.5 
We've fixed some compatibility issues for internal tooling due to code deprecations in Jetpack 9.5. 
This change doesn't affect customer workflows
1. Apply the PR
2. Establish A Jetpack connection via `wp jetpack-start connect`

Hotfix: jetpack-start WP CLI command compatibility with Jetpack 9.5

---

misc.php

Check https://github.com/Automattic/vip-go-mu-plugins/pull/1978 for context
There is a possibility in the core that if a notoptions are being updated at the same time, a change could be rewritten.
This would then result in option being stored in DB but also marked as non-existing in notoptions making further attempts to add such option always fail without removing the options from the list of non-existing options.
We have deployed a fix for this over a week ago but decided to do 2 phase deployment. The first phase was all non-prod environments. As we did not see any negative effects of this change we will roll it out to prod environments with this change.
As this is race condition it is really hard to reproduce …

Fix the potential race condition with notoptions

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Check #2018 for context
PHP `array_rand()` functions require a non-empty array, and it will raise a PHP warning in PHP 7.1-7.4 and a fatal error in PHP 8 in the case the array is empty. 
Testing the issue would involve the possibilty to control Elasticsearch server, so that's not easy to test. However, the fact that `array_rand` requires a non-empty array and that `Search::get_random_host()` currently doesn't ensure that is self-evident.

Ensure hosts not empty before randomly picking one

---

config/class-site-details-index.php

Add a field with the PHP version to the site details document.
The site details data contains information that is extracted from WP sites in run time. This PR adds an extra field with the PHP version to the site details data. This will help us to identify which sites are running old PHP versions, so we can investigate the reason and ensure they are upgraded.
1. Check out PR in a VIP Go Sandbox
1. Execute wp cron-control events list and find the id for the entry `vip_config_sync_cron`
1. Run it manually with `wp cron-control events run <id>`
1. Check the output in `/chroot/tmp/logstash.log` and ensure the PHP version is now included in the JSON document

Add PHP version field to the site details data

---

bin/utils.sh

These tests don't really make sense for us as they check among other
things if .md/packache files are correct. Those are core developer aimed
tests.
The current failing one is that SECURITY.md didn't have some expected line in it.
We have excluded some of the core WordPress tests from running as part of our mu-plugins build pipeline to avoid false failures.

Exclude basic file tests from core run

---

security.php

Reduces the username to ASCII. All valid usernames should already be in this format. This is the equivalent of calling `sanitize_user( $username, true )` every time `sanitize_user()` is called.

Enforce strict username sanitization

---

lib/feature/class-feature.php
search/includes/classes/class-health.php
search/includes/classes/class-healthjob.php

This enables index settings monitoring on all sites with VIP Search by removing the feature gate. Auto healing of mismatched settings is currently disabled.
Enables the automatic monitoring of inconsistent index settings for all sites (previously limited to 25%).
1. Add a `var_dump( $unhealth_indexables )` to `HealthJob::check_all_indexables_settings_health()` (so we can tell it's running)
2. NOTE - depending on your local setup, you may have to comment out the early returns in `HealthJob::check_health()` (which prevent the check from running when the job isn't enabled or the index isn't built).
1. In `wp shell`...
1. `$search = …

Search: Enable index settings monitoring on all sites

---

lib/feature/class-feature.php
search/includes/classes/class-health.php
search/includes/classes/class-healthjob.php
tests/search/includes/classes/test-class-health.php
tests/search/includes/classes/test-class-healthjob.php

When index settings are determined to be inconsistent with the desired settings, automatically update the (specific) settings to keep it in sync.
This change adds support for automatically updating an index's settings to match the desired state, enabled on only a subset of sites. This provides the ability to easily control index settings both per-site and across the VIP platform.
1. Add a `var_dump()` to `HealthJob::check_all_indexables_settings_health()` - `var_dump( $unhealthy_indexables );` - this is a super hack but this method sends alerts to Slack / IRC which doesn't work in local dev or sandbox (need a better way to do …

Search: Add index setting automation

---

.deployignore

Adds the `bin` and `tests` directory for the object-cache dropin to the `.deployignore` file so our deploy system ignores them.
This change has no production impact - it simply adds 2 directories to the `.deployignore` file to prevent them from being deployed. NOTE - the object-cache drop-in file referenced here is not currently used in production (but it is the same version).
- n/a This change works and has been tested on a Go sandbox.
- n/a I've created a changelog description that …

Ignore the bin and tests directories of object-cache dropin for deployment

---

search/includes/classes/class-health.php
tests/search/includes/classes/test-class-health.php

* When processing validate_contents we store the id we are working of
* IF the process would end unexpectly we would recover that id and start
from where we left of.
Adds an interruption recovery mechanism to the validate content feature. 
The hardest part here is to simulate interruption.One way you can do this is by adding `exit()` in the validate-contnets loop.
1. add `exit()` call in `search/includes/classes/class-health.php` somewhere in the loop around line `323`
2. Run validate_contents with some start_id (so that it doesnt get interrupted on index 1 so that we can see it works)
`lando wp vip-search health validate-contents --start_post_id=5`
3. Clear parallel execution lock (as we killed the process it …

Adds validate content interruption recovery

---

lib/feature/class-feature.php
search/includes/classes/class-health.php
search/includes/classes/class-healthjob.php
search/includes/classes/commands/class-healthcommand.php
tests/search/includes/classes/test-class-health.php

Adds automated cron task that will run once a week and will validate all the post contents by comparing data in database against the documents in elasticsearch. It will automatically fix any issues it finds.
- [`n/a`] This change has relevant unit tests (if applicable).
1. There are some hacking needed first - in `class-healthjob.php:152` add `var_dump($results);` - to see stuff
1. In  `class-healthjob.php:is_enabled` add `return true;` right at the beginning (to enable it outside of prod)
1. In `lib/feature/class-feature.php` change `'search_content_validation_and_auto_heal_cron_job' => 0.1` to `'search_content_validation_and_auto_heal_cron_job' => 1`
1. `wp eval …

Add validate content cron

---

gutenberg-ramp.php
lib/feature/class-feature.php

We are aiming to remove the Gutenberg Ramp plugin, and we wish to do this step-wise. This Pull-Request will disable Gutenberg Ramp for 10% of sites by making use of the Feature Flags -- this is as close it comes to remove it without removing it. If successful, we will then disable it for further 10 percent of sites and so forth, until 100%. If problems arise, we might change strategy.
Previous PRs are #1986, #1958.
Another Pull-Request, #1992 will remove it; we will merge it when we have reached 100% with the Feature Flags used in the current Pull-Request.
We have already taken steps to remove any invocations to the plugin by submitting Pull-Requests.
This Pull-Request will disable Gutenberg Ramp plugin for 10% of sites, using the Feature Flags. When merged and if everything looks good, …

Stepwise disabling of Gutenberg Ramp plugin

---

files/class-image-sizes.php

As per https://developer.wordpress.org/reference/hooks/intermediate_image_sizes_advanced/, the filter now accepts 3 parameters, to not break compatibility with other filters, it would be good to add the third parameter.
Fixed the `intermediate_image_sizes_advanced` filter by adding the attachment_id third parameter.
- fixes the `intermediate_image_sizes_advanced` filter by adding the attachment_id third parameter

fixes intermediate_image_sizes_advanced param size

---

search/includes/classes/class-healthjob.php

Update to the alert message received for validate-contents search cron. This change adds site URL and switches from detailed to summary report.
- [`n/a` ] This change has relevant unit tests (if applicable).
- [ `n/a`] This change has relevant documentation additions / updates (if applicable).
1. There are some hacking needed first - in `class-healthjob.php:156` (in the `else if ( ! empty( $results ) )` path ) add `var_dump($message);` - to see stuff
1. In  `class-healthjob.php:is_enabled` add `return true;` right at the beginning (to enable it outside of prod)
1. In `lib/feature/class-feature.php` change `'search_content_validation_and_auto_heal_cron_job' => 0.1` to …

Search Cron - validate contents: Update alert text with site ID

---

lib/environment/class-environment.php
tests/lib/environment/test-class-environment.php

This adds a new `Automattic\VIP\Environment` utility class for determining details about the current environment (like if this is a sandbox or CLI/Batch container). This will replace existing logic that is hardcoded into 000-vip-init.php, making it testable. It's currently not used anywhere (but will be soon).
This adds a new `Automattic\VIP\Environment` utility class for determining details about the current environment (like if this is a sandbox or CLI/Batch container). This will replace existing logic that is hardcoded into 000-vip-init.php, making it testable.
The code isn't yet included from anywhere (want to get this …

Extract sandbox/cli container detection to new Environment class

---

lib/feature/class-feature.php

We are aiming to remove the Gutenberg Ramp plugin, and we wish to do this step-wise. This Pull-Request will disable Gutenberg Ramp for 25% of sites by making use of the Feature Flags -- this is as close it comes to remove it without removing it. 
Previous PRs are #1986, #1958 and #2039.
Another Pull-Request, #1992 will remove Gutenberg Ramp; we will merge it when we have reached 100% with the Feature Flags used in the current Pull-Request.
We have already taken steps to remove any invocations to the plugin by submitting Pull-Requests.
Deploying this on March 30th, 2021 would be optimal, if possible.
Disable Gutenberg Ramp plugin for 25% of sites, using the Feature Flags. We will then continue to iterate based on the outcome of this deployment.
- [N/A] This change works and has been tested …

Stepwise disabling of Gutenberg Ramp plugin: 25%

---

misc.php

The default columns to search when searching the list of multisite sites in `/network/sites.php` include `domain` and `path`, [except when `! is_subdomain_install()`](https://github.com/WordPress/WordPress/blob/058f9903676a7efaee534a682df0a2a8b87574d8/wp-admin/includes/class-wp-ms-sites-list-table.php#L130). On Go, all multisites are technically subdirectory installs so a Site Search only searches `path`. On large multisite installations with many domains, this leads to inaccurate search results as the site domains are not considered for a search.
This PR filters [`site_search_columns`](https://developer.wordpress.org/reference/hooks/site_search_columns/) to add `domain` back into the columns to search, which greatly improves search results when searching large multisites with many …

Add domain to site search columns to improve WP Admin site search results

---

lib/feature/class-feature.php

Previously, search index setting automation was enabled for 10% of sites, this increases it to 50%
This increases the percentage of sites that receive automated index settings from 10% to 50%
Not much to test manually as this is just a feature flag percentage change

Search: Enable index setting automation on 50% of sites

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

We recently decreased the index.max_result_window to 9000 from the default of 10k, this had negative impact on some sites, this hotfix restores the default value.
Set the value of index.max_result_window to 10000
<!--

Hotfix: Restore index.max_result_window to Elasticsearch default of 10000

---

lib/feature/class-feature.php
search/includes/classes/class-healthjob.php
tests/search/includes/classes/test-class-healthjob.php

Increases the percentage of sites that receive automatic index setting updating to 100%
This will sync the settings defined in code with the ES index settings via cron for all sites. Note that only [some settings are synced](https://github.com/Automattic/vip-go-mu-plugins/blob/342572fd4d0d4c044939d5a640744f22cff95535/search/includes/classes/class-health.php#L34-L38).
1. Mostly just a config change, but can run the health function directly
2. `$search = \Automattic\VIP\Search\Search::instance();`
3. `$job = new \Automattic\VIP\Search\HealthJob();`
4. `$job->check_health()`

Search: Enable auto index setting updating on all sites

---

.circleci/config.yml

This removes `php73-build-multisite` and `php73-build-singlesite` CircleCI jobs
We'll keep the `php73-lint` in place until we officially bump the minimum supported version to 7.4

Remove CircleCI php7.3-build-* jobs

---

lib/feature/class-feature.php

We are aiming to remove the Gutenberg Ramp plugin, and we wish to do this step-wise. This Pull-Request will disable Gutenberg Ramp for 45% of sites by making use of the Feature Flags -- this is as close it comes to remove it without removing it. 
Previous PRs are #1986, #1958, #2039 and #2045.
Another Pull-Request, #1992 will remove Gutenberg Ramp; we will merge it when we have reached 100% with the Feature Flags used in the current Pull-Request.
We have already taken steps to remove any invocations to the plugin by submitting Pull-Requests.
This Pull-Request can be deployed whenever suits Platform.
Disable Gutenberg Ramp plugin for 45% of sites, using the Feature Flags. We will then continue to iterate based on the outcome of this deployment.
- [N/A] This change works and has been tested …

Stepwise disabling of Gutenberg Ramp plugin: 45%

---

jetpack.php

Set Jetpack 9.6 as the default version, so it gets rolled out to all VIP Go sites (except those that are pinned)
We have rolled out Jetpack 9.6 to all VIP Go sites (except those that are pinned to a specific version).
You can find [here](https://github.com/Automattic/jetpack-production/releases/tag/9.6) the list of changes in this version.
1. Ensure the enabled version is 9.6
1. Ensure everything else keeps working

Set Jetpack 9.6 as the default version for all VIP sites

---

lib/feature/class-feature.php

We are aiming to remove the Gutenberg Ramp plugin, and we wish to do this step-wise. This Pull-Request will disable Gutenberg Ramp for 70% of sites by making use of the Feature Flags -- this is as close it comes to remove it without removing it. 
Previous PRs are #1986, #1958, #2039, #2045 and #2064.
Another Pull-Request, #1992 will remove Gutenberg Ramp completely. 
We have already taken steps to remove any invocations to the plugin by submitting Pull-Requests.
This Pull-Request can be deployed whenever suits Platform.
Disable Gutenberg Ramp plugin for 70% of sites, using the Feature Flags. We will then continue to iterate based on the outcome of this deployment.
- [N/A] This change works and has been tested locally (or has an appropriate fallback).
- [N/A] This change has relevant unit …

Stepwise disabling of Gutenberg Ramp plugin: 70%

---

.deployignore

After adding Jetpack 9.7 subtree, there are a few files that belong to third parties that throw linting errors on the `vip-go-stacks` commit hooks. In all cases it's code that doesn't get executed because they are either compatibility code for older/newer PHP versions, or build scripts.
Ideally, we should make the linting hook skip all vendor directories, but for the moment we'll use this simple approach.
Due to recent code introduced in Jetpack 9.7, which is only to be executed on PHP <=7.2 or PHP >=8.0, some linting jobs are failing when deploying mu-plugins. This PR removes them from the deploy so the process can be completed.
1. Run the same rsync command used by `vip-go-utility-scripts/mu-plugins/prepare-deploy.sh`
1. Ensure the files added to `.deployignore` in this …

Avoid deploying some Jetpack files that throw linting errors

---

lib/feature/class-feature.php
search/includes/classes/class-healthjob.php

Updates automated cron task that runs once a week and validates all the post contents by comparing data in database against the documents in elasticsearch. It will automatically fix any issues it finds. This change increases the amount of sites running this cron to 100% from 50%.
1. There are some hacking needed first - in `class-healthjob.php:147` add `var_dump($results);` - to see stuff
1. In  `class-healthjob.php:is_enabled` add `return true;` right at the beginning (to enable it outside of prod)
1. `wp eval "var_dump(do_action('vip_search_health_validate_content'));"`
1. Now introduce some issue (like delete post from DB directly)
1. `wp eval "var_dump(do_action('vip_search_health_validate_content'));"` - …

Run search validate contents on all sites

---

lib/feature/class-feature.php

Bumping the password admin password change verification to 25% of the sites.
Bumping the password admin password change verification to 25% of the sites.

Bump Admin Password Verification to 25%

---

vaultpress.php

This PR removes the ValutPress onboarding prompt asking the user to register VaultPress. In the VIP platform, we don't want users registering VaultPress since that is done by Customer Success.
However, the registration screen is still available under the VaultPress Dashboard.
**Before:**
**After:**
Removing the prompt asking the user to register VaultPress when launching a site without a connection to VaultPress.
2. Make sure you are in a WP site without a Jetpack connection
3. Go to `wp-admin` 
4. You shouldn't see the VP banner.

Hide VaultPress onboarding prompts when not connected

---

vip-jetpack/vip-jetpack.php

Jetpack UI would break if all submenu items were removed (as it might be the case when Akismet and VaultPress are not active). Therefore, this PR adds a dummy submenu item that alerts the user that Jetpack is not connected and should contact the system administrator (VIP Support) to activate it.
Adding Jetpack Connect Notice to wp-admin sidebar when Jetpack is not connected.

Add Jetpack Connect Notice

---

vip-jetpack/vip-jetpack.php

#2095 introduced a potential fatal if Jetpack is not active. 
Address that by adding a `class_exists` check before trying to call any Jetpack methods.
Internal update
1. Check Out the PR.
2. Disable Jetpack via constant
3. Verify there are no fatals

Don't try to add Jetpack connect menu if Jetpack is not active

---

jetpack.php

We upgraded the default Jetpack version from 9.6 to 9.7. This will impact all unpinned sites.
1) Check the version in admin -> jetpack

Update default JetPack vesion from 9.6 to 9.7

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php

To check if Jetpack is connected, Connection Pilot was using `is_development_mode`. This method [got deprecated in `8.8.0`](https://github.com/Automattic/jetpack/blob/5648ec24f73fd69b82603d7f9cc7a38484f77bab/projects/packages/status/src/class-status.php#L25) and it is now recommended to use `is_offline_mode`.
This PR changes the check for a development mode in Jetpack for offline mode.
Connection Pilot now checks for Jetpack's offline mode.

Use Jetpack's offline mode in Connection Pilot

---

.deployignore

This adds source files and Preact-specific build-related files for Search Dev Tools to .deployignore
Deploy and find out

Add search-dev-tools related records to .deployignore

---

.github/PULL_REQUEST_TEMPLATE.md

Update to the PR template - no need to publish a changelog
Adds an ask to the PR template for keeping the changelog title formatted as a title

Adds ask for keeping the changelog title as title

---

vaultpress.php

At VIP, VaultPress needs Jetpack to work. If we have the `VIP_JETPACK_SKIP_LOAD` constant, we should not load VaultPress because some things would not work.
Not loading VaultPress if Jetpack is disabled.

Not loading VaultPress when Jetpack is disabled

---

alloptions-limit.php

Simplify ALLOPTIONS alerting/blocking logic: use higher limits for uncompressed values for alerting purposes, and only check the compressed limit before terminating the request. 
The previous iteration did reduce the number of alerts and unnecessary blocking but it may have inadvertently affected the performance during certain traffic scenarios. This should handle things in a more careful fashion.
The next step will be to remove this logic from web context, since we're trying to limit this once a minute, running on cron would allow us to eliminate any potential race conditions due to traffic spikes.
We've reworked some internal alerting regarding very large autoloader options.
1. Checkout the PR
2. Add a large …

ALLOPTIONS handling improvements

---

jetpack.php
vip-jetpack/vip-jetpack.php

In this PR:
- We load VIP Jetpack customizations (`vip-jetpack.php`) only if Jetpack is enabled (we move the unconditional `require_once` to inside a function that's only reached if Jetpack is enabled).
- We disable some additional Jetpack messaging through the `jetpack_just_in_time_msgs` constant.
Better handling of Jetpack when it's disabled. Removal of some extra Jetpack messaging.
2. Load wp-admin with Jetpack enabled (Jetpack should function just fine).
3. Load wp-admin with Jetpack disabled (we shouldn't see any errors).

Loading VIP Jetpack conditionally and hiding more messaging

---

search/includes/classes/class-search.php
search/search-dev-tools/search-dev-tools.php

This PR addresses a couple of compatibility issues:
1. Pass a correct WP_Post object instead of a null to Search::get_post_meta_allow_list, this way we'll make sure to correctly gather the meta keys for each post type and avoid potential fatals in case a user code implements a filter callback with a type hint.
2. Remove the check for VIP_ENABLE_VIP_SEARCH constant - we've changed the way things loaded and it's redundant now.
Additionally:
1. Bump the required capability to manage_options.
2. Rate-limiting tab now also shows the number of queries and the limit.
3. Minor PHPDoc improvements.
- We've addressed a few incompatibilities that may have caused issues in edge case scenarios where a `vip_search_post_meta_allow_list` filter callback has a type-hinted argument.
- Rate Limiting tab …

Search Dev Tools compatibility fixes and permission restrictions

---

search/includes/classes/class-queue.php
tests/search/includes/classes/test-class-queue.php

There is an edge case that can cause the cleanup job of deadlocked jobs ... well to be deadlocked itself :) Please see the comment in the code for more context.
Update deadlock cleanup job for the indexing queue to handle correctly multiple jobs trying to reindex the same object.
This is quite hard to test. I think the state can happen due to a race condition in EP code.
The scenario you want is:
* 2 jobs in the queue - wp_vip_search_index_queue db table
* 1 needs to be in state 'running'
* 1 needs to be in state 'scheduled'
So I guess inserting those to DB directly works:
```
INSERT into wp_vip_search_index_queue (`object_id`, `object_type`, `status`, `index_version`, `scheduled_time`) VALUES (1, 'post', …
```

Deadlock Job Cleanup Updateup

---

000-vip-init.php

Introduces a new constant to exclude the front-end of a site from
maintenance mode. This can be used for Kubernetes migrations where
the front-end of the site will still work, but we want to prevent
database writes in wp-admin.
Added a constant, `WPCOM_VIP_SITE_ADMIN_ONLY_MAINTENANCE`, that can be used to put a site into maintenance mode without impacting the front-end. The idea being to prevent database writes(e.g.: post creation) in wp-admin from happening at an inopportune time during periods of maintenance while still allowing the site to operate normally.
Example:
2. Set `WPCOM_VIP_SITE_MAINTENANCE_MODE` and `WPCOM_VIP_SITE_ADMIN_ONLY_MAINTENANCE` to `true`
3. Confirm maintenance mode is …

Allow maintenance mode for wp-admin only

---

tests/bootstrap.php

This is a hotfix for an issue that was introduced in the core commit https://core.trac.wordpress.org/browser/trunk/src/wp-includes/blocks/legacy-widget.php?rev=50997#L58 resulting in our tests failing with:
```
WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type "core/legacy-widget" is already registered.
```
1. Run `circleci local execute --job php74-build-singlesite-nightly`
1. Verify no tests are failing
1. Rejoice.

Temporarily remove register_block_core_legacy_widget because it interferes with our tests

---

search/search-dev-tools/search-dev-tools.php
tests/search/test-search-dev-tools.php

This PR adds a strict validation for the URL argument for search/dev-tools REST endpoint. 
We used to do a fairly naive check - a valid URL ending in '_search'  would pass it. Theoretically, that can be exploited.
With PR validation is much stricter now.
We've added strict validation rules for the REST endpoint arguments
1.  Add `$query['url'] = 'somethingbogus'` around https://github.com/Automattic/vip-go-mu-plugins/blob/92f77df56e3c3a3268b9abd080f14b1cedae8680/search/search-dev-tools/search-dev-tools.php#L134
2. Open Dev Tools and try to edit a query
3. The remote request to the REST endpoint should be a 400 now.

Stricter validation for URLs in Search Dev Tools

---

000-vip-init.php
lib/feature/class-feature.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

Please do not deploy before https://github.com/Automattic/vip-go-mu-plugins/pull/2197
This PR enables Connection Pilot by default to all sites.
Example for a plugin upgrade:
Enabling Connection Pilot by default.

Enable Connection Pilot for all sites

---

renovate.json

This is a follow-up PR to https://github.com/Automattic/vip-go-mu-plugins/pull/2198. 
Given that we're pulling VaultPress and Akismet from upstream and we don't want to update its dependencies, we're configuring the bot to ignore those repositories.
No customer impact

Ignoring Akismet and VaultPress dirs for Renovate bot

---

search/includes/classes/commands/class-corecommand.php

Adds a confirmation step before removing the previous index version when using automatic reindexing using versions.
Adds a confirmation step before removing the previous index version when using automatic reindexing using versions.
1. run `dev-env exec -- wp vip-search index --using-versions --setup --indexables="post"`
2. See a confirm message before removing index

Adds confirm message 

---

search/includes/classes/queue/class-schema.php

DROP INDEX `IF EXISTS` is not supported on Vitess or mysql. Looking at it closer I think it is safe to remove those lines totally (as oppose to manually check for index existence before removal).
The idea there was that version 2 of vip-search DB queue used and created it, however the current version 3 no longer creates or uses this DB index (switched around a year ago).
As this code ultimately runs on every admin/CLI request it is reasonable to assume the old index is cleaned out already.  
@nickdaugherty could you please check if my assumptions make sense to you?
Removes legacy DB index cleanup that is no longer needed.
IF you want to execute this code:
1.  On …

Remove index removal

---

search/includes/classes/class-healthjob.php
tests/search/includes/classes/test-class-healthjob.php

Moves search count inconsistencies to a separate channel. As there is an async aspect to indexing some level of inconsistencies is expected and therefore not actionable.
This is not really testable as the only change is the IRC/Slack channel name and those messages are only pushed from the real environment.

Search move inconsistency alerts

---

akismet.php

This PR removes some admin notices that Akismet would display when it was not activated. Given that we want to move towards activating Akismet automatically, we don't want to show the user buttons that are not actionable.
We are removing notices such as:
The PR includes a small refactor to remove Akismet pages as well.
Removed Akismet notices.
- [ x] I've created a changelog description that aligns with the provided examples.
Example:
2. Go to `wp-admin` > `Plugins`
3. If Akismet is not active but Jetpack is, you shouldn't see the admin notice.

Hide Akismet admin notices

---

renovate.json

Apparently, our renovatebot config was outdated and also had some warnings, this should address the issue. 
Additionally, use a more generic pattern for ignorePaths.
Merge and hope the ignored dependencies will be ignored this time.

Update renovatebot config to address the warnings

---

blogpublic-notice.php

Removing the unused `$wp_admin_bar` argument from the `\Automattic\VIP\Blog_Public\notice()` callback since the `admin_notices` hook doesn't ever pass arguments. This doesn't seem to be a problem for WordPress in general, but if a plugin is attempting to do something with the output of notices (like move them around on it's own pages) and uses `call_user_func()` instead of `call_user_func_array()` like WordPress core, this will cause a fatal error.
Removed the `$wp_admin_bar` parameter from the callback since the `admin_notices` hook doesn't pass any arguments.
1. Get a non-production App with a domain that does not end with `.go-vip.co` or `.go-vip.net` and make sure the `blog_public` option is set to `1`.
2. …

Remove `$wp_admin_bar` argument

---

000-vip-init.php
lib/feature/class-feature.php
tests/search/test-search-dev-tools.php

This PR enables Search Dev Tools for 25% of sites and ALL non-prod sites.
We enabled Search Dev Tools on 25% of sites and all non-production sites.

Enable Search Dev Tools for 25% of sites and ALL non-prod sites

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

This PR extends Jetpack Connection Pilot capability to add autoconnection to Akismet. If a Jetpack connection is active, the system will try to connect automatically to Akismet
This PR extends Jetpack Connection Pilot capability to add autoconnection to Akismet. If a Jetpack connection is active, the system will try to connect automatically to Akismet.
Connection Pilot is now capable of autoconnecting to Akismet.
2. Go to a Sandbox and launch a CLI.
3. Run the `reconnect()` routine from Connection Pilot.

Adding Akismet autoconnection

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php

Akismet autoconnection would fail because the Jetpack connection would not be valid. That is because the Jetpack connection is owned by the WP VIP user. This PR forces that user when the connection attempt is performed.
Fix bug for Akismet autoconnection.

Forcing VIP user to perform Akismet autoconnect

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

This PR extends Jetpack Connection Pilot capability to add autoconnection to VaultPress. If a Jetpack connection is active, the system will try to connect automatically to VaultPress.
This PR extends Jetpack Connection Pilot capability to add autoconnection to VaultPress. If a Jetpack connection is active, the system will try to connect automatically to VaultPress.
Connection Pilot is now capable of autoconnecting to VaultPress.
2. Go to a Sandbox and launch a CLI.
3. Run the `reconnect()` routine from Connection Pilot.

Adding VaultPress autoconnection

---

search/includes/classes/commands/class-corecommand.php

When investigating different ES alerts I kinda missed an ability to easily check the settings of a given index in elasticsearch. This introduces a tool to do just that.
Adds `wp vip-search get-index-settings` command. This tool enables validation of mapping file and other settings of an index.
1.) Test all the switches of `wp vip-search get-index-settings`

Adds get settings subcommand

---

lib/class-vip-request-block.php

`VIP_Request_Block` used to block specific request uses now 403 instead of 410 http code. 410 code could lead to unintended caching.
1. Add `VIP_Request_Block::ip( '13.37.13.37' );`
2. Run request with HTTP header  HTTP_TRUE_CLIENT_IP: 13.37.13.37

Block using 403 http code as 410 has unintended cache implications

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php

This PR tweaks Jetpack's Connection Pilot behavior to check if Jetpack is connected with the correct email *after* we check Jetpack is connected at all. This will allow us to have way cleaner error logs.
Improving reliability of Jetpack Connection Pilot to check if the site is connected.

Checking Jetpack Connection owner after Jetpack site is connected

---

vip-dashboard/components/forms/sortable-list/index.jsx

This PR removes a couple of linter warnings that were flagged up when you compiled `vip-dashboard` using `gulp`.
Note that there's no need to deploy this PR since the generated code doesn't change.
Code cleanup for VIP Dashboard.
2. Go to `wp-admin` > `VIP Dashboard`.
3. Verify that the UI works as expected.

Removing else linter warnings on vip-dashboard

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

This PR tweaks how cron jobs are scheduled for Jetpack Connection Pilot so connections happen a bit quickly. Two modifications:
- First run goes down from ~1 minute after environment initialization to ~0 minutes after.
- Second run goes from between 1 and 60 minutes to 2 and 30 minutes. Note that subsequent runs are kept in an hourly schedule.
Tweaked Jetpack Connection cron jobs schedules to improve auto connection times.

Tweaking Connection Pilot cron job schedules

---

lib/class-vip-request-block.php

This PR clarifies the usage of VIP_Request_Block class by explicitly spelling out that it only applies to origin and not edge.
As I don't believe there's docs on this class (just yet), best to be as explicit as possible here that this blocking does not block edge requests
We've updated a code comment in VIP_Request_Block to clarify the fact that the library is meant to be used to block abusive clients at the origin and not edge locations.

Specify blocking only applies to origin requests

---

search/includes/classes/class-cache.php

In a certain edge case related to the load order of userland code Automattic\VIP\Search::disable_apc_for_ep_enabled_requests with message 'Call to a member function elasticpress_enabled() on bool' in Search\Cache::disable_apc_for_ep_enabled_requests.
This PR addresses that by checking for truthiness before trying to call 'elasticpress_enabled' method.
We've addressed an edge case that could potentially result in a fatal error in `Automattic\VIP\Search::disable_apc_for_ep_enabled_requests` pre_get_posts callback

Indexables::factory may return a boolean FALSE if an indexable is not  registered, which may result in Error: Uncaught exception 'Error'

---

vip-mail.php

Out of an abundance of caution and due to the fact the unit tests are missing for the feature we're gating it under `USE_VIP_PHPMAILER` constant.
We've released a compatibility fix for PHPMailer and VIP Filesystem so that VIP Filesystem attachments are allowed to be sent with an email.  
Currently, it requires `define( 'USE_VIP_PHPMAILER', true )` in vip-config.php
Define the constant and follow the steps outlined in #2057

Add a temporary feature flag for VIP_PHPMailer until unit tests are added

---

.circleci/config.yml

Add the Circle CI jobs for all currently used WP versions to avoid unpleasant surprises.

Add WP 5.4-5.7 Circle CI jobs, reshuffle the order of the jobs

---

tests/test-vip-mail.php
vip-mail.php

#2242 and #2057 introduced a regression on 5.4 due to the fact that PHPMailer paths were changed in 5.5, which we didn't catch because of not testing 5.4. 
This should address by checking the WP version and not requiring the new class if WordPress is older than 5.5
We've disabled the new VIP_PHPMailer implementation on WordPress installs older than 5.5.

Don't include the VIP_PHPMailer on WordPress < 5.5, add test coverage

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

This PR removes some additional checks that Connection Pilot has in place to check if it should reconnect. Given that the current behavior is to attempt a Jetpack reconnection to all sites that have CP enabled, those checks are not meaningful anymore and we can have simpler logic.
We are also removing the `is_fresh_site` check, used during the ramp-up process.
Removed some redundant checks.

Removing redundant Connection Pilot connection checks

---

000-vip-init.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

To wrap up the rollout of Connection Pilot, we are getting rid of some constants that were being used in earlier versions but are no longer relevant (CP is enabled by default on all sites and it always tries to reconnect Jetpack, VaultPress and Akismet).
We are removing the usage of deprecated constants in Connection Pilot.

Removing Connection Pilot legacy constants

---

jetpack.php

After the release of Jetpack 9.9, this PR makes that version default given that the WordPress version is compatible.
We made Jetpack 9.9 the default version of Jetpack.
2. Go to the Jetpack admin panel.
3. Check that the version displayed is 9.9

Making Jetpack 9.9 default

---

akismet.php
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-widget.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/notice.php

Update Akismet plugin to version 4.1.10
We upgraded Akismet 4.1.9 to Akismet 4.1.10
- Simplified the code around checking comments in REST API and XML-RPC requests.
- Added rel=”noopener” to the widget link to avoid warnings in Google Lighthouse.
- Set the Akismet JavaScript as deferred instead of async to improve responsiveness.
- Improved the preloading of screenshot popups on the edit comments admin page.
1. Go to `wp-admin`> make sure site works normally as expected, and Akismet is installed
1. Run `wp plugin list` to ensure latest version.

Update Akismet to v4.1.10

---

search/includes/classes/class-search.php

This PR removes the `vip` prefix from a log that doesn't need it (the prefix gets added by the logger class automatically).
Improved internal logging for VIP Search.

Remove duplicate prefix on failed Query Log

---

000-vip-init.php

Connection Pilot was enabled on _all_ environments. This PR enables it only on VIP Go environments, or what is the same, it disables Connection Pilot on local development environments (where connecting Jetpack does not make sense).
Limits the execution of Jetpack Connection Pilot on development environments.
1. Check out PR on a Sandbox and see that CP autoconnects.
2. Check ot PR locally and see that CP is not instantiated.

Don't run Connection Pilot on local environments

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

Jetpack Connection Pilot would fail to log an error because it was calling a function that did not exist, `notify_pilot`. This PR replaces that call with the `send_alert` function, that is used elsewhere and does the same thing.
Fixes an edge case in which a log would not be sent due to calling a non-existent method.

Fix non-existent notify_pilot function in Connection Pilot

---

misc.php

WordPress 5.8 [adds support for WebP images](https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/). That file format is not yet supported on the VIP File System, therefore we're disabling the possibility to upload `webp` files.
We are disabling WebP uploads for the WordPress 5.8 release until we can add proper support for webp transformation in the VIP Files Service. 
jpeg and png files will continue to be converted to and served as webp files to clients that request them. 
2. Go to `wp-admin` > `Media Library`
3. Try to upload a webp image. You shouldn't be allowed.

Disabling WebP images upload temporarily 

---

search/includes/classes/class-versioning.php

The last EP upgrade (https://github.com/Automattic/vip-go-mu-plugins/pull/2293) introduced a new hook, `ep_delete_post` with a single argument (instead of the two arguments the generic `ep_delete_ . $slug` had): https://github.com/Automattic/ElasticPress/blob/35a7c4a22158b460f55ef684e53a3cac318df66f/includes/classes/Indexable/Post/SyncManager.php#L389 
For this reason, our `action__ep_delete_indexable` would fail to execute, because sometimes the second argument would not be passed. Given that there is no such `ep_delete_term` or `ep_delete_user` with one argument, we can assume that the second argument is `post`. We are adding that as a default parameter to the function to avoid a fatal PHP error.
We upgraded our VIP Search integration with Elasticpress to fix a broken hook.
Please make …

Fix broken EP hook after EP upgrade

---

.deployignore

Husky v7 uses a different structure for its hooks and we should ignore them for deploy as well.
Upgrades around internal tooling and deploys.

Ignoring husky v7 files on deploy

---

jetpack.php

After the release of Jetpack 10.0, this PR makes that version default given that the WordPress version is compatible.
We made Jetpack 10.0 the default version of Jetpack.
2. Go to the Jetpack admin panel.
3. Check that the version displayed is 10.0

Bumps Default JP to 10.0

---

config/class-site-details-index.php

Check if the SERVICES_AUTH_TOKEN is empty before sending data to the site details service.
If the `services_auth_token` meta is not defined for a site, this define will be an empty string. In this case, we don't want to send data to the site details service, as it will fail for sure.
We are about to release the site details service to production, and we need to ensure we can do it gradually, allowing to test some sites first. This PR allows that to happen

Check if the SERVICES_AUTH_TOKEN is empty

---

config/class-site-details-index.php

The url for the site details service was wrong, pointing incorrectly to the site info service.
As part of the preparation for the site details service, we keep adding small improvements and fixes for `vip-go-mu-plugins`

Fix the url for the Site Details service

---

.circleci/config.yml

This PR adds an explicit CI test for WordPress 5.8 (we would have it already since it's the current `latest`, but when 5.9 is released we won't have it).
No need to deploy this change to production.
This PR adds internal tests for WordPress 5.8.

Adding WordPress 5.8 CI tests

---

.github/.stale

This PR adds the Stale bot to this repository. We are using the default configuration, which means that PRs will be marked as stale after 60 days of inactivity and will be closed 7 days after.
Following the [instructions of the bot](https://github.com/apps/stale), I have already enabled the app on the repository.
Note that this PR only affects the GitHub repository thus it doesn't need to be deployed.
Internal tooling update to better track external contributions.

Adding Stale bot to GitHub repository

---

wp-parsely.php

We want to enable the plugin for some sites but not show the UI (settings menu / page, admin header warning, widget & controls). This change unhooks certain actions and filters when the plugin is loaded by this wrapper file _*unless*_ it was enabled via the `wpvip_parsely_load_mu` filter.
For future extensibility sake, we also check the return value of a new filter `wpvip_parsely_hide_ui_for_mu` which can be independently overridden.
A bit of refactoring is also included:
* namespace the wrapper file to `Automattic\VIP\WP_Parsely_Integration`
* simplify the function name since it's namespaced
* pull the list of `SUPPORTED_VERSIONS` out to a constant
* attempt to load versions in top-down order (the first element is the default, so no need to maintain the `WPVIP_PARSELY_DEFAULT_VERSION` …

wp-parsley: Some loader improvements & maybe hide plugin UI

---

search/ui/class-vip-search-widget.php
search/ui/css/search-widget-admin-ui.css

We were missing some styles on the search widget admin panel, which made the options render in a sub-optimal way. This PR adds back those styles from Jetpack.
Before:
After:
Improving the visual layout of the admin UI of the Search widget.

Adding admin styles to VIP Search Widget

---

search/includes/classes/class-queue.php
search/includes/classes/queue/class-cron.php
tests/search/includes/classes/queue/test-class-cron.php
tests/search/includes/classes/test-class-queue.php

Currently, we store all the job_ids for the async search indexing queue as an argument for the cron instance. This is stored in autoloaded cron option. As this option is autoloaded on every request we would like to minimize the amount of data stored there.
Before the change, we would store an array of size up to 1000 per cron instance (up to 5). This change switches from using `[1,2,3,4,5]` to `1-5`.
This change optimizes the storage mechanism for cron processes in the async index queue.
One of the ways to get items to the queue is having a second index version. Updates to post then will be queued in `wp_vip_search_index_queue` for the inactive version.
1) Watch the table in DB - wp_vip_search_index_queue
2) …

Using id range instead of ids

---

bin/phpunit-docker.sh
tests/bootstrap.php
tests/parsely/test-mu-parsely-integration.php
wp-parsely.php

This is currently reporting an erroneous warning: "Invalid value configured via wpvip_parsely_version filter" even when a site is not overriding the filter.  This only performs the check when it is.
This also includes a first pass at integration tests for the plugin. Since WordPress is already mostly loaded and the plugin is sourced prior to running phpunit test cases, we have to hook into the phpunit bootstrap file to vary behavior. We do that by leveraging environment variables specified on the test runner host machine.
These will be hooked into CI in a follow up PR.
We made some behind-the-scenes changes that will help customers try Parse.ly on their sites more easily.
2. Run docker
3. …

wp-parsely: Only trigger warning when actually specifying a version via filter

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

This PR adds three additional fields to ElasticPress's error logs: `is_cli` (whether the error comes from a CLI or not), `reponse` (whole body of the response) and `request` (if the request is an error or not).
We are also removing the `vip_` prefix from the errors, as it was duplicated (the `log2logstash` function would add it as well).
Adds some additional logs for when an ElasticPress request fails.

Adding enhanced logging for ElasticPress and changing error name

---

search/includes/classes/class-search.php

As of 3.5.6, the default search date weight changed from `1` to `0.001`: https://github.com/10up/ElasticPress/pull/2061.
Unfortunately, this can have unintended side effects if `min_score` is modified via `ep_formatted_args`, as the calculated scoring will end up as a different value to what is expected. For future-proofing, we will keep it at 0.001.
I didn't need to set `epwr_score_mode` or `epwr_boost_mode`, since that was already done via https://github.com/Automattic/vip-go-mu-plugins/pull/1537.

Enterprise Search: Add date relevancy default for weight

---

.circleci/config.yml

`libgcc-8-dev` is not available in Debian Bullseye; the suggested replacement is `libgcc-10-dev` to match the version of `gcc`.
This PR fixes [this issue](https://github.com/Automattic/vip-go-mu-plugins/pull/2367#issuecomment-903464648).
Because the CI images switched to Debian Bullseye, libgcc-X-dev needs to be updated accordingly.
If everything is good, CirceCI jobs should succeed (with the possible exception of `php74-build-multisite-nightly` and `php74-build-singlesite-nightly`, see #2367).

Use libgcc-10-dev instead of libgcc-8-dev

---

bin/phpunit-docker.sh
composer.json
composer.lock
tests/files/test-image.php

The nightly version of WordPress requires `yoast/phpunit-polyfills` to run unit tests.
Without the polyfills, it [throws an error](https://app.circleci.com/pipelines/github/Automattic/vip-go-mu-plugins/6933/workflows/92e8384c-31db-4547-afe6-ba550d8900a4/jobs/49746?invite=true#step-105-62)
> Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.
This PR adds the missing polyfill.
Adds yoast/phpunit-polyfills to composer.{json,lock}
`php74-build-multisite-nightly` and `php74-build-singlesite-nightly` CI jobs should succeed.

Fix unit tests for WordPress nightly

---

config/class-sync.php

This PR reduces the site details sync interval, in order for site details service to have more up-to-date data for each site.
We lowered the site details update interval from 30 to 5 minutes.

FORNO-829: Decrease site details sync interval to 5 minutes

---

000-vip-init.php
lib/feature/class-feature.php
search/search.php

This PR enables Search Dev Tools for all sites that are using Enterprise Search.
This PR enables Search Dev Tools for all sites that are using Enterprise Search.
2. Enable Enterprise Search
3. Check that the dev tools appear and work.

Enabling Search Dev Tools to all sites

---

phpcs.xml.dist

Configuration values should be put into the `value` attribute, not as a text inside the tag.
The value for the `ignore_warnings_on_exit` options was specified incorrectly.
Has already been tested by the CI jobs in #2367

Fix the configuration option in phpcs.xml.dist

---

files/class-vip-filesystem.php

Handle unsupported `dirsize` requests gracefully to avoid polluting error logs.
1) Clear dirsize cace: `wp --allow-root --path=/var/www eval 'delete_transient("dirsize_cache");'`
1) Run code that fetches dirsize: `wp --allow-root --path=/var/www eval '\Jetpack_Heartbeat::generate_stats_array();'`

Handle unsupported calls to dirsize

---

search/search.php

We have recently introduced a VIP Search UI Widget that consisted of a search box. Given that the widget currently only displays a search box, its functionality is already covered by WordPress' search widget.
We are temporarily disabling our widget to avoid confusion and duplication.
Please use WordPress's Core Search widget instead.
<!--

Temporarily disabling VIP Search UI

---

search/includes/classes/commands/class-corecommand.php

It started as fixing the discrepancy between the ElasticPress command and the Enterprise Search command. We had `start-object-id` and `end-object-id` arguments which was deemed confusing when the PR was merged to the upstream, so it was swapped for `upper-limit-object-id` and `lower-limit-object-id` which is less confusing.  Unfortunately we didn't catch that during the merge.
While fixing it we realized that the command doesn't really explain what do all of those arguments mean so we decided to address that as well.
We've added detailed descriptions for each argument for the indexing command. 
Use `wp help vip-search index` to see them all.
1. Check out the PR
2. Run `wp help vip-search index`
3. Observe that …

Search: add descriptions for the supported named arguments for the index command

---

files/class-vip-filesystem.php

Following @GaryJones comment on @pschoffer PR (https://github.com/Automattic/vip-go-mu-plugins/pull/2370), we are using the predefined `__return_zero` filter instead of a custom function.
Internal code optimizations

Use __return_zero filter for files filter

---

.circleci/config.yml
jetpack.php

Given that we no longer run WordPress 5.4 (or lower) sites on our platform, we are safe to drop the checks for those versions. This PR removes the checks on the Jetpack loading script and also drops the testing pipeline for 5.4.
We are dropping support for WordPress 5.4 or lower in mu-plugins.

Removing Jetpack check for old WP versions

---

jetpack.php

This PR makes Jetpack 10.1 the default version. We are also updating the plugin header from that same latest version.
We are making Jetpack 10.1 the new default version.
2. Make sure you have Jetpack enabled but no version pinned.
3. Check that you're running Jetpack 10.1.

Making Jetpack 10.1 default version

---

admin-notice.php
admin-notice/class-admin-notice-controller.php
admin-notice/class-admin-notice.php
admin-notice/conditions/class-date-condition.php

This PR opens a series of code style fixes; in particular, it deals with the issues found by `phpcs` in `admin-notice` plugin. As a side note, these PRs give me a great opportunity to familiarize myself with the codebase.
I will annotate all found issues except for the whitespace-related ones.
Fix phpcs errors and warnings for admin-notice plugin
1. Run `composer install`
2. Run `vendor/bin/phpcs -s admin-notice.php admin-notice` and observe the reported issues
3. Check out the PR
4. Re-run `vendor/bin/phpcs -s admin-notice.php admin-notice` and make sure that all previously reported issues are gone.

Fix phpcs issues for admin-notice plugin

---

tests/vip-helpers/test-class-user-cleanup.php
vip-helpers/class-user-cleanup.php

If `User_Cleanup::revoke_roles_for_users()` is called with a non-existing user ID, it will try to return a `WP_Error`. However, because of the name resolution rules, PHP will try to use `\Automattic\VIP\Helpers\WP_Error` instead of `\WP_Error`,
which will cause a fatal error.
Fix a fatal error caused by the name resolution rules.
2. Comment out line 5 in `vip-helpers/class-user-cleanup.php`
3. Run `./bin/phpunit-docker.sh tests/vip-helpers/test-class-user-cleanup.php` and observe that it crashes with `Error: Class 'Automattic\VIP\Helpers\WP_Error' not found`
4. Revert the change to `vip-helpers/class-user-cleanup.php` and rerun the tests. Verify that the error is gone.

Fix "Class 'Automattic\VIP\Helpers\WP_Error' not found" in `User_Cleanup::revoke_roles_for_users()`

---

.gitignore

If the `vip` CLI is used to spin up a local development environment, a file (`dev-env-plugin.php`) is created to make things work. We don't want that file to slip into production, hence we are ignoring it through `.gitignore`. 
Internal code change to prevent conflicts with `vip dev-env`.

Ignoring dev-env related file

---

performance/vip-tweaks.php
vip-helpers/vip-caching.php

Removed legacy code from WordPress.com days that cached the comment counts. The `wp_comment_count` function in core now caches the values and this code is no longer used.
Removed legacy code that caused sites with WooCommerce to show the wrong count for total comments in the WordPress Dashboard.
- [ x ] This change works and has been tested locally (or has an appropriate fallback).
- [ x ] This change works and has been tested on a Go sandbox.
- [ x ] I've created a changelog description that aligns with the provided examples.
Closes #1618

Removed legacy code which broke comment counts.

---

files/class-vip-filesystem-stream-wrapper.php

The previous debug mode used `error_log` and `wp_debug_backtrace_summary`, both can be fairly limiting. 
So we're utilizing `debug_backtrace()` which provides more information and and log2logstash as a better logging mechanism.

Re-work streamWrapper debug using log2logstash and more detailed debug backtrace

---

wp-parsely.php

This PR changes the default Parse.ly version from 2.5 to 2.6.
We upgraded Parsely from 2.5 to 2.6.
2. Go to the Parse.ly dashboard and check 2.6 is the enabled version.

Change default Parse.ly to 2.6

---

wp-parsely.php

The code after the last conditional that removes some hooks doesn't work. That happens because `$parsely` is null. This is due to the fact that it has not yet been initialized (initialization of the wp-parsely plugin happens on the `plugins_loaded` hook, whereas this code happens on `muplugins_loaded`).
This PR moves this second part of the logic to the `init` hook, where wp-parsely is already initialized.
Some minor checks on the Parse.ly initialization were not being called.

Hooking Parsely plugin tweaks to init

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php

The current implementation of the `wp vip-search health validate-counts` command is only validating the `Post` and `User` indexables. The goal of this PR is to validate the remaining indexables - `Term` and `Comment`.
Add the remaining missing indexables  - `Term` and `Comment` - to the ES health validation CLI command.
2. If terms and comments are not yet indexed, they will need to be enabled, [per the Enterprise Search documentation](https://docs.wpvip.com/how-tos/vip-search/vip-search-features/#h-terms). If they are, skip this step.
For terms:
```bash
$ wp vip-search activate-feature terms
$ wp vip-search put-mapping --indexables="term"
$ wp vip-search index --indexables="term"
```
For …

Search: Health - Validate counts for terms and comments indexables

---

wp-parsely.php

This PR builds on top of https://github.com/Automattic/vip-go-mu-plugins/pull/2459. We keep the functionality, but we avoid doing a further conditional check by only enqueuing the `init` action once we're sure we loaded Parse.ly through mu-plugins.
Improving the way the wp-parsely plugin is loaded through mu-plugins.
2. Enable Parse.ly through the option. Check no Parse.ly UI is visible on wp-admin.
3. Enable Parse.ly through the filter. Check that the UI is visible now.

Conditionally loading init action on wp-parsely

---

wp-parsely.php

Instead of using potentially problematic `global $parsely`, we're moving to the use of safer `$GLOBALS['parsely']`.
We are implementing a safer way of loading the Parse.ly plugin.

Don't use global declaration on Parse.ly

---

.husky/pre-push
package.json

This PR fixes the pre-push hook by reading the entire stdin before invoking `phpcs`.
The issue arose because the pre-push hook receives a list of to-be-updated refs through stdin. When our hook invoked `phcs` via `npm run phpcs:changed:remote`, `phpcs` saw that the stdin is not empty and tried to read the code to check from it *instead of* reading the files specified in its configuration file. I confirmed this with `vendor/bin/phpcs -vsp`:
```
+ vendor/bin/phpcs -vsp
Registering sniffs in the VIP-Go-mu-plugins standard... DONE (291 sniffs registered)
Changing into directory .
Processing STDIN [PHP => 1 tokens in 1 lines]... DONE in 6ms (0 errors, 0 warnings)
Time: 128ms; Memory: 14MB
```
The fix is to clear the stdin before invoking `phpcs`.
* Fix the `pre-push` hook.
* Improve …

Fix the pre-push Git hook

---

000-pre-vip-config/requires.php

We have a bunch of "secret sauce" that was loaded prior to vip-config.php but wasn't exposed anywhere, there's no particularly good reason to do so. Furthermore, it's a bit annoying because it's opaque and in case customers don't use our Local Dev Env they'll no doubt will be tripped up by that. 
This PR aims to address the issue by introducing a new folder, which is very explicitly named `000-pre-vip-config`. This needs to be accompanied with:
Previously we included a few classes, notably VIP_Request_Block and our custom error handler very early in the bootstrap, prior to loading the `vip-config.php`. Although those files are located in mu-plugins we didn't load them from there. 
We've made a change to include `000-pre-vip-config/requires.php` that will now contain those early …

Create a new folder 000-pre-vip-config and move all the requires that happen before vip-config.php there for better visibility

---

.circleci/config.yml

WordPress versions we use in our tests lag behind the latest releases. This PR fixes that.
Use the latest versions of WordPress to run tests.

Use the latest available WordPress versions for tests

---

search/includes/classes/class-search.php

There seems to be a lot of index_not_found_exception errors in our logs stemming from the cron `maybe_alert_for_field_count` which calls `get_current_field_count()` — it attempts to do a GET request on an index that doesn't exist. We should return early if index does not exist.
No need to perform a remote request since it will throw an index_not_found_exception.
1) Check out PR
2) Spin up search site
3) If index exists, delete it `wp vip-search delete-index`
4) Use `Automattic\VIP\Search\Search::instance()->maybe_alert_for_field_count();` to see if `$current_field_count` returns NULL.

Search: Do not perform current field count if no index exists

---

bin/phpunit-docker.sh

This PR changes the MariaDB image used to run local tests from `mariadb/server` to `mariadb`. The first one is deprecated and it is not compatible with ARM architectures (like the M1 Mac series).
Improving tooling for local development and testing.
1. Check out this PR.
2. Run `composer install`
3. Run the tests (make sure Docker is running): `bin/phpunit-docker.sh`

Change local Maria testing image

---

jetpack.php

The default Jetpack version will be the 10.3 subtree
We upgraded Jetpack 10.2 to Jetpack 10.3
Jetpack 10.3 contains many new updates and more information can be found here: [Jetpack 10.3 Release](https://jetpack.com/2021/11/02/jetpack-10-3-under-the-hood-improvements-for-your-site/) .
- [] This change works and has been tested on a Go sandbox.
- [] This change has relevant unit tests (if applicable).
1. Run WP
1. Log into wp-admin
1. Verify Jetpack is 10.3

Bump Jetpack Version to 10.3 Release

---

search/includes/classes/class-healthjob.php

We should stagger the scheduling of health jobs to ensure the health of our clusters.
To ensure the integrity of our clusters.

Search: Stagger health jobs scheduling

---

wp-cli/vip-data-cleanup.php

Show success messages after data cleanup CLIs are completed. Helps make the job logs a bit more tidy and clear when the CLIs have finished successfully.
n/a (can skip this from changelog)
- `wp vip data-cleanup datasync`
- `wp vip data-cleanup sql-import`

CLI: Add success messages after data cleanup CLIs

---

jetpack-start/wp-cli-provision.php

This function has been deprecated since 9.5 and removed in 10.3. See https://github.com/Automattic/jetpack/pull/16434
Update `jetpack-start` to use modern function.
Unsure personally. Reported in vip-jetpack via p1636058453047900-slack-CDD9LQRSN

jetpack-start: Update to use modern function

---

search/includes/classes/class-health.php

Implement a randomized delay between batches to give ES clusters a bit of breathing space because large content validations can put a strain on them.
This will only run if it's in the CLI context and the `silent` flag is passed. 
We've implemented a delay between validation batches to minimize the chances of causing a resource strain during periodic content validation.

Search: Implement delay between content validation batches

---

search/search-dev-tools/package-lock.json
search/search-dev-tools/package.json

This PR updates dependencies for Search Dev Tools to fix security issues.
Update development dependencies to fix security issues:
* bump @babel/eslint-parser from 7.15.8 to 7.16.0
* bump eslint-plugin-import from 2.24.2 to 2.25.2
* bump eslint-config-wpvip to Automattic/eslint-config-wpvip#d0aa883793f9fb9030112b8f60c947fbc3052e3a
* update ansi-regex to 5.0.1 (fix CVE-2021-3807)
* update glob-parent to 5.1.2 (fix CVE-2020-28469)
* update lodash to 4.17.21 (fix CVE-2021-23337)
* update path-parse to 1.0.7 (fix CVE-2021-23343)

Search Dev Tools: update dependencies

---

search/search-dev-tools/search-dev-tools.php

This PR improves the cacheability of Search Dev Tools' static assets.
Currently, the plugin enqueues its static assets so that the browser has to re-download them on every request, even if the assets haven't changed. This PR changes that by using the file modification time as the version string (vs the current time).
Improve cacheability of the static assets.
N/A

Search Dev Tools: do not bust assets cache for every request

---

search/includes/classes/class-health.php
tests/search/includes/classes/test-class-health.php

This PR fixes the `Invalid argument supplied for foreach() in /wp-content/mu-plugins/search/includes/classes/class-health.php on line 777` warning, which happens when one of the keys contains a `null` value.
Fix PHP warning in `Health::diff_document_and_prepared_document()`
Added a unit test for this case — the CI should pass.

Fix 'Invalid value supplied for foreach' warning

---

vip-parsely/vip-parsely.php

We've been running the Parse.ly telemetry option for some time now on staging sites without any issues. We can now enable it by default to all sites.
We enabled Parse.ly telemetry for all sites that have Parse.ly enabled.

Enabling Parse.ly telemetry by default

---

performance/bulk-edit.php

`esc_html__` was used on a HTML string. This PR removes it.
Fix overescaping of a notification message.

Fix overescaping when displaying "Bulk actions disabled" notice

---

akismet.php

We introduced a couple of filters that checked if Akismet was correctly installed and active, and if that wasn't the case, it would hide some elements from `wp-admin`. This comes at the cost of an additional HTTP request, that might impact the server's performance. 
Given the fact that Akismet is always enabled (unless Jetpack is not) and VIP's Connection Pilot should connect it automatically, we no longer need to hide those messages. The only situation in which they would show up and they would redirect to a non-connected site is when CP fails, in which case is fine that the user sees that something is wrong.
Getting rid of some custom code regarding Akismet messaging.
1. Check out PR on a Sandbox.
2. …

Removing custom Akismet filters

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-versioncommand.php

This PR fixes two issues:
* `get_error_message()` called on `Exception` object instead of `getMessage()`;
* `get_error_message()` on a wrong/uninitialized variable.
* Bug fix: `get_error_message()` called on `Exception` object instead of `getMessage()`
* Bug fix: when `get_error_message()` was called on a uninitialized variable in wp-cli commands
N/A — we don't have tests (yet) that could have caught this bug.

Fix incorrect invocation of get_error_message()

---

search/includes/classes/class-health.php
tests/search/includes/classes/test-class-health.php

Related to #2603 and fixes more cases that could generate the warning.
Fix PHP warning in Health::diff_document_and_prepared_document()
Added a unit test for this case — the CI should pass.

Make sure that *diff_document_and_prepared_document receives an array

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

We should not be logging any remote calls to `index_exists` as a failed request. 
`index_exists()` [does a remote request to determine if a 200 or a 404 is being returned](https://github.com/Automattic/ElasticPress/blob/fef833793a85e0229bf6fa3f66ba75333f00d8c8/includes/classes/Elasticsearch.php#L1001-L1023), but if there's no index, it gets logged as a failed request: https://github.com/Automattic/vip-go-mu-plugins/blob/3ee96e7db66a9345858f66eb0f28bd23c0172280/search/includes/classes/class-search.php#L729-L730
** DEPLOY NOTE: THIS MUST GO OUT AFTER (or in tandem with) https://github.com/Automattic/vip-go-mu-plugins/pull/2621 **

Search: Bail and do not log when request is index_exists

---

bin/test.sh

This PR adds a more powerful alternative to `bin/phpunit-docker.sh`.
Its features:
* supports multiple PHP versions (7.4, 8.0, 8.1), available via `--php` parameter (7.4 is the default one);
* supports multiple PHPUnit versions (7, 8, 9), available via `--phpunit` parameter (the default is the one bundled with the application);
* supports passing extra command-line arguments to PHP (`--php-options` parameter); this can be useful to profile slow tests; this feature depends on Automattic/vip-container-images#46;
* can use the existing MySQL database server for tests (`--network` and `--dbhost` parameters), which eliminates the need to create, start, and stop MySQL for every invocation.
Among other things, it is faster than the old `phpunit-docker.sh`.
This runner:
```
PHPUnit 7.5.20 by …
```

Add more powerful test runner for local development

---

search/includes/classes/class-healthjob.php

The validate-contents job can be scheduled from 1-7 days and then, 1-24 hours after that point to ensure that if jobs are scheduled on the same day, they aren't the same hour.

Search: stagger validate-contents job more

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

My lizard brain forgot that it's the order you pass in, not by parameter name 🥇 

Search: filter__ep_do_intercept_request: Account for $failures parameter

---

search/includes/classes/class-versioning.php
tests/search/includes/classes/test-class-versioning.php

When a new index version is created but it hasn't been indexed yet, it will have no posts in it. If you attempt to delete a post, it will attempt to delete the post from the inactive index as well. We should check that the post exists before attempting to delete it.
Reproduction Steps:
1) Create some posts
2) Index: `wp vip-search index`
3) Add new index version `wp vip-search index-versions add post`
4) Delete a post
5) See logging:
```
wp_trash_post, wp_update_post, wp_insert_post, do_action('wp_insert_post'), WP_Hook->do_action, WP_Hook->apply_filters, ElasticPress\\\\Indexable\\\\Post\\\\SyncManager->action_sync_on_update, ElasticPress\\\\Indexable\\\\Post\\\\SyncManager->action_delete_post, …
```

Search: Check object exists before attempting to delete object

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

Kind of a part 2 to https://github.com/Automattic/vip-go-mu-plugins/pull/2629.
Similar to what we did in https://github.com/Automattic/vip-go-mu-plugins/pull/2620. We should not be logging if we call `$indexable->get()` on a non-existent post (object) since I wouldn't exactly call that a failed request either. 
1) Pull down PR
2) Open wp shell
3) `$indexable = \ElasticPress\Indexables::factory()->get( 'post' );`
4) `$indexable->get( 1821312123123123123123 );`
5) Notice no `search_query_error` being logged

Search: Do not log on $indexable->get() for non-existent posts

---

.circleci/config.yml
bin/test.sh
tests/bootstrap.php
tests/cache/mock-header.php
tests/cache/test-vary-cache.php
tests/files/acl/mock-header.php
tests/files/acl/test-acl.php
tests/mock-header.php
tests/search/includes/classes/mock-header.php
tests/search/includes/classes/test-class-search.php

This PR tries to speed up our CI by eliminating the dependency on XDebug and mocking `header()` and related functions for tests that use it. In many cases, this also allowed us to get rid of the `@runInSeparateProcess` annotation, which also positively affected performance.
On averages, the builds are now 1 to 2 minutes faster (I guess that depends on CircleCI's workload, need to test this in a more quiet time). Well, it ain't much but it's honest work :grinning:

Remove XDebug and Speed Up CI

---

tests/search/includes/classes/test-class-search.php

`Search::filter__ep_pre_request_host()` is declared with two arguments (`$host`, `$failures`), but our tests pass four arguments to it.
This PR fixes those calls.

Remove extra arguments passed to filter__ep_pre_request_host()

---

000-vip-init.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

- Lower the max backoff for connection attempts to once a week.
- Cleanup cron registration:
- Remove the internal job
- Unregister the job when auto-connections are disabled
- Limit conditions when it is registered
- Expose CLI command regardless of `VIP_JETPACK_AUTO_MANAGE_CONNECTION` 
Lower the max backoff time for connection attempts, and unregister the cron job when it's not needed.
Not much to test here, but could disable `VIP_JETPACK_AUTO_MANAGE_CONNECTION` and ensure the job is gone (keep batch containers in mind).
And then manually set a backoff factor to something more than 24 * 7 and set an old timestamp, then ensure the event still runs. Unit tests cover this already though :)

Cleanup JP connection pilot cron registration & run conditions

---

lib/utils/class-alerts.php
tests/lib/utils/class-testable-alerts.php
tests/lib/utils/test-alerts.php

I have refactored Alerts tests so that they don't have to be run in a separate process.
The main changes are:
* the testable methods are now `protected`, not `private`. This allows us not to use the Reflection API and makes tests more readable;
* I have introduced two `protected static` helper methods: `get_service_address()` and `get_service_port`. They can be overridden by a descendant; their raison d'être is to allow us not to use PHP constants and, as a consequence, to be able to run all tests in a single process;
* another helper method is `clear_instance()`: because Singletons are hard to test :-( 
With these changes, it takes 2.68 seconds to complete the tests (vs 1.08 minutes).

Make Alerts more testable

---

tests/test-vip-mail.php

Just like #2633 but for VIP Mail tests: refactor `@runInSeparateProcess` tests so that they don't need a separate process to run.

Refactor mail tests

---

tests/logstash/class-testable-logger.php
tests/logstash/test-logger.php

Refactor Logger tests:
* do not use Reflection API;
* run tests in the same process.

Refactor Logger tests

---

tests/security/test-password.php

Refactor password tests to allow them to run in a single process.
This PR adds the necessary clean-up logic, and drops `@runInSeparateProcess` declarations for `test-password.php`.
Timings (for my local environment, it is *slower* than CircleCI):
* before: 21.34 seconds
* after: 3.95 seconds

Refactor password tests

---

tests/test-cache-purge-term.php

Refactor term purging tests to allow them to run in a single process.
Time before: 20.39 seconds
Time after: 2.57 seconds

Refactor term purging tests

---

security/class-lockout.php
security/class-private-sites.php
tests/bootstrap.php
tests/mock-constants.php
tests/security/test-class-private-sites.php
tests/security/test-lockout.php

This PR refactors tests for Private Sites and Lockouts and Warnings by mocking all calls to `defined()` and `constant()`; this allows us to run all those tests in a single process.
For this to work, I had to patch `security/class-private-sites.php` and `security/class-lockout.php` to use `constant()` instead of accessing constants directly.
Mocking relies upon the [name resolution rules](http://php.net/manual/en/language.namespaces.rules.php) of PHP namespaces. However, because the PHP compiler tries to optimize away all calls to `defined()`, it is crucial that the mock is loaded before the tested class.
Timings (PS + Lockout)
* Before: 23.92 seconds + 31.89 seconds
* After: 2.68 seconds + 3.53 seconds

Refactor tests for private sites and Lockout component

---

search/includes/classes/class-healthjob.php

Since we have more than one cron job, we should make the constants more descriptive for better readability.

Search: Make constants used for the healthcheck job more descriptive

---

tests/test-vip-cache-manager.php

This PR removes the `@runTestsInSeparateProcesses` declaration from `VIP_Go_Cache_Manager_Test`, as the tests seem safe to run in the same process.
Timings:
* before: 25.2 seconds
* after: 3.88 seconds

Run VIP Cache Manager tests in a single process

---

tests/lib/environment/test-class-environment.php
tests/lib/helpers/test-environment.php
tests/mock-constants.php

Refactor Environment tests to allow them to run in a single process.
Timings (tests/lib/environment/test-class-environment.php + tests/lib/helpers/test-environment.php):
* before: 51.87 seconds + 17.36 seconds
* after: 2.97 seconds + 2.8 seconds

Refactor Environment tests

---

search/includes/classes/class-search.php

We should start caching index_exists requests since we use it as a check in many places (e.g. get_current_field_count).
Cache index_exists requests into an option.
1) Check out PR
2) Shell in
3) Do an index_exists request:
```
$indexable = \ElasticPress\Indexables::factory()->get( 'post' );
$indexable->index_exists();
```
4) Check it exists in the option: `wp option get es_index_exists_vip-200508-post-1` (you may need to change it accordingly to your index name since the format is `es_index_exists_<index-name>`
5) Delete the index: `wp vip-search delete-index`
6) Check the option does not exist `wp option get es_index_exists_vip-200508-post-1`

Search: Cache index_exists requests

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php
tests/mock-constants.php

Refactor Vary Cache tests to allow them to run in a single process.
Timings:
* before: 27.38 seconds
* after: 2.61 seconds

Refactor Vary Cache tests

---

bin/test.sh

Add `--docker-options options` command-line switch to pass extra options to `docker`.
Usage example:
```bash
./bin/test.sh --multisite 1 --docker-options '-e WPVIP_PARSELY_INTEGRATION_TEST_MODE=filter_enabled'
```

Update test runner

---

.deployignore
wp-parsely-3.0/.github/dependabot.yml
wp-parsely-3.0/.github/workflows/deploy.yml
wp-parsely-3.0/.github/workflows/e2e-tests.yml
wp-parsely-3.0/.github/workflows/node.js.yml
wp-parsely-3.0/CHANGELOG.md
wp-parsely-3.0/README.md
wp-parsely-3.0/src/UI/class-settings-page.php
wp-parsely-3.0/src/class-parsely.php
wp-parsely-3.0/tests/e2e/README.md
wp-parsely-3.0/tests/e2e/specs/activation-flow.spec.js
wp-parsely-3.0/tests/e2e/specs/plugin-action-link.spec.js
wp-parsely-3.0/tests/e2e/specs/recommended-widget.spec.js
wp-parsely-3.0/tests/e2e/utils.js
wp-parsely-3.0/wp-parsely.php

This PR pulls the latest version of the 3.0.0 release of the wp-parsely plugin (Release Candidate 2). The following command was run:
```
bin/manage-wp-parsely-subtree.sh 3.0 3.0.0-RC2 
```
Pulling the latest version of wp-parsely.

Updating Parsely 3.0 to 3.0.0-RC2

---

001-core/privacy.php

Fixes #2677
The `generate_personal_data_export_file` function generates an error when it is trying to generate the personal data report when the report has its `_export_file_path` meta set to `/` or any other existing dir path. 
It isn't expected to store a dir path in this meta filed, but it can happen if a filter is used or if the meta value is manually/programmatically updated (it happened to a customer already).
When this happens, the `wp_delete_file` function ([here](https://github.com/Automattic/vip-go-mu-plugins/blob/7624078badd666531b5a3ccc67d7c51ac719e128/001-core/privacy.php#L268)) fails because it is expecting the path of a file to be deleted. This also causes some orphaned files in the `/tmp/` folder, as [the code that is designed to unlink the previously generated JSON and …

 Ensure the file exists before trying to delete it

---

akismet.php

Akismet will check for the constant: "VIP_AKISMET_SKIP_LOAD"  when it loads.
If the value is set to `true` the plugin will be disabled.
The Akismet plugin, in Must-Use plugins, may now be disabled by adding the "VIP_AKISMET_SKIP_LOAD" constant, and setting the value to "true".
1. Add a line with: `define( 'VIP_AKISMET_SKIP_LOAD', true );` to wp-config.php or wp-config-multisite.php 
1. The Akismet Anti-Spam sub-menu should be missing

Adds "VIP_AKISMET_SKIP_LOAD" constant to allow disabling of Akismet

---

000-debug/debug-mode.php
search/includes/classes/class-search.php
vip-helpers/class-user-cleanup.php
vip-helpers/vip-utils.php

This PR fixes incompatibilities with PHP 8.1 described in #2667.
Fix incompatibilities with PHP 8.1
Fix incompatibilities with PHP 8.1
Fix incompatibilities with PHP 8.1
The CI should pass; PHP 8.1 will still fail.

Fix incompatibilities with PHP 8.1

---

logstash/class-logger.php
tests/logstash/test-logger.php

Currently, we have a cut-off of 30 logstash entries per request, as a failsafe. The problem is we call trigger_error when we're over the threshold. This leads to an unhelpful situation where a useful log entry gets replaced by an unuseful generic error not providing any information beyond the fact that it happened.
This PR increases the limit to 100 for web requests and 500 for CLI requests - this may change pending feedback.
When a threshold is crossed only one E_USER_WARNING is triggered.
Additionally, this PR also surfaces user agent for request (if available) 
We've updated the internal logging library to surface the user agent information for custom log entries and to increase the maximum number of logs to be processed during a single request.
Please make sure the items below have …

Increase the logstash limit to 100 in web and 500 in CLI contexts and set 'http_user_agent' based on _SERVER['HTTP_USER_AGENT']

---

search/includes/classes/queue/class-cron.php
tests/search/includes/classes/queue/test-class-cron.php

Reduce the maximum amount of jobs to 3 to reduce indexing pressure.
Don't log the fact the processor job couldn't be scheduled as it's correct behavior in case the concurrency limit is hit. 
We've reduced the maximum number of concurrent jobs to prevent indexing operations potentially affecting search performance. 

Reduce the maximum amount of jobs to 3 to reduce indexing pressure

---

cron/action-scheduler-dynamic-queue.php

Followup fix for https://github.com/Automattic/vip-go-mu-plugins/pull/2441, since svn pre-commit hooks aren't updated yet.
Skipping changelog on this one.

Action schedule dynamic queue: drop php 7.4 syntax

---

performance/vip-tweaks.php

Follow-up to https://github.com/Automattic/vip-go-mu-plugins/pull/1883.
tl;dr, the query to generate the year/month filter dropdown on posts pages can be a bit expensive on large sites and is never cached. There is a new filter in WP core that will allow us to intercept and cache the results: https://core.trac.wordpress.org/ticket/51660
To prevent an expensive query occurring on every admin posts-edit page load, this caches the available months/years for the dropdown filter.
1. Go to a listing page e.g.: `/wp-admin/edit.php` or a custom post type listing page (`/wp-admin/edit.php?post_type=myCustomPostType`) or media library (`/wp-admin/upload.php`)
2. When the page is first loaded, the query should take place …

Add caching to the months dropdown filter for posts

---

vip-helpers/class-user-cleanup.php
wp-cli/class-vip-user-cli-command.php

Remove unused filter / constant that allows bypassing user cleanup. Removing this filter would allow us to pass `--skip-plugins` and `--skip-themes` when running this command and fix the many instances when this command fails due to customer code.
"Unused" has been verified by a search of VIP codebases and environment variable names. However, this probably needs more scrutiny.
Remove filter `vip_do_user_cleanup` and related constant `VIP_SKIP_USER_CLEANUP`. This allows us to skip loading of plugins and themes when removing Automattic users from VIP sites.

Remove ununsed filter / constant to improve user cleanup command

---

plugin-fixes.php

Fixes #2710 
This changes our Contact Form 7 workaround to use a subdirectory rather than storing files directly in `/tmp`, which CF7 then tries to clean-up, including any unrelated files.
Changed path of `WPCF7_UPLOADS_TMP_DIR` to use a subdirectory of `/tmp`
1. Install and activate a recent version of Contact Form 7 on a VIP Go site and sandbox it.
2. Check for the presence of `/tmp/cf7`
3. On the sandbox, add some files directly to `/tmp` both as a privileged user and unprivileged user
4. The cleanup is initiated on `template_redirect` so navigate through some pages.
5. Check logs for warnings for failed deletes to files in the `/tmp` dir
6. Check for removed files added as an unprivileged user in `/tmp`. …

Use a sub-directory for CF7 uploads to avoid CF7 cleanup deleting unrelated files

---

search/includes/classes/class-search.php

This PR refactors error handling in the `filter__ep_do_intercept_request()` function by moving invariant function calls out of the loop.
Refactor error handling by moving expensive function calls out of the loop.

Move invariant function calls out of the loop

---

search/includes/classes/class-search.php

Inspired by #2703, let's re-factor the functionality of `get_cached_index_exists_request` and `invalidate_cached_index_exists_request` into one filter: `filter__ep_do_intercept_request`. This way we can ensure no requests are made when concurrency is hit.
Test to ensure that index_exists caching and invalidation of it is still functional:
1) Shell in
2) Make an index exists request:
```
$indexable = \ElasticPress\Indexables::factory()->get( 'post' );
$indexable->index_exists();
```
3) get the option to ensure it's cached: `get_option( 'es_index_exists_vip-200508-post-1' );`
4) delete index `wp vip-search delete-index`
5) repeat `#3` but ensure it returns false

Search: Combine other filters into filter__ep_do_intercept_request

---

plugin-fixes.php
search/includes/classes/class-search.php

Since we want to add more information to our `search_http_error` errors, let's just re-factor it into the same logging code piece for `search_query_error`.

Search: Add more information to search_http_error logging

---

search/includes/classes/class-search.php

Since only need to cache if the response is a 200 or 404. All other ones (i.e. 410) should be ignored and not cached. If a bad response has been stored, invalidate it.
Only cache index_exists requests that are valid. Invalidate if response code is not in safelist.
To test the actual caching of the index_exists option:
1) Make an index_exists request:
```
$indexable = \ElasticPress\Indexables::factory()->get( 'post' );
$indexable->index_exists();
```
2) Get the option `wp option get es_index_exists_vip-200508-post-1`

Search: For index_exists cached option, only cache if response code is valid

---

search/includes/classes/class-healthjob.php

It's not necessary to alert that a validate-contents error occurred if it's just a validation that's already ongoing.

Search: Do not alert as an error if content validation is already ongoing

---

search/includes/classes/class-search.php

To reduce the noise, let's add caching for the queue count and alert when the queue count isn't decreasing. 

Search: Alert if we don't have a queue count value cached OR if the queue count isn't decreasing

---

search/includes/classes/class-healthjob.php

The autohealing alert is not necessary — I think we only need to alert if an error occurred. Otherwise, it's safe to assume that it went fine and dandy.

Search: remove autohealing alert

---

search/includes/classes/class-search.php
search/includes/classes/class-syncmanager-helper.php
tests/search/includes/classes/test-syncmanager-helper.php

Implementation of @rinatkhaziev's Automattic/ElasticPress#132 for mu-plugins
Do not synchronize index on term updates that update nothing (e.g., when a user clicks Save without modifying anything).
The CI should pass — I have added unit tests for this feature.

Do not sync index on fake term updates

---

search/includes/classes/commands/class-queuecommand.php

Remove `stress-test`. It was a subcommand from the early days of the product, we don't really need it anymore, because we have plenty of real-world usage.
Introduce `purge` subcommand to be able to quickly remove all items from queue.
We've introduced `wp vip-search queue purge` command that would clear everything from async index queue.
Examle usage: 
> wp vip-search queue purge
1. Run `wp vip-search queue purge`, verify it asks for confirmation
1. Run `wp vip-search queue purge --skip-confirm`, verify it doesn't ask for confirmation
1. Verify the queue is actually empty

Search: rework the queue command, remove the stress-queue subcommand and introduce purge subcommand

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

If the response code and message are available, we should return those instead of the generic default error message for better details.
1) Make a bad request
2) Expect to see the response code and message returned in the logging

Search: Add response code and message if available

---

tests/search/includes/classes/test-class-versioning.php

Tests for WP trunk [fail](https://app.circleci.com/pipelines/github/Automattic/vip-go-mu-plugins/9248/workflows/fbf2e035-0f44-4be1-8eee-7b693fc44074/jobs/88669) because of the modifications to how the blocks are registered (arre yaar, I wish there was a way to tell WP not to load all that block stuff if I don't need it).
Here I am trying to fix that.

Fix tests for WP trunk

---

search/includes/classes/class-search.php
search/includes/classes/class-syncmanager-helper.php

This adds basic invalidation via adding `last_changed` as a suffix for the cache key.
We have implemented cache invalidation after index and bulk index to make sure that any cached requests will not use stale data.
2. Hit a search `?s=test`
3. Open Debug Bar or Query Monitor and verify there's a remote request to ES
4. Hit the search again
5. Verify there's no request
6. Perform an action that results in an indexing (e.g. save a post)
7. Hit the search again and verify the request is made again.

Search: Basic request cache invalidation via last_changed approach

---

.gitmodules
001-cron.php

Add new submodule pointing towards https://github.com/Automattic/Cron-Control/pull/231 to allow for a a slow rollout / incremental testing. Nothing is currently using the new constant, so this PR wont' have any effect on its own.
Initial plan was to replace the existing `VIP_CRON_CONTROL_USE_NEXT_VERSION` instance, but there are a handful of production sites using it still - and would prefer to not push out to productions right away.
Once we are done w/ the rollout, all additional instances will be removed and just `cron-control` will remain w/ the updated version.
1. Add `define( 'VIP_CRON_CONTROL_USE_NEXT_VERSION_V2', true );` to vip-config.php
2. Check that new version of cron control is loaded.
Note: the …

Add "cron control next, v2" submodule

---

phpcs.xml.dist

Exclude `cron-control-next-v2` from PHPCS checks.

Exclude cron-control-next-v2 from linting

---

composer.json

This PR adds support for Composer 2.2.
Composer 2.2 introduces [more secure plugin execution](https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution) and this PR adds support for it.
The idea was taken from Parsely/wp-parsely#559 :-)

Support Composer 2.2

---

tests/search/includes/classes/test-class-queue.php

Ref: https://app.circleci.com/pipelines/github/Automattic/vip-go-mu-plugins/9317/workflows/0fb186e8-f2c8-496f-9e21-4f3b2cb19fd4/jobs/89967
> 1) Automattic\VIP\Search\Queue_Test::test_checkout_jobs
> Job 3 has the wrong scheduled_time
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'2021-12-24 02:59:01'
> +'2021-12-24 02:59:02'
This happens when the `$expected_scheduled_time` value is captured on the last microseconds of the current second; `checkout_jobs()` happens then the next second and the test fails. This PR tries to fix it.

Fix flaky test

---

composer.lock

- Upgrading mustache/mustache (v2.13.0 => v2.14.0)
- Upgrading phpdocumentor/reflection-docblock (5.2.2 => 5.3.0)
- Upgrading phpspec/prophecy (1.14.0 => v1.15.0)
- Upgrading phpunit/php-file-iterator (2.0.4 => 2.0.5)
- Upgrading sebastian/exporter (3.1.3 => 3.1.4)
- Upgrading squizlabs/php_codesniffer (3.6.0 => 3.6.2)
- Upgrading symfony/finder (v5.3.7 => v5.4.0)

Update PHP transient development dependencies

---

lib/class-vip-request-block.php
tests/lib/test-vip-request-block.php

The original implementation of `VIP_Request_Block::ip()` incorrectly handles the `X-Forwarded-For` header, which sometimes leads to up to 2,625 additional IPs being blocked. This PR attempts to fix this issue.
For example, `VIP_Request_Block::ip( '1.1.1.1' )` could result in `11.1.1.1`, `21.1.1.1`,…, `251.1.1.199` being blocked.
As a side effect, this PR makes the `VIP_Request_Block` class more testable.
The plugin now correctly handles partial IP matches in the X-Forwarded-For header.
I have added a test for my bug fix. The CI should pass.

Fix X-Forwarded-For in VIP_Request_Block

---

search/includes/classes/class-settingshealthjob.php
tests/search/includes/classes/test-class-settingshealthjob.php

1) There is redundant alerting in `heal_index_settings()`. The same alerting logic lives in `process_indexables_settings_health_results()`, albeit with different wording:
- https://github.com/Automattic/vip-go-mu-plugins/blob/21052843b3b037453f2e5bf14dbb74d000e125e2/search/includes/classes/class-settingshealthjob.php#L96-L102
- https://github.com/Automattic/vip-go-mu-plugins/blob/21052843b3b037453f2e5bf14dbb74d000e125e2/search/includes/classes/class-settingshealthjob.php#L106-L111
2) I don't think it's necessary to alert when index settings are updated, just when there is failure of some sort, so let's remove that.

Search: Remove redundant alerting from heal_index_settings 

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

Instead of a `foreach` check using Jetpack's helper function  `wp_in` this check can be simplified by using a regex.

Better check for if current query is cacheable

---

search/search-dev-tools/search-dev-tools.php

There's a potential fatal in the rest endpoint for Search dev tools when a request times out due to the fact that WP_Error was treated as an array. This PR addresses that by explicitly checking for `is_wp_error` and handling appropriately.
Enterprise Search Dev Tools now correctly handle requests that have timed out
1. Apply the PR
2. Load a search page and pop the dev tools open
3. in Search::filter_Do_intercept_request break an URL in any way (e.g. domain)
4. try to run a query from Search Dev Tools
5. Now you should see the correct message in the response section instead of a 500.

Search Dev Tools: prevent potential fatals on requests that resulted in a WP_Error (timeouts/connectivity issues)

---

search/includes/classes/class-queue.php

#2722 introduced the prevention of performing any actions on immaterial term updates. However, it was pointed out by @rinatkhaziev that we are still offloading ALL term updates:
https://github.com/Automattic/vip-go-mu-plugins/blob/41c4b4ac10c08dbfd0a9d5ad3faaa64ea1614ba3/search/includes/classes/class-queue.php#L263
This PR uses the value of the filter `ep_skip_action_edited_term` derived from `SyncManager_Helper ` to check before we perform any logic towards offloading the term update. It also adjusts the hook to use a later one to ensure we have the filtered value. 
Skip offloading immaterial term updates to queue.
1) Create a category called "Fruits"
2) Go to the edit page for "Fruits"
3) Make no changes and …

Search: Do not do any offloading if we are skipping term actions

---

.github/workflows/e2e.yml

colors@1.4.1 still has the bad code; it does not show up because the dependencies are probably using `colors/safe`; still, we need to fix this.
Ref: #2788

E2E: Roll back to colors@1.4.0 instead of 1.4.1

---

.github/workflows/e2e.yml

This PR undoes the fix to the `vip` package for the broken version of `colors` introduced in #2788 
It must not be merged until `vip` gets rid of the `colors` package.
OK to merge, we released `@automattic/vip` 2.7.1 yesterday.

E2E: Undo 'colors' fix

---

search/includes/classes/class-settingshealthjob.php
tests/search/includes/classes/test-class-settingshealthjob.php

In `build_new_job()`, pass in the slug rather than the entire object since we don't need it and I want to prevent any potential bugs that occur during serialization/deserialization.

Search: in build_new_job(), pass in string slug instead

---

files/class-meta-updater.php

This PR mainly adds logging for `get_filesize_from_file()` and some logic to ignore 404 errors for metadata updates.
Ignore 404 errors on metadata updates.
N/A

CANTINA-848: ignore 404 errors in update_attachment_meta()

---

search/includes/classes/class-health.php

It is not necessary to check the index settings for inconsistencies on an inactive version.
1) Add some "bad" settings to current index "1", e.g.
```
$bad_settings = [ 'index.number_of_replicas' => 8, 'index.max_result_window' => 50 ];
$indexable = \ElasticPress\Indexables::factory()->get( 'post' );
$indexable-> update_index_settings( $bad_settings );
```
2) Create a new post index version "2" `wp vip-search index-versions add post`
3) Swap to the new index "2" `wp vip-search index-versions activate post next`
4) Ensure that the old index "1" isn't returned from `get_index_settings_health_for_all_indexables()`

Search: Only check index settings for active version

---

000-pre-vip-config/requires.php
000-vip-init.php

#2758 had to be reverted because of a sudden spike in errors; supposedly, that was because of the asynchronous nature of deployments: if the "main" code gets updated before `requires.php` does, this will cause fatal errors.
We now want to try another approach: first, deploy the code that makes the Context class globally available. After that, try to deploy the rest of the original PR.
`Context` class is now available in a single-site mode.
Unfortunately, tests do not catch the bugs here :-(

Make Context available for non-MU sites

---

search/includes/classes/commands/class-healthcommand.php

Just fixing the code command examples that still have `vip-es` (the previous name for the command).

Search: Fix remnants of "vip-es" in code command examples

---

search/includes/classes/class-search.php

The `_open` action needs a longer timeout or else the request will fail due to the short timeout, which causes `open_index` to fail: https://github.com/Automattic/ElasticPress/blob/139dc6ce4d9aa82724bf8828cf1c3624ac3462dc/includes/classes/Elasticsearch.php#L905.
Increase timeout for _open actions
1) Call `open_index()` and see it fail
2) Apply PR
3) Call `open_index()` again and see it successfully return a 200

Search: Increase timeout for _open actions

---

wp-parsely-3.0/src/Integrations/class-amp.php
wp-parsely-3.0/src/class-parsely.php
wp-parsely.php

Fixing some errors we saw on Parse.ly 3.0 due to type errors. This PR makes some additional checks on parameters to ensure types are always consistent.
This PR changes files on the wp-parsely source code. We will back port them to the main plugin.
Fixes potential issues on wp-parsely 3.0.
2. Activate Parse.ly on your site and check it renders correctly.

Fixing Parse.ly 3.0 release

---

wp-parsely-3.0/src/class-parsely.php

Fixes an issue when the `name` property of a term would not be defined on some circumstances.
Fix an issue when getting the terms.

Fix empty name on Parse.ly 3.0

---

wp-parsely-3.0/src/Integrations/class-amp.php
wp-parsely-3.0/src/class-parsely.php
wp-parsely.php

Fixing some errors we saw on Parse.ly 3.0 due to type errors. This PR makes some additional checks on parameters to ensure types are always consistent.
This PR changes files on the wp-parsely source code. We will back port them to the main plugin.
This pulls in previous fixes in #2823 & #2824 (which got reverted in #2826 & #2825, respectively) & also adds  a couple of additional fixes to guard against type errors.
Fix type errors on Parse.ly 3.0
Fix two issues when getting metadata in certain circumstances.
* Run the main branch.
* Add the following to an mu-plugin:
```
add_filter( 'get_term', function ( $term, $taxonomy ) {
if ( 'category' === $taxonomy && 'uncategorized' === $term->slug ) {
$term->name = …
```

Fix wp-parsely Type Errors for the 3.0 tree

---

wp-parsely.php

This PR changes the default wp-parsely version that gets loaded on sites that have the managed support of the plugin enabled. 
We are changing from version 2.6 to 3.0, which contains breaking changes.
Changed the default version of wp-parsely from 2.6 to 3.0.
2. Make sure wp-parsely is enabled.
3. Check that the version loaded is 3.0.

Setting Parse.ly 3.0 as the default version

---

001-cron.php

After https://github.com/Automattic/vip-go-mu-plugins/pull/2839, we can allow cron control to still be active for archived/spam subsites. Helps keep things consistent across the platform.
Also increments the plugin version.
n/a, will add a note with the other cron control changelog post.

Load cron control for archived/spam/deactivated subsites

---

.circleci/config.yml
composer.json
composer.lock

WP 5.9 supports the latest PHPUnit; let's use it in our tests.
This PR enables PHPUnit 9 by default (since most of the tests run on WP latest anyway) and uses PHPUnit 7 for older WordPress versions. By updating PHPUnit, we also got rid of several deprecated and unsupported dependencies.

Switch WP 5.9 jobs to PHPUnit 9

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

Fixes this fatal:
> PHP message: PHP Fatal error: Caught Error: Trying to access array offset on value of type bool in /wp-content/mu-plugins/vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php:211 
Occurs under a quite rare circumstance, but tis possible so patching it up.
n/a, can skip.
Run `do_action( 'wpcom_vip_run_jetpack_connection_pilot' );`

JP Connection Pilot: Ensure "last_heartbeat" is an array

---

query-monitor.php

This just bumps some metadata that was missed in #2805. Prevents confusion when looking at the version number in the file.
* Fix plugin metadata

Bump the metadata for QM

---

composer.json
composer.lock

- Upgrading mustache/mustache (v2.14.0 => v2.14.1)
- Upgrading phpdocumentor/type-resolver (1.5.1 => 1.6.0)
- Upgrading symfony/finder (v5.4.0 => v5.4.2)
- Upgrading symfony/polyfill-ctype (v1.23.0 => v1.24.0)
- Upgrading symfony/polyfill-php80 (v1.23.1 => v1.24.0)
- Upgrading johnpbloch/wordpress-core (5.8.3 => 5.9.0)
- Upgrading wp-cli/wp-cli (v2.5.0 => v2.6.0)
- Upgrading wp-phpunit/wp-phpunit (5.8.3 => 5.9.0)

Update development dependencies (PHP)

---

tests/bootstrap.php

This is one of the reasons for transient failures ([example](https://github.com/Automattic/vip-go-mu-plugins/runs/4970502794?check_suite_focus=true)).
We should not make external requests in our tests unless absolutely necessary.

Do not contact wordpress.org for translations

---

search/includes/classes/class-health.php

Decreasing the batch size to 300 to slow down the jobs. 
We've reduced the batch size for content validation checks from 500 to 300.

Bump down the default content validation batch size to 300

---

.github/workflows/e2e.yml
.github/workflows/nightly.yml
.github/workflows/parsely.yml
.github/workflows/release-changelog.yml

Without these annotations, Renovate just picks the latest commit and creates a PR to update the action with the commit hash.
With these annotations, Renovate will follow the tags and will not offer potentially unstable commits to the main branch.
Reference: https://docs.renovatebot.com/modules/manager/github-actions/#additional-information

Add annotations for Renovate to GitHub workflows

---

files/class-api-client.php

If a third-party plugin tries to create a file in `wp-content` before `plugins_loaded` fires (hello mailpoet), this results in a fatal error, because of the use of `wp_check_filetype()` function, which (indirectly) relies upon `wp_get_current_user()`, which is loaded from `pluggable.php`.
This PR adds a check whether `wp_get_current_user()` is available before calling `wp_check_filetype()`.
Do not generate a fatal error if a file upload happens before `plugins_loaded` action fires.

Allow for using VIP Filesystem Wrapper before plugins_loaded fires

---

search/includes/classes/class-settingshealthjob.php
tests/search/includes/classes/test-class-settingshealthjob.php

Due to limitations with PHP-fpm requiring `WP_CLI::runcommand()` to set the 'launch' flag to `false`, I've decided to go about another way since it wouldn't capture any STDERR. This is continuation of the work from #2776.
To test with the post Indexable:
1) `$es = new \Automattic\VIP\Search\Search();`
2) `$es->init();`
3) `$hj = new \Automattic\VIP\Search\SettingsHealthJob( $es );`
4) `$hj->build_new_index( 'post' );`

Search: Re-factor build_new_index() to not use WP_CLI::runcommand()

---

files/class-meta-updater.php

For the `wp vip files update-filesizes` cmd, there are situations where an upload that doesn't have `wp_get_attachment_metadata()['filesize']` might get incorrectly skipped.
Ex: PDFs uploaded outside of VIP (without our `filter_wp_generate_attachment_metadata` filter adding file size), may have a `false` return from `wp_get_attachment_metadata()`. Without considering that `false` return in our check for attachment meta, the filesize meta backfill will be skipped, despite needing it.
I imagine this applies to other filetypes besides pdf, but pdf would be the big one.
fix `wp vip files update-filesizes` to include PDF attachments that don't already have a post attachment metadata
1. on the main/master branch, …

fix `wp vip files update-filesizes` to include pre-VIP uploaded PDF attachments

---

search/includes/classes/class-healthjob.php

`HealthJob::count_indexable_posts()` is a private method and is no longer referenced from the code. It's time to remove it :-) 
The last reference was removed in f7910629262b1b1dd816124c6b39c65c7c4bf432.

Remove the unused private method count_indexable_posts()

---

search/includes/classes/class-versioning.php
search/includes/classes/class-versioningcleanupjob.php

It's hard to filter through the Kibana logs for `search_versioning` since the messages can differ.

Search: Make log message more filterable for successful deletes

---

lib/feature/class-feature.php
search/includes/classes/class-versioningcleanupjob.php

This should go out alongside #2886 to ensure that the new criteria for re-building indexes isn't triggered all at once.

Roll out index re-building for non-production sites at 25%

---

search/includes/classes/class-versioning.php

Let's remove the deprecated check for global version storage since enough time has passed, so all new sites should should have the proper option and older ones should have it corrected already.

Search: Remove deprecated check for global version storage

---

jetpack-10.6/3rd-party/debug-bar/class-jetpack-search-debug-bar.php

To prevent the below fatal from occurring:
```
PHP Fatal error:  Uncaught Error: Call to a member function get_last_query_info() on null
```

Jetpack: Return on no object for $jetpack_search in debug bar

---

search/includes/classes/class-search.php

Part of the issue described in #2909, we were finding that the option was stored in the `options` group rather than `alloptions`. Let's use `add_option()` instead since it checks if the `$autoload` parameter is set before deciding which option group it's set at: https://github.com/WordPress/WordPress/blob/a4026420cc1845aec29661239e625c5d3cfee452/wp-includes/option.php#L645-L651
Compared to `update_option()` where it only checks the current state of alloptions: https://github.com/WordPress/WordPress/blob/a4026420cc1845aec29661239e625c5d3cfee452/wp-includes/option.php#L508-L514

Use add_option over update_option for better concurrency handling

---

vip-support/class-vip-support-user.php

Cloned from Automattic/vip-support#88
Differences from the original PR:
- use `__return_zero` instead of a custom function returning zero in `disable_admin_email_check()`

Disable admin email check for VIP Support users

---

search/includes/functions/utils.php

This is for https://github.com/Automattic/ElasticPress/pull/149, but certain EP options are on a network level and we want to start towards transitioning them to a site one. This is so individual subsites can have more granular control on a per-site basis, rather than assuming network level.
Added vip_maybe_backfill_ep_option() to utils
1) Create any a network option that doesn't exist on a site basis: `update_site_option( 'ep_test_option', [ 1, 2, 3 ] );`
2) Call helper function `vip_maybe_backfill_ep_option( false, 'ep_test_option' );
3) Check if option was created on a site level `get_option( 'ep_test_option' );`

Search: Add backfilling EP option wrapper

---

search/includes/classes/class-search.php
search/search.php
vip-jetpack/vip-jetpack.php

The current recommended process for activating the search module is via code or CLI: https://docs.wpvip.com/technical-references/elasticsearch/integrating-jetpack-search/#how-to-activate-the-search-module
For activating Instant Search, that requires opening a ZD ticket. This PR disables the page that allows activating Instant Search.
Also, the `Jetpack_Search_Dashboard_Page` class doesn't seem to exist any longer.
Removed page to toggle Search and Instant Search. To toggle search on and off, use code and for Instant Search, please open a ZD ticket with us.
1) Sandbox
2) Apply PR 
3) Go to Jetpack menu and see no "Search" anymore.

Search: Remove the JP Search toggling page

---

search/includes/classes/class-settingshealthjob.php

Bugfix for the auto-rebuilding of indexes - in https://github.com/Automattic/vip-go-mu-plugins/pull/2795/files forgot to include changing `$slug` to `$indexable_slug` 
Tihs also escapes WP_Error
```
$es = new \Automattic\VIP\Search\Search();
$es->init();
$hj = new \Automattic\VIP\Search\SettingsHealthJob( $es );
$hj->build_new_index( 'post' )
```

Search: Escape WP_Error namespace and use $indexable_slug not $slug

---

search/includes/classes/class-health.php

When doing a DB count, having an `orderby` in the query clause can be quite expensive for large datasets, so setting its value to `none` could provide some speed benefits.
Avoid excessive resource usage by setting `orderby` to `none` for the `health validate-counts` command.
1. apply the patch
2. measure time it take to run before and after the patch against
```
wp vip-search health validate-counts
```

setting orderby to none for db counts

---

.deployignore
.dockerignore

When we are building docker image from the code we need dockerignore file in place. We used to use `.deployignore` to limit files that are synced to SVN, and then build from that down the line.
As we are getting rid of the sync step, switching to dockerignore makes sense.
Not really applicable here. Just checking the output when deploying the code.

Add .dockerignore for k8s build

---

bin/add-jetpack-subtree.sh
bin/update-jetpack-subtree.sh

Currently, the subtree isn't added properly resulting in the below error when you attempt to update it:
```
─$ ./bin/update-jetpack-subtree.sh 10.7 10.7-beta2
Updating jetpack subtree jetpack-10.7 to the jetpack tag 10.7-beta2
From https://github.com/Automattic/jetpack-production
* tag                   10.7-beta2 -> FETCH_HEAD
Can't squash-merge: 'jetpack-10.7' was never added.
```
This PR fixes that.

JP /bin/ Scripts: Fix adding and updating subtree properly

---

search/includes/classes/class-settingshealthjob.php

Updated variable to `$delete_version` but it still checks if `$versioning` is a WP_Error. This could potentially cause the cron job to silently fail if there is a notice being thrown.

Search: Fix updated variable in case it was affecting the cron job

---

.dockerignore

Adding the WINDOWS file to deploy ignore so it doesn't get included.

Ignore Parse.ly WINDOWS file on deploys

---

search/includes/classes/class-healthjob.php
search/includes/classes/class-search.php
tests/mock-constants.php
tests/search/includes/classes/test-class-healthjob.php
tests/search/includes/classes/test-class-search.php

In this PR, there are no changes to functionality and the changes in it should only affect the below for tests:
- Accounts for `ABSPATH` resolving to `/tmp/wordpress` in a tests context — this was the reason why Search tests stopped running because it directly exits if not defined: https://github.com/Automattic/vip-go-mu-plugins/blob/129f6fd216cf33ae2379c23cbf43a11464e76104/search/search.php#L17-L19 
- Utilizes the `Constant_Mocker` class in `HealthJob_Test` and `Search_Test` and makes changes in the affected classes to use `constant()` rather than calling it directly
- Search_Test: adds a `init_es()` helper
- HealthJob_Test: removes two tests that are not applicable since it still technically runs if indexing is occurring or if a first index hasn't occurred, as the logic for that lives …

Search: Fix tests not running

---

wp-parsely.php

After the release of wp-parsely 3.0, the main class got namespaced, so its name changed from `Parsely` to `Parsely\Parsely`. This PR updates the wrapper code that loads the plugin to catch that change. If some rare circumstances were met, this could lead to a fatal error.
We upgraded the wp-parsely wrapper to detect if new versions of Parse.ly are manually loaded.
2. Upload wp-parsely >= 3.0 manually to your client plugins repo and load it using `wpcom_vip_load_plugin`. 
3. Make this filter return true: `add_filter( 'wpvip_parsely_load_mu', '__return_true' );`
4. Without the PR, you should get a fatal. Otherwise, it should load the version defined manually.

Detect if new Parse.ly versions are manually loaded

---

akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt

This PR upgrades the Akismet plugin to the latest minor revision (from 4.2.1 to 4.2.2). The upgrade has been made by dumping the contents of the plugin from WordPress.org: https://wordpress.org/plugins/Akismet/
We upgraded Akismet 4.2.1 to 4.2.2.
2. Go to `wp-admin` > `Jetpack` > `Akismet`
3. Check that the page loads correctly and the version number matches 4.2.2.

Upgrading Akismet to 4.2.2

---

search/includes/classes/commands/class-corecommand.php

Just in-case we have rogue ep_feature_settings option on multisites with the `EP_IS_NETWORK` constant is defined, let's add a command to delete it.
1) `wp option update ep_feature_settings test`
2) `wp vip-search clean-ep-feature-settings`

Search: Add temporary command clean-ep-feature-settings before we backfill ep_feature_settings

---

jetpack.php

Ran into some issues during 10.7 deploy, rolling back to 10.6 for now (no db upgrades, so is safe to go back).

Rollback default JP version

---

vip-dashboard/vip-dashboard.php

Removing the platform description from the text included with support tickets opened from the VIP screen in WP Admin.
Removed unnecessary content from the body of support tickets.

Remove string speficiying the platform as it's now redundant

---

lib/feature/class-feature.php
search/includes/classes/class-settingshealthjob.php

Continuing work from #2954, this PR:
- logs instead of alerts on successful index re-building
- rolls out the change to 25% of non-production environments

Search: Index re-building - log instead of alert on successful build and roll out to 25% of non-production

---

config/class-site-details-index.php
config/class-sync.php

These two logging lines happen on every SDS sync, so is a bit noisy and feels unnecessary (since they happen every time during the "ideal" path). Currently floods the batch logs quite a bit.
n/a
n/a

Remove unnecessary SDS logging

---

search/includes/classes/class-search.php

Calling `$this->alerts->send_to_chat()` will result in a fatal error on local dev-envs because `$this->alerts` could have be initiated as a WP_Error(), [seen here](https://github.com/Automattic/vip-go-mu-plugins/blob/3498a07756cc0296458a6b4e33da14b5c76e5479/lib/utils/class-alerts.php#L277-L303). Notably this makes testing the SDI syncs locally pretty tough.
The alerts class does provide a [helper method](https://github.com/Automattic/vip-go-mu-plugins/blob/3498a07756cc0296458a6b4e33da14b5c76e5479/lib/utils/class-alerts.php#L352-L363) that protects against this, but you can't test/mock statics so some of the existing tests end up failing.
Ultimately I think maybe the Alerts class could use some refactoring so that it always works peacefully even if not hooked up all the way (but stays …

Prevent local dev-env fatals during SDI syncs

---

jetpack.php

This PR makes Jetpack 10.7 the default version. Previously rolled back in #2962.
Jetpack 10.7 is the new default version.

Jetpack: Make 10.7 default version

---

search/includes/classes/class-settingshealthjob.php

Re-factored in #2954, I didn't update the `add_action()` call to account for the fact that `build_new_index()` can take two arguments now.

Search: Update add_action to account for build_new_index taking two args

---

search/includes/classes/class-versioningcleanupjob.php

No need to have the app_id, since it's already in the namespace.

Search: Remove app_id in logging for deleting stale inactive indexes 

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php

From the initial days of Enterprise Search we had some per-site implementations in mu-plugins.
The specific site owner has moved those to their client code making it possible for us to remove from mu-plugins repo.
We have removed deprecated exceptions per site as those were no longer used by anybody.
Search still generates valid queries.

Remove exception for site 1284

---

a8c-files.php
files/class-image-sizes.php
files/class-image.php
files/class-vip-filesystem.php
tests/files/test-image-sizes.php
tests/files/test-image.php

Fix the currently broken nightly tests :), and adds support for how WP 6.0 will be handling this feature.
With https://core.trac.wordpress.org/ticket/49412 landing in core (WP 6.0), the attachment `filesize` will be saved in attachment postmeta. We happen to [already do this](https://github.com/Automattic/vip-go-mu-plugins/blob/30acf90f5a2cda3466f11fdcdc36b6b8482eb5c4/files/class-vip-filesystem.php#L337-L348), and notably our filter will essentially just early return once core starts adding the meta beforehand. So the switchover on that side of things will be pretty smooth.
Core also stores the `filesize` for each additional attachment/thumbnail sizes though, which we do not currently do. This PR adds in early support for that because once core has this, it becomes an expectation that it …

Add support for WP 6.0's attachment filesize changes

---

search/includes/classes/class-health.php

Introduced in #2921. For the Users Indexable, `query_db()` uses a direct query, rather than a `WP_User_Query` which forces the value of `orderby` to be `none` in the query (rather than removing it from the SQL statement): https://github.com/Automattic/ElasticPress/blob/cfa08368e168f47ed537c833c288d17b069be889/includes/classes/Indexable/User/User.php#L701.
E.g.
```
SELECT SQL_CALC_FOUND_ROWS ID FROM wp_users ORDER BY none asc LIMIT 0, 350
```
Since the other indexables (Post, Comment, Term) use their respective WP_*_Query for `query_db()`, where `orderby` of `none` is a valid value, we should skip setting it for Users indexable.
Fix bug where `wp vip-search health validate-counts` was not showing accurate count of users in DB.
Please make sure the items below have been covered before …

Search: Fix invalid value of "orderby" for Users query

---

admin-notice/admin-notice.php

Let's remove the admin notice for WP 5.9, it's no longer relevant.

Admin_Notice: Remove notice for 5.9

---

admin-notice/admin-notice.php
admin-notice/class-admin-notice.php

This PR does two things:
- Allows the anchor tag to be used in Admin_Notice
- For sites that still have the `JETPACK_SEARCH_VIP_INDEX` constant defined, adds a notice regarding the EOL.
Add wp-admin notice to notify user of upcoming end-of-life for Jetpack Search custom indexes
1) Check out PR
2) Add `define( 'JETPACK_SEARCH_VIP_INDEX', true );` in vip-config
3) Go to wp-admin and expect to see notice panel

wp-admin: add notice for Jetpack Search migrations

---

admin-notice/admin-notice.php
admin-notice/class-admin-notice.php

Exclude certain IDs from displaying the message in #3010.

wp-admin: Do not display Search Migrations admin notice for extensions

---

search/includes/classes/class-search.php

#2913 tried to add a few extra headers, unfortunately, there's a bug that prevented the correct headers from being passed. Instead of the proper notation a PHP _SERVER variant was being passed. E.g. `HTTP_USER_AGENT` instead of `User-Agent`. 
This PR addresses that by using `getallheaders()` if available (in web context)
We've fixed a bug that resulted in not passing extra headers from the Enterprise Search client. 
1. Apply the PR
2. Set an XDebug breakpoint around `class-search.php:888`
3. Open a browser tab with XDebug on and hit any search page.
4. Verify that `User-Agent` is present in `$args['headers']`

Use getallheaders() if available instead of _SERVER superglobal when setting extra headers for Search requests

---

bin/manage-wp-parsely-subtree.sh

We were previously adding the wp-parsely versions by directly adding a Git subtree from the wp-parsely repository. The issue is that a lot of development-related files got included in the mu-plugins releases, which had many unintended consequences.
We are now shifting this and adding the wp-parsely package from its production version, i.e., we're downloading it from the WordPress.org plugin repository.
PRs with slimmer versions of Parse.ly will follow.
We upgraded the way the Parse.ly plugin gets downloaded into mu-plugins.
Run `bin/manage-wp-parsely-subtree.sh 3.1 3.1.3` and check that a slimmer version of Parse.ly is downloaded, but this version keeps working.

Parse.ly version manager downloads from WordPress.org

---

wp-parsely-3.2/README.md
wp-parsely-3.2/src/RemoteAPI/class-cached-proxy.php
wp-parsely-3.2/src/RemoteAPI/class-wordpress-cache.php
wp-parsely-3.2/wp-parsely.php

This PR pulls in the latest minor release of the Parse.ly plugin.
We upgraded wp-parsely from 3.2.0 to 3.2.1
1. Sandbox a test VIP Go site to test against (e.g. https://blog.parse.ly)
1. Confirm current status (what plugin version is loading, are meta data printed, is tracking script loaded, etc.)
1. Confirm current status (what plugin version is loading, are meta data printed, is tracking script loaded, etc.)
* You should see version `3.2.0` at this point and meta data and tracking script should be loaded as before
1. Copy modified files from this branch to the appropriate location on the sandbox (e.g. the `wp-content/mu-plugins/wp-parsely-3.2` directory)
1. Confirm current status (what plugin version is …

Updating Parse.ly 3.2 branch to 3.2.1

---

.github/workflows/parsely.yml
wp-parsely.php

This PR changes the default wp-parsely version that gets loaded on sites that have the managed support of the plugin enabled. 
We are changing from version 3.1 to 3.2, which does not contain breaking changes.
Changed the default version of wp-parsely from 3.1 to 3.2.
2. Make sure wp-parsely is enabled.
3. Check that the version loaded is 3.2.

Setting Parse.ly 3.2 as the default version

---

bin/update-jetpack-subtree.sh

`git subtree` seems to refuse later squash pulls since it can't find earlier adds, so we get an error when attempting to update the subtree when later commits have been added since: 
```
Can't squash-merge: $tree_version was never added.
```
This just modifies the script to remove it and add it back instead since in 99% of scenarios, we'll have commits since the initial subtree addition.

Fix update-jetpack-subtree.sh to just remove and add instead

---

search/includes/classes/commands/class-corecommand.php

When attempting to index on multisites where there is over 100 sites and using batch mode, it may return a `Error: Blog ID <id> does not exist!` error because the default `number` parameter of `get_sites()` is `100`. This PR fixes that issue by passing in the `site__in` parameter to it and adjusting the `number` to the number of sites passed into batch mode.
Fixed bug when indexing a multisites with over 100 sites in batch mode, a false error of site not existing is returned.
1) Create a multisite with over 100 sites
2) Attempt to index it in batch mode by passing in a single site ID into the command option `blog-ids` that wouldn't be returned in the first 100: `wp vip-search index --setup --blog-ids=999`

Search: Fixed bug when indexing a multisites with over 100 sites in batch mode, a false error of site not existing is returned.

---

stats.php

We need that key-value pair for better tracking of VIP sites via Jetpack pixel.
1. Apply the PR on a sandbox with active Jetpack connection
1. Open the siite's source
1. Verify that `_stq.push(` now contains `hp:"vip"`

Add hp=vip to kv for stats pixel

---

tests/vip-helpers/test-vip-roles.php
vip-helpers/vip-roles.php

This PR fixes #2980 by adding the code to persist the overridden capabilities to the database.
Bug fix: `wpcom_vip_override_role_caps()` now persists the capabilities to the database.
The CI should pass -- I have added a test case for this issue.

GH-2980: make sure `wpcom_vip_override_role_caps()` persists capabilities

---

.github/workflows/dependency-review.yml

This PR adds a check to prevent the introduction of known supply chain vulnerabilities into our codebase.
Reference: https://github.blog/2022-04-06-prevent-introduction-known-vulnerabilities-into-your-code/

Prevent the introduction of known vulnerabilities into the code

---

search/includes/classes/class-search.php

There's been an increase in `299 Elasticsearch-7.5.1-3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96 "[types removal] Specifying types in search requests is deprecated."` in the warnings which should not be happening since we're on Elasticsearch 7.5.1. This is because requests are being made to `/<index>/post/_search`, when it should be going to `<index>/_search`. 
This is occurring [when this check returns true](https://github.com/10up/ElasticPress/blob/5a9662f95a38477552a7de0b0d3654eec75d0961/includes/classes/Elasticsearch.php#L257) and since the version can potentially be a `false` value if the server doesn't respond (see [here](https://github.com/10up/ElasticPress/blob/5a9662f95a38477552a7de0b0d3654eec75d0961/includes/classes/Elasticsearch.php#L1328) and …

Search: Add fallback elasticsearch version

---

search/includes/classes/class-search.php

Default cache time is at 5 minutes which is too low, since this info almost never typically changes (unless an ES upgrade occurs). It's safe to leave it cached for a much longer period of time to avoid doing repeated requests for the information in `get_elasticsearch_info()` after expiration:
https://github.com/Automattic/ElasticPress/blob/be49944aab4723bd699173b356f21dbd916939cd/includes/classes/Elasticsearch.php#L1379-L1385
Increase cache expiration in get_elasticsearch_info().
1) Shell in and populate the cache:
```
\ElasticPress\Elasticsearch::factory()->get_elasticsearch_info();
```
2) Check that the transient hasn't expired after 5 minutes: `get_site_transient( 'ep_es_info' );`

Search: Extend Elasticsearch info cache expiration

---

search/includes/classes/commands/class-corecommand.php

We should disallow the command `wp vip-search delete-index` since it doesn't take into account the index versioning nor does it block deleting an active version.
Disable delete-index command and recommend to use index versioning instead.
1) Attempt to run command `wp vip-search delete-index` and expect error

Search: Throw error when delete-index command is attempted to be used

---

.github/workflows/dependency-review.yml

This PR pins action version to specific commit hashes to match other workflows.

Pin action versions in dependency-review.yml

---

files/class-vip-filesystem.php

This PR fixes a bug described in #3092: it adds a check to make sure that the `$offset` parameter to `strpos()` is contained in the `$haystack` parameter to avoid fatal errors in PHP 8.
Fixes: #3092
Fix compatibility issues with PHP 8.x.

GH-3092: PHP 8 compat: offset must be contained in haystack for strpos()

---

debug-bar-cron/debug-bar-cron.php

Fixes: #1850 
This PR applies PHP 8.0 compatibility fixes to the `debug-bar-cron` plugin. 
Ensure compatibility with PHP 8.0

GH-1850: Replace create_function() with a closure

---

rest-api/vip-endpoints.php

This removes a crufty endpoint that should have been supposed to be removed a long time ago. Introduced in #1325.

Remove Go migration Jetpack endpoint

---

.circleci/config.yml
vip-helpers/vip-utils.php

Replace `cimg/php:7.4-node` with `cimg/php:8.0-node` for linting jobs so that we can catch syntax errors specific to PHP 8 (phpcs does not check syntax).

Use PHP 8.0 for linting

---

jetpack.php

The default Jetpack version will now be 10.8
We upgraded the default Jetpack version to Jetpack 10.9.
2. Go to wp-admin > Jetpack
3. Verify default Jetpack version is 10.9

Jetpack: Default version to 10.9

---

search/includes/classes/class-dashboard.php

In single sites, it's been reported that there's a double UI admin menu showing — so we should only append the UI if `EP_IS_NETWORK` is defined (else it will already be appended resulting in a double UI)
Fix bug on single sites where a double UI admin menu was showing twice.
1) Create single site
2) Go to wp-admin
3) See double menu
4) Apply PR
5) See menu singular now

Search: Fix double UI bug appearing for single sites

---

.github/workflows/parsely.yml
tests/parsely/test-mu-parsely-integration.php
wp-parsely.php

This PR changes the default wp-parsely version that gets loaded on sites that have the managed support of the plugin enabled. 
We are changing from version 3.2 to 3.3, which does not contain breaking changes.
Changed the default version of wp-parsely from 3.2 to 3.3.
2. Make sure wp-parsely is enabled.
3. Check that the version loaded is 3.3.

Setting Parse.ly 3.3 as the default version

---

wp-parsely-3.3/README.md
wp-parsely-3.3/src/UI/class-metadata-renderer.php
wp-parsely-3.3/wp-parsely.php

This PR pulls in the latest minor release of the Parse.ly plugin.
We upgraded wp-parsely from 3.3.1 to 3.3.2
1. Sandbox a test VIP Go site to test against (e.g. https://blog.parse.ly)
1. Confirm current status (what plugin version is loading, are meta data printed, is tracking script loaded, etc.)
1. Confirm current status (what plugin version is loading, are meta data printed, is tracking script loaded, etc.)
* You should see version `3.3.1` at this point and meta data and tracking script should be loaded as before
1. Copy modified files from this branch to the appropriate location on the sandbox (e.g. the `wp-content/mu-plugins/wp-parsely-3.3` directory)
1. Confirm current status (what plugin version is …

Updating Parse.ly 3.3 branch to 3.3.2

---

jetpack-10.9/jetpack_vendor/automattic/jetpack-publicize/src/class-publicize.php

Mirrors https://github.com/Automattic/jetpack-production/commit/a4552152c8ae189fc30b9dc0a476230f4c9ad391.
Fixes fatal at `http://wp-admin/options-general.php?page=sharing`:
```
Fatal error: Uncaught Error: Class 'Automattic\Jetpack\Publicize\Jetpack' not found
in /var/www/wp-content/mu-plugins/jetpack-10.9/jetpack_vendor/automattic/jetpack-publicize/src/class-publicize.php on line 94
Call stack:
Automattic\J\P\Publicize::admin_page_warning()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-content/mu-plugins/jetpack-10.9/modules/sharedaddy/sharing.php:242
Sharing_Admin::management_page()
wp-content/mu-plugins/jetpack-10.9/_inc/lib/admin-pages/class.jetpack-admin-page.php:403 …
```

Jetpack 10.9 Hotfix: Fix namespacing issue in Publicize

---

admin-notice/admin-notice.php

Just to give folks an extra nudge it was decided to introduce a new notice that would display on non-prods. 
It's likely we'll have to adjust the slug a few times in case folks would dismiss and forget about it. 
On dev-env: 
1. Check out the PR
2. Start a VIP local dev env using PHP 7.4
3. Verify the notice is displayed.

Add PHP 8 migration notice on non-prods

---

000-vip-init.php
tests/vip-helpers/test-wpcomvip-restrictions.php
vip-helpers/class-wpcomvip-restrictions.php

This PR adds some restrictions for `wpcomvip` user:
* it does not show up in REST;
* it cannot be attributed any posts/pages/attachments;
* it is excluded from `wp_dropdown_users()`.
Add restrictions to `wpcomvip` user to improve security.

Add restrictions for wpcomvp user

---

search/includes/classes/class-search.php

The defensive logic in `vip_safe_wp_remote_request` returns a `remote_request_disabled` error with highly varying error message, which makes it difficult to filter for in logs. Moreover, since the request is never made it would not be indicative of the backend health. 
We've implemented error logging improvements to improve signal-to-noise ratio. 

Skip remote_request_disabled errors from logs, they're noisy and don't actually tell us there's an issue with backend

---

tests/test-performance-lastpostmodified.php
tests/vip-helpers/test-wpcomvip-restrictions.php

It looks like `lastpostmodified_Test` is sensitive to the order in which our tests run and may fail if other tests update a post and run before it.
This PR tries to fix this behavior.

Fix flaky tests

---

security.php
wpcom-vip-two-factor/is-jetpack-sso.php

This PR fixes several tests by adding a check whether the headers have already been sent before invoking a function that sends additional headers.
This primarily affects WP Core Tests and the cases when it is impossible to mock `header()` and related functions.
Split from #3059

Check if headers has already been sent before sending new ones

---

jetpack.php
query-monitor.php
two-factor.php
vaultpress.php
vip-support.php

This PR disables the loading of several problematic plugins when `WP_INSTALLING` is `true`. The affected plugins access the database before WP has a chance to create tables, which leads to unpleasant error messages.
Related: #3059

Skip problematic plugins on WP installation

---

debug-bar.php
debug-bar/debug-bar.php
debug-bar/panels/class-debug-bar-wp-http.php
debug-bar/panels/class-debug-bar-wp-query.php
debug-bar/readme.txt

Update debug-bar to 1.1.3
Updated Debug Bar from 1.1.2 to 1.1.3.
Changelog:
- Fix notices in HTTP Requests panel when a request is stopped/doesn't finish.
- Decode the SQL in the WP_Query panel.

Update debug-bar to 1.1.3

---

.github/workflows/dependency-review.yml

Have to do this manually while Renovate is suspended.

Update actions/dependency-review-action to 1.0.2

---

search/includes/classes/class-search.php
tests/search/includes/classes/test-class-search.php
tests/search/includes/classes/test-class-versioning.php

In #2913 we added a few headers to be able to identify requests along their lifecycle better, this, however, had an unfortunate side-effect of varying the resulting `$cache_key`.
This PR addresses that by only using the query body to determine the cache key hash.
Fix a regression that resulted in request cache using unique keys thus not using cached responses.
On a sandbox: 
1. Checkout the PR
2. Search for something and note the HTTP request made 
3. Refresh the page, verify the request is not made anymore but search results are present

Fix regression that was introduced by varying the  by adding unique headers, use body of the query to calculate the hash

---

.circleci/config.yml

Now that `latest` is `6.0`, we need a CI job for WP 5.9. This PR adds it.

Add CI job for WP 5.9.4

---

security.php
tests/test-security.php

This PR fixes a notice in `wpcom_vip_lost_password_limit()` which breaks WordPress core tests.
The bug happens when a `lostpassword_post` action is fired with an empty `$_POST`. This is fine for WordPress, because `retrieve_password()` may be invoked with a user login; in this case, `$_POST` is not used.
Fix an "Undefined index" notice in `wpcom_vip_lost_password_limit()`

Fix "Undefined index" in `wpcom_vip_lost_password_limit()`

---

search/includes/classes/commands/class-healthcommand.php

We currently cache if an index exists via an option: https://github.com/Automattic/vip-go-mu-plugins/blob/6292ffbc0a6202c3070dd629bd50ac3babd610ab/search/includes/classes/class-search.php#L999-L1002
In multisite, we should be switching into the subsite context BEFORE checking if the index exists. If not, this will result in the option being stored in site 1, which will also return it after as not existing subsequently after any changes are made when `wp vip-search health validate-counts --network-wide` is run. This is because the invalidation logic below will not fire:
https://github.com/Automattic/vip-go-mu-plugins/blob/6292ffbc0a6202c3070dd629bd50ac3babd610ab/search/includes/classes/class-search.php#L846
Fix bug where health validate-counts command was not returning correct results when …

Search: Fix bug where health validate-counts on multisite returns incorrect results

---

search/includes/classes/class-versioningcleanupjob.php

Let's stagger the stale index version clean up job from 1 to 60 minutes to ensure they don't all run at the same time for multisites that enable Enterprise Search at the exact same time.

Search: Stagger stale index versioning clean up jobs
