Automattic/vip-go-mu-plugins

a8c-files.php

One cannot simply call `__return_empty_array()` inside a function and walk away. One must return what's returned.
Since there was no return value, the effect was the same, but triggered a warning when WP later tried to iterate over a null when it expected an array.
I caused this with 989083f.

Fix a PHP warning because a filter callback didn't return anything

---

a8c-files.php

WordPress 4.5 introduced a new filter, `wp_unique_filename`, which we can use instead of relying on a variable hook to modify the ultimate filename. Since themes and plugins can change the action that is used in the variable hook, it's possible for our filters to be bypassed. Switching to this new filter ensures that regardless of how files are uploaded to Go sites, they'll receive unique filenames.

Update hooks used to check filename uniqueness and filetype validity

---

cache-manager.php

Clients have custom endpoints, such as feeds, etc, that also need
purged to avoid a 30m TTL.
This makes the list of purged urls filterable by client code, passing
the list and post id as arguments

Add a filter to allow purged urls to be modified by client code

---

000-vip-init.php
vip-helpers/vip-syndication-cache.php

In order to properly setup the cache class for the Syndication plugin as it was implemented by @sboisvert on WordPress.com platform, we have to load the class early during the WP init
This code has already been deployed to the VIP Go platform

Sync syndication cache

---

.gitmodules
wp-cron-control.php

The WordPress.com jobs system will be used trigger cron tasks, with the aid of the WP-Cron Control plugin. This is, essentially, how cron works on WordPress.com VIP.

Use WP-Cron Control to, well, control cron execution from an external service

---

a8c-files.php

This should allow users to filter the image URL arguments in a way similar to Jetpack.  This way arguments such as `quality` and `strip` can be added.

Adding `jetpack_photon_pre_args` compatible filter

---

.gitmodules

We're no longer testing an alternate version of Jetpack, so the extra submodule is unnecessary.

Jetpack: remove unused alternate Jetpack build

---

vip-rest-api.php

To ensure we can access a list of subsites on a multisite network, we need a REST API endpoint on the multisite network that will list all sites (main and its subsites) on the network. The VIP Go API is only aware of the main site, and in lieu of synching a list of subsites to the API, we'll rely on the WordPress network to report on itself.
For consistency, the response matches that from the VIP Go API. I've also added a response for single-site installs.
The domain name isn't simply pulled from the `wp_blogs` table, as that would bypass any filtering VIP or clients may apply to the domain name. While `switch_to_blog()` doesn't load the full blog context for each subsite, retrieving the `home_url()` while switched to each child blog will, at least, encounter some of the filtering we may …

Introduce REST API endpoint to list domains for current site

---

cache-manager.php

Comprehensive cache clearance for archives of associated terms
* Get all the taxonomies which apply to a post and loop over them
* Filter to allow devs to change the max number of pages purged from the term archive
* Also purge associated feed URLs
I'm a little uncertain about the filter introduced by https://github.com/Automattic/vip-go-mu-plugins/commit/28389b0f78bd5a45c9926df92bc51bdbebe42f87; I wonder if this is necessary as the `$GLOBALS['wp_rewrite']->pagination_base` is a public property, and I think it's designed for this purpose.

Purge term archives

---

cache-manager.php

**Should be merged after #231**
Hook `clean_term_cache` and purge URLs associated with the terms.

Purge removed term archives

---

cache-manager.php

Somehow, when merging #229 and #232, this redundant check of a term's existence was reinstated. As noted in #229, the term can't be returned by `get_terms()` if it doesn't exist.

Remove errant merge artifact

---

.gitmodules

No longer necessary, once #236 is merged.

Remove beta now that Jetpack 4.1 is released

---

000-vip-init.php
vip-helpers/vip-clean-term-cache.php

Backporting the vip-clean-term-cache.php mu-plugin and conditional loading based on a constant as it was patched on SVN in terms of fixing issues on beta.thesun.co.uk in the past week.

Sync clean term cache

---

shared-plugins/wp-parsely/parsely-javascript.php
shared-plugins/wp-parsely/readme.txt
shared-plugins/wp-parsely/wp-parsely.php

Last week `wp-parsely` was updated in WordPress.com to version 1.9. 
I'm now merging that update with VIP Go.

Updating wp-parsely to 1.9

---

cache-manager.php

This reverts commit cf8b9906a503a0a2206331070a99c0ac915d929e.

Revert "We should be using `break` not `continue`"

---

vip-mail.php

WP 4.6 adds some improvements to how it handles the 'from' address, so
by using the filter we take advantage of that and use the 'native' way

Use wp_mail_from filter, instead of setting $phpmailer->Sender directly

---

misc.php

The DB gets updated properly, but the cache gets fubar'd because old
data can overwrite new in concurrent environments
See https://core.trac.wordpress.org/ticket/31245
And specifically https://core.trac.wordpress.org/ticket/31245#comment:19 and https://core.trac.wordpress.org/ticket/31245#comment:26 (fix comes from the latter)

On add|update|delete of autoloaded option, clear alloptions cache

---

misc.php

Switches all sites to use the new alloptions cache clearing strategy to
prevent concurrency issues.

Enable new alloptions cache clearing for all sites

---

misc.php

Hooks `pre_ping` to stop any pinging from happening, unless `WPCOM_VIP_DO_PINGS` is set to `true`

Default to no pingbacks

---

rewrite-rules-inspector.php

…to default in case the site is not setting permalink structure via code, but rather via admin screen
Calling the `wpcom_vip_refresh_wp_rewrite` function in case none of the helper functions for setting permalinks via theme's code, eg.: `wpcom_vip_load_permastruct`, is used leads to resetting the permalink structure to the default WordPress one.
All of the helper functions for setting a custom permalink structure set a constant which can be used for the necessary check inside the Rewrite Rules Inspector's custom hook which is calling the `wpcom_vip_refresh_wp_rewrite`.
This commit adds the conditional, taking advantage of mentioned constans, and only runs the `wpcom_vip_refresh_wp_rewrite` if the permalink structure is being set via code.

Rewrite Rules Inspector: prevent resetting permalink structure

---

cache-manager.php

Since we now have files and app/web cache stored in the same Varnish instance we need to exclude files from a site-wide page cache purge.

Do not BAN files for a page cache purge

---

wp-cron-control.php

Future-post validation performs query for `future` posts without any limit, which causes performance issues on sites with many scheduled posts.
See https://github.com/Automattic/WP-Cron-Control/issues/3.

Disable future-post cron validation until limit is added to query.

---

.gitmodules
jetpack.php

* Upgrades the `jetpack` folder to 4.3.1
* Removes the `jetpack-beta` folder, which means everyone using that will fall back to the stable Jetpack release in the `jetpack` folder

Update to Jetpack 4.3.1

---

wp-cron-control.php

Now that limit is in place and index is used, also restores future-post validation.
See https://github.com/Automattic/WP-Cron-Control/issues/3

Update WP-Cron Control with improved future-post validation

---

a8c-files.php

Needs the `/sites/ . get_current_blog_id()` code from
`save_image_file()` to properly generate urls when downloading the
import file
props @emrikol - he did all the work, I just copied his 'screen shot' :)

Support multisite in wp imports

---

wp-cli.php
wp-cli/vip-utf8-to-utf8mb4.php

Modeled on Core's `upgrade_430()` and `upgrade_network()` functions, and leveraging a clone of its `maybe_convert_table_to_utf8mb4()` function, this CLI command will convert an installation's eligible `utf8` tables to `utf8mb4`.

CLI command to convert `utf8` tables to `utf8mb4`

---

cache-manager.php

Trying to purge too many URLs at once slows down post saving and will eventually cause post save actions to fail. We can be a bit more conservative with the number of pages that we purge. Luckily, this method of manually sending purge requests to each cache node is temporary and the new method should be much more robust.

Cache Purging: More sensible purge limits

---

cache-manager.php

Fix the issue where {“status”:”ok”} was appended to all requests that performed cache invalidations.

Do not output curl data

---

cache-manager.php

Since attachments use the `inherit` post status, their updates do not currently trigger Varnish purges because we ignore that status. We'd also left out the file URL itself, so even if purging had applied to attachments, only the attachment pages would've been cleared.

Purge attachment pages and files when attachments are updated

---

.gitmodules

This will allow self-selected sites to test the various fixes for Jetpack Identity Crises which are being worked on. 
This PR for VIP Go MU plugins provides in this fix for testing: https://github.com/Automattic/jetpack/pull/5278

Add Jetpack IDC branch

---

000-vip-init.php
shared-plugins/new-device-notification/new-device-notification.php
vip-helpers/vip-utils.php

Now that we can make a proxy check, we should add a function which
checks if the current user is proxied. Instead of adding this directly
to is_automattician() like I originally thought, we're introducing a new
function because is_automattician() can also check other users.
Fixes #314

Add is_proxied_automattician()

---

shared-plugins/new-device-notification/new-device-notification.php

Removes old, outdated code in New Device Notifications that allowed
bypassing of the notification for certain IPs or user agents.
Thank you to @cfg for responsibly reporting this issue.

Remove unused code in NDN plugin

---

vip-helpers/vip-utils.php

`wpcom_vip_wp_oembed_helper()` was recently updated on WordPress.com to allow the cache to expire, otherwise old and/or unwanted data might stay in it forever

Updating wpcom_vip_wp_oembed_helper()

---

misc.php

Always use HTTPS on WP API urls, regardless of other site settings.
This applies to the production as well as local development
environments, to keep theme as close as possible.
If this must be disabled for local development, the filter can be
removed, but HTTPS is enforced at the web server level in production.

Filter WP API urls to always use HTTPS

---

vip-helpers/vip-utils.php

Matching the change in r265769-wpcom-vip:
Since WordPress 4.6, wpcom_vip_file_get_contents error logs have been cutting off, leaving some of them useless.

Updating wpcom_vip_file_get_contents

---

vip-cache-manager/vip-cache-manager.php

In https://github.com/Automattic/vip-go-mu-plugins/pull/247 the `wpcom_vip_cache_purge_urls`
filter name was erroneously changed. This changes it back.

Fix a filter name

---

jetpack.php

If there's a Jetpack in the `plugins` directory, then allow it to override the one in MU plugins. Require a `VIP_JETPACK_LOCAL` constant to trigger this behaviour.

Allow a Jetpack in the plugins directory

---

vip-cache-manager/vip-cache-manager.php

In case a permalink is changed during the post update, the old permalink is never purged as `get_permalink` call inside the `queue_post_purge` is being called with `$post_id` and thus returns the current/new URL.
This commit is adding a new `WPCOM_VIP_Cache_Manager::queue_old_permalink_purge` method hooked to `post_udapted` action and obtains the old permalink by calling `get_permalink` while passing it the `$post_before` WP_Post object.
The cache purge is scheduled only in case the permalink got changed and if the post's status before the update was 'publish'.

vip-cache-manager: adding cache purging logic for changed permalinks

---

vip-cache-manager/vip-cache-manager.php

Fixing PHP warnings due to undefined $term variable

vip-cache-manager: syncing changes committed to SVN only

---

ci/prepare.sh
vip-helpers/vip-syndication-cache.php

Cribs from the core approach here:
https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/feed.php#L672-L679
Addresses #365

Require the required class files separately, if necessary

---

.gitmodules
debug-bar.php

Since we're already including the Debug Bar plugin, Debug Bar Cron would be a helpful addition, particularly to monitor the new cron plugin (#329).
Fixes #371

Load Debug Bar Cron if it isn't already present

---

001-core.php
tests/test-core.php

We don't want to show core update nags since VIP currently maintains the update. Two related changes here:
- Removes `update_core` cap from all users (including super admins).
- Disables the displays of the core update nags (since those are still shown to users that cannot update core).

No Core Update Nags

---

a8c-files.php

In case code swiches from a site with a directory style URL (eg. /my-awesome-site) to a main site using `switch_to_blog`, the upload URL path does not get properly set, since the `upload_url_path` option inside the _wp_upload_dir() function call is empty. The `WP_CONTENT_DIR` constant gets used, but it is already set to previous site's url path.
This commit is filtering the `upload_url_path` option and always, when `is_multisite` is true, sets it to `site_url() . '/wp-content/uploads'` which resolves the issues.

a8c-files.php: fix media upload after switch_to_blog

---

000-vip-init.php
vip-cache-manager/vip-cache-manager.php

Reverts Automattic/vip-go-mu-plugins#359
@darthhexx says:
> the check is happening before any DB or Memcached queries so the container could be broken and yet still be kept in the Varnish cache "Healthy" list.
We need to run the check at a point where we're confident that db and memcache connections are active and working.

Revert "Move the health check early"

---

performance.php
performance/lastpostmodified.php
tests/bootstrap.php
tests/test-performance-lastpostmodified.php

Instead of calculating on-the-fly, which can be slow on large sites (or problematic when publishing large volumes of content), store the modified date of the last post save on publish/update and use that value instead.

Performance: Add plugin that stores lastpostmodified async

---

misc.php

The WordPress core is currently [not setting `no_found_rows`](https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/class-wp-editor.php#L1351,L1358) inside the `_WP_Editors::wp_link_query` and [is setting `suppress_filters` to `true`](https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/class-wp-editor.php#L1353).
Since the `_WP_Editors::wp_link_query` method [is not using the `found_posts` nor `max_num_pages` properties](https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/class-wp-editor.php#L1383,L1385) of `WP_Query` class, the `SQL_CALC_FOUND_ROWS` in produced SQL query is extra and useless.
Setting `suppress_filters` to `false`, on the other hand, is …

Improve perfomance of _WP_Editors::wp_link_query

---

performance/lastpostmodified.php
tests/test-performance-lastpostmodified.php

We should store and properly return that value when requested.

get_lastpostmodified defaults post_type to any

---

shared-plugins/new-device-notification/new-device-notification.php
shared-plugins/new-device-notification/wpcom-helper.php

It seems that WordPress.com doesn't set the From header automatically,
and it shows as the emails are from "unknown sender"

Adding the 'From' header to the wpcom-helper file

---

vip-helpers/vip-clean-term-cache.php

Following code can be used from within a theme for disabling term cache updates
```
add_filter( 'wpcom_vip_disable_term_cache_invalidation', '__return_true' );
```

Adding filter for disabling term cache updates

---

shared-plugins/disqus/lib/api/disqus/disqus.php
shared-plugins/disqus/lib/api/disqus/json.php
shared-plugins/disqus/lib/wpapi.php

With `__construct` for PHP7+ compat
See #402

Disqus: replace PHP4-style constructors

---

shared-plugins/mediapass/mediapass_api.php

With `__construct` for PHP7+ compat
See #402

MediaPass: replace PHP4-style constructor

---

vip-helpers/vip-utils.php

Always https and always call to en (since www redirects to en).

Reduce redirects to gravatar with get_user_profile

---

wordpress-importer/languages/wordpress-importer.pot
wordpress-importer/parsers.php
wordpress-importer/readme.txt
wordpress-importer/wordpress-importer.php

[Changelog](https://wordpress.org/plugins/wordpress-importer/changelog/) for 0.6.2 + 0.6.3:
- Add support for import term metadata.
- Fix bug that caused slashes to be stripped from imported content.
- Fix bug that caused characters to be stripped inside of CDATA in some cases.
- Fix PHP notices.
- Add wp_import_existing_post filter. See: https://core.trac.wordpress.org/ticket/33721

Update wordpress-importer to v0.6.3

---

misc.php

It's awkward to disable locally since you need local modifications to mu-plugins, which makes updates a pain. Only add the filter when we are in a Go-server environment (i.e. VIP_GO_ENV !== false) to make this easier.

Only force https REST API URLs on Go environments

---

performance/lastpostmodified.php

Instead of `cache.get => cache.add` for locking, just rely on `cache.add` since it's atomic and bails if the lock is already set. This also reduces races due to https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use

Simplify Lock

---

001-cron.php
misc.php

VIP_GO_ENV isn't really meant to be used as a boolean value; More as a
way to differentiate Go-environments.
WPCOM_IS_VIP_ENV is a better choice here.
Fixes #354

Swap bool uses of VIP_GO_ENV to WPCOM_IS_VIP_ENV

---

vip-helpers/vip-utils.php

Prevents notices like: `Notice: Undefined index: HTTP_REFERER in wp-content/mu-plugins/vip-helpers/vip-utils.php`
Fixes #249

Check SERVER key exists before accessing

---

001-cron.php

Depending on site's needs, we offer two approaches to improving Core's cron reliability. In some cases, such as local development environments or private multisite subsites, we aren't able to execute either alternative approach, so Core's offering should be used.

Allow Core's cron behaviour to be restored

---

.travis.yml

Now that PHP 7.1 is the latest stable release, we should prepare for it.

Update Travis to check latest stable PHP version

---

lib/proxy/ip-forward.php
lib/proxy/ip-utils.php
tests/bootstrap.php
tests/test-lib-proxy-ip-forward.php

This allows more securely forwarding the origin IP address. It requires a trusted whitelist of proxy IP addresses (both IPv4 -- exact and CIDR -- and IPv6 are supported).
Assumes that the local proxy passes through a server var with comma-separated IPs in the form of `user_ip, remote_proxy_ip`.
In `vip-config/vip-config`:
```
$proxy_lib = ABSPATH . '/wp-content/mu-plugins/lib/proxy/ip-forward.php';
if ( file_exists( $proxy_lib ) && ! empty( $_SERVER['HTTP_X_SECRET_TRAIL_KEY'] ) ) {
require_once( ABSPATH . '/wp-content/mu-plugins/lib/proxy/ip-forward.php' );
$ip_whitelist = [ '1.2.3.4', '5.6.7/8' ];
Automattic\VIP\Proxy\fix_remote_address_from_ip_trail( $_SERVER['HTTP_X_SECRET_TRAIL_KEY'], $ip_whitelist );
unset( $ip_whitelist );
}
```

Whitelisted Proxy IP Forwarding

---

vip-rest-api.php

The endpoint does not have any secret data and is used for several internal tools. This will be replaced with a more thorough auth system in the near future.

Allow unauth-ed access to /vip/ sites endpoint

---

performance.php
performance/bulk-edit.php

Each post updated triggers a term count update which can be very slow, especially when updating lots of posts.

Disable term counting for bulk edit

---

lib/proxy/ip-forward.php
tests/test-lib-proxy-ip-forward.php

Split into a more focused function that takes user ip + remote proxy ip which can be used on its own if needed.

Split fix_remote_addr_from_ip_trail

---

vip-helpers/vip-media.php

- Added `$post_data` param to `wpcom_vip_download_image` which gets passed to `media_handle_sideload`. This is to create better parity with the `media_handle_sideload` function. Allows you to add things like a description and title when sideloading an image.
- Added documentation for `$description` param for `wpcom_vip_download_image` func.
Not sure which branch I should open this PR against, please let me know if there's a more appropriate branch.

Adding post_data arg to vip_download_image function

---

vip-rest-api.php

We're not supporting < 4.6 any more.

Remove get_sites back-compat from REST API

---

performance/lastpostmodified.php

We only need them for feeds and don't need them loaded for every request.

Don't autoload lastpostmodified options

---

performance/bulk-edit.php

Bulk editing can have a considerable, negative impact on database servers, so by limiting the number of posts that can be processed at one time, the feature can be used without endangering stability.
WordPress is a little funny with this, and for hierarchical post types, uses a per-page value of `-1` to ensure all children can be nested under their parents. In that case, we block all bulk actions as there's no reliable way of knowing how many entries might be affected.

Impose limits on bulk-editing

---

vip-helpers/vip-wp-cli.php

These are pulled from WordPress.com, but are missing the PushPress and Elasticsearch components that don't exist on VIP Go.

Adding bulk operation functions to VIP CLI Helper

---

vip-helpers/vip-deprecated.php

`wpcom_vip_remove_playlist_styles()` is missing from VIP Go, and as far as I can tell not needed, so it should be deprecated.

Adding missing VIP helper function from WPCOM

---

akismet.php

Use filter instead of constant, since Akismet doesn't check if constant is already defined before defining its default.
`PHP Notice:  Constant AKISMET_DELETE_LIMIT already defined in /.../wp-content/mu-plugins/akismet.php on line 18`
See 46faf19 and #472

Fix PHP notice from Akismet overrides

---

alloptions-limit.php
vip-helpers/vip-utils.php

Update IRC function to use new IRC delivery service.
Updates constants, adds an argument for ‘level’ (instead of using the
`wpcom_vip_irc_color()` function) and replaces the socket connection
with an WP HTTP API POST to the new IRC service.
Depends on VIPd changes.
Depends on updating IRC constants with new ones in config.
Fixes #464

Use new irc system

---

misc.php

As some sites die on parse_request. Also, no cache for these requests.

Run SSL verify early on parse_request

---

stats.php

The stat shouldn't be bumped when `WP_IMPORTING` is defined and `true`.

Don't track publish events during imports

---

vip-jetpack/vip-jetpack.php

When a sandbox has an old version of stacks, this can lead to some serious issues because Jetpack tries to auto-correct the version on each load. The mismatch between the sandbox environment and live environment leads to a constant fight to override the option.
This just kills a request when an attempt to do a Jetpack version update is triggered from a sandbox.

Prevent Jetpack version ping-pong on sandboxes

---

query-monitor.php

With the latest update, the `activate()` function was moved to a new `QM_Activation` class.
See: #506

Fix query monitor

---

a8c-files.php

Continued from #515
Jetpack Photon's filters aren't currently supported for the Dashboard so all images end up full size since we don't allow intermediate sizes (and there is nothing else dynamically resizing them).
Until Jetpack allows using Photon in the admin (https://github.com/Automattic/jetpack/pull/6702), we can just fallback to Go's image downsize behaviour.

Fallback to Go image_downsize for is_admin

---

a8c-files.php

When using Jetpack Photon with Jetpack dev mode enabled, we end up with full size images everywhere enabled because jetpack_photon_url is short-circuited.
By force disabling dev mode for Photon, we can work around this.

Force disable dev mode for Photon

---

a8c-files.php
tests/a8c-files-utils.php
tests/bootstrap.php
tests/test-a8c-files-utils.php

Jetpack's [dimension stripping](https://github.com/Automattic/jetpack/blob/master/class.photon.php#L867-L874) doesn't quite work for us since it requires `file_exists` lookups. For now, filter `the_content` to strip out the dimensions from image file names.

Strip dimensions from intermediate images in the_content

---

001-cron.php

With the introduction of 4fa4d2c, we can ping any multisite subsite that hasn't been somehow marked inactive.

Don't unnecessarily fall back to Core cron

---

performance.php
performance/media.php

For media search. This results in meta queries that are super slow on large sites and can take upwards of 30+ seconds for search.
see https://core.trac.wordpress.org/ticket/39358
Fixes #545

Prevent core from doing filename lookups

---

two-factor.php

Just use a hard-coded set of caps instead.

two-factor: Handle when contributor doesn't exist

---

vip-helpers/vip-caching.php

By running our callback as the very first one, we would capture the value returend from the database. That means custom callbacks to `old_slug_redirect_url` run on any later callback won't pollute the cache.
By adding the `apply_filters( 'old_slug_redirect_url', $redirect )` call to before the custom `wp_redirect` one the plugin now actually makes any custom callbacks working on cached old slug redirects.

Run the `wpcom_vip_set_old_slug_redirect_cache` early 

---

jetpack-start/wp-cli-api.php

Ends up being treated as a separate arg, which breaks things.

rm `--` when calling `user create`

---

performance/media.php

Causing the filter to not be removed correctly.

Fix typo in filter name

---

.gitmodules
001-cron.php

WP-Cron Control is no longer necessary. This is dependent upon D4971-code.

Enable Cron Control for all sites but those we can't ping externally

---

001-cron.php

For "efficiency" reasons, Cron Control skips events whose actions have no callbacks. Unfortunately, this causes some jobs to be rescheduled infinitely. This functionality will be fixed or removed upstream, but this stops the runaway event creation in the meantime.

Don't skip empty events, as it causes them to be rescheduled infinitely

---

a8c-files.php
tests/test-a8c-files-utils.php

Otherwise passing those URLs through `jetpack_photon_url` ends up attempting to serve the image through the Go Files service, which does not work.
Without the patch (and with `WPCOM_VIP_USE_JETPACK_PHOTON` enabled), passing a remote image through a site ends up with the domain: `https://example.go-vip.co/example.com/wp-content/file.jpg`. With the patch, we get a correct Photon URL: `https://i0.wp.com/example.com/wp-content/file.jpg`

Allow remote images to be served from Photon

---

vip-helpers/vip-utils.php

Network-activated plugins, and community plugins activated via the wp-admin UI, won't have their `vipgo-helper.php` loaded. In many cases, performance- and architecture-related changes are omitted as a result.
For a plugin like msm-sitemap, this causes performance issues when generating sitemaps.
This is a continuation of https://github.com/Automattic/vip-dashboard/pull/71, properly situated and incorporating feedback from @mjangda.
Fixes #580

Include our helpers for any network or site plugins loaded outside of our custom methods

---

vaultpress.php

To prevent issues in the rare cases when the VaultPress API is slow to respond. 10s is a bit arbitrary but better than the default 60s.

Force a lower timeout for VaultPress

---

a8c-files.php

In case the `wp_get_attachment_url` returns `false`, we should return false from the `image_resize` in order to not interfere with core's `image_downsize` functionality.
See related code:
* https://developer.wordpress.org/reference/functions/wp_get_attachment_url/
* https://developer.wordpress.org/reference/functions/image_downsize/
* https://developer.wordpress.org/reference/functions/wp_get_attachment_image_url/

a8c-files: image_resize should return false if image does not exists

---

001-cron.php

Plugin performs its own authorization, and blocking this breaks cron execution for the site.

Override any client code that might block access to the Cron Control REST endpoints

---

performance/vip-tweaks.php

Ticket about slow queries on Laughing Squid: https://wordpressvip.zendesk.com/agent/tickets/65236
The slowness is the result of a select-distinct query when looking for media. Select-distinct is already expensive so it should be cached. But if it doesn't get any results, it still has to do a bunch of complicated processing, returns nothing, and nothing isn't cached, so the query stays slow. 
This filter caches the nothing, as it were. It is active on Wordpress.com and tests okay on LaughingSquid.com, a VIP site. 
Here's context for the bug:  https://keepingtheirblogsgoing.wordpress.com/2016/04/27/speeding-up-wp-admin/
Here's the same code that was pushed on wp.com on 19 April: https://wpcom.trac.automattic.com/changeset/154832

Update to reduce slow media queries

---

query-monitor.php

We should stop loading additional bits like custom classes and other filters when this happens to avoid unexpected behaviour like fatals.
Fixes #588

Handle cases when QueryMonitor doesn't fully load

---

debug-bar/panels/class-debug-bar-elasticsearch.php
vip-helpers/vip-elasticsearch.php

Be a little more verbose for consistency with `es_time`.

Rename `elapsed` to `elapsed_time` for consistency

---

vip-helpers/vip-caching.php

Adding the `instagram_cache_oembed_api_response_body` filter that's currently present on WordPress.com that will cache Instagram oEmbed responses.

Add instagram_cache_oembed_api_response_body

---

jetpack-start/wp-cli-api.php

Also make language clearer: "Jetpack is already active (connected)"

Display the master user when found to be active

---

jetpack-start/wp-cli-api.php

Output looks like this:
``` bash
-- Verifying VIP machine user exists (or creating one, if not)
-- Fetching keys from Jetpack Start API
Error: Failed to fetch keys from Jetpack Start: This site already has an existing Jetpack shadow site but the `wpcomvip` is not an administrator on it.
From within `wp shell` on your WPCom sandbox: `add_user_to_blog( 12345, get_user_by( "login", "wpcomvip" )->ID, "administrator" ); `
```

Print whole command to add user to shadow blog

---

jetpack-start/wp-cli-api.php

We should be able to start a multisite without manually looping through subsites. To avoid doing so unexpectedly, the `--network` flag is introduced to the `wp jetpack-start api connect` command.
See #594

Jetpack Start for multisites: connections

---

vip-jetpack/vip-jetpack.php

Adds JP Search queries to the Elasticsearch Panel.
Same as `wpcom_vip_did_elasticsearch_query()`

Log Jetpack Search queries to Debug Bar Elasticsearch Panel

---

vip-helpers/vip-elasticsearch.php

Allow setting an arg for `es_api_search_index` (`authenticated_request => true`), which would make an authenticated request to the search API using Jetpack internal auth.
Note that calling methods (e.g. `vip-go-elasticsearch`) need to filter through the returned results list to strip out any content that the user should not have access to.

Allow authenticated requests to ES

---

001-core.php
tests/test-core.php

Upgrade cap restrictions should only apply to production environments where we can't actually trigger upgrades due to the read-only file system.

Allow local core upgrades

---

wp-cli/vip-migrations.php

If we pass the network flag on a single site, show a warning but continue.

Graceful continue for dbdelta for network flag

---

000-debug/0-load.php
000-debug/logger.php
000-vip-init.php

Borrowed directly from WP.com.
Puts the file in a new `000-debug` directory and my thinking here is that we should move debug bar, query monitor and others into this folder as well.

Add debug helpers

---

wp-cli/vip-cache.php

This file will hopefully contain helper scripts for cache related commands.
Right now, I've started it with a command to purge a site's Varnish cache.  This is useful for automating site cloning, so a support user doesn't have to log in to every newly cloned site and manually purge the cache.  It's pretty barebones (it's got one job) but I'm open to suggestions of other additions if needed.

Adding vip-cache.php

---

z-client-mu-plugins.php

This change allows sites to add a `client-mu-plugins` folder (open to name change) in their VIP Go repo, which we load similar to mu-plugins. The client mu-plugins are loaded after the VIP Go mu-plugins are loaded ("enforced" by the filename prefix).
As part of this change, we will probably need a few others:
We will also probably need to re-create web containers for any sites that want to use this.
See #166

Add support for additional mu-plugins

---

shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php

- Fix ERROR: 
-- stripslashes() expects parameter 1 to be string, array given. 
-- vip-go-elasticsearch.php (643)
- Solution:
-- add stripslashes_deep.
-- move stripslashes_deep outside loops

add stripslashes_deep. move stripslashes_deep outside loops

---

tests/bootstrap.php
tests/test-cache-ttl-manager-rest.php
vip-cache-manager.php
vip-cache-manager/ttl-manager.php

Which sets a default TTL of 60s for all unauthenticated, read requests to REST API endpoints instead of the default 30 mins.
```
curl 'http://vagrant.local/?rest_route=/wp/v2/posts' -v -s > /dev/null
...
< Cache-Control: max-age=60
...
```
Fixes #658

Introduce a TTL Manager class

---

rest-api/vip-endpoints.php
z-client-mu-plugins.php

This creates a new private endpoint for determining all active plugins on a site grouped by type:
Also added a helper function to grab client mu plugin information

Introduce new plugins endpoint for querying all types of plugins

---

wp-cli/vip-fixers.php

Any sites using a go-vip.co domain should have their domain set to https since we enforce that at the server level.

Add one-time script for forcing go-vip to SSL

---

two-factor.php

SSO is not allowed on those sites so users end up locked out.

Disable jetpack-force-2fa for Jetpack Staging sites

---

000-vip-init.php

Filesystem interaction on Go will always use the `direct` method. This also helps simplify instantiation of the global filesystem object (via `WP_Filesystem`), which by default tries to write to `WP_CONTENT_DIR` and fails (since only /tmp is writeable).
The workaround without setting this constant would look something like:
```
WP_Filesystem( false, get_temp_dir(), true );
```

Enforce FS_METHOD as direct.

---

phpunit-multisite.xml
tests/bootstrap.php
tests/test-wp-cli-ssl.php
wp-cli.php

We need to make sure the correct URLs are returned by the site_url() function, which relies on is_ssl() which defaults to `false` in our currently environment. Without this, you end up with incorrect URLs returned which can be problematic when using them to generate data (e.g. Jetpack connections).

Force is_ssl() in wp-cli based on siteurl

---

.gitmodules

This change lets us provide our memcache drop-in code for easier local testing. The code currently lives in (private) VIP Go internals. Note that on it's own, this doesn't do anything as it needs to be loaded manually.
Once deployed, we can update the VIP Go internals to use this instead:
TODO post-merge and deploy:
We can later look at including HyperDB as well.

Add object-cache drop-in

---

vip-helpers/vip-utils.php

Currently Cron's go under "index.php" which muddies the waters in terms of what is and what isn't slow. It also makes some sites with low traffic seem slow because cron is a bigger proportion of the requests.
I'm adding this as plugins_loaded 11 instead of earlier to account for https://github.com/Automattic/Cron-Control/blob/master/includes/class-events.php#L27 which may load on plugins_loaded.

Correctly identify Cron & Remove from Apdex

---

akismet.php
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/notice.php

- Disabled Akismet’s debug log output by default unless AKISMET_DEBUG is defined.
- URL previews now begin preloading when the mouse moves near them in the comments section of wp-admin.
- When a comment is caught by the Comment Blacklist, Akismet will always allow it to stay in the trash even if it is spam as well.
- Fixed a bug that was preventing an error from being shown when a site can’t reach Akismet’s servers.

Bump Akismet to 3.3.4

---

vip-cache-manager/vip-cache-manager.php

WP_IMPORTING can be set under a number of conditions, such as
syndication via REST apis, and shouldn’t end up BAN-ing the entire site.
Question - what impact will this have on CLI-based imports? Lots of extra code below the removed block could end up running, which could really slow things down. Needs some thought.
Fixes #705

Don't call WPCOM_VIP_Cache_Manager::purge_site_cache() when saving posts under WP_IMPORTING

---

tests/test-client-mu-plugins.php
z-client-mu-plugins.php

By default, it only works with plugins and mu-plugins. Any calls inside client-mu-plugins end up with a non-existent path and this change helps return a correct URL instead.
Fixes #675

Make plugins_url work with client-mu-plugins

---

001-cron.php

Since alternate cron redirects to ?doing_cron, it breaks WP-CLI. This disables alternate cron in the CLI context.

Fix WP-CLI with alternate cron

---

vip-helpers/vip-debug-bar-panels.php

These are only an issue when our `db.php` and `object-cache.php` aren't loaded, such as in local development, but they generate enough noise that one can miss important errors.
* PHP Notice:  Undefined property: WP_Object_Cache::$time_total in /mu-plugins/vip-helpers/vip-debug-bar-panels.php on line 70
* PHP Notice:  Undefined index: query in /mu-plugins/vip-helpers/vip-debug-bar-panels.php on line 126
* PHP Notice:  Undefined index: elapsed in /mu-plugins/vip-helpers/vip-debug-bar-panels.php on line 149
* PHP Notice:  Undefined variable: query_time_pct in /mu-plugins/vip-helpers/vip-debug-bar-panels.php on line 171

Resolve several notices in custom Debug Bar panels

---

001-cron.php

With the switch to the CLI runner, this exception is unnecessary.
See https://github.com/Automattic/Cron-Control/pull/114

Enable Cron Control for Basic Auth sites

---

performance/vip-tweaks.php

- checks new attachment against (removing query as it's not needed)
- make sure there is a transient before trying to remove it

Clearing transient on add_attachement

---

performance/vip-tweaks.php

When a transient is set, it always returns so isn't the expected behaviour.
We want to clear when data isn't correct and there is a transient set.

Fixing delete transient wpcom_media_months_array

---

000-vip-init.php

CLI containers execute PHP via php-cli, rather than php-fpm; php-fpm provides the chroot used in web containers, therefore it isn't present in CLI containers. `/private` also isn't symlinked to `/chroot/private`, so references to `/private` will fail, but clients should be using `WPCOM_VIP_PRIVATE_DIR` anyway.
I used the `VIP_GO` prefix to avoid any confusion with WP.com's async jobs system and its constants.

Correct `WPCOM_VIP_PRIVATE_DIR` path for CLI containers

---

000-vip-init.php

I meant to include this in #733 and forgot to push it. While CLI containers do run on jobs hosts, the check we're performing has nothing to do with the host, but with the container.

Clarify constant name used to identify CLI containers

---

vip-helpers/vip-utils.php

This constant allows us to disable loading shared plugins - in particular it will stop `vip-go-elasticsearch` loading (or any other plugin we need to retire) in order for us to safely switch away.
Two arrays are added: One for retired plugins and one for protected shared plugins (2fa etc).
Test with:
`define( 'WPCOM_VIP_DISABLE_SHARED_PLUGINS', true );`

Introduce constant for sites with moved shared plugins

---

performance/do-pings.php

If the event was already blocked, either by Core or other code, `$event` won't be an object. Checking for this resolves a "trying to get property of non-object" notice.

Don't try to block an already-blocked event

---

misc.php

Prevents Woocommerce from trying to create files where they can't be created, which just leads to lots of `mkdir(): Read-only file system` errors.
Fixes #736

Bypass Woocommerce file creation

---

vip-jetpack/vip-jetpack.php

To only our machine user. All connections should be happening through Jetpack Start and not managed by individual users.

Limit Jetpack connection management

---

wp-cli/vip-go-convert-to-utf8mb4.php

Deprecated as of 4.8.2
h/t @soulseekah [#](https://github.com/Automattic/vip-go-mu-plugins/commit/3badb54961370724b7d24076b1feadc1c02d4bd2#commitcomment-24429023)

Don't use placeholders for wpdb->prepare

---

vip-jetpack/vip-jetpack.php

Sync Listener looks for events that need to be added to the sync queue. On many requests, such as frontend views, we wouldn't expect there to be any DB writes so there should be nothing for Jetpack to listen for.
This change stops Listener from loading on those requests.
See pp1HpG7-45O-p2

Jetpack: Disable Sync Listener for some requests.

---

vip-helpers/vip-debug-bar-panels.php

It's only an issue in local development, but it produces quite a bit of noise.

Stop notices related to a property that HyperDB provides

---

two-factor.php

There was previously a bug causing this not to work. When that was fixed, it caused some confusion about why two-step authentication was suddenly being enabled. Anyone who still wants to force two-step auth can do so by enabling `jetpack-force-2fa` or `two-factor` in their site repository with the `wpcom_vip_load_plugin` helper function.

Temporarily disable force two-step auth

---

000-vip-init.php
vip-helpers/vip-newrelic.php
vip-helpers/vip-utils.php

Move all New Relic logic to one file and add logging of Cron and WP_CLI as separate transactions that don't impact the Apdex score of the site (since those transactions don't impact what users get in terms of performance)

Move New Relic separate file + Track WP_CLI and Cron

---

vip-helpers/vip-utils.php

Corrects class references broken by #749.

Fix `is_automattician()`

---

tests/test-vip-cache-manager.php
vip-cache-manager/vip-cache-manager.php

Mostly, we want to strip off the fragment off any URLs since servers don't care about them.
So, a URL like `https://example.com/#q1` is added to the PURGE list as `https://example.com/` instead.

Normalize URLs before adding them to purge list

---

tests/test-vip-cache-manager.php

Newer versions of PHPUnit note this is the preferred way to test for an explicit exception.
Should hopefully address the failing tests we're seeing on Travis:
```
1) VIP_Go_Cache_Manager_Test::test__invalid__queue_purge_url with data set "invalid_scheme" ('badscheme://example.com/path')
PHPUnit_Framework_Exception: Invalid expected exception message regex given: ''
```

setExpectedExceptionRegExp => expectException

---

rest-api/vip-endpoints.php

For quickly checking if any sites are missing the constant.

Add check for WPCOM_VIP_DISABLE_SHARED_PLUGINS to /plugins api endpoint

---

tests/test-cache-purge-term.php
vip-cache-manager/vip-cache-manager.php

As it just wastes resources. The URLs for terms in these taxonomies are not publicly accessible so we end up triggering purge requests for URLs that always 404.

Don't purge non-public taxonomies

---

000-vip-init.php

Also switched to use the `wp_headers` filter instead since it's cleaner and easier to remove the header if ever necessary.

Add x-powered-by header

---

vip-helpers/vip-utils.php

...if not already set. All sites using shared plugin should be migrated by now so this should have no impact but we're adding it as a fail safe.

Set the disable shared plugins constant

---

akismet/class.akismet-admin.php

Swap the order of the response processing for get_jetpack_user to match the order of the API calls.
This fix is being reviewed for the next version of Akismet but we're pushing through now so we can make use of the underlying code.
See `pZbK5-54x`

Hotfix: Correctly handle Akismet API response order

---

jetpack.php

As `$_REQUEST` doesn't always have an `action` key, the logging code
would trigger an error, which is visibly annoying in local development
environments.
This change takes that into account while also make the code more
readable by breaking it out onto multiple lines.

Fix for "undefined index" notice in jetpack.php

---

jetpack-start/wp-cli-api.php

As an added method of confirmation. `cancel` should rarely ever be used with JPSv2.

Require a flag when running `jetpack-start cancel`

---

phpcs.xml

This is an external library, so for the sake of future updates, we
shouldn't report errors or automatically fix PHPCS issues.

Ignore the ip-utils lib

---

vip-cache-manager/vip-cache-manager.php

Easier to use when you want to filter multiple taxonomies in one go.
```
add_filter( 'wpcom_vip_cache_purge_term_urls', function( $purge_urls, $term_id ) {
$filtered_urls = [];
foreach ( $purge_urls as $url ) {
$path = parse_url( $url, PHP_URL_PATH );
if ( 0 === strpos( $path, '/wp-json/' ) ) {
$filtered_urls[] = $url;
}
}
return $filtered_urls;
}, 10, 2 );
```

Add generic filter for term purge URLs

---

akismet/class.akismet-admin.php

This was breaking the register-via-Jetpack support
Upstream fix and details at https://plugins.trac.wordpress.org/changeset/1756297 (props @cfinke)
Previously: #773

Akismet: hotfix for API ordering quirk

---

ci/deploy.sh

Was renamed to `vip-go-mu-plugins-built` (https://github.com/automattic/vip-go-mu-plugins-built)

deploy.sh: Update the reference to the deploy repo

---

fix-template-caching.php

Flush the theme file cache each time the admin screens are loaded which uses the file list.
Copy of the plugin from https://gist.github.com/westonruter/6c2ca0e5a4da233bf4bd88a1871dd950 with additional `funciton_exists` check for our MU plugins.

WP Trac #42573: Fix for theme template file caching.

---

vip-helpers/vip-utils.php

matches r316138-wpcom
limit of 1 month and minimum of 5h

Add ability to specify TTL in wpcom_vip_wp_oembed_get

---

jetpack.php

Closes https://github.com/Automattic/vip-go-mu-plugins/issues/797

Use `client-mu-plugins` instead of `plugins` for the alternative Jetpack codebase

---

tests/test-vip-plugins.php
vip-plugins/vip-plugins.php

* Remove empty checks to ensure we always merge code activated plugins with our options. 
* Stop code activated plugins being saved to the DB.
Closes #790 
Closes #791

VIP Plugins: Remove empty() checks for sites without plugins active

---

.gitmodules
vip-light-term-count.php

Some sites are having performance problems caused by term counting.
Term counting is slow and on WordPress.com is either sent to the jobs system or uses this plugin.
The plugin has been enabled on WordPress.com for around 8 months now and has proven stable.
This was tested on vip-test.go-vip.co by creating new tags, adding posts to them, removing posts from them and making sure the count matched.

Add Lightweight term counting plugin

---

vip-jetpack/vip-jetpack.php

Otherwise we get into situations where we can’t connect JP, since the
upgrade wouldn’t have been triggered any other way (since there is an
`is_active()` check wrapping the upgrade routine)
Fixes #812

Only block sandbox jetpack downgrades (not upgrades)

---

.gitmodules

SSH submodules require a Github account and associated SSH key. Since all of these submodules are public, we can use HTTPS instead to avoid requiring a Github account to clone the repo.

Use HTTPS for submodules

---

vip-wp-cli-to-cron.php
vip-wp-cli-to-cron/limit-wp-cli-command.php

This is not ready for client use. If you are interested in learning, please contact VIP Support.
The code in this PR is a mechanism for offloading WP CLI commands to WP Cron which allows those command to be run on CLI containers, instead of sandboxes, which takes the commands closer to the production servers and thus should provide better performance for the commands.

Run WP CLI commands via WP Cron

---

tests/test-vip-rest-api.php

Auth failures will now return a 401 from core when the request is not from a logged in user.
See https://core.trac.wordpress.org/ticket/42828

Update REST test assertions

---

a8c-files.php

`wp_unique_filename` allows passing in a custom callback as an added level of customization. In our filter for `wp_unique_filename`, we're just passing through the results as-is if the custom callback is used. Otherwise we can end up modifying the results, which may be undesirable.
One use case is when we want to override an existing file. We can use the custom callback to set the existing file's name. Without this change, our mu-plugins unique filename check runs and modifies the filename, which is not what we want.

Don't override results of unique_filename_callback

---

vip-helpers/vip-utils.php

As it's defined post our initial `get_defined_vars()` call, this variable is leaking to the global namespace.
This commit adds the variable to the blacklist, which is meant to prevent such situations.

Blacklist $helper_file variable in _wpcom_vip_include_plugin

---

vip-cache-manager/vip-cache-manager.php

In case the slug contains some percentage signs, for instance due to encoding non-ascii chars, the `sprintf` call fails.
Instead of proposed str_replace escaping ( #823 ), this approach does no mess up with the URL, but only calls sprintf with `$paging_endpoint` as a param - that variable is supposed to contain  single `%d` conversion specifier and thus the `sprintf` should not fail due to the confusion over missing params.
Fixes #823

Moving the sprintf to act on `$paging_endpoint` only

---

jetpack-start/wp-cli-api.php

Since we don't use them heavily in the method anyway. This also fixes compatibility issues with PHP 7.1 because we have at least one call to the method that doesn't pass in the arg.
Fixes #853

Jetpack Start: Make args for `connect_site` optional

---

jetpack-start/wp-cli-api.php

Use the direct `Jetpack::disconnect` method so that the connection state actually gets cleared in the current request. Otherwise, our `is_active()` check on reconnection fails because Jetpack is still connected in the current session.

Jetpack Start: Fix disconnect-and-connect routine in Jetpack Start

---

.travis.yml

Drop PHP 7 & PHP 7.1 from Travis tests

---

files/class-wp-filesystem-vip-uploads.php

To avoid dependency loading issues if the Filesystem class is called too early. `wp_tempname` uses `wp_generate_password` which is loaded later.

Restore tempnam (and drop the use of wp_tempnam)

---

files/class-wp-filesystem-vip-uploads.php
tests/files/test-wp-filesystem-vip-uploads.php

We don't have an API for managing directories so let's just assume we can create files on all paths.

WP_Filesystem_VIP:  Add naive implementation of `is_dir` 

---

vip-jetpack/vip-jetpack.php

As per #826, we should only allow [email sharing](https://jetpack.com/support/sharing/) if recaptcha is set-up.
1) If it's not enabled already, go to Settings > Sharing and drag & drop the "Email" button into "Enabled Services"
2) Assuming recaptcha isn't set-up yet, go to a post and you should see the email sharing icon not visible.
3) [Set-up recapatcha](https://jetpack.com/tag/recaptcha/)
4) Go back to post and you should see that the email sharing icon is visible.
props @mjangda 
Fixes #826

Disable email sharing when recaptcha is not set-up

---

plugin-fixes.php

Intended for addition of modifications to known plugins to resolve platform level issues while fixes get integrated back up to core repos.
Modified AMP Query Var filter to handle relative links. Existing AMP-WP plugin causes the AMP page to be rendered regardless of what comes after the /AMP/ portion of the link. To ensure that we don't get in infinite indexing loops we are enforcing that AMP triggers 404s appropriately instead of re-rendering the page. This is temporary until merged into core.

Plugin Fixes Plugin

---

.gitmodules
ramp-for-gutenberg.php
vip-plugins.php

This PR allows VIPs to load Gutenberg conditionally from their themes using a helper called `wpcom_vip_load_gutenberg`.  This function is a wrapper for `ramp_for_gutenberg_load_gutenberg` and accepts the same parameters.  In order to use this function pre-5.0, VIPs will need to separately install the Gutenberg plugin in the `/plugins` directory of their repos.
Included in this PR:
- submodule for the Gutenberg Ramp plugin.
- provide a wrapper for `ramp_for_gutenberg_load_gutenberg` called `wpcom_vip_load_gutenberg`
- turn off Ramp UI by default

add Gutenberg loading functionality to Go

---

vip-helpers/vip-migrations.php

This is to avoid a VaultPress fatal during the sync, which is caused by
the `vaultpress` option being present in the child site db.

Added a call to remove the `vaultpress` option from the db prior to plugin registration

---

ramp-for-gutenberg.php

`ramp_for_gutenberg_load_gutenberg` accepts a single argument and defaults to `false`
`wpcom_vip_load_gutenberg` should do the same to avoid accidental fatal errors. [The documentation](https://vip.wordpress.com/documentation/vip-go/loading-gutenberg/#examples) already demonstrates usage with no arguments passed to `wpcom_vip_load_gutenberg`

Improve Gutenberg Ramp argument consistency

---

001-core.php
001-core/privacy.php
files/class-api-client.php

Core relies on the ability to write files directly to the uploads folder which doesn't currently work on Go. Core also expects the PHP `zip` module to always be available even though it won't for all applications, so we fall back to `PclZip` in those instances.
Generate a request; then:
- On a site with `zip` module enabled, make sure the export is generated and downloadable.
- On a site without the `zip` module enabled, make sure the export is generated and downloadable.
- Make sure that archives for requests are being deleted after 3 days and no longer accessible past that time.

Add custom handlers for WordPress 4.9.6 personal data export feature

---

001-core/privacy.php

Privacy Compat Fixes

---

akismet.php
akismet/_inc/akismet.css
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/notice.php

https://blog.akismet.com/2018/05/28/version-4-0-7-of-the-akismet-wordpress-plugin-is-now-available/
```
4.0.7
Release Date – 28 May 2018
Based on user feedback, the link on “Learn how your comment data is processed.” in the optional privacy notice now has a target of _blank and opens in a new tab/window.
Updated the in-admin privacy notice to use the term “comment” instead of “contact” in “Akismet can display a notice to your users under your comment forms.”
Only show in-admin privacy notice if Akismet has an API Key configured
4.0.6
Release Date – 26 May 2018
Moved away from using empty( get_option() ) to instantiating a variable to be compatible with older versions of PHP (5.3, 5.4, etc).
4.0.5
Release Date – 26 May 2018
Corrected version number after tagging. Sorry…
4.0.4
Release Date …
```

Upgrade to Akismet 4.0.7

---

a8c-files.php

Works better with unicode characters than our previous `sanitize_title_with_dashes` implementation for sanitization.

Switch to `sanitize_file_name`

---

tests/vip-helpers/test-vip-utils.php
vip-helpers/vip-utils.php

The VIP Go Files services has the same capabilities and fewer issues on sites with restricted access.

Don't use Photon for `wpcom_vip_get_resized_attachment_url()`

---

jetpack.php

> This point fix addresses a small bug that prevented stats from working on the AMP view for a site, as well as an uncommon issue with the VR shortcode.
https://jetpack.com/?p=31394
https://github.com/Automattic/jetpack/releases/tag/6.2.1

Update to Jetpack 6.2.1

---

vip-helpers/vip-utils.php

Fixes #883
Question: since New Relic extension is not loaded on sandboxes I could not test it properly. Is there a way to test this on non-production environments?
The rest of the code seems to work and it's fairly trivial, but I would prefer testing it anyway.

Don't silently handle missing plugins on VIP environments

---

.gitmodules
gutenberg-ramp.php

Rename from `ramp-for-gutenberg` to `gutenberg-ramp` and update to the latest 1.0.0 tag.
Prefixes for Ramp have also changed, so everything `ramp_for_gutenberg_*` has been renamed to `gutenberg_ramp_*`
I used `git mv` to rename the git module and manually altered `.gitmodules` to update the GitHub URL.

Rename & Update Gutenberg Ramp

---

rewrite-rules-inspector.php

replace wpcom_initiate_flush_rewrite_rules() with flush_rewrite_rules().
Fixes `PHP Notice:  wpcom_initiate_flush_rewrite_rules is <strong>deprecated</strong> since version 2.0.0! Use flush_rewrite_rules instead. in /srv/www/theundefeated/public_html/wp-includes/functions.php on line 3840`

replace deprecated wpcom_initiate_flush_rewrite_rules call

---

vip-helpers/vip-utils.php

In some cases, `$includepath` may not be defined leading to an incorrect error:
```
wpcom_vip_load_plugin: Unable to load plugin `photonfill`; the path `` does not exist.
```
Instead, we selectively build the error message based on the context.

Fix plugin load warning

---

vaultpress.php
vaultpress/class.vaultpress-ixr-ssl-client.php
vaultpress/readme.txt
vaultpress/vaultpress.php
vaultpress/vp-scanner.php

```
= 1.9.5 - 2 February 2018
* Removing activation notice
= 1.9.4 - 15 November 2017
* Error handling improvements in the scanner
= 1.9.3 - 9 November 2017
* Compatibility update
* Send a better user-agent string to VaultPress servers
```

Update to VaultPress 1.9.5

---

vip-jetpack/jetpack-mandatory.php

We rely on other monitoring systems instead.

Remove Jetpack Monitor from mandatory modules

---

lib/sunrise/sunrise.php

Switch to `htmlspecialchars` instead.

Can't use esc_html in sunrise

---

errors/site-not-found.html

The site not found page for multisites can be confusing. We should make it more clear that it's a multisite, but the domain is not mapped to a site.

Fix multisite not found error message

---

vip-helpers/vip-query-monitor.php

**Problem**:
With PHP Errors enabled, Query Monitor was displaying notices that `is_main_query` and `has_main_query` were missing. 
**Reason**:
This is because VIP Go has a [custom DB Collector implementation](https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-query-monitor.php) that's slightly outdated (last updated October 2016) but Query Monitor implemented the `is_main_query` functionality on Feb, 2017: https://github.com/johnbillion/query-monitor/commit/5a8dc9832427b187ce70acfee9a1ccf61457ec0a
**Solution**:
Copy & Paste the changes made to `process_db_object` method from https://github.com/johnbillion/query-monitor/commit/5a8dc9832427b187ce70acfee9a1ccf61457ec0a and https://github.com/johnbillion/query-monitor/commit/7e28e515d0f9d2f4e617ec424334929cf9a63fd2 …

Fix Query Monitor 3.0.1 notices

---

vip-plugins/vip-plugins.php

Right now, this conditional
```php
if ( 'plugins' === $screen->id ) {
unset( $actions['network_active'] );
}
```
can cause [issues with Jetpack](https://wordpressvip.zendesk.com/agent/tickets/80336). The problem is that code is run on the `plugin_action_links` filter, which Jetpack does also call on `admin_init`. However, on `admin_init`, the `current_screen` is not yet defined, so `$screen` above ends up being `null`, of which we then try to fetch a property.
The issue is ultimately in Jetpack, which shouldn't call that filter on `admin_init`, and I have [sent a PR to their repo](https://github.com/Automattic/jetpack/pull/9960), BUT we can simply add a check to ensure that `$screen` is defined and is a `WP_Screen` object. This change would fix the ZD ticket, and it doesn't seem out of …

Removed $screen check in plugin_action_links filter

---

000-vip-init.php
001-core.php
alloptions-limit.php
async-publish-actions.php
performance.php
schema.php
stats.php
two-factor.php
vip-feed-cache.php

Some MU plugins lack proper name/description and thus show up in the plugins view just with their slugs, as shown below:
This PR aims at fixing them, providing all MU plugins with an apt header section. This is particularly important since we are going to show those in the general plugins view, as per #947.

Added/improved header section for some MU plugins 

---

gutenberg-ramp.php

Currently, calling `wpcom_vip_load_gutenberg()` makes `$criteria` default to `false`. That means calling `wpcom_vip_load_gutenberg()` does not load Gutenberg. This needs to change.
The current state of the code has led to at least three instances of clients thinking they have enabled Gutenberg when they have not, and filing high priority support tickets.
The new version of this code sets `$criteria` to `true` by default, making for a more logical connection between function name and function behaviour.

Change default behaviour of wpcom_vip_load_gutenberg() function.

---

tests/test-cache-ttl-manager-rest.php
vip-cache-manager/ttl-manager.php

If the header is set via `header()` we should not override it.
Previously, we were only checking if the Cache-Control header was set via the REST Response object. Now, we look at both.
- Set `header( 'Cache-Control: max-age=404' );` somewhere in your pageload cycle and make a request to a `wp-json` endpoint.
- Verify that the `Cache-Control` header is set to `max-age=404`.
Then:
- Remove the `header()` call and make the request again. Verify that the `Cache-Control` header now has `max-age=60`.

Don't override Cache-Control headers in REST API

---

async-publish-actions.php

With lots of publishing activity on a site, we can end up with a backlog. Enabling some concurrency allows that to be cleared a bit faster.
Main caveat is that the events are no longer atomic and anything relying on post state should check the current value in the event callback.
Related #964
n/a

Bump concurrency of the transition events

---

misc.php
tests/test-check-for-404-and-remove-cache-headers.php
tests/test-misc.php

Added a check to see if `global $wp_query` is set before using `is_404()` to avoid the following notice:
```
Notice: is_404 was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.)
```
Fixes #935
2. Add the following code snippet to a PHP file in `client-mu-plugins` directory in your sandbox
```
if ( isset( $_GET['dont-cache'] ) ) {
nocache_headers();
}
```
3. Visit a page that you know will throw a 404 error with the following appended to the URL:
`/?dont-cache=1`
4. …

Prevent Notice when calling `nocache_headers()` super early

---

lib/proxy/ip-forward.php
tests/test-lib-proxy-ip-forward.php

This solves #977
`hash_equals()` expects both values passed into it to be strings. However `get_proxy_verification_key()` may return an integer when `WPCOM_VIP_PROXY_VERIFICATION` is undefined, triggering a PHP warning. Casting `rand()` to a  string prevents this.
phpunit tests updated to reflect string instead of integer. Added `assertNotEmpty()` to verify that the string of numbers are properly returned when `WPCOM_VIP_PROXY_VERIFICATION` undefined or blank.

Fix hash_equals() php warning

---

000-debug/logger.php

As per #887, we should rename `e()` to `vip_timer()` due to a naming collision with Laravel's templating engine "blade" and `el()` (might as well) since going by the pattern, `el()` wouldn't make much sense anymore.
2. Call `vip_timer()` in theme.
3. Ensure it works as expected with no fatals or anything.

Rename `e()` (and `el()`) due to naming collision 

---

wp-cli.php

Warnings and notices can break things like JSON output, especially for critical plugins like cron-control.
Only do this on production servers to allow local and sandbox debugging.
1. Add a call to `trigger_error( 'boo', E_USER_WARNING )` in `client-mu-plugins`
1. On local, sandbox, and production, run a wp-cli command.
1. Verify that the warning shows up on local and sandbox, but now on production.

Disable `display_errors` for wp-cli

---

gutenberg-ramp.php

When certain js files are run through the existing concatenation on VIP, some are not properly rendered which breaks things in the Gutenberg editor. This fix whitelists a subset of files so that the functionality works correctly.
Gutenberg works
Performance can be slightly affected if not all files aren't concatenated
1. Enable Gutenberg for the Go site if not enabled already
2. Set `vip-go-mu-plugins` on the site to one that does not include any concat fixes (https://github.com/Automattic/vip-go-mu-plugins/commit/8335bb772bf5784b453df2634e5aa187489054ae or older)
3. Verify that the Gutenberg editor does not load for a Gutenberg-enabled post in wp-admin (the post are will be white space and you will see JavaScript errors in the console like: `TypeError: f is undefined`)
4. Update the …

Impliment concatention whitelist for Ramp

---

gutenberg-ramp.php

Reverts Automattic/vip-go-mu-plugins#985
Reverted on production in r120264-deploy
Looking at a slightly different approach: https://github.com/Automattic/nginx-http-concat/pull/42

Revert "Impliment concatention whitelist for Ramp"

---

security.php
tests/test-security.php

This adds rate limits to lost password requests using similar logic to our login limiter. It generalizes a few of the existing functions used in limiting login attempts so the logic could be applied to multiple contexts. We're limiting lost password requests to 3 attempts. I've also added two tests related to the new functionality.
1. Go to `/wp-login.php?action=lostpassword`
1. Fill out and submit the form.
1. Verify that an error message is returned after the third attempt.
1. Verify that no password reset email is received after the third attempt.

Add lost password limits

---

vip-helpers/vip-utils.php

In order to allow themes to be more easily copied as-is from
WordPress.com, this makes wpcom_vip_load_plugin interpret 'plugins'
as the default plugin location. This is because it really is the default
location, but WordPress.com themes commonly set it anyway because they
need to set a release candidate version. When we copy the theme to VIP
Go, it tries to load the theme from wp-content/plugins/plugins.

WPCOM Compat: 'plugins' means the default plugin location

---

vip-helpers/vip-migrations.php

If it's a multisite, ensure we update the global tables. For each blog, update the blog tables.
First, in a sandbox:
```
wp --allow-root cron event schedule vip_after_data_migration
```
After the command has finished, verify the schema is correct:
```
$ vipgo db <site>
mysql> show indexes from wp_postmeta;
```
Ensure the `vip_meta_key_value` index exists.

Run dbDelta during migration cleanup

---

vip-helpers/vip-migrations.php

It's defined in an wp-admin includes file which isn't loaded everywhere. To be safe, we should require that file before calling dbDelta.
Introduced in #989

vip-migration: Fix dbDelta fatals

---

stats.php

Changed our concatenation stats metric to calculate the  efficiency ratio based on the average group size relative to the number of scripts in all groups:
`average_groupsize`/`total_number_scripts_in_groups`:
1) 1 group of 10 scripts:   10/10 = 100%
2) 2 groups, one of 5, one of 15 = 10/20 = 50%
2) 3 groups of 3 scripts each : 3/9 = 33%
3)  10 groups of 1 script each = 1/10 = 10%
Also see: https://github.com/Automattic/vip-go-mu-plugins/pull/997

Changed group metric calculation 

---

gutenberg-ramp.php

When certain js files are run through the existing concatenation on VIP, some are not properly rendered which breaks things in the Gutenberg editor. We have implemented a fix in the http_concat_plugin to bypass files that have inline scripts. See:
https://github.com/Automattic/nginx-http-concat/pull/42
Gutenberg works
Performance can be slightly affected if not all files aren't concatenated
1. Enable Gutenberg for the Go site if not enabled already
2. Set `vip-go-mu-plugins` on the site to one that does not include any concat fixes (https://github.com/Automattic/vip-go-mu-plugins/commit/8335bb772bf5784b453df2634e5aa187489054ae or older)
3. Verify that the Gutenberg editor does not load for a Gutenberg-enabled post in wp-admin (the post are will be white space and you will see JavaScript …

Remove concatenation fixes from Ramp. Use fixes in http_concat plugin instead.

---

rest-api/vip-endpoints.php

For migrations we want to use the /sites endpoint to figure out the domain name for a given subsite. In order to associate domains to blog IDs, we need to include the blog ID in the response here.
Testing:
Testing will be easier once https://github.com/Automattic/vip-go-mu-plugins/pull/1015 is merged so that we don't need to generate and pass an authorization token. You could hack `wpcom_vip_go_rest_api_request_allowed()` on your sandbox to always return true, though.
Then `curl https://<domain>/wp-json/vip/v1/sites` should return a list of sites with IDs.

Add blog ID to the /vip/v1/sites response

---

vip-helpers/vip-migrations.php

First, in a sandbox:
```
wp --allow-root cron event schedule vip_after_data_migration
```
After the command has finished, verify Akismet is connected:
```
wp --allow-root shell
wp> Akismet_Admin::display_status();
<div class="akismet-alert akismet-active">
<h3 class="akismet-key-status">Akismet is now protecting your site from spam. Happy blogging!</h3>
</div>
```

Connect akismet during migration cleanup

---

rest-api/vip-endpoints.php
tests/test-vip-rest-api.php
vip-rest-api.php

Use case: We need to use the vip/v1/sites endpoint to get information
about multisites in the migration CLI. Rather than hardcoding a shared
secret in the CLI, we can create a user on the site and use that
username and password to authenticate for the API endpoints.
This uses the basic auth plugin (https://github.com/WP-API/Basic-Auth)
to populte the current user based on HTTP basic auth. We can then use
that current user to decide whether to authenticate the current request
for our internal endpoints.
Note: We're also checking `current_user_can( 'vip_support' )` here
because VIP Support users only have `read`, `subscriber`, and
`vip_support` in this context. We may just want to fix that instead.
Testing:
1. Load the PR on your sandbox
2. Create support user on a test site
3. curl -u …

Add support for basic auth to internal API endpoints

---

vip-jetpack/vip-jetpack.php

VIP Go has a built-in Content Acceleration Network, so the Photon CDN functionality is not necessary (it just adds another HTTP layer and limits the capability of our concat functionality).
CLI:
1. Update to Jetpack 6.7.
1. `wp jetpack module list`.
1. Verify that photon-cdn is not in the list.
1. `wp jetpack module activate photon-cdn`.
1. Verify that this fails.
UI:
1. Update to Jetpack 6.7.
1. Verify Site Accelerator is not available in the Jetpack Settings page.

Jetpack: Globally remove Photon CDN support

---

performance/media.php

Currently Filename searches are disabled for performance reasons. However clients have requested this functionality be enabled. (see Ticket 81547 in Zendesk). This update names the anonymous function so that clients can remove it if needed.
I'm not sure if we want to have documentation on this feature as it is a performance concern.
1. Go to `wp-admin` > `Media`
1. Perform a search for a filename
1. Verify expected media is *not* returned.
1. Add `remove_action( 'pre_get_posts', 'vip_filter_query_attachment_filenames');` to a themes functions.php file.
1. Go to `wp-admin` > `Media`
1. Perform a search for a filename
1. Verify expected media *is* returned.

Use named function to allow re-enabling filename media searches

---

.ackrc
.gitignore
.travis.yml
Makefile
README.md
composer.json
composer.lock

We're pinned to 5.7.x right now and a recent update to PHPUnit 7.x on Travis started causing failures:
```
PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /tmp/wordpress-tests-lib-4.9.8/includes/phpunit6-compat.php on line 18
```
This helps us manage our destiny better and hopefully avoid conflicts with Travis' global version when they push updates. :)

Use a local version of PHPUnit

---

jetpack.php

https://jetpack.com/2018/11/27/jetpack-6-8-building-jetpack-for-the-new-wordpress-editor/
> Today, we’re introducing the first wave of Jetpack blocks built specifically for the new WordPress editor, Gutenberg. The features you’ve come to rely on have been adapted for this new experience: payment buttons, forms, maps, and markdown.
To be deployed today (December 5, 2018) around 2000 UTC.

Jetpack 6.8

---

a8c-files.php

If the PURGE_SERVER_TYPE is configured for mangle, use it for files purges instead of direct calls to Varnish. Also, don't fire off deletes to the files service for every image size as this slows down the request needlessly.
1. Set the purge server type constant on you sandbox to 'mangle'.
2. Delete a file.
3. Ask systems to check the DC LB host logs to ensure only a single DELETE hit the files service and only a single PURGE took place to the mangle cache invalidation service.

Use mangle cache invalidation for file purges

---

vip-mail.php

In some cases (usually migrations before the site is ready) we want
to ensure wp_mail isn't sending out emails. This allows us to set
VIP_BLOCK_WP_MAIL, which will redefine wp_mail to do nothing.
Fixes #991 
1. Load the code on a sandbox
2. Set `VIP_BLOCK_WP_MAIL` to `true`
3. Run `wp_mail( $to, $subject, $message )` in `wp shell`
`wp_mail` should return NULL and you should not get an email. (Normally `wp_mail` returns `true` on success.)

Block wp_mail if VIP_BLOCK_WP_MAIL is set

---

bin/download-wp-tests.sh
bin/install-wp-tests.sh
bin/phpunit-docker.sh

```
usage: ./bin/phpunit-docker.sh [wp-version]
```
Adds a new script that uses docker to create a temporary database
container, installs the WP Unit Test dependencies, and runs the tests
in a phpunit container.
We're also splitting the existing install-wp-tests.sh script into two parts
so the applicable parts are reusable for this. The part that sets up a
local database is unnecessary here since we're using Docker for that.
The existing script still references the new download-wp-tests.sh script
internally, so that should continue to function the same as before.
Fixes #1017

Add PHPUnit test script

---

gutenberg-ramp.php

Remove Classic Editor references since we have Ramp in place. Add links and references to VIP docs and resources instead.
1. Upgrade to 5.0.
1. Go to `wp-admin/about.php`
1. Verify you don't see the Classic Editor references.
1. Verify you get VIP specific messaging at the top.
Repeat with 4.9.8 and make sure the About page isn't modified.

Modify the 5.0 about page to be more VIP-specific

---

vip-helpers/vip-utils.php

For WordPress 5.0+, any environments that want to use the Gutenberg plugin need to define the `GUTENBERG_USE_PLUGIN` constant. This facilitates the upgrade path where core disables the Gutenberg plugin as part of the upgrade. Without the constant in place, the upgrade routine would fail to deactivate the plugin and continue using it.
If the constant is defined, any attempts to load the plugin via `wpcom_vip_load_plugin` will skip loading the plugin and just fallback to the core block editor.
We'll want to coordinate this with the 5.0 upgrade on Go sites.
1. Add Gutenberg plugin
1. Add `wpcom_vip_load_plugin( 'gutenberg' )` to a client-mu-plugin.
1. Upgrade to 5.0.
1. Verify that the plugin was deactivated and …

Require the GUTENBERG_USE_PLUGIN constant

---

http-concat.php

These used to be output individually and bypass concat. 5.0 registers
them as scripts which gets them picked up by our concat.
However, tinymce.min.js (root) does not handle that situation well.
It ends up initializing with the baseURL set to that of the script.
Which then leads to problems loading additional dependencies and
everything breaks.
By skipping concat, we restore earlier behaviour and keep sites working.
1. Apply PR
1. Load classic editor on 5.0 
1. Verify it works

Retain < 5.0 behaviour for tinyMCE scripts.

---

akismet.php
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet-cli.php
akismet/class.akismet-rest-api.php
akismet/class.akismet.php
akismet/readme.txt

https://blog.akismet.com/2018/11/12/version-4-1-of-the-akismet-wordpress-plugin-is-now-available/
```
* Added a WP-CLI method for retrieving stats.
* Hooked into the new "Personal Data Eraser" functionality from WordPress 4.9.6.
* Added functionality to clear outdated alerts from Akismet.com.
```

Akismet 4.1

---

vip-filesystem.php

To prevent breaking local environments where those are not set. The notices with WP_DEBUG can break uploads.
Temp fix until we deploy #1052

Only init VIP Filesystem with FILES constants

---

.travis.yml
Makefile

No need to run multiple times for each separate test env which is a waste of time.
Fixes #1055 
- Check Travis results
- Verify that only single site test has PHPCS run

Only run phpcs once on Travis

---

a8c-files.php

Lobby Post: https://lobby.vip.wordpress.com/2018/09/13/call-for-testing-responsive-images-coming-to-vip-go/
After a lengthy testing period, we are going to enable `srcset` for all production sites.
For testing purposes, you can now optionally disable `srcset` using the `disable_vip_srcset` query string.
1. Update the `a8c-files.php` on your Sandbox.
2. Check images on your sandbox and make sure they look as expected
3. Inspect the source of the images to make sure the `srcset` sizes are present.
4. Add `?disable_image_sizes` to your URL to check to see if disabling works.

Enable srcset for all VIP Go Production sites

---

.travis.yml

Since it's a bit broken and we're not actively reviewing the failures.

Skip PHPCS on Travis for now

---

a8c-files.php

If an attachment doesn't have the appropriate meta (width/height/file), we can't really resize it, and we should skip attempting to process it anyway.
Prevents warnings that are triggering because of this:
```
Warning: Illegal string offset 'width' in /var/www/wp-content/mu-plugins/files/class-image.php on line 48 [wp-content/mu-plugins/files/class-image-sizes.php:31 Automattic\VIP\Files\Image->__construct(), wp-content/mu-plugins/a8c-files.php:918 Automattic\VIP\Files\ImageSizes->__construct(), wp-includes/class-wp-hook.php:286 a8c_files_maybe_inject_image_sizes() ... ]
```

Don't process images with missing metadata

---

files/class-api-client.php
files/class-vip-filesystem-stream-wrapper.php
files/class-vip-filesystem.php
tests/files/test-api-client.php
tests/files/test-vip-filesystem.php

Add the required filter hooks for the new Filesystem Stream Wrapper plugin

Add filetype check to Stream Wrappers 

---

wp-cli/vip-migrations.php

This wires up the --yes option.
The documentation says --yes skips the confirmation, but it
didn't do anything before now.
1. Sandbox a site
1. Checkout this PR in mu-plugins
1. wp vip migration cleanup --yes
1. Verify the confirmation step is skipped

Fix --yes flag on wp vip migration cleanup

---

jetpack.php

Should reduce the number of queries run to build a Jetpack sitemap.
See #1058

Bump up JP_SITEMAP_BATCH_SIZE to 200

---

files/class-vip-filesystem.php
tests/files/test-vip-filesystem.php

Add a filter to purge file from cache on delete.
Branched off of changes in #1061 

Add Stream Wrapper purge cache on delete

---

jetpack-start/bin/partner-provision.sh

After migrations, we run `wp vip migration cleanup` on a CLI container.
This runs `wp jetpack-start connect` internally, which calls the
partner-provision script.
Apparently the PATH variable is not set in the PHP exec(), which breaks
the partner-provision script. Here we're setting the full path to
executables that are used in the partner-provision script.
Alternatively, we could fix the PATH environment variable.
Related: https://github.com/Automattic/vip-go-api/pull/1702

Fix partner-provision.sh on CLI containers

---

.travis.yml

Start testing against PHP 7.3 in Travis to prep for upgrade on Go.

Prepare for PHP 7.3

---

files/class-vip-filesystem-stream-wrapper.php
files/class-vip-filesystem.php

Update `trigger_error` calls to include `#vip-go-streams` tag so that we can search for Filesystem specific errors easier.

Update Filesystem/Stream Wrapper errors

---

stats.php

Add new functions to track file uploads and deletes in MC Stats.
Should be able to track between the new Stream Wrapper file uploads and the older a8c-files uploads.

Add file upload & delete stats

---

shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php

`continue` is deprecated inside switch without a numeric identifier. Switch to `continue 3` to match the `year` case in `date_histogram`.
Fixes #1064 

PHP 7.3 Compat: continue 3 for consistency

---

stats.php

They just slow down the process and skew the counts.
See #1081

Don't track upload/delete stats for imports

---

wp-cli/vip-migrations.php

We prompt for confirmation (or --skip-confirm is passed) when the command is first run. We shouldn't prompt for confirmation of every subsite as well.
1. Sandbox a multisite
1. Run `wp vip migration cleanup`
1. Confirm that subsites don't prompt for additional confirmation

wp vip migration cleanup: Skip confirm for subsites

---

files/class-api-client.php

We don't need to use the default 10s timeout for all API calls. Some of them like `is_file` and `unique_filename` should be fast and we should set those timeouts accordingly.
Fixes #1089 

Set shorter timeouts for low-cost API calls

---

files/class-wp-filesystem-vip.php

When stream wrapper is enabled, we can just use PHP core functions for media. This is because wp_upload_dir will return a vip:// path.
- N/A This change works and has been tested locally (or has an appropriate fallback).
- N/A This change has relevant unit tests (if applicable).
- N/A This change has relevant documentation additions / updates (if applicable).
1. Sandbox a site.
1. Enable stream wrapper with `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', true );`
1. `wp shell`
1. `wp_filesystem( request_filesystem_credentials( site_url() ) );
1. `$GLOBALS['wp_filesystem']->put_contents( 'vip://wp-content/uploads/testing.txt', 'Hello world' );`
1. `$GLOBALS['wp_filesystem']->get_contents( 'vip://wp-content/uploads/testing.txt' );` (should output "Hello World")
1. Disable …

WP_Filesystem: Switch `uploads` paths to use WP_Filesystem_Direct

---

vip-helpers/vip-deprecated.php

These functions have been deprecated on VIP Go and are currently unused
by any VIP Go sites. We'll move this code to the vip-go-wpcom-compat
plugin so sites that are moving from WordPress.com are safe, but this
code is not loaded on the rest of VIP Go sites.

Remove unused, deprecated functions

---

files/class-api-client.php

Add file to local file cache on a `get_file` request to the Fileservice API
Fixes #1097 

Add to file cache on get file request

---

vip-helpers/vip-roles.php

This should be on the core / lower-level functions to do. Usage is also very rare.
Us overriding the global can lead to unexpected behaviour in multisite  contexts like switching blogs and overriding/removing core roles.
Updating it is not actually necessary since core tracks changes to role objects in the `wp_roles()` global instead.
- Start by verifying that the VIP Support roles are still there with the PR in place (`wp role list`).
- Add the `$wp_user_roles` global with some custom roles to `vip-config` and verify that the VIP Support roles are still there (again, `wp role list`).
Next, verify the previously broken flow doesn't break:
1. On a multisite install, make sure you have two sites.
1. Verify …

Don't update the $wp_user_roles global

---

files/class-vip-filesystem.php
tests/files/test-vip-filesystem.php

To resolve some issues caused by wrong `_wp_attached_file` post meta data

Add get attached file filter

---

files/class-api-client.php
files/class-vip-filesystem-stream-wrapper.php
tests/files/test-api-client.php

Instead of doing two separate API calls (is_file and get_file), just do one and use the signal from get_file to determine if the file exists.
In the case where files don't exist, we'll still do 1 call as previously, but in the case where they do, we drop down the count from 2 to 1.
Fixes #1105
1. `wp shell`
1. `file_put_contents( 'vip://wp-content/uploads/file-' . time() '.txt', 'testing ' . time() );`
1. Verify that works and that fetching the file returns the correct content.

Optimize Stream_Wrapper::stream_open

---

vip-helpers/vip-utils.php
z-client-mu-plugins.php

Leads to unnecessarily loading plugins which can sometimes break WP-CLI because of unexpected fatals. This also defeats the purpose of the skip-plugins flag.
We're now preventing breaking WP-CLI by skipping plugin loading when that context is set.
Fixes #1069 
*Scenario 1: UI-activated plugin with fatal*
1. Add a plugin and activate via UI (wp-admin > Plugins)
1. Add a fatal to the main plugin file (e.g. `poop();`)
1. Call `wp shell --skip-plugins`.and verify that shell loads without error. Previously, this would fatal.
1. Call `wp shell` and verify that it fatals.
*Scenario 2: client-mu-plugin with fatal*
1. Add a client-mu-plugin file.
1. Add a fatal to the plugin file (e.g. `poop();`)
1. Call `wp shell …

Fix `wp --skip-plugins`

---

a8c-files.php

Don't allow use of Stream Wrappers for sites hosted on AMS.
Fixes #1103 

Disable stream wrapper on AMS

---

files/class-api-client.php

Debug log for the VIP Filesystem API Client. Depends on the `VIP_FILESYSTEM_STREAM_WRAPPER_DEBUG` constant to be set to `true`.

Add debug log for API client

---

a8c-files.php

Move a8c files init to use the `muplugins_loaded` hook instead of `init`.
Fixes #1104 

Register Stream Wrapper `init` hook earlier

---

a8c-files.php

Wait till Jetpack and the Photon module are ready before attempting to use them to avoid fatals.
Related #1110 
Four conditions:
- `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', true );` and `define( 'WPCOM_VIP_USE_JETPACK_PHOTON', false );`
- `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', true );` and `define( 'WPCOM_VIP_USE_JETPACK_PHOTON', true );`
- `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', false );` and `define( 'WPCOM_VIP_USE_JETPACK_PHOTON', true );`
- `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', false );` and `define( 'WPCOM_VIP_USE_JETPACK_PHOTON', false );`
Verify that:
- front-end and backend of sites load without errors.
- uploading a file works
- deleting a file works.

a8c-files: Load Photon on `init`

---

files/class-api-client.php

By default, WordPress skips them via error_reporting, which is causing our trigger_error calls to be useless. If debugging is enabled for stream wrappers, we're now allowing E_USER_NOTICE so the debug gets tracked properly.
Previously #1114 
1. With `define( 'VIP_FILESYSTEM_STREAM_WRAPPER_DEBUG', false )`, verify that nothing is logged when browsing attachment pages and uploading and deleting files.
1. With `define( 'VIP_FILESYSTEM_STREAM_WRAPPER_DEBUG', true )` and `define( 'WP_DEBUG', false );`, verify that nothing is logged when browsing attachment pages and uploading and deleting files.
1. With `define( 'VIP_FILESYSTEM_STREAM_WRAPPER_DEBUG', true )` and `define( 'WP_DEBUG', true );` verify that API client …

Allow E_USER_NOTICE for debugging in API Client

---

files/class-vip-filesystem.php
tests/files/test-vip-filesystem.php

To avoid the need to do repeated checks against the API anytime the filesize for an attachment is needed.
With stream wrappers, we end up making lots of API calls for `filesize` because core functions (like `prepare_attachment_for_js` will attempt to use it). This cuts down the load on the API quite a bit.
Fixes #695
1. Enable stream wrapper: `define( 'VIP_FILESYSTEM_USE_STREAM_WRAPPER', true );`
1. Upload a file
1. Verify that the edit attachment page displays the filesize but not HTTP calls are triggered.
1. Call `wp_get_attachment_metadata` for the metadata and verify that the filesize is stored.

Store the filesize in meta on upload

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

By making the value optional and add some tests.
See #1122 
Adds new unit tests for the method.

Vary Cache: Simplify logic for is_user_in_group

---

cache/class-vary-cache.php

Implement the encrypted cookie approach to allow encrypted segmentation.
See #1122 
Example:
1. Start with the [GDPR example](https://github.com/wpcomvip/vip-vary-cache-testing)
2. Set `VIP_GO_AUTH_COOKIE_KEY` and `VIP_GO_AUTH_COOKIE_IV` constants for the site
3. Enable encryption by setting `Vary_Cache::set_encryption( true );` before the register_groups call
4. Ensure that the segmentation functionality works as expected

Enable Vary Cache with encrypted groups/data

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Fixes an issue where checking if the user is in a group will return true if user hasn't been assigned a segment in that group yet.
We'll have to be clear in the documentation that the user must set a non-empty value for the segment for the user to be considered in the group.

Fix group check logic to return false for groups with empty segments

---

cache/class-vary-cache.php
jetpack.php
tests/cache/test-vary-cache.php

Set separator value to be more Unique and also make sure that the seprator values aren't used in the group name or segment 
Fixes #1129 

Vary Cache: Set group separator to be more unique 

---

cache/class-vary-cache.php

To simplify debugging, it can be helpful to see which groups we're varying on.
#1123
1. Enable WP_DEBUG.
1. Go to the GDPR example. Verify that requests show the `X-VIP-Go_Segementation_Debug` response header.
1. Turn off WP_DEBUG; verify that requests no longer have the header.

Vary Cache: Send a debug header if WP_DEBUG enabled

---

cache/class-vary-cache.php

Should only set it when stringifying groups. Previously we were appending it to the value which meant that encrypted cookies and cb cookies were getting incorrect values set.
1. Using the GDPR example, verify that all things work.
1. Enable encryption for the GDPR example; make sure that the cookie value does not have the version prefix visible.
1. Call `Vary_Cache::set_no_cache_for_user()` on a page; verify that the `vip-go-cb` cookie is set with a value of `1`.

Vary Cache: Fix version prefix

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Much cleaner than remembering to wrap your value in an array.
```
Vary_Cache::register_groups( [ 'gdpr' ] );
Vary_Cache::register_group( 'gdpr' );
```
See #1122 
TODO

Vary_Cache: Add single version of register_group

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Adds validation for
- IV/Key set if using the encrypted approach
- Cookie values only being alphanumeric, dash or underscore
- Cookie values not containing separator (refactored into single validation method)
Fixes #1131 

Vary Cache: Validate auth keys and cookie values

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

- Moves the `send_headers` call into the class alongside other WP hooks
- Rather than re-parsing the cookie every time a method is called, which is a bit of a waste, parse it once on init.
Fixes #1132
See #1122
With the GDPR example, make sure that the 3 different states work as expected and get correctly cached values on multiple refreshes.

Vary Cache: Group WP hooks / callbacks together

---

composer.json
composer.lock

It would be good to have the PHPUnit version consistent between the local docker tests (`./bin/phpunit-docker.sh`) and what the CI service runs.Currently the local environment runs 6.5.x and Travis runs 5.7 This change bumps the version the Travis uses to match the one used in local testing.

Bump PHPUnit version so that CI tests are consistent with local tests

---

tests/cache/test-vary-cache.php
tests/test-vip-cache-manager.php

Re-nable to tests that check for PHP errors now that the PHPUnit version in Travis has been bumped up

Add skipped tests back in now that PHPUnit versions are in sync

---

bin/phpunit-docker.sh
cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Fail when changes are attempted after send_headers.
We can't set cookies or the vary header after headers have already been sent and should warn users when they attempt to do that.
Fixes #1130
1. Add `add_action( 'template_redirect', function() { Vary_Cache::register_group( 'dev-group' ); } );`
1. Verify warning is thrown.
1. Add `add_action( 'template_redirect', function() { var_dump( Vary_Cache::set_group_for_user( 'dev-group', 'yay' ) ); } );`
1. Verify WP_Error is output.

Add send_headers checks

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Only send the cookie once instead of calling setcookie every time a change is triggered. This also allows for easier testing and organizes the code a bit more cleanly.
Also introduces a new action `vip_vary_cache_did_send_headers` that must be used for early exits. We attempted falling back to `shutdown` for those cases, but can't reliably do so since output has already been sent in many cases by the time our shutdown callback fires.
Fixes #1133 
Make sure the GDPR example works (just pushed an update to work with this PR).

Vary Cache: Set cookies only once

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

We need to check to make sure that he group has been added via register_groups() before try adding the user to it.
Fixes #1147 
Example:
2. Callng `var_dump(Vary_Cache::set_group_for_user( 'dev-group', 'yay' ) );` should output an error
3. Adding `Vary_Cache:register_group('dev-group');` before that line should output true

Change set_group_for_user() to check if group is registered first

---

wp-cli/vip-migrations.php

The `validate-attachments` command in the `vip migration` command was doing a synchronous HTTP request for each attachment, which was really slow for sites with a big amount of attachments.
I have implemented the HTTP status code validation using `curl_multi`, so it tests 10 URLs asynchronously. From my tests, I believe this change makes the process ~10x faster than the previous method using `wp_remote_get`.
Additionally, I have included two optional arguments: `--start_date` and `--end_date`, to time box the validation, which is useful when dealing with delta imports of media.
There was a problem with 301 redirections from http to https being included in the CSV, despite of the `--log-found-files` argument. This was addressing by having the cURL request follow any redirections that might …

Migrations CLI: Use cURL multi for attachements validation

---

security.php
tests/test-security.php

Fixes issue with incorrect error being returned in the case of multiple calls(system.multicall) in single xmlrpc request after rate limit was hit.
Example:
2. Send a payload to xmlrpc.php with 50+ login calls via system.multicall
```
<?xml version="1.0"?>
<methodCall>
<methodName>system.multicall</methodName>
<params>
<param>
<value><array><data>
<value><struct>
<member>
<name>methodName</name>
<value><string>wp.getUsersBlogs</string></value>
</member>
<member>
<name>params</name><value><array><data>
<value><array><data>
<value><string>admin20</string></value>
<value><string>password</string></value>
</data></array></value> …
```

Fix multicall to always return 429 once rate limit exceeded

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

To conserve resources, we probably don't need to embed empty groups in the cookie value. This removes empty groups before we generate the cookie text.
Fixes #1159 
Fixes #1139 

Optimize cookie output by removing empty groups

---

ci/generate-docs.sh

The Doc build have been failing with the following error:
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "JMS\Serializer\Annotation\Type" in property phpDocumentor\Configuration::$title does not exist, or could not be auto-loaded. in /tmp/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
This appears to be from a newer version of jms/serializer that's incompatible:
https://github.com/phpDocumentor/phpDocumentor2/issues/1868
This pins the version of both to get the doc generation running again.

Fix PHPdoc documentation Generation

---

cache/class-vary-cache.php
phpdoc.dist.xml

The latest stable version of PHPDocumentor(2.9.0) doesn't seem to support private consts (that were introduced in PHP7.1)
This changes the Vary Cache constants to public which does result in the docs generating correctly.
I tried adding the `@ignore` annotations to the constants, but this didn't appear to make a difference.

Remove private scope on Vary Cache consts to enable PHPdoc generation

---

wp-cli/vip-filesystem.php

A couple of optimizations and improvements:
- Create meta if it doesn't exist
- BETWEEN instead of LIMIT (much faster when using INDEX)
- Confirmation step
And a few other small changes.

Stream Wrapper: Tweaks to `vip files update-filesizes` script

---

vip-helpers/vip-caching.php

I found that `wpcom_vip_url_to_postid()` couldn't be directly substituted with `url_to_postid()` when debugging a performance issue last month. The reason was that the sanity check we do doesn't account for when only a path is passed and not a full URL. Core does this same sanity check, so we shouldn't need to: https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/rewrite.php#L477-L483
And then I'm 90% sure the first condition is no longer needed either as we just directly use the site/home urls on VIP GO rather than the mapping logic on wpcom.

Update wpcom_vip_url_to_postid() to be interchangeable with url_to_postid()

---

cache/class-vary-cache.php

Some filter-related methods are public in order to be called by hooks but we aren't intended to be called directly (by custom code outside of the plugin)
This marks them as private in the phpdocs to make this more clear.

Vary Cache: Mark methods that should not be directly called as 'private'

---

stats.php

Some plugins (like `enable-media-replace`) call the action manually but don't pass the correct number of params (1 instead of 2), which can result in fatals:
```
Uncaught ArgumentCountError: Too few arguments to function Automattic\VIP\Stats\handle_file_upload(), 1 passed in /var/www/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected
```
Set a default to prevent those fatals.
1. Install enable-media-replace plugin
1. Upload a file and then replace it.
1. …

Stats: Set default for context param for wp_handle_upload

---

000-debug/debug-mode.php

Related #1164 
- Pull down PR
- Enable Debug Mode by appending `?a8c-debug=true` - verify it works as expected
- Disable Debug Mode by appending `?a8c-debug=false` - verify it works as expected
- Attempt to enable with proxy disabled - verify it works as expected
- Verify that the appropriate stats have been tracked in MC

Debug Mode: Track stats when enabled/disabled

---

files/class-vip-filesystem.php

Only schedule the meta update event on production environments.
Also removes any existing scheduled meta update event from non-production environments.
Fixes #1190 

Stream Wrapper: Don’t schedule meta update for non-prod env

---

plugin-fixes.php

The plugin attempts to write to a `wp-content` path which will fail. These files are transient and only meant to be included as attachment, so let's just tell CF7 to put them in `/tmp/` which will work.
1. Install and activate Contact Form 7.
1. Add a form with an file field.
1. Something a form with a file and verify it's attached to the outgoing email.

Plugin Compat: Add fix for Contact Form 7 attachments

---

plugin-fixes.php

Check that `WPCF7_UPLOADS_TMP_DIR` isn't already defined before defining it to avoid notices/warnings.
Continued from #1189

Check if constant defined first

---

files/class-wp-filesystem-vip.php

Pretty annoying that this this didn't work. If we're outside the VIP environment and in installing mode, just use the direct method for `WP_Filesystem` rather than blocking it.
Previously:
```
$ wp core upgrade
Updating to version 5.1.1 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-5.1.1-no-content.zip...
Unpacking the update...
Warning: The `/vagrant/www/wordpress-default/public_html/wp-content/upgrade/wp_5c8aa1b7b5437` file cannot be managed by the `Automattic\VIP\Files\WP_Filesystem_VIP` class. Writes are only allowed for the `/uploads` and `/tmp` directories and reads can be performed everywhere. in /vagrant/www/wordpress-default/public_html/wp-content/mu-plugins/files/class-wp-filesystem-vip.php on line 65
Warning: The …
```

Make (Local) Core Upgrades Work Again

---

security/class-lockout.php

We remove all caps when locked and should show the lockout message to all users with `read` instead. Otherwise the message never gets displayed.
1. Enabled lockout with warning (`define( 'VIP_LOCKOUT_STATE', 'warning' )` and `define( 'VIP_LOCKOUT_MESSAGE', 'oh no!' );`)
1. Verify message is displayed to an administrator user but not any other roles.
1. Switch to locked (`define( 'VIP_LOCKOUT_STATE', 'locked' )`)
1. Verify message is displayed to all users and they can only access Dashboard and Profile.

Lockout: Fix message display when locked

---

files/class-meta-updater.php

If the site has no posts, we get a null and fatal because the return value is typecast as an int.

Cast returned max ID as int

---

files/class-meta-updater.php
files/class-vip-filesystem.php
wp-cli/vip-filesystem.php

- Fix index bug that was causing batches to be skipped
- `get_attachments` only returns attachments without filesize for faster iteration through jobs
- `update_attachments` now returns counts of the various results
- use a HEAD request and header sniffing to get the content size (few requests and faster)
- Speed up the jobs by increasing batch size and frequency
- Add more detail to output

Production sync of update-filesize changes

---

vip-feed-cache/class-vip-go-feed-cache.php

Reverts Automattic/vip-go-mu-plugins#1121: `Fatal error: Cannot make non static method SimplePie_Cache::create() static in class VIP_Go_Feed_Cache`

Revert "Make feed cache create method static"

---

a8c-files.php

Due to the way that images are generated dynamically on VIP Go, when new image sizes are added to a site, they do not show up in the attachment metadata.  This will dynamically add missing image sizes to attachment metadata.
Example:
1. Add new image size to site's theme/plugins
1. Visit a media REST API endpoint (ex: `https://example.com/wp-json/wp/v2/media/12345`)
1. Compare before and after of API response for new size.

Adds missing image sizes to attachment metadata

---

a8c-files.php

wp_get_attachment_metadata can be called a lot on image heavy pages which triggers our image processing code many many time as well.
Once we've processed the sizes we don't really need to do it again so cache in memory and re-use.
Includes a few minor small order optimizations to bail out early if we don't want to process the attachement (e.g. not an image, don't have the necessary data).
TODO

Cache a local copy of generated image sizes

---

bin/phpunit-docker.sh
security.php
security/machine-user.php
tests/security/test-machine-user.php

It should never be editable/removable.
Adds several automated tests for this logic.
For manual testing:
- Make sure you've run Jetpack Start so that the machine user is created.
- Then using a super admin, admin, and other user, try to edit / delete / role change thee machine user. All of which should fail (or not be allowed at least).
Not that on multisite, there is a pathway to remove a user from a blog which is not ideal because core doesn't do the right permissions checks.

Prevent modifications of the VIP machine user

---

a8c-files.php
files/class-meta-updater.php
files/class-vip-filesystem.php

Move the scheduled attachment filesize metadata updater into `a8c-files` so that it can run on all sites regardless of wether Stream Wrappers is active or not. This will allow us to run the job before activating the Stream Wrapper for a site and avoid the initial performance hit.

Move update filesizes job

---

a8c-files.php

Stops `array_keys() expects parameter 1 to be array` by wrapping the usage of `$_wp_additional_image_sizes` in an `is_array()` check
1. Visit a site that does not have a global `$_wp_additional_image_sizes`
1. View warnings.
1. Refresh Site.
1. Verify warnings are gone.

Fix PHP Warning

---

vip-plugins/vip-plugins.php

Since we're using wpvip.com now, we need to point the plugins dashboard to use the API there instead of vip.wordpress.com.

Switch the plugins dashboard to use wpvip.com

---

two-factor.php
wpcom-vip-two-factor/set-providers.php

Enables `two-factor` by default and requires it for anyone with `edit_posts` capabilities.
We need to deploy a fix to two-factor that lets it work with Jetpack SSO: georgestephanis/two-factor#276 / #1214
1. Load this PR on a sandbox.
2. You may need to comment out the line that disables this for proxied users.
3. See that most of the sidebar options are gone except for Profile.
4. Enable two-factor in your profile.
5. See that sidebar options are back as expected.

Enable 2FA by default

---

two-factor.php

May 23 is right before the Memorial Day weekend in the US, so we'll push this back to the follow week to avoid enforcement kicking in right as people are leaving for a long weekend.

Update two-factor enforcement date to May 29

---

two-factor.php

These popular SSO solutions already provide a way for users to login
via multi-factor authentication, we don't need to add yet another
authentication mechanism to the mix.

Don't force 2FA for OneLogin or SimplSaml

---

two-factor.php

As it interferes with Gutenberg.
1. Log in unproxied to an account without 2fa
1. Verify the message is shown everywhere in wp-admin except the Posts > Add New screen.
1. Enable 2fa
1. Verify the message goes away everywhere.

Don't show 2fa notice on Edit Post screen

---

a8c-files.php
tests/test-a8c-files-utils.php

The VIP Go files service currently only rewrites the home_url of a site.  If a site has a site_url that's different than the home_url, it will default to a Photon URL instead.  Also, some sites now have .go-vip.net domains as their native domains, and this should allow them to work properly.
Example:
1. Find site with split URL setup
1. Verify all proper URLs are being rewritten.

Updates files service to allow split URL setup, and go-vip.net domain

---

two-factor.php

To allow completely skipping loading the two-factor plugin
1. Verify the two-factor plugin loads as expected.
1. Add `add_filter( 'wpcom_vip_enable_two_factor', '__return_false' );`
1. Verify the two-factor plugin is no longer loaded.

Add wpcom_vip_enable_two_factor filter

---

two-factor.php

Adds a filter to customize the capability that's used to decide whether to enforce 2fa.

Add wpcom_vip_two_factor_enforcement_cap filter

---

two-factor.php

Use `is_block_editor()` method to capture all cases where the block editor is active to hide the 2fa notice
1. Start with an account without 2fa active.
1. Verify that when the block editor is loaded, the 2fa notice is not displayed.
1. Verify that the notice shows up on other pages.

Better screen check

---

.gitmodules
001-cron.php

Adds a new "next" submodule for Cron Control along with the ability to conditionally load this next version via setting the `VIP_CRON_CONTROL_USE_NEXT_VERSION` constant to `true`.
Currently, the "next" version is pinned to https://github.com/Automattic/Cron-Control/pull/178/commits/df1740b005bfc2ce92b35772df2e86fddd962b35 from https://github.com/Automattic/Cron-Control/pull/178
Example:
1. Update submodules - `git submodule update --init --recursive`
1. `define( 'VIP_CRON_CONTROL_USE_NEXT_VERSION', true );` in `vip-config.php` or similar
1. Try some cron commands, should work normally:
1. `wp --allow-root cron event schedule something`
1. `wp …

Add pre release version of Cron Control for testing

---

wpcom-vip-two-factor/sms-provider.php

This PR simply adds a footnote to the SMS 2FA provider field about the need to use a country code when entering your phone number.
I'm aware it's indicated in the placeholder but it isn't obvious enough. Since the 2FA nag went live yesterday I've had to help multiple users who had locked themselves out of their accounts because they chose SMS 2FA and didn't use a country code, thus never received the SMS messages.

Added footnote to SMS provider field about country codes

---

wpcom-vip-two-factor/is-jetpack-sso.php

We load the cookie constants early. This ensures we properly define the MS cookie constants.

Two Factor: Load MS constants

---

files/class-vip-filesystem.php

The iptc and exif functions don't always work with streams. So, download a local copy of the file and use that to read the exif data from that file instead.
Props S3-Uploads and humanmade for the fix (https://github.com/humanmade/S3-Uploads/blob/942eb80dd289235d6bb60b0f68ca9fecb3fe227c/inc/class-s3-uploads.php#L233-L249)
1. Upload an image with a caption.
1. Verify that the caption is added to the attachment.

Exif compat for Streams.

---

security/class-lockout.php

Sites may have external registered users that have a subscriber role (with `read`) who we don't want to display the message to.
1. Enable lockout by setting the constants.
1. Login as subscriber and verify you don't see the message.
1. Login as contributor and verify you do see the message.

Only lock out contributors and up

---

vip-jetpack/vip-jetpack.php

No other filter is above the law! This filter must take priority over everything else.
Example:
1. Add a filter like `add_filter( 'sharing_services_email', '__return_true' );`
1. `apply_filters( 'sharing_services_email', true )`
1. Should return `false` if site doesn't have captcha configured

Enforce captcha for email sending (fix priority)

---

jetpack.php

Just fixes the JP version in the mu-plugins file - currently reporting 7.2.1 but should be 7.3
Example:
1. wp plugin list
1. JP should now correctly report 7.3

Fix reported JP version (7.3)

---

vip-jetpack/vip-jetpack.php

Since Jetpack executes a full sync on user connection, it overrides an ongoing full sync and thus, the ongoing full sync never ends up completing:
https://github.com/Automattic/jetpack/blame/19f9d99879d28bcdc51da94539cb26b0d1b117be/sync/class.jetpack-sync-actions.php#L529
Unfortunately, this needs to be deployed on production, as it communicates via the Jetpack production code per Enej.

Remove executing full sync on user authorization to Jetpack

---

security/class-lockout.php
tests/security/test-lockout.php

Can end up emptying out the entire list of super admin because of how the filter interacts with grant and revoke super admin functions.
1. Make sure you're testing on a multisite.
1. Add a super admin user.
1. Enable lockout by adding `define( 'VIP_LOCKOUT_STATE', 'locked' ); define( 'VIP_LOCKOUT_MESSAGE', 'Oh no!' );` to `vip-config.php`
1. Add another user and try to grant them super admin via `wp shell`: `grant_super_admin( $user_id )`
1. Verify in the db that the site_admins option still has the original user and not the new user (`SELECT * FROM wp_sitemeta WHERE meta_key = 'site_admins'`).

Prevent super admin updates when locked

---

lib/sms.php

Instead of fire-and-forget, we should actually log the errors we hit from Twilio
1. `wp shell`
1. `require_once( WPMU_PLUGIN_DIR . '/lib/sms.php' );`
1. `\Automattic\VIP\SMS\send_sms( 'INVALIDPHONENUMBER', 'Testing )` --  verify this fails; should have entry in error log. 
1. `\Automattic\VIP\SMS\send_sms( 'VALIDPHONENUMBER', 'Testing )` --  verify this succeeds

 Better error handling for Twilio 

---

vaultpress.php
vaultpress/cron-tasks.php
vaultpress/readme.txt
vaultpress/vaultpress.php
vaultpress/vp-scanner.php

```
1.9.10 – 4 April 2019
* Bugfix: Fix a PHP fatal error caused by passing an object to the current() function.
1.9.9 – 28 March 2019
* PHP 7.2.0 compatibility fix.
* Adding button to delete all VaultPress settings
```
@scarstocea This includes the same core modification that we made in https://github.com/Automattic/vip-go-mu-plugins/pull/907 do you have an update on if this can be resolved upstream?

VaultPress 1.9.10

---

akismet.php
akismet/_inc/akismet.css
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/get.php
akismet/wrapper.php

```
* Fixed a conflict between the Akismet setup banner and other plugin
notices.
* Reduced the number of API requests made by the plugin when
attempting to verify the API key.
* Include additional data in the pingback pre-check API request to
help make the stats more accurate.
* Fixed a bug that was enabling the “Check for Spam” button when no
comments were eligible to be checked.
* Improved Akismet’s AMP compatibility.
```
https://blog.akismet.com/2019/05/14/akismet-plugin-4-1-2/

Akismet 4.1.2

---

.circleci/config.yml
.travis.yml
ci/prepare.sh

Based on the WP-CLI scaffold template: https://github.com/wp-cli/scaffold-command/blob/master/templates/plugin-circle.mustache
Fixes #1176

Add initial Circle CI config

---

wp-cli/vip-two-factor.php

Allows us to get the report in CSV format, or any of the formats supported by `WP_CLI\Utils\format_items()`.

wp vip two-factor report: Add option to set format

---

vip-jetpack/vip-jetpack.php

Currently JP Sync is disabled for WP CLI commands. This presents a big problem for the consistency of the data, as changes from CLI commands are not synced normally.
Previously: https://github.com/Automattic/vip-go-mu-plugins/pull/665
1. wp option update blogdescription 'My new description'
1. Check value on wpcom, not updated 😑 
1. wp option update blogdescription 'My new description'
1. Check value on wpcom, now is updated 🎉

Allow JP Sync to run during WP CLI commands

---

two-factor.php

We'll use this to enable 2FA for all newly created sites.

Allow VIP_2FA_TIME_GATE to be overwritten by other mu-plugins

---

wpcom-vip-two-factor/sms-provider.php

Add a confirmation step to the SMS provider to make sure the user is able to receive messages at the phone number they entered
Fixes #535 
1. Go into the Edit profile for a user in wp-admin
2. Enter your SMS number and click Submit
3. The verification fields should now be where the phone number fields were.Enter the verification code and click submit"
4. The 'Correctly configured for <phone number>` message should now appear
Delete the number and repeat steps 1-4, this time checking the "enabled" checkbox on each step. It should only persist as 'enabled' once the 'correctly configured' message appears

Add phone verification step when configuring SMS two-factor

---

000-vip-init.php

The private dir is only prefixed with `/chroot` if you're running a sandbox as root, which shouldn't really happen anymore. As it is, this can break some sites when sandboxed because web requests are never root.
Fixes #858

Fix WPCOM_VIP_PRIVATE_DIR

---

cache/class-vary-cache.php
tests/cache/test-vary-cache.php

Sets the encrypted cookie in orer for Varnish to properly decrypte and deconstruct on future requests
1. Use a segmentation example such as:
https://github.com/Automattic/vip-go-mu-plugins/blob/master/cache/examples/segmentation-beta/beta.php
2. After the register_groups command, add `Vary_Cache::enable_encryption();`
3. Ensure the group logic works as it did in the unencrypted version

Cache Personalization: Tweaks to encrypted segmentation flow

---

security.php

Ensure cache consistency by always varying on Origin header.
Currently this runs on unauthenticated GET requests, which handles most instances where requests are cacheable, but we can also consider just running it on every request for simplicity and completeness.

Vary cache on Origin

---

wp-cli/vip-two-factor.php

Per https://github.com/Automattic/vip-go-mu-plugins/commit/c8fde7992ab2101915ae493bfa4e21fa2793352a#diff-9f0b8e5764792448766b0150acdd71a6, we're only requiring two factor for admins to start.

Update Two Factor Report Cap to manage_options

---

two-factor.php

Adds a `wpcom_vip_is_two_factor_local_testing` filter. 2FA enforcement will be disabled by default in local environments, but if you need to test the 2FA functionality, you can easily enable it in local environments with this filter.
We generally try to make the local environment as close as possible to production, but this is an instance where it would just get in the way most of the time.
Some things to consider during review:
1. The idea of conditionally enabling 2FA enforcement in local dev. Generally we try to keep local dev as close as possible to production, but this seems like a good example of where it will be more annoying than helpful most of the time.
2. The approach used here. I don't know of other functionality that you can optionally enable in local dev. How do we feel …

Don't enforce 2FA by default in local dev

---

performance/bulk-edit.php

Fixes https://github.com/Automattic/vip-go-mu-plugins/issues/1280
At the moment, pages (and other hierarchical post types) cannot be bulk edited when there are more than 20 total, regardless of how many are set to show per page. This is because WP core sets the `posts_per_page` query arg to -1 here for these post types, [seen here](https://github.com/WordPress/WordPress/blob/c77e771c849a85b63cef1b9457ad1a501a331afa/wp-admin/includes/post.php#L1169-L1176). I assume this is so it can properly list children under their parents.
The `per_page` value/option is still respected though when it comes to how many posts show per pages in the lists table though, [seen here](https://github.com/WordPress/WordPress/blob/cf3fa9f7c8038447303eea1fbd3636c5fece28cd/wp-admin/includes/class-wp-posts-list-table. …

Allow bulk editing for hierarchical post types

---

two-factor.php

By adding this filter at default priority, it is applied after code in client-mu-plugins and therefore overrides client code unless clients specifically add it at priority 11. By changing this to 9, we honor client code at the default priority.

Two Factor: Add `wpcom_vip_is_two_factor_forced` before default to allow overriding

---

000-vip-init.php
two-factor.php

The wpcomvip user is responsible for the Jetpack connection, among other things. We don't want to restrict access here and logins are blocked anyway.
I've manually tested on a sandbox with my support user and just changed the username instances to `wpcomvip`.

2FA: Don't restrict wpcomvip, logins are blocked anyway

---

001-core.php

By default, WordPress falls back to a default theme if it can't find
the active theme. This is undesirable because it requires manually
re-activating the correct theme and can lead to data loss in the form
of missing sidebar widgets.
1. Checkout PR
1. Activate a non-default theme.
1. Delete the active theme.
1. Navigate to the Appearance > Themes page.
1. Observe the error message, but the theme does not revert to default.
Expected notice with this change:
```
ERROR: The theme directory "twentyfifteen" does not exist.
```
Expected notice without this change:
```
The active theme is broken. Reverting to the default theme.
```

Disable current theme validation

---

two-factor.php

When connecting a local user to a WordPress.com account via Jetpack, WordPress.com and Jetpack make a few requests back and forth to one another to make sure the connection is legitimate.
Let's not require 2FA to be set up during those WordPress.com -> Jetpack requests, since we don't have all the information yet about whether the user really has 2FA set up :)
Note: Currently, WordPress.com tries these requests via XML-RPC first, and REST as a fallback. For VIP Go sites, we only really need the XML-RPC stuff in this PR (the first commit). The REST stuff is more complicated and will probably never be used currently on VIP Go sites since the XML-RPC request should be sufficient (assuming no other bugs in the connection process :)). It's possible WordPress.com will switch the order at some …

Improve 2FA enforcement compatibility with Jetpack

---

jetpack.php

Upgrades VIP Go sites to Jetpack 7.6
https://github.com/Automattic/jetpack/releases/tag/7.6
1. Verify version in footer
1. Verify version via `wp plugin list`
1. Test a variety of functionality, looking for new warnings / errors

Upgrade Jetpack to 7.6

---

jetpack.php

Updates the JP submodule to 7.7
https://jetpack.com/2019/09/03/jetpack-7-7-better-experience-start/
Example:
1. Ensure correct JP version is reported
1. `wp plugin list`
1. Ensure right JP version is reported

Upgrade JP to 7.7

---

jetpack.php

Updates the JP submodule to 7.7.1
https://github.com/Automattic/jetpack/releases/tag/7.7.1
Example:
1. Ensure correct JP version is reported
1. `wp plugin list`
1. Ensure right JP version is reported

Upgrade Jetpack to 7.7.1

---

vip-jetpack/vip-jetpack.php

Initial syncs are being triggered again overwriting full syncs. See #1257.  However, Jetpack was re-factored and we need to update it with the correct namespace: https://github.com/Automattic/jetpack/blob/a5a11059d24eb7ee50b25dbdb08f04ead55a0d50/packages/sync/src/Main.php#L32

Fix namespacing for remove_action of do_initial_sync

---

files/class-vip-filesystem.php
tests/files/test-vip-filesystem.php

Before deleting files, strip off any query string params that snuck through.
WIP
TBD

Strip query string from file path when deleting files

---

vip-cache-manager/vip-cache-manager.php

Adds an option to disable cache purging on content changes.
1. Apply changes to a platform sandbox host.
1. Sandbox a site (delete and restart if using an existing one)
1. Add the following to `vip-config/vip-config.php`: `define( 'VIP_GO_DISABLE_CACHE_PURGING', true );`
1. Add `error_log( 'Skipping cache purge' );` just before the `return` inside of `init()`, vip-cache-manager/vip-cache-manager.php`
1. Load a page, you should see `[date time] Skipping cache purge` in `/chroot/tmp/php-errors`.
1. Now take away the `define` and reload: you shouldn't see any additional line in `/chroot/tmp/php-errors`

Do not purge cache if VIP_GO_DISABLE_CACHE_PURGING is enabled

---

vip-jetpack/vip-jetpack.php

#1257 was done as stopgap for initial syncs being interrupted.  Now that https://github.com/Automattic/jetpack/pull/1354 is in 7.9, we should remove it.

Revert #1257 now that https://github.com/Automattic/jetpack/pull/1354 is live

---

tests/files/test-image-sizes.php

WordPress 5.3 introduced two new image sizes which are causing our tests to fail because the assertions are not expecting them.
This PR updates the assertions to take those 2 new default image sizes into account.
Note: it's not ideal that the tests are susceptible to upstream changes and would be better to isolate the test environment with more clearly mocked + controlled data. But... we're not there yet.
Skipping as this is a tests only change.
Run the tests and make sure they pass :)

Fix image size tests

---

bin/download-wp-tests.sh

The only external included is the wordpress importer, which we don't really need. It's also currently breaking on CircleCI due to rate limits.
Make sure the tests on Circle work :)

Skip externals for test repo

---

files/class-path-utils.php
tests/files/test-path-utils.php

`Path_Utils::trim_leading_multisite_directory()` will return `false` for file paths that doesn't include the `/sites/#` sub-directory. This causes problems for multisite sites that are running their default site without the `/sites/#` sub-directory as their files are uploaded to the wrong directory.

Accept multisite paths with no `site` sub-directory

---

files/class-vip-filesystem-stream-wrapper.php
tests/files/test-image-sizes.php

Add support for append mode file operations into the streamwrapper class.
Currently using `fopen()` with `a` or `a+` mode or `file_put_contents()` with the `FILE_APPEND` flag does not work as expected. This should fix that.
Example:
1. Sandbox a test site
1. `wp shell`
1. Create new file: `file_put_contents( 'vip://wp-content/uploads/append-test.txt', 'new file' );`
1. Append to file: `file_put_contents( 'vip://wp-content/uploads/append-test.txt', ' appended', FILE_APPEND );`
1. Verify file contents is now `new file appended`.

VIP FS: Add append mode support to streamwrapper

---

tests/test-vip-jetpack.php
vip-jetpack/vip-jetpack.php

Just increases the JP sync queue limits a bit

Increase jp sync queue limits

---

a8c-files.php
misc.php

WordPress 5.3 comes with a new feature capping the max size of uploaded images. This does not seem to be needed on VIP Go as we are using Photon for media handling.
A possible side-effects of limiting the max size of images are users unable to upload hi-res images to their sites.
This can safely land prior 5.3 rollout.

Disable the big image threshold in anticipation of WordPress 5.3 rollout

---

000-vip-init.php

It has been discovered that at least in one case a non-prod domain didn't have a proper robots.txt blocking bots. This commit is intended as a fallback for situations like that.

Add conditional to check for non-production domains based on HTTP_HOST to properly set X-Robots-Tag for non-prod domains

---

back-compat.php

Copies over a patch from WP.com which restores `window.$` which was being leaked by the mediaelement script. WP 5.3 "fixed" that leak but there are many instances of code that still rely on that leaked global.
This will help prevent possible issues until we get all those instances fixed.
props @david-binda 
1. Add the following snippet to a 5.3 site:
```
add_action( 'admin_print_footer_scripts', function() {
?>
<script>console.log( $.fn.jquery );</script>
<?php
}, PHP_INT_MAX );
```
2. Load the post edit page (with classic editor). Console should show an error (related to …

Add back-compat for window.$

---

files/class-api-cache.php
files/class-api-client.php
tests/files/test-vip-filesystem-api-cache.php

The current implementation of caching for the Stream Wrapper have issues with `Out of Memory` errors when uploading large files. This is due to the fact the fact the caching works by creating local, temporary copies of the file which can lead to PHP running out of memory when uploading large files.
Example:
1. Upload a file that's close to the PHP `upload_max_filesize` limit
1. Ensure file is properly uploaded.

Improve stream wrapper cache memory efficiency

---

vip-jetpack/jetpack-mandatory.php

Fixes https://github.com/Automattic/vip-go-mu-plugins/issues/1368
1. Make this change on a VIP Go site.
1. Load the backend and frontend a few times and make sure there aren't any new PHP errors.

Remove ‘manage’ as a mandatory JP module

---

vip-jetpack/vip-jetpack.php

Increases the throughput of JP Sync when running via cron by:
* Allowing the cron job to run for 4 minutes (default is 30s)
* Reducing the wait time between batches from 10s to 1s
The cron job for incremental syncing runs every 5 minutes, but by default is only allowed to run for 30s. This is much too short for VIP sites, so this PR increases the limit to 4 minutes, to allow more items to be processed per cron event, while leaving a small buffer between completion and the start of the next event.
The `sync_wait_time` change affects how long cron waits in between batches of content before restarting, in an effort to reduce performance impacts. By default this is 10 seconds, but VIP can be more aggressive and doesn't need to wait as long (we'll still wait a small amount).
Please make sure …

Increase jp sync throughput on cron

---

two-factor.php

This will make `wpcom_vip_should_force_two_factor` more flexible by allowing other third party SSO solutions or custom logic to help figure out whether or not 2FA should be forced.
This PR will allow customization of whether or not 2FA should be forced. 
Two Usage examples:
* Implement a custom SSO Plugin other than OneLogin or SimpleSaml
* Force 2FA for users that aren't using SSO. For example:
```php
add_filter( 'wpcom_vip_use_custom_sso', function( $enabled ) {
// The user `justnorris` isn't using OneLogin, force 2FA for him
$user = wp_get_current_user();
if ( isset( $user->user_login ) && 'justnorris' === $user->user_login  ) {
return false;
}
// Check if OneLogin SSO is enabled
if ( function_exists( 'is_saml_enabled' ) && is_saml_enabled() ) {
return true;
}
return $enabled;
} );
``` …

Two Factor: Add wpcom_vip_use_custom_sso filter

---

query-monitor.php

The `WPCOM_VIP_QM_ENABLE` constant hasn't been in use since it was switched to a [capability check](https://github.com/Automattic/vip-go-mu-plugins/commit/2718e4a6a816b2af17ebdcd6c8092d2c3cc4e843#diff-211594f60b2377d8575aa91038d52f3c).
This commit fixes the documentation for that change.
N/A - just a documentation change.

QM: Fix docs

---

tests/fixtures/jetpack/class-jetpack-sync-immediately.php
tests/test-vip-jetpack.php
vip-jetpack/vip-jetpack.php

JP 8.0+ includes a new full sync strategy - immediate.
This adds a filter that enables the new strategy, based on the value of the `VIP_JETPACK_FULL_SYNC_IMMEDIATELY` constant, which will be used to do early testing and a gradual rollout of this feature.
TBD

Conditionally enable immediate full sync, based on value of constant

---

debug-bar.php

The existing filter callback to force-enable the Debug Bar for Automatticians was a little too black-and-white. If you are an Automattician, it was enabled, and if you aren't, then it got disabled.
This doesn't work well with filter callbacks that clients might have, that may enable or disable it based on role, capability, or environment.
If they ran at an earlier priority (say, 50), then their conditions get ignored, as the vip-mu-go-plugins code doesn't take any of it into consideration.
If they ran at a later priority, then their conditions would also need to take `is_automattician()` into account, or otherwise Debug Bar gets disabled for VIP Support users; that isn't something that the client code should care about.
The solution is to only force-enable Debug Bar for Automatticians, …

Debug Bar: Play nice with other enable filters

---

.circleci/config.yml

To prep for eventual PHP 7.4 rollout.
Make sure Circle tests run PHP 7.4 and are all 🍏 📗 💚 🥗

Circle CI: Test on PHP 7.4

---

files/class-vip-filesystem.php

Some sites may not use the year/month upload scheme, and the current `check_filetype_with_backend()` will make all uploads fail with this warning:
```
PHP Warning:  The specified file path (`wp-content/uploadsfilename.jpg`) does not begin with `/wp-content/uploads/`. #vip-go-streams in /var/www/wp-content/mu-plugins/files/class-vip-filesystem.php on line 211
```
Unit tests are already written properly at https://github.com/Automattic/vip-go-mu-plugins/blob/e09535fd8b56577479b96033fee9d195f717752a/tests/files/test-api-client.php#L71 so there shouldn't need to be any changes there :)
1. Add `add_filter( 'pre_option_uploads_use_yearmonth_folders', function() {return '0';}, 9999 );` to a site.
1. …

Add trailing slash to make valid upload path

---

files/class-wp-filesystem-vip.php
tests/files/test-wp-filesystem-vip.php

Our custom filesystem class currently blocks most paths, which can be frustrating locally when trying to install and update plugins / themes / etc. via WP_CLI. This allows that to work and simplifies a pretty frustrating part of managing a site on VIP.
Fixes #1370
1. `wp plugin install gutenberg` and `wp plugin install gutenberg --force` should both work
1. `wp plugin uninstall gutenberg` should work
1. `wp plugin install gutenberg --version=5.0` and `wp plugin update gutenberg` should work.
If you're feeling up for it, feel free to test out theme and language updates too :)

Allow local install/updates for plugins/themes/language packs via WP-CLI

---

tests/vip-helpers/test-vip-elasticsearch.php
vip-helpers/vip-elasticsearch.php

Add a filter to rename ElasticPress indexes into something that would work more consistently in VIP Go.
TBD

Add filter for elasticpress index name

---

tests/vip-helpers/test-vip-elasticsearch.php
vip-helpers/vip-elasticsearch.php

Older versions of ElasticPress only pass 2 args to the `ep_index_name` filter which triggers a PHP fatal, so to avoid that, only add the filter when the constant is defined
Example:
1. Install ElasticPresss 2.1
1. Ensure no "too few arguments" fatals are thrown

Add conditional around add_filter() to prevent PHP fatal

---

composer.json
composer.lock
phpcs.xml

Update the PHPCS configuration. See the individual commits for more info, but feel free to squash when merging.
Fixes #1032.
Note that PHPCS is not run as part of Travis as this was [removed](https://github.com/Automattic/vip-go-mu-plugins/commit/8ac02327ec9162d8cd3b6f363e9332ceca87582e), so there will be no effects on builds / jobs for other PRs. There will need to be some tidy-up for this to pass successfully:
- At severity 1, there are 354 errors and 773 warnings.
- At severity 5, there are 342 errors and 554 warnings.
- At severity 6, there are 32 errors and 130 warnings.
Included in this are some PHPCompatibilityWP issues, which are worth fixing sooner rather than later, in a different PR. Work on fixing those, and other violations will be easier to start once this PR is merged. …

Refresh PHPCS configuration

---

tests/vip-helpers/test-vip-elasticsearch.php
vip-helpers/vip-elasticsearch.php

Adds a default `EP_SYNC_CHUNK_LIMIT` value for ElasticPress bulk syncing, when using VIP Elasticsearch.
1. `define( 'USE_VIP_ELASTICSEARCH', true );` in site code
1. `echo EP_SYNC_CHUNK_LIMIT` - should be 250 (default)
1. `define( 'EP_SYNC_CHUNK_LIMIT', 500 );` - should not cause any problems

Add default EP_SYNC_CHUNK_LIMIT constant for bulk syncing

---

tests/vip-helpers/test-vip-elasticsearch.php
vip-helpers/vip-elasticsearch.php

Global type Elasticsearch indexes won't have a blog id for ElasticPress index names, so we need to handle that condition to avoid names like `vip-1-users-` (with a trailing dash).
1. Do a bulk index of users
1. Check ES indexes, should now have one without the trailing hyphen

Conditionally add blog_id to index name

---

001-core/privacy.php

ZipArchive and PclZip don't support stream paths. To make our privacy export workaround work, we're now forcing the archive to be generated locally (in the tmp dir) and then uploaded after.
This also generates the HTML file locally as well, which was previously being generated on the Files Service and then attempted to be downloaded when archiving.
Most of that file and workaround is a bit of a hack so this should be considered a short-term fix.
Fixes #1399 
1. Go to wp-admin > Tools > Privacy
1. Generate a request
1. Attempt to download the file for the request (it should …

Fix privacy archive generation

---

.gitmodules

We are now going to use our own forked version of ElasticPress, because we need to make some VIP-only customization.
1. cd into `elasticsearch`
1. `git submodule sync`
1. `git remote -v` and verify the remote is now pointing to `Automattic/ElasticPress` rather than `10up/ElasticPress`

Use forked version of ElasticPress

---

001-core/privacy.php

When generating an export in a subsite (on a multisite install), the export was always uploaded to the root, rather than the `/sites/%d` path.
This fixes the path of the upload.
This is a quick fix until we can remove most of the workaround hacks in this file.
From a multisite main site:
1. Generate a export request (Tools > Export Privacy Data)
1. Click "download export file"
1. Verify the zip file downloads and has the correct export.
Then:
1. Goto a subsite, and repeat steps above.
Verify again with stream wrapper disabled. Both should work.

Fix subsite upload path for privacy exports

---

tests/test-vip-jetpack.php
vip-jetpack/vip-jetpack.php

Enables queue-less full sync across all non-production sites for beta testing prior to JP 8.2
Example:
1. On non-prod site, ensure the `VIP_JETPACK_FULL_SYNC_IMMEDIATELY` const is always set to `true`
1. On prod site, ensure the constant is not set
1. Define the constant in vip-config.php and ensure there are no conflicts

Enable new JP full sync approach for all non-prod sites

---

alloptions-limit.php

On the Automattic-side, a ping in #vip-deploy-on-call is fairly disruptive to developers. Only things impacting production environments should land there.
This adds that restriction, while maintaining alerts in #nagios-vip.
Quick:
1. Verify no syntax errors
1. Make sure strings and vars are spelled properly
Super-sure:
1. Pick a test site
1. `update_option( 'large-option-test', implode( ' ', range( 0, 149999 ) ) );` should create an option big enough to create a warning (give or take other options)
1. In some environments, IRC may be blocked. Can modify the `wpcom_vip_irc()` lines to use `error_log()` for testing
1. Note the `VIP_GO_ENV` value for your test site and test the conditional

Only ping #vip-deploy-on-call for alloptions issues affecting production

---

lib/proxy/ip-forward.php

A bit dated and the opinions should live outside of code (in our wpvip.com docs)
n/a (no functional changes)
n/a (no functional changes)

IP Forward: Remove mentions of preferred methods from inline docs

---

vaultpress.php

There are a few large and complex JS files that lead to consistently high CPU usage on scan. Ignore them for now until we get things fixed on the VP side.
Non-skipped file:
- `wp shell`
- `$GLOBALS['vp_signatures'] = get_option( '_vp_signatures' );`
- `vp_scan_file( WPMU_PLUGIN_DIR . '/vip-plugins/js/plugins-ui.js' )`
- Should return an empty array
Skipped file:
- `vp_scan_file( WPMU_PLUGIN_DIR . 'elasticsearch/elasticpress/dist/js/ordering-script.min.js' )`
- Should return true

VaultPress: skip some files

---

two-factor.php

Continued from #1424 
We need to actually allow the requests for now rather than passing back the default which is `false`.

$enable => true

---

elasticsearch/class-elasticsearch.php
tests/bootstrap.php

Previously our hooks/constants were defined _after_ the plugin code was loaded, which meant that early-running code (such as on-require) could run before config constants and filters were registered, leading to inconsistent behavior.
1. Setup ES configs (`EP_HOST` and `ES_SHIELD` if applicable)
1. Test ES functionality to ensure it's normal

Setup constants / hooks _before_ loading dependencies

---

elasticsearch/class-elasticsearch.php
tests/bootstrap.php
tests/elasticsearch/test-class-elasticsearch.php

For VIP Elasticsearch, define the requisite ElasticPress constants automatically when they have been defined by the system in wp-config.php
1. Define `VIP_ELASTICSEARCH_ENDPOINTS` to an array of hostnames
1. Define `VIP_ELASTICSEARCH_USERNAME` and `VIP_ELASTICSEARCH_PASSWORD`
1. Check that `EP_HOST` and `ES_SHIELD` are correctly populated with those values

Define the EP_HOST and ES_SHIELD constants automatically

---

elasticsearch/class-elasticsearch.php

ES server is using a self-signed cert during testing phase, will be replaced with real cert in near future then this can be removed.
1. Try query operation - should succeed
1. Try indexing operation - should succeed

Temporarily disable ssl verification on requests to VIP ES server

---

jetpack-start/wp-cli-api.php

Currently the method silently dies in case case WP_CLI::runcommand for `wp user create` errors out. This behavior is opaque and confusing.
To change that this commit updates WP_CLI::runcommand with 
```
[ 
'return' => 'all', 
'exit_error' => false
]
```
This changes behavior for the runcommand - it doesn't die and instead of returning STDOUT only it returns an object:
```
class stdClass#1609 (3) {
public $stdout =>
string(0) ""
public $stderr =>
string(40) "Error: Role doesn't exist: administrator"
public $return_code =>
int(1)
}
```
If `$stderr` is not empty and `$stdout` is, we return a new `WP_Error` with the value of `$stderr`
This should be sufficient for the purpose of surfacing the error.
To further minimize the chance of the child command erroring pass `--skip-themes` and …

Make Jetpack_Start_CLI_Command::maybe_create_user not die silently on error

---

tests/bootstrap.php
vip-helpers/vip-utils.php

Previously, `vip_safe_wp_remote_get()` called `error_log()`, which doesn't properly format the messages for sending to VIP's error log service. This changes that call to a `trigger_error()` (notice level), and adds another logging call that records when requests have been throttled.
Example:
1. Add this to a test site, and ensure the right errors are logged (3 for timeouts, 2 for throttle):
```
for( $i = 0; $i < 5; $i++ ) {
vip_safe_wp_remote_get( 'http://slowwly.robertomurray.co.uk/delay/2000/url/http://www.google.co.uk' );
}
```

Send error logs from vip_safe_wp_remote_request() to main logs

---

vip-jetpack/vip-jetpack.php

To a default that we expect for VIP. This will avoid issues with the option getting corrupted and breaking Jetpack features like Search.
props @mikeyarce and @brettshumaker for the initial batch of work on this.
1. `get_option( 'jetpack_active_plan' )` should return the correct object.
1. Jetpack functionality like Search and Dashboard should continue to work.

Enforce the jetpack_active_plan option

---

README.md

Added text stating that xdebug must be enabled in VVV prior to running tests if you get an error stating that an xdebug function is undefined.
Attempt to run tests as outlined in the README without xdebug enabled on VVV. 
You should get an error of `Error: Call to undefined function Automattic\VIP\Cache\xdebug_get_headers()` or similar.
Turn xdebug on in VVV and then try to run tests again. All tests should pass successfully.

chore: add note about turning xdebug on in vvv prior to running tests

---

elasticsearch/includes/classes/class-health.php

```
Fatal error: Uncaught Error: Class 'Automattic\VIP\Elasticsearch\WP_Error' not found in wp-content/mu-plugins/elasticsearch/includes/classes/class-health.php:52
```
1. Change the `EP_HOST` constant to an invalid host, to fail the connection
1. Run `wp vip-es health validate-counts`
1. Should be no fatal error when the request fails

Add missing 'use' statement for WP_Error class namespace

---

elasticsearch/includes/classes/class-health.php

By default, it stops at 10,000. We can ask for an exact number by setting the `track_total_hits` arg.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#track-total-hits-10000-default
- On a test site with indexed documents more than 10K, run `wp vip-es health validate-posts-count`
- Verify that diff doesn't error.

Get accurate total count from Elasticsearch

---

elasticsearch/includes/classes/class-health.php

The `diff` returned by the health class should be an int and the calling class should decide what to do with it.
Right now, we're sending a string which makes the value less useful and makes the output somewhat awkward: `(DB: 5789, ES: 0, Diff: , diff: -5789)`
With this change, we're much cleaner: `(DB: 5789, ES: 0, Diff: -5789)`
- Run `wp vip-es health validate-posts-count`
- Verify that the diff output looks clean.

ES Health: Cleanup diff output

---

elasticsearch/includes/classes/class-elasticsearch.php

Limit the Elasticsearch health check cron job to only run on `production` sites.
Example:
1. Sandbox a production site
1. Ensure the `vip_search_healthcheck` job is scheduled

Start health check only on production env

---

elasticsearch/includes/classes/class-health-job.php

Found by looking at PHP logs:
```
phpfpm_1         | NOTICE: PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/mu-plugins/elasticsearch/includes/classes/class-health-job.php on line 93
```
1. Look at your PHP (or phpfpm if you are using 10updocker) logs, they should be clean, no warnings.

Fix typo in variable name

---

elasticsearch/includes/classes/class-elasticsearch.php
tests/elasticsearch/test-class-elasticsearch.php

Deactivate all the automatically registered Jetpack widgets when VIP Search is enabled as the widgets will force the site to keep using Jetpack search.
1. Enable JP Search + a widget on a test site
1. Set `USE_VIP_ELASTICSEARCH` to true in wp-config.php
1. Run a query on the frontend - JP Search should not enable itself (check Debug Bar for any Elasticsearch queries from JP)

Deactivate jetpack widgets when VIP search is enabled

---

elasticsearch/includes/classes/class-health-job.php
elasticsearch/includes/classes/class-health.php
elasticsearch/includes/classes/commands/class-healthcommand.php

Fixes [PLAT-911].
Also adds a missing check on the result of `Indexables::factory()->get()` that may return `boolean|Array`.
In case of failure, that function returns `false` so we must take that into account.
1. Delete ES indexes on test site: `dcwp elasticpress delete-index`.
1. Run the validation command: `dcwp vip-es health validate-counts`.
1. Verify that no stacktrace gets printed out.
[PLAT-911]: https://vipjira.atlassian.net/browse/PLAT-911

Fix fatal error in validate-health command

---

elasticsearch/elasticpress/includes/classes/Indexable.php
elasticsearch/includes/classes/class-elasticsearch.php
tests/elasticsearch/test-class-elasticsearch.php

PLAT-885
Increase ep_bulk_items_per_page and EP_SYNC_CHUNK_LIMIT to 500
TBD

Increase ep_bulk_items_per_page and EP_SYNC_CHUNK_LIMIT to 500

---

elasticsearch/elasticsearch.php

Since we're only requiring one file here, an auto-loader seems a bit
overkill. Having the explicit `require_once` line leaves no doubt
about what code is running and where.
Example:
1. `define( 'USE_VIP_ELASTICSEARCH', true );`
1. Go to `wp-admin`
1. Verify ElasticPress menu shows on the left

Switch Elasticsearch auto-loader to require_once

---

vip-plugins/vip-plugins.php

Ensures that if a value stored in `wpcom_vip_active_plugins` is not an array, that the subsequent `foreach` does not run. Without it, "Invalid argument supplied for foreach" PHP Warnings are generated (currently ~3700 per day on VIP Go).
Fix could optionally also include a ` || empty( retired_plugins_option )` in the conditional as well, though the `foreach` should not through a warning for an empty array. 
1. `wp option set wpcom_vip_active_plugins notanarray`
1. Load site and check logs for "Invalid argument supplied for foreach" PHP Warnings.
1. Apply PR
1. Load site again, and check for no new PHP Warnings.

Shared plugins: Add defensive code to fix Warning

---

.gitmodules
elasticsearch/elasticsearch.php
elasticsearch/includes/classes/class-elasticsearch.php
tests/elasticsearch/test-class-elasticsearch.php

Fixes [PLAT-924].
Adds the debug bar plugin for ElasticPress and loads it if ES is enabled and EP is loaded.
Clone the PR on a sandbox host.
Sandbox a site and activate VIP Search; verify that the Debug bar contains an "Elastic Press" item.
Query monitor should not contain anything related to EP, instead.
[PLAT-924]: https://vipjira.atlassian.net/browse/PLAT-924

Add debug-bar-elasticpress submodule

---

elasticsearch/includes/classes/class-elasticsearch.php

Do not allow sync via Dashboard (WP-CLI is preferred for indexing). The Dashboard is hidden anyway but just in case.
1. On a site with VIP Search enabled, `wp shell`.
1. `constant( 'EP_DASHBOARD_SYNC' )` should be false.

Add EP_DASHBOARD_SYNC constant

---

elasticsearch/includes/classes/class-elasticsearch.php

We're ready to re-enable SSL cert verification in our ES requests, so this PR does that :)
1. Try various ES operations - querying from frontend, indexing on CLI
1. Nothing should error

Re-enabled ssl verification in ES requests

---

elasticsearch/includes/classes/class-dashboard.php
elasticsearch/includes/classes/class-elasticsearch.php

We don't need most of the EP dashboard. We'll provide a custom
dashboard for things like health info and we don't want it to
be possible to trigger an index operation from the dashboard.
Note: This only hides the dashboard so far. We'll also want to
explicitly block indexing from the dashboard.

Remove ElasticPress dashboard

---

elasticsearch/includes/classes/class-elasticsearch.php
elasticsearch/includes/classes/class-health-job.php
elasticsearch/includes/classes/commands/class-healthcommand.php
tests/elasticsearch/includes/classes/commands/test-class-healthcommand.php
tests/elasticsearch/includes/classes/test-class-healthjob.php
tests/elasticsearch/test-class-elasticsearch.php

We're missing some requires now that we removed the autoloader, and I missed updating a variable name in one spot.
Example:
1. `wp vip-es health validate-counts`
1. `wp shell`
1. `do_action( 'vip_search_healthcheck' );`

Fix missing require for es health class and typo

---

elasticsearch/includes/classes/class-health-job.php
tests/elasticsearch/includes/classes/test-class-healthjob.php

The new isset() to prevent undefined index warnings caused the reporting to run for all results, instead of just those where a diff was detected.
This PR adds tests to `Health::process_results()` to prevent future regressions.
Example:
1. `wp shell`
1. `do_action( 'vip_search_healthcheck' )`

Only alert when diff is not 0

---

elasticsearch/includes/classes/class-elasticsearch.php

This code runs on plugins_loaded, but the EP debug bar also hooks into plugins_loaded, so we need to explicitly call the setup function ourselves to ensure it registers itself.
Example:
1. Run some search queries
1. Ensure queries show up in EP Debug Bar

Manually setup EP Debug Bar logging due to plugins_loaded already firing

---

a8c-files.php

This will be bundled with an internal change to incrementally release stream wrappers to all envs.
There are lots of other unused functions now in this file that can likely be removed, but we'll want to throw a deprecated notice to them first just to be safe.
1. Try to upload a file to the media library.
1. Verify it works.

Enabled Stream Wrappers on AMS

---

elasticsearch/includes/classes/class-health-job.php
tests/elasticsearch/includes/classes/test-class-healthjob.php

If the Users feature is not enabled, the check will always fail.
1. Ensure healthchecks are enabled - `add_filter( 'enable_vip_search_healthchecks', '__return_true' );`
1. `wp elasticpress deactivate-feature users`
1. `wp shell`
1. `$job = new \Automattic\VIP\Elasticsearch\HealthJob()`
1. `$job->check_health()`
1. Ensure it doesn't try to run the user healthcheck - may need to add manual debug code (var_dump(), etc)
1. Enable the feature with `wp elasticpress activate-feature users`
1. Repeat above, ensure the users check runs

Only validate user counts in Search healthcheck if Users feature is enabled

---

000-vip-init.php
elasticsearch/elasticsearch.php
elasticsearch/includes/classes/class-dashboard.php
elasticsearch/includes/classes/class-elasticsearch.php
elasticsearch/includes/classes/class-health-job.php
elasticsearch/includes/classes/class-health.php
elasticsearch/includes/classes/commands/class-healthcommand.php
tests/elasticsearch/includes/classes/commands/test-class-healthcommand.php
tests/elasticsearch/includes/classes/test-class-healthjob.php
tests/elasticsearch/test-class-elasticsearch.php

Rename references to "Elasticsearch" with "VIP Search"
NOTE - this doesn't rename any files / directories, just references in code / comments / tests. Files will be renamed in a separate PR.
Example:
1. Try a command - `wp vip-search health validate-counts`
1. Try some searches - `?s=test` - ensure searching works normally

Replace Elasticsearch references with VIP Search

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Disable document indexing. Not currently supported.
NOTE - this is branched off #1481 to prevent merge conflicts, so that will need to be merged first.
1. Attempt to enable document indexing via EP UI
1. Ensure feature stays disabled
1. Attempt to enable document indexing via CLI - `wp elasticpress activate-feature documents`
1. Ensure feature stays disabled

Disable document indexing feature

---

tests/search/test-class-search.php

Updates our EP submodule to `master` on `Automattic/ElasticPress`.
Brings in EP 3.4 plus term re-indexing, the failed request hook, and a fix for the post status array
1. Try some searches `?s=test`
1. Try CLI commands: `wp elasticpress index`, `wp vip-search health validate-counts`

Update ElasticPress submodule to master

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

[PLAT-863]
Added a filter for `ep_pre_request_host` to round-robin retry our endpoints.
Added a random load balance implementation for setting EP_HOST from our endpoints.
2. `./bin/phpunit-docker.sh tests/search/test-class-search.php`
[PLAT-863]: https://vipjira.atlassian.net/browse/PLAT-863

Add retries and random load balancing for EP_HOST

---

.huskyrc.json
README.md
package-lock.json
package.json

Uses husky to automatically add a pre-commit hook that auto-runs `phpcs:changed:local`  automatically on commit (assuming `npm install` has been run).
```
$ git ci
husky > pre-commit (node v10.15.2)
> @automattic/vip-go-mu-plugins@1.0.0 phpcs:changed:local /Users/mjangda/Sites/vipgo/mu-plugins-docker/mu-plugins
> vendor/bin/phpcs --report=bin/phpcs-eslint-report.php | eslines --quiet -d index
[update/husky-pre-commit ff53fd2f] Update README with details about PHPCS
1 file changed, 19 insertions(+)
```
n/a
1. `composer install`
1. `npm install`
1. Edit a file and add a PHPCS issue (e.g. `$a     = [  ];`)
1. `git add` + `git commit`
The commit should fail.

Add husky to enforce phpcs on pre-commit

---

.circleci/config.yml
.huskyrc.json
Makefile
bin/php-lint.sh
package.json

Builds on #1486.
Drops most of the stuff from Makefile since that wasn't really being used and centralizes into npm scripts so we have fewer entry points. And adds to husyrc so we can run linting on pre-commit.
```
$ git ci
husky > pre-commit (node v10.15.2)
> @automattic/vip-go-mu-plugins@1.0.0 phplint /Users/mjangda/Sites/vipgo/mu-plugins-docker/mu-plugins
> bin/php-lint.sh
> @automattic/vip-go-mu-plugins@1.0.0 phpcs:changed:local /Users/mjangda/Sites/vipgo/mu-plugins-docker/mu-plugins
> vendor/bin/phpcs --report=bin/phpcs-eslint-report.php | eslines --quiet -d index
[update/husky-lint-pre-commit 26b063ca] Update readme for php lint changes
1 file changed, 5 insertions(+), 1 deletion(-)
```
n/a
1. `npm install`
1. Edit a file and add a PHP error.
1. `git add -u` and `git commit`
This …

Add php linting to pre-commit

---

search/includes/classes/class-search.php
search/includes/functions/ep-get-query-log.php

[PLAT-975]
Added and required 'ep_get_query_log' function to override queries and filter out the Authorization header so it's not shown in the ElasticPress debug bar/QM panel.
1. Make sure you constants are set locally for Search(including relevant Search-specific username and password constants).
2. Do a search locally. Check the headers of the action in the EP debug bar. You should see an `Authorization` header.
3. Pull down PR.
4. Do a search locally(again). Check the headers of the action in the EP debug bar. You shouldn't see the `Authorization` header anymore.
[PLAT-975]: https://vipjira.atlassian.net/browse/PLAT-975

Search: Hide Authorization header in EP Debug Bar request log

---

search/includes/classes/class-health.php

Indexable::query_es result was changed slightly. So 'found_documents' is now the result count and not 'found_documents'['value']. This caused our health checks to fail.
1. `wp vip-search health validate-counts` # it will fail.
3. `wp vip-search health validate-counts` # It will succeed.

Fix health check failure notifications related to index counts

---

wpcom-vip-two-factor/sms-provider.php

Per #1476, we now have standardized SMS messages for 2FA.
The new (current) format looks like:
```
123456 is your FooBar verification code.
@foobar.com #123456
```
We currently do not include the path of the Site URL which is needed for subsites of multisites (e.g. - `example.com/subsite` will only return `example.com`).
- [ x ] This change works and has been tested on a Go sandbox.
- [ N/A ] This change has relevant unit tests (if applicable).
2. On a multisite:
Go to wp-admin > Edit My Profile > Two-Factor Options > SMS
3. Enter your SMS number and click Submit
4. Check your phone and verify the message format. It should look like:
```
123456 is your FooBar verification code.
@foobar.com/subsite #123456
```
The parent site, or any single sites, should still return:
``` …
```

Fix 2fa SMS messages to include path for multisite subsites

---

phpcs.xml.dist

Not relevant for mu-plugins since that function can be used in this codebase.

phpcs: Ignore wpcom_vip_irc function rule

---

001-cron.php

PLAT-943
As is conventional, send alerts for "option uncacheable" messages to the `#vip-go-criticals` channel.
1. Check out the branch in this PR
1. Make sure the `wpcom_vip_log_cron_control_uncacheable_cron_option` function exists & is callable without syntax errors

Alerts: Send option uncacheable alerts to the critical channel

---

search/includes/classes/class-search.php

Temporarily disable user indexing feature.
1. Enable user feature.
2. Run a health check. It should run.
3. Run a health check, user check should cause `Warning: failure retrieving user documents from ES #vip-search`

Temporarily force disable user indexing

---

vip-helpers/vip-utils.php

Removed alert for if you're not using Gutenburg. It was logging quite a bit to certain sites and is no longer needed.

Removed gutenburg alert

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Needed more validation checks for empty array and non-arrays so that
those values don't get handed into the get_next_host function.
1. Define `VIP_ELASTICSEARCH_ENDPOINTS` as empty array.
2. Trigger an `ep_pre_request_host` action. You should get an error.
3. Pull down PR.
4. Trigger an `ep_pre_request_host` action. You shouldn't get an error.

More validation checks for ep_pre_request_host

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

This adds a custom HTTP header to indicate when the search results came from Elasticsearch.  This is necessary in cases where we want to ensure the search didn't fall back to using the wpdb query.
1. Check out PR on a site with ElasticPress enabled
1. Enter a search term and click "Search"
1. Verify that the custom header was sent in the HTTP response for the results request.

Add header to indicate when search results come from Elasticsearch

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

The index isn't dropped or anything, docs are just re-indexed in-place, so it's safe to allow queries against the index while a bulk index is being performed.
NOTE - the filter doesn't yet exist, but will as of https://github.com/Automattic/ElasticPress/pull/15 (safe to deploy without it though)
1. First have to be sure you're running the new filter from https://github.com/Automattic/ElasticPress/pull/15
1. Then start a bulk index with `wp elasticpress index`
1. While the index is running, perform some searches (`?s=test`)
1. EP Debug Bar should report queries were performed while the indexing was occurring

Allow queries during indexing

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

\ElasticPress\Elasticsearch only records queries if WP_DEBUG or WP_EP_DEBUG are true - we're not setting those in prod (WP_DEBUG is set on sandboxes) so the debug bar panel is showing no queries.
See https://github.com/Automattic/ElasticPress/blob/941b5c69e1b0622babe3c54852e03a1a91b70d33/includes/classes/Elasticsearch.php#L1299
1. Ensure `WP_DEBUG` is `false`
1. Ensure the `debug_bar_enable` filter returns true (may need to add a filter locally)
1. (For local testing, may also need to comment out this line, which works in local dev but not in production, otherwise it'll set the WP_EP_DEBUG constant instead of our …

Add the missing WP_EP_DEBUG constant

---

phpcs.xml.dist

The `minimum_supported_wp_version` property [is used](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#minimum-wp-version-to-check-for-usage-of-deprecated-functions-classes-and-function-parameters) for checking deprecated functions, classes and function parameters, and alternative functions.
By default, the value of the `minimum_supported_wp_version` property is set to three versions before the currently released WP version (disregarding patch releases). [Currently `5.0`](https://github.com/WordPress/WordPress-Coding-Standards/blob/2f927b0ba2bfcbffaa8f3251c086e109302d6622/WordPress/Sniff.php#L85).
There are no new violations if this is set to 5.3, but it will mark deprecations as Errors when used in the future.
Aside: Also removes the …

PHPCS: Add minimum_supported_wp_version of 5.3

---

vip-helpers/vip-wp-cli.php

When we nerf the stats object, it causes errors because the object cache dropin assumes the array exists in a certain format. The value of deleting this object is limited because there are only a handful of integers. It won't actually reclaim that much memory.

Don't nerf $wp_object_cache->stats in stop_the_insanity()

---

tests/wpcom-vip-two-factor/sms-provider.php
wpcom-vip-two-factor/sms-provider.php

We're formatting the SMS code as a number, but it's really a string that just happens to be made up of numbers. If it starts with 0, we don't want the leading 0 to be truncated.
```
php > var_dump( sprintf( '%d', '08' ) );
string(1) "8"
```
```
php > var_dump( sprintf( '%s', '08' ) );
string(2) "08"
```

Fix SMS codes with leading zeros

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Disable facet queries in VIP Search but still set the default facet taxonomies size just in case it gets enabled at some point so it doesn't error out.
1. Do a search with VIP Search enabled.
2. Check the Query body in QM/debug bar, there will be multiple size attributes.
3. Check out PR.
4. Do a search.
5. There should now only be one size attribute.

Add facet query filters to search

---

.deployignore
tests/search/data/test_fixtures.yml

Added yaml config for search testing.
This yaml can be run with [nlemoine/wp-cli-fixtures](https://github.com/nlemoine/wp-cli-fixtures) to generate fake data for testing purposes.  
Presently being run.

Added yaml config for search testing

---

lib/wpcom-error-handler/wpcom-error-handler.php

Checks error type is a numeric value first before checking if the error type is in `error_reporting`.
This is to prevent the error:
`PHP Warning: A non-numeric value encountered in /chroot/var/www/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 85`
TBD

Check type is numeric first

---

search/includes/classes/class-search.php

Adds a new option, `vip_enable_vip_search_query_integration`, that if set to a truthy value (`true`, `1`, or `yes`), will enable search integration, even if the `VIP_ENABLE_VIP_SEARCH_QUERY_INTEGRATION` constant is not set.
1. Disable integration (ensure constant is not set)
1. Run a query - ensure VIP Search didn't run
1. Set the option `wp option set vip_enable_vip_search_query_integration true`
1. Re-run a search - VIP Search should kick in
1. Disable the option - `wp option set vip_enable_vip_search_query_integration false`
1. VIP Search should not run
1. Enable the constant
1. VIP Search should run

Allow enabling search query integration via an option

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Add track_total hits as true to formatted args.
Only when the value isn't already set.
1. Do a search with VIP Search enabled. The query body won't have 'track_total_hits' set.
2. Checkout the PR.
3. Do a search with VIP Search enabled. The query body will have 'track_total_hits' set to true.

Add track_total hits as true to formatted args

---

000-vip-init.php
lib/statsd/class-statsd.php

Add StatsD library
1. Run StatsD locally - it's very easy:
1. Clone https://github.com/statsd/statsd
1. Edit `exampleConfig.js` in that directory to this:
```
{
port: 8125
, backends: [ "./backends/console" ]
}
```
1. Run StatsD - `node stats.js exampleConfig.js`
1. Define the host/port constants somewhere:
```
define( 'VIP_STATSD_HOST', 'host.docker.internal' );
define( 'VIP_STATSD_PORT', 8125 );
```
1. Anywhere in the code path, just track a stat:
```
$statsD = new Automattic\VIP\StatsD();
$statsD->increment( 'my-custom-stat' );
```
1. Watch the StatsD console and see the stat being recorded

Add StatsD library

---

search/includes/classes/class-search.php

Fuzziness is enabled by default for queries. This results in some pretty unexpected search results since something like 'March' would match 'arch' and anything else within a Levenshtein distance of 1. Not great for search relevancy or performance.
1. Perform a search with VIP Search and query monitory/debug bar enabled.
2. Note that fuzziness is 1 in places.
3. Apply PR.
4. Perform another search.
5. Fuzziness is 0 across the board.

Remove fuzziness from EP search queries

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Added a quick win for search relevancy
Only applied when the query structure is in an expected format
1. `./bin/phpunit-docker.sh tests/search/test-class-search.php`
1. Run a VIP Search without this PR that doesn't changed formatted args structure.
2. Record the query body from ElasticPress tab of Query Monitor/Debug Bar.
3. Apply this PR.
4. Run the same search.
5. Record the query body from ElasticPress tab of Query Monitor/Debug Bar.
6. Compare the query bodies. There should be one 'should' replaced with a 'must' and a new 'AND'.

Added a quick win for search relevancy

---

bin/upgrade-plugin.sh

Currently supports just VaultPress and Akismet but makes it easier to go through and update to the latest but automating a few of the steps.
Could be improved further in additional PRs by:
- Updating the version number in the mu-plugins plugin file
- Adding support for other plugins including those in subdirs and using submodules (e.g. Jetpack)
- n/a This change works and has been tested on a Go sandbox.
- `./bin/upgrade-plugin.sh` should show usage
- `./bin/upgrade-plugin.sh akismet` should update akismet locally
- `./bin/upgrade-plugin.sh other` should fail

First pass at simple plugin upgrade script

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Only run index validation when it's expected to be consistent - so not when an index is being built, or no index yet exists.
Depends on https://github.com/Automattic/ElasticPress/pull/26
Tricky to actually test b/c healthchecks don't run outside production, but can try this:
1. `define( 'VIP_GO_ENV', 'production' );`
1. Start a bulk index - `wp elasticpress index`
1. In a separate `wp shell`, try `\Automattic\VIP\Search\HealthJob::is_enabled()`

Disable search index validation until index is built

---

search/includes/classes/class-search.php

Depends on https://github.com/Automattic/ElasticPress/pull/25
Applied the defaults from Jetpack Search to the ElasticPress filters
1. Do a search with VIP Search. Note the results.
2. Apply PR.
3. Do the same search with VIP Search.
4. Note the increased date relevancy.

Added new defaults for date relevancy

---

logstash/class-logger.php
tests/logstash/test-logger.php

Fixes `TypeError` originating from merging code from #1530 
Fixes #1534 
1. Checkout PR
1. Make sure your local environment will try to store log data to `debug.log` by setting `VIP_GO_ENV` to `false` and `WP_DEBUG` to `true`
1. Create a log message by calling `Logger::log2logstash()`
1. Confirm there is no `TypeError` in the PHP error log

Fix TypeError in maybe_wp_debug_log_entries

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php
tests/search/includes/classes/test-class-health.php

Going to move detailed diff to a different command runnable on a range of post ids.
Added --silent, --format, --batch_size, and --max_diff_size flags for
controlling output level, output format, batch size, and max memory
usage for diff array respectively.
1. `./bin/phpunit-docker.sh tests/search/includes/classes/test-class-health.php`
--------
1. Have an indexed VIP Search running.
2. `wp vip-search health validate-contents --help`
3. Pull down PR
4. `wp vip-search health validate-contents --help`
5. Note the new commands and try them out.
----------
1. Have an indexed VIP Search running.
2. `wp vip-search health validate-contents`
3. Pull down PR
4. `wp vip-search health validate-contents`
5. Note the …

Reduced diff output for validate-content and added options

---

search/includes/classes/class-health.php
search/includes/classes/commands/class-healthcommand.php
tests/search/includes/classes/test-class-health.php

Depends upon https://github.com/Automattic/vip-go-mu-plugins/pull/1545
Add inspect flag for validate-contents command
1. `./bin/phpunit-docker.sh tests/search/includes/classes/test-class-health.php`
-----
1. Have a fully indexes VIP Search instance.
3. Run `wp vip-search health validate-contents --inspect`
4. It should work.

Add inspect flag for validate-contents command

---

000-vip-init.php
search/includes/classes/class-search.php

Adds an optional static `instance()` method to the Search class, to easily access the main instance from anywhere in the code base without relying on globals.
Example:
1. Perform a variety of search operations - ensure everything works normally

Add a singleton instance() method to Search class

---

files/class-vip-filesystem-stream-wrapper.php
tests/files/test-vip-filesystem-stream-wrapper.php

Previously, the temporary file name was used for the file contents for the _new_ file.  This will pull the actual file contents and use it instead.
Currently, when a file goes through PHP's `rename()` the stream wrapper will download a copy, and try to upload a new copy with the new name.  Unfortunately, instead of copying the file it just uploads a new file with a `tempnam()` as its contents.
1. Grab an uploaded URL from a site.
1. `wp shell` in
1. Do a `rename()` on the file, and then `curl` the _new_ file to see its contents is broken
1. Check out PR and merge the fixes, etc...
1. Do a _new_ `rename()` and `curl` the _new_ file again to see that it's now correct.

Fixes an issue with `rename()` breaking files.

---

files/class-vip-filesystem-stream-wrapper.php

After merging #1426 , the following errors are spotted in log file after a media upload:
```
[10-Apr-2020 08:41:10 UTC] PHP Warning:  stream_flush failed for wp-content/uploads/2020/04/2B7BACFB-A449-4520-8DFA-C227E776CB93.jpg with error: No writes allowed in "read" mode    #vip-go-streams in /var/www/wp-content/mu-plugins/files/class-vip-filesystem-stream-wrapper.php on line 309
[10-Apr-2020 08:41:10 UTC] PHP Stack trace:
[10-Apr-2020 08:41:10 UTC] PHP   1. {main}() /var/www/wp-admin/async-upload.php:0
[10-Apr-2020 08:41:10 UTC] PHP   2. wp_ajax_upload_attachment() /var/www/wp-admin/async-upload.php:33
[10-Apr-2020 08:41:10 UTC] PHP   3. media_handle_upload() /var/www/wp-admin/includes/ajax-actions.php:2546
[10-Apr-2020 08:41:10 UTC] PHP   4. wp_generate_attachment_metadata() …
```

Streamwrapper: Check if file is read mode first before flush

---

files/class-vip-filesystem-stream-wrapper.php
tests/files/test-vip-filesystem-stream-wrapper.php

A bug in the file mode validation method results in it returning an undefined value instead of true.
Fixes #1552  
Example:
1. Upload code to sandbox
1. `wp shell`
1. Create a new file with mode `x`: `fopen( 'vip://wp-content/uploads/new-file.txt', 'x' );`
1. Verify file opened properly

Streamwrapper: Fix bug in file mode validation method

---

vip-jetpack/css/mandatory-settings.css
vip-jetpack/vip-jetpack.php

A couple of small UI changes to hide some of the Instant Search elements for now
1. Pull down PR locally or to sandbox
1. Navigate to Jetpack setting screen (`/wp-admin/admin.php?page=jetpack#/performance`)
1. Under the Search section under the "Add Jetpack Search Widget", confirm that this card/button no longer appears: "Help visitors quickly find answers with highly relevant instant search results and powerful filtering | Upgrade "

Tweaks for Jetpack 8.4

---

search/includes/classes/class-search.php

Have an object cache value that expires in a reasonable time frame(currently set to 5 minutes).
Increment the value for each request that passes through VIP Search.
If this value gets higher than the define limits, disable query integration for roughly half of the requests.
1. Checkout PR
2. Change `private static $max_query_count = 3000 + 1;` to `private static $max_query_count = 1;`
3. Run a search with QM/Debug Bar open for ElasticPress.
4. Keep refreshing the page while watching the queries.
5. Roughly half shouldn't go through ElasticPress.
6. Reset `private static $max_query_count` back to normal.

Offload queries to database if RPS too high in VIP Search

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

This modifies the default shard + replica counts for ES indexes to the following:
1 shard on most indexes
4 shards on sites with over 1 million posts
2 replicas on all indexes
Example:
1. Create new index - `wp elasticpress index --setup`
1. Verify that all functionality works as expected
1. Verify shard + index counts with the `/<index>/_settings` API endpoint

Set default es shard + replica count

---

search/includes/classes/class-search.php

EP has a bug in the Facets feature where Facets can be incorrectly enabled on regular queries, causing them to be served by ElasticPress.
This works around that (as a temporary measure) for a few sites experiencing this problem by skipping query integration for the main query on them.
Example:
1. Test regular queries
1. Test HP on affected sites, ensure no ES queries are performed

Disable EP queries on the HP on some sites

---

search/includes/classes/class-search.php

Exact search was added to sort out search relevancy on certain sites. Since that also ruined search relevancy for certain search queries on another site but didn't really affect things on other sites, a whitelist for enabling exact search was added for VIP Go sites. 
1. Do a search, note the query body in the ElasticPress debug bar.
3. Do a search, note the change to the query body in the ElasticPress debug bar.

Added whitelist for exact search

---

vip-helpers/vip-stats.php

Fixes https://github.com/Automattic/vip-go-mu-plugins/issues/1565
More info in the issue, but essentially `stats_get_csv()` returns like this:
```
stats_get_csv( 'postviews', [ 'post_id'=> 123 , 'num_days' => 90 ] );
> array(1) { [0] => array(1) { 'views' => "10123" } }
```
To get the view number, it needs to go a level deeper. I also tested with invalid IDs and the logic continues to work (views is still set as a key, just to NULL). The function calls `absint()` at the end as well, so this function will always return a number. 
I took a look over existing usage and it looks mainly in use by those coming from WPcom migrations, specifically ones migrating right now/soon.

Return the correct view count from wpcom_vip_get_post_pageviews()

---

search/includes/classes/class-queue.php
search/includes/classes/queue/class-cron.php
search/includes/classes/queue/class-schema.php
tests/search/includes/classes/queue/test-class-cron.php
tests/search/includes/classes/test-class-queue.php

Prevent deadlocks in the async indexing queue by recording when a job is scheduled (when a cron job is created to process it), then free up any deadlocked jobs in the "sweeper" job.
Currently it's configured to consider a job deadlocked after 5 minutes, which means, if it was scheduled via a cron job, but hasn't been finished within 5 minutes, it's deadlocked and will be re-scheduled.
1. Visit an admin page to trigger the db schema update
1. Manually add an item to the queue table, with status = `scheduled` and a `scheduled_time` in the past (over 5 minutes ago)...this is a "deadlocked" job
1. Run the sweeper cron …

Add deadlock protection to indexing queue

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Record Search stats on a per-app and per-index basis.
NOTE - keeps existing "global" stats for backwards compatibility with existing dashboards.
1. `define( 'VIP_STATSD_HOST', 'docker.for.mac.localhost' );`
1. `define( 'VIP_STATSD_PORT', 8125 );`
1. Run some queries
1. Watch StatsD output - should include metrics for both the global stats, then metrics the site id and index name in them

Add per site/index search stats

---

.circleci/config.yml
search/includes/classes/class-search.php
tests/search/test-class-search.php

Adds compatibility with es-wp-query, which uses `es` as the query var to enable offloading. ElasticPress uses `ep_integrate`, so this PR just lets you use either.
1. Pull PR
1. In functions.php (or anywhere), add this to enable query offloading on the main query:
```
add_filter( 'pre_get_posts', function( $query ) {
if ( ! $query->is_main_query() ) { 
return $query;
}
if ( ! $query->is_category() && ! $query->is_home() ) {
return $query;
}
$query->set( 'es', true );
} );
```
1. Visit several frontend pages (hp, category, etc)
1. Check debug bar - should be recording 1 ES query per page (with arguments matching the normal WP_Query)

Support offloading WP_Query to ES via the 'es' query var

---

search/includes/classes/class-search.php

Allows user indexing in Search - will still be disabled by default, but this allows clients to opt-in.
1. `wp elasticpress activate-feature users`
1. Check the ElasticPress dashboard in WP Admin to see if the Users feature shows as Enabled (it should)
1. NOTE - can't use `wp elasticpress list-features` to verify this b/c there is a bug - it [doesn't check the filter](https://github.com/Automattic/ElasticPress/blob/c2e7749477e67480f5481c36ba86e4160d100656/includes/classes/Command.php#L137-L143) that the other code uses :(

Allow user indexing in Search

---

search/includes/classes/class-queue.php
search/includes/classes/class-search.php
tests/search/includes/classes/test-class-queue.php
tests/search/test-class-search.php

Added ratelimiting for indexing operations. A bit more succinct and focused than initial thoughts/test implementations.
Still needs tests and verification.
1. Checkout PR.
2. `./bin/phpunit-docker.sh tests/search/includes/classes/test-class-queue.php`
-----
1. Checkout PR.
2. Ensure Automattic/Elasticpress is working.
3. Set `$max_indexing_op_count` in `search/includes/classes/class-queue.php` to 0.
4. Add a new post in wp-admin.
5. The post should be added to the queue(`wp_vip_search_index_queue` database table)

Added ratelimiting for indexing operations

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

Adds "query mirroring" functionality for transparently testing the offloading of queries on VIP Search.
1. Pull PR
1. Make sure the site is enabling query mirroring - `define( 'VIP_ENABLE_SEARCH_QUERY_MIRRORING', true );`
1. Try some queries and check debug bar - there should be _no_ ES queries yet
1. Enable query mirroring by adding some rules to `should_mirror_wp_query()`:
```
// Is this one of the targeted queries?
if ( $query->is_home() || $query->is_category() || $query->is_archive() ) {
return true;
}
```
1. Request the HP, a category page, and an archive page
1. Each should run the regular DB query, but also the ES version …

Add support for query mirroring for offloaded queries

---

search/includes/classes/class-search.php

Enables the WP_Query "query mirroring" (to ES) on site 2160 for category + archive queries, for testing.
Example:
1. Sandbox 2160
1. Navigate around the site (visit a variety of pages, page through a category, page through a year/month)
1. Nothing should be broken :)

Enable query mirroring on category+archives for site 2160

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Disable VIP Search health checks for 2341
1. Checkout PR.
2. `./bin/phpunit-docker.sh tests/search/includes/classes/test-class-healthjob.php`

Disable healthchecks for 2341
