vip-helpers/vip-utils.php

We want to know the exact URL that was hit so we can reproduce what's happening.

Add URI to New Relic

---

misc.php

Prevent concatenation outside VIP Go

---

jetpack.php

Update to latest release, per https://github.com/Automattic/jetpack/releases

Jetpack 4.0.4

---

jetpack.php

See https://github.com/Automattic/jetpack/releases/tag/4.1.0

Update to Jetpack 4.1

---

jetpack.php

Bumps us to the latest version: https://github.com/Automattic/jetpack/releases/tag/4.1.1.

Update to Jetpack 4.1.1

---

cache-manager.php

Don't send New Relic data for cache health check requests

---

misc.php

Prevent alloptions pollution

---

a8c-files.php

Hardcode upload limit to 1GB

---

shared-plugins/wpcom-legacy-redirector/includes/wp-cli.php
shared-plugins/wpcom-legacy-redirector/wpcom-legacy-redirector.php

Update legacy redirector plugin

---

jetpack.php

See https://github.com/Automattic/jetpack/releases/tag/4.2.1

Jetpack 4.2.1

---

jetpack.php

See https://github.com/Automattic/jetpack/releases/tag/4.2.2

Jetpack: bump to latest version

---

vip-mail.php

Will better allow other code to override our filter without changing
priority
props @kraftbj

Set the wp_mail_from priority to 1

---

wp-cron-control.php

Eliminates two discrepancies between production and GitHub.

Update WP-Cron Control

---

cache-manager.php

* Add support for cache invalidation via the mangle service, in addition to the existing Varnish routines.
* Default to Varnish in the absence of the PURGE_SERVER_TYPE and PURGE_SERVER_URL defines.

Mangle Cache Invalidations

---

misc.php

In some cases, we use this to disable do_pings as it can be quite slow. This can be enabled on a per-site basis by setting `VIP_CUSTOM_PINGS`. By default trackbacks are disabled since they're the slowest, but there are filters to enable/disable the other actions as well.

Sync do_pings hack from wp.com

---

.gitmodules
jetpack-force-2fa.php
misc.php

Forces 2FA for admins if Jetpack SSO is enabled.
See https://github.com/Automattic/vip-go-mu-plugins/pull/293

Add Jetpack Force 2FA

---

vip-helpers/vip-caching.php

I've done this in several commits to try and keep parity with the changes made on WordPress.com

Bring vip-caching.php up to date with WordPress.com's wpcom-caching.php

---

vip-helpers/vip-caching.php

@joshbetz, ran this through PHPCS to fix some of the earlier issues that were brought up

PHPCS Fixes

---

vip-helpers/vip-query-monitor.php

Check the index `notice` is set, before accessing it

---

vip-helpers/vip-caching.php

SVN commit messages:
r266855-wpcom-vip: `put a limit to how long we cache when something is found to not be present. Also add cache busting to term_existsso that when a new term is created we purge any not found results in cache`
r266857-wpcom-vip: `skip a costly meta_value lookup in wp_old_slug_redirect when we're pretty sure this is a mistake. with help from @jmdodd`

Bringing vip-caching up to date from wpcom

---

000-vip-init.php
ci/prepare.sh
vip-cache-manager/vip-cache-manager.php

Move the health check early

---

shared-plugins/chartbeat/chartbeat.php
shared-plugins/chartbeat/readme.txt

This syncs changes made to the Chartbeat plugin on the WordPress.com shared plugins repository to the VIP Go shared plugins repository.

Syncing Chartbeat changes from wpcom to GH

---

vip-feed-cache.php
vip-feed-cache/vipgo-feed-cache-classes.php

This should work as a temporary fix to a caching problem with SimplePie (and `fetch_feed()`).

VIP: Feed Cache Plugin

---

vip-feed-cache.php
vip-feed-cache/class-vip-go-feed-cache.php

Naming consistency: VIPGO => VIP_Go

---

performance/lastpostmodified.php
tests/bootstrap.php

Add a disable filter for folks who want to opt-out

Remove constant check for lastpostmodified

---

a8c-files.php

Correct variable name is img_url
Fixes #414

Fix PHP Notice: Undefined variable: image_url

---

akismet.php
akismet/.htaccess
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet-cli.php
akismet/class.akismet-widget.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/get.php
akismet/views/notice.php
akismet/views/start.php
akismet/views/stats.php

Update Akismet to 3.2

---

jetpack.php

See https://github.com/Automattic/jetpack/releases/tag/4.5

Jetpack 4.5

---

alloptions-limit.php
wp-cli/alloptions.php

Tweaks to improve the consistency of reported sizes.
FIxes #432

432 alloptions size discrepency

---

lib/proxy/ip-forward.php
lib/proxy/ip-utils.php

Minor typo/spacing cleanup

---

lib/proxy/ip-forward.php
tests/test-lib-proxy-ip-forward.php

Make sure we're sent through a valid IPv4 or IPv6 address.
"Because the internet is a weird place"
Fixes #442

Validate user_ip

---

tests/bootstrap.php
tests/test-lib-proxy-ip-forward.php
tests/test-lib-proxy-ip-utils.php

Copied over from original symfony http-foundation repo: https://github.com/symfony/http-foundation

Add IpUtils tests

---

vaultpress/class.vaultpress-cli.php
vaultpress/class.vaultpress-hotfixes.php
vaultpress/readme.txt
vaultpress/styles.css
vaultpress/vaultpress.php
vaultpress/vp-scanner.php

> 1.8.6 - 26 January 2016
> Compatibility updates
> Security hotfixes
> Improved performance for security scanner
> Misc small bugfixes
https://wordpress.org/plugins/vaultpress/

Update to VaultPress 1.8.6

---

misc.php

Disallow flv files from being uploaded

---

http-concat.php
misc.php

Move http-concat loading to own file

---

akismet.php

- Limit cache increments for sites with lots of spam
- Limit number of spam comments in delete batch
- Identify Akismet requests as coming from vipgo

Performance and other tweaks for Akismet

---

tests/bootstrap.php
tests/test-core.php

Fixes the broken test surfaced in #479 and improves the existing tests.

Fix super admin core cap test

---

performance.php
performance/vip-tweaks.php

Bringing over performance tweak functionality from WordPress.com's `vip-helper-wpcom.php`

Porting "VIP Performance Tweaks" from WPCOM

---

performance/bulk-edit.php

So they have someone to talk to instead of feeling stuck.
h/t @andrealeebishop

Have users contact us when we block Bulk Edit

---

stats.php

Track post-publish volume using a late, non-blocking request.

Track publish events

---

.gitignore
.travis.yml
000-vip-init.php
Makefile
ci/generate-docs.sh
ci/prepare.sh
phpdoc.dist.xml

Generate documentation for our MU plugins repo, and publish it to GitHub pages.

Generate PHPDocs

---

.travis.yml
ci/generate-docs.sh

Fix unknown GitHub host

---

schema.php
tests/bootstrap.php
tests/test-schema.php

Add an index on the postmeta.meta_value for all new sites.

Add meta_key_value index

---

misc.php
performance.php
performance/do-pings.php

Disable do_pings

---

.travis.yml

Borrowed from https://core.trac.wordpress.org/changeset/40255

Travis + PHP7 + phpunit compat

---

.gitmodules
vip-jetpack/css/mandatory-settings.css
vip-jetpack/jetpack-mandatory.php
vip-jetpack/vip-jetpack.php

See https://github.com/Automattic/vip-go-mu-plugins/pull/482#issuecomment-284635069
The code is fairly vip-specific and not particularly useful as a generic plugin. It can be used a reference instead.
Related #458 (which changes around where the force-2fa submodule lives and will need to be updated).

Un-submodule vip-jetpack

---

jetpack.php

4.7 code already pushed as part of #509

Bump jetpack plugin header version to 4.7

---

query-monitor.php

See https://github.com/johnbillion/query-monitor/releases

Update Query Monitor to latest release

---

a8c-files.php

No longer needed as we're on 4.7

Remove < 4.5 back-compat code

---

jetpack.php

https://jetpack.com/2017/03/14/471-markdown-widget-visibility-sso-fixes/

Bump Jetpack to 4.7.1

---

a8c-files.php

Relies on existing Jetpack Photon code that converts URL references to intermediate image sizes (`file-{w}x{h}.jpg`) to a dyanmic one (`?resize={w},{h}`) served by our Go Files service, which has similar capabilities as Photon.
/cc @mdrovdahl

Add dynamic rewrites for intermediate image sizes

---

vip-helpers/vip-caching.php

In case a post_name is changed and item is published, we should flush all previous wp_old_slug_redirect cache in order to prevent possible redirect loops.

Adding a funciton for flushing wp_old_slug_redirect_cache on post_update

---

bin/svn

Not sure if this is where we'd want to put a script like this, but it seems as good a place as any.

Add a simple svn wrapper to do pre-deploy checks.

---

000-vip-init.php
jetpack-start.php
jetpack-start/jetpack-start.php
jetpack-start/wp-cli-api.php
jetpack-start/wp-cli-keys.php

Can help easily set up VaultPress, Akismet, and Jetpack connections if we have the valid keys.

CLI scripts to automate Jetpack connections

---

jetpack-start/wp-cli-api.php
jetpack-start/wp-cli-keys.php

Two fixes:
- Fix WP_CLI namespace for jetpack keys
- Fix Akismet conditional when setting keys
See #433

Jetpack Start fixes

---

stats.php

Don't bump stats from sandboxes

---

jetpack.php

Going from 4.7.1 => 4.8.1.
Announcements:
https://jetpack.com/2017/04/04/settings-overhaul-redesign/
https://jetpack.com/2017/04/05/jetpack-4-8-1-php-version-incompatibility-fix/
Changelog:
https://wordpress.org/plugins/jetpack/#changelog

Update to Jetpack 4.8.1

---

jetpack-start/wp-cli-api.php

Especially when adding keys fails.

Add a bit more verbosity to aid debugging

---

jetpack.php

Bump Jetpack version number to 4.8.2

---

001-cron.php

Cron Control runs JP sync events, it shouldn't also trigger them on shutdown. In some cases, the sync action delays the REST response sufficiently to trigger a timeout in the runner.
Fixes #590

Don't trigger Jetpack Sync on shutdown if the request is for Cron Control

---

jetpack.php

https://jetpack.com/2017/05/02/jetpack-4-9-widgets-and-improvements/

Bump Jetpack to 4.9

---

shared-plugins/mediapass/mediapass_api.php

Need to actually check that it's a truthy value.

MediaPass: Fix WP_DEBUG usage

---

001-cron.php

Related: https://github.com/Automattic/vipd/pull/401

Switch to alt cron if basic auth is enabled

---

jetpack.php

Updates to Jetpack 5.0
https://jetpack.com/2017/06/06/jetpack-5-0-spring-clean/
https://lobby.vip.wordpress.com/2017/05/31/jetpack-5-0-beta/

Update to Jetpack 5.0

---

advanced-post-cache.php
jetpack-start.php
vip-cache-manager.php
vip-dashboard.php
vip-support.php

For wider compat across environments and simpler deploys.
Previously #643

Drop symlinks

---

performance/vip-tweaks.php

Solved add new media array_shift() issue.

---

shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php

Add more strict checking of API results before using as an array

---

wp-cli/vip-migrations.php

This command will iterate over attachments in the database and create a CSV of any missing (or other non-200 status) files.  This can be useful to determine if a media import has went wrong.

Add "validate-attachments" CLI command.

---

wp-cli/vip-plugins.php

Adds commands from WP.com for managing shared plugins via CLI

Fix vip plugins

---

000-debug/logger.php

Allow debug helpers to be used locally

---

jetpack.php

To be deployed `2017-07-06` (ET late afternoon).

Bump Jetpack to 5.1

---

000-vip-init.php
z-client-mu-plugins.php

And move constant for client-mu-plugins alongside it.

Add constant for private dir path

---

vip-cache-manager/ttl-manager.php

Drops the class and updates docs.
See #673

Update TTL Manager

---

000-vip-init.php
tests/bootstrap.php
tests/test-vip-mail.php
vip-mail.php

This will allow us to validate and track where emails are coming from.

Add mail tracking header to outbound emails

---

lib/proxy/ip-forward.php
tests/test-lib-proxy-ip-forward.php

Introduce fix_remote_address_from_ip_trail_with_verification_key()

---

akismet.php
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet-widget.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/start.php

```
* Reduced amount of bandwidth used by the URL Preview feature.
* Improved the admin UI when the API key is manually pre-defined for the site.
* Removed a workaround for WordPress installations older than 3.3 that will improve Akismet's com    patibility with other plugins.
* The number of spam blocked that is displayed on the WordPress dashboard will now be more accura    te and updated more frequently.
* Fixed a bug in the Akismet widget that could cause PHP warnings.
```

Update to Akismet 3.3.3

---

shared-plugins/split-home-site-urls/split-home-site-urls.php

Don't load plugin when URLs are the same, it will just cause a redirect loop

---

wp-cli/vip-migrations.php

If nothing is passed to dbDelta it will not grab the schema and therefore the queries will be empty which will lead to not actually doing the dbDelta (but the command will tell us it was successful)

Pass '' to dbDelta

---

lib/wpcom-error-handler/wpcom-error-handler.php

Remove reference to undefined constant

---

lib/sunrise/sunrise.php

Depends on:
* software-stacks update: 1ad16-pb
* `vipd` update: https://github.com/Automattic/vipd/pull/448

Via `sunrise.php`, log invalid multisite configurations

---

vip-helpers/vip-newrelic.php

Name the transaction based on the wp-api route, as well as set a parameter for which route and a flag that these are API requests.

Track and identify wp-api In New Relic

---

vip-helpers/vip-newrelic.php

Make it clearer which functions clients should use.
Only load the actions if the extension is loaded.

Nr improve readability

---

query-monitor.php

See https://github.com/johnbillion/query-monitor/releases/tag/2.14.0

Bump Query Monitor to v2.14.0

---

akismet.php
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet-rest-api.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php

> * Added REST API endpoints for configuring Akismet and retrieving stats.
> * Increased the minimum supported WordPress version to 4.0.
> * Added compatibility with comments submitted via the REST API.
> * Improved the progress indicator on the "Check for Spam" button.
https://blog.akismet.com/2017/09/19/akismet-wordpress-plugin-4-0-now-available/

Upgrade to Akismet 4.0

---

two-factor.php

Otherwise we do many checks for whether the current user has two factor
enabled that are unnecessary.

Two Factor: Only filter map_meta_cap for logged in users

---

jetpack.php

Switches JP submodule to `branch-5.4-built`
https://github.com/Automattic/jetpack/compare/branch-5.4-built
https://github.com/Automattic/jetpack/commit/f95fc1a8a7779909f05ff81b359
e6b4287dd7d17
Preparing for scheduled Oct 4th upgrade.

Bump Jetpack to 5.4

---

vip-helpers/vip-deprecated.php

The replacement is a filter, not a function.
props @paulschreiber.

Fix replacement for wpcom_vip_enable_opengraph

---

vip-support.php

* Fixes incorrect a11n promotion, see https://github.com/Automattic/vip-support/pull/56
* Ensures Core constants are respected, see https://github.com/Automattic/vip-support/pull/53

Bump VIP Support to latest

---

000-vip-init.php

Fixes #757
props @simonwheatley | h/t @paulschrieber

Fix confusing code comment

---

vip-cache-manager/vip-cache-manager.php

No need to PURGE thousands of URLs at a time.

Limit the number of PURGE and BAN urls

---

Makefile
phpcs.xml

Started in #520, this is a somewhat weak check (only reports errors above priority 5), but currently passes and gives us a starting point.

Add PHPCS on PR

---

rest-api/vip-endpoints.php

Now the shared plugins UI is retired we are no longer adding the shared plugin information to our custom API endpoint. Whilst we still have 3 remaining shared plugins it will be useful if this continues to work. This re-instates the functionality.

Fix shared plugin reporting

---

jetpack.php

* Jetpack version to 5.5.1
* Tweaks to `wpcom_vip_log_updating_jetpack_version()`

Syncing some Jetpack changes from production

---

jetpack.php

https://github.com/Automattic/jetpack/releases/tag/5.6

Update Jetpack to 5.6

---

jetpack.php

Forgot to bump the version here to match what’s in the JP submodule

Bump JP Version number in mu-plugin file

---

jetpack.php

https://jetpack.com/2018/01/16/jetpack-5-7-1/

Update Jetpack to 5.7.1

---

vip-helpers/vip-newrelic.php

Props @spacedmonkey
Reference: https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_background_job

Mark Cron transactions as background (non-web)

---

jetpack.php

The issues have since been resolved.

Jetpack: remove unused upgrade debug

---

jetpack.php

See https://jetpack.com/2018/02/06/jetpack-5-8-release/
Pending deploy today at 2000 UTC.

Update to Jetpack 5.8

---

000-vip-init.php
vip-helpers/vip-migrations.php
wp-cli/vip-migrations.php

So we can use it via CLI, or wp cron
Adds a wp cron entry point
Fixes #840

Extract migration cleanup into standalone functions

---

akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt

https://blog.akismet.com/2018/02/19/version-4-0-3-of-the-akismet-wordpress-plugin-is-now-available/

Bump akismet to 4.0.3

---

akismet.php

Bump Akismet version number

---

vip-wp-cli-to-cron.php

Some improvements to the logging for CLI commands offloaded to cron;
* Improved the URL reported when running on multisite
* Added additional IRC logging to record the completed run

WP CLI to Cron logging improvements

---

jetpack.php

https://jetpack.com/2018/03/06/jetpack-5-9/

Upgrade to Jetpack 5.9

---

errors/alloptions-limit.html
errors/site-maintenance.html

Update error docs

---

files/class-api-client.php

Our lint checks haven't caught up yet...
Introduced in #868

Drop PHP 7.2 syntax

---

files/class-api-client.php
files/class-curl-streamer.php
files/class-wp-filesystem-vip-uploads.php
files/class-wp-filesystem-vip.php

WP_Filesystem: Fix issues found in testing 

---

jetpack.php

https://jetpack.com/2018/05/22/jetpack-6-1-1-privacy-update/
> Jetpack 6.1.1 is now available for download and includes more privacy and consent tools to ensure your site is GDPR compliant. We’re also shipping a few small fixes in this release, including a fix for secondary languages (for example, English or Spanish variations) with the Likes feature.

Upgrade to Jetpack 6.1.1

---

wp-cli/vip-migrations.php

Fixes WP-CLI output

---

vaultpress/class.vaultpress-cli.php

Allow VaultPress registration to fail gracefully, but still output the error

Allow VaultPress registration to fail gracefully

---

jetpack.php

https://jetpack.com/2018/06/05/jetpack-6-2-general-maintenance/
To be deployed on Wednesday, June 6 at 1500 EDT / 1900 UTC.

Jetpack 6.2

---

000-vip-init.php

Discussed here: https://github.com/Automattic/vip-go-mu-plugins/issues/904

No index non production sites with a custom domain

---

query-monitor.php

https://github.com/johnbillion/query-monitor/releases/tag/3.0.0
Previously #843

Upgrade Query Monitor to 3.0.0

---

lib/wpcom-error-handler/wpcom-error-handler.php

Two related fixes:
- Properly render class methods
- Handle array args for filters (to prevent an array-conversion notice)

Update Error Handler

---

vip-helpers/vip-utils.php

Typo: s/sprint/sprintf/

---

akismet.php
akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/notice.php

* Improved the grammar and consistency of the in-admin privacy related notes (notice and config).
* Revised in-admin explanation of the comment form privacy notice to make its usage clearer.
* Added `rel="nofollow noopener"` to the comment form privacy notice to improve SEO and security.

Update to Akismet 4.0.8

---

a8c-files.php
files/class-path-utils.php
tests/files/test-path-utils.php

Add's regex checks and path substitutions for sub-sub directory multisite file uniqueness checks and uploads.

Support sub-sub directory multisite file uploads

---

jetpack.php

> This point fix addresses a bug affecting Social Login on Jetpack Comments.
>
> For this point release, we fixed an issue that was published with Jetpack 6.4, which affected visitors attempting to comment by authenticating with Social Login buttons on the Jetpack Comments form.
https://jetpack.com/2018/08/10/jetpack-6-4-2-fix-for-social-login-in-comments/

Jetpack 6.4.2

---

vaultpress.php
vaultpress/class.vaultpress-cli.php
vaultpress/readme.txt
vaultpress/vaultpress.php

* Limit vp_ai_ping% entries to improve stability when a site gets disconnected from VaultPress.com
https://wordpress.org/plugins/vaultpress/

VaultPress 1.9.6

---

vip-cache-manager/vip-cache-manager.php

Closes https://github.com/Automattic/vip-go-mu-plugins/issues/961
Update the text to be more clear about what it does and that it will mostly only appear for a12s.
Updated:

Update “purge page cache” button description

---

jetpack.php

https://jetpack.com/2018/09/04/jetpack-6-5-general-maintenance-and-security-update/

Jetpack 6.5

---

jetpack.php

https://jetpack.com/2018/10/09/jetpack-6-6-better-site-verification-tools/
To be deployed Oct 10 ~1900 UTC.

Jetpack 6.6

---

001-core/privacy.php

`init` is too early to override the core privacy file generation hook, so switch to `admin_init`. Keep the cron handler on `init`.
Previously, we would have both our override and the core ones hooked, which meant we would fall through to the core handle and trigger their `ZipArchive` check and fail the entire request. 
- Apply patch to a site without the `zip` extension.
- Generate a privacy report for a user
- Verify that it gets generated successfully.
- Verify that our custom cron job runs and deletes old files.

Privacy: Use different hooks for overriding filters

---

README-PUBLIC.md
README.md

I've updated the instructions for running tests with PHPUnit to include specific instruction for using VVV. These are the steps @mjangda provided me to get my local setup working correctly.

Updated PHPUnit setup instructions

---

files/class-image-sizes.php

Makes the comment sound less Scottish 😉

Fix spelling error

---

vip-helpers/vip-migrations.php

Reverts Automattic/vip-go-mu-plugins#988

Revert "Connect akismet during migration cleanup"

---

jetpack.php

Upgrade to Jetpack 6.7: https://jetpack.com/2018/11/06/jetpack-6-7-site-accelerator-activity/
To be deployed on Monday, November 12, 2018.
TODO:

Jetpack: Upgrade to 6.7

---

gutenberg-ramp.php

Bump Ramp version in loader

---

performance/media.php

Fix function formatting

---

query-monitor.php

Includes changes from https://github.com/johnbillion/query-monitor/releases/tag/3.1.0 and https://github.com/johnbillion/query-monitor/releases/tag/3.1.1
Fixes #971 
1. Log in with VIP Support account
1. Verify Query Monitor works as expected.

Update to Query Monitor 3.1.1

---

jetpack.php

See https://github.com/Automattic/jetpack/releases/tag/6.8.1

Update to Jetpack 6.8.1

---

README.md

Add instructions for running PHPUnit in Docker via the script added in #1018.

Add PHPUnit/Docker details to README

---

vip-plugins/vip-plugins.php

Slight change to a string to make the error less scary (and more accurate).

Use "display" instead of "load"

---

.deployignore

More things we don't need to deploy.

Add more files to deployignore

---

a8c-files.php

Update the comment for `_check_uniqueness_with_backend` method to reflect it's implementation more accurately.

Update comment for check uniqueness method

---

vip-cache-manager/vip-cache-manager.php

Remove unnecessary cache purges on file upload

---

files/class-vip-filesystem-stream-wrapper.php

Specifically, add the calling function and the path we were operating on. This will make debugging much easier.

Add more verbose errors for streamwrapper methods

---

akismet.php
akismet/_inc/akismet.css
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/get.php
akismet/views/notice.php

```
* Fixed the "Setup Akismet" notice so it resizes responsively.
* Only highlight the "Save Changes" button in the Akismet config when changes have been made.
* The count of comments in your spam queue shown on the dashboard show now always be up-to-date.
```
https://blog.akismet.com/2019/01/31/version-4-1-1-of-the-akismet-wordpress-plugin-is-now-available/

Akismet 4.1.1

---

jetpack.php

https://jetpack.com/2019/02/05/jetpack-7-0-be-more-productive-one-post-at-a-time/
https://wordpress.org/plugins/jetpack/#developers
To be deployed <strike>Feb 6</strike> Feb 7, 2019 ~2000 UTC.

Jetpack 7.0

---

vaultpress.php
vaultpress/readme.txt
vaultpress/vaultpress.php

**Changelog**
1.9.8 – 7 February 2019
* Limit the size of vp_ai_ping% entries when a site gets disconnected from VaultPress.com
1.9.7 – 11 December 2018
* Update firewall IP detection rules to autodetect various reverse proxy setups
https://wordpress.org/plugins/vaultpress/
Issue #1108

Update VaultPress to 1.9.8

---

jetpack.php

https://jetpack.com/2019/02/14/jetpack-701-security-maintenance/

Jetpack 7.0.1

---

jetpack.php

https://jetpack.com/2019/03/05/jetpack-7-1-business-blocks/
https://jetpack.com/2019/03/06/jetpack-7-1-1-maintenance-release/

Jetpack 7.1.1

---

.deployignore
cache/README.md
cache/examples/segmentation-beta/beta.php

This is technical documentation to guide developers on the use cases and implementation of the Vary Cache library. The goals are to clearly explain the what & why, and follow up with examples that are easy to understand (and implement.)
Fixes #1134

Vary Cache: Developer docs

---

files/class-meta-updater.php
files/class-vip-filesystem.php
wp-cli/vip-filesystem.php

Add a scheduled cron event to update attachment metadata with file sizes to improve performance of sites with Stream Wrappers enabled
Resolves #1182 

Stream Wrapper: Add update meta cron job

---

files/class-vip-filesystem.php

Update Filesize: Add max_id to "Batch completed" message

---

jetpack.php

https://jetpack.com/?p=59162
https://github.com/Automattic/jetpack/releases/tag/7.2
To be deployed Wednesday, April 3, 2019 at 2000 UTC

Jetpack 7.2

---

jetpack.php

Maintenance Release
https://github.com/Automattic/jetpack/releases/tag/7.2.1
https://jetpack.com/?p=65806

Jetpack 7.2.1

---

cache/README.md
cache/examples/segmentation-maintenance-mode-bypass/vip-config.php

Vary Cache: Add Maintenance Mode Bypass example

---

vip-feed-cache/class-vip-go-feed-cache.php

See #1120
Tested only locally, but the change is *very* minimal and backward compatible.

Make feed cache create method static

---

ci/deploy.sh
ci/templates/composer.json

So we can publish to Packagist.
See #1193

Add a composer file to built copy

---

a8c-files.php

Continued from (and deployed already with) #1216

Prevent warnings when sizes key not set

---

two-factor.php

We need to do some testing before blocking API logins this way.
https://github.com/Automattic/vip-go-mu-plugins/issues/1221

Ensure API logins are not blocked by two-factor

---

vip-jetpack/vip-jetpack.php

Same as #1252 but removing checks.

Disable do_initial_sync() for all sites now

---

wp-cli/vip-migrations.php

After editing an image in the wp-admin media library, the attachment meta will be updated with the file for the edited file.  We want to make sure these are also valid.
Example:
1. Run wp-cli command like: `wp vip migration validate-attachments output.csv --extra-check`
1. Verify URLs from attachment meta are checked.

Update validate-attachments for extra URLs

---

wp-cli/vip-two-factor.php

Adds a CLI command that we can use to report adoption of 2FA on a VIP Go site.

Add `two-factor report` CLI command

---

alloptions-limit.php

Better fits our internal workflows.

Send alloptions alerts to vip-deploy-on-call

---

two-factor.php

Pushes enforcement back to July 17

2FA: Push back enforcement

---

.travis.yml

Since the docs/build scripts check its value
Fixes #1268

Travis: Restore DEPLOY_BRANCH env var

---

jetpack.php

Upgrade to Jetpack 7.4
1. Verify version
1. Verify mu-plugin version
1. Test through various workflows, pages, different site types

Jetpack 7.4

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

What the title says :)
Need to add an Issue template as well.

Update templates to include public repo warning

---

two-factor.php

Pushes the default enforcement date for 2FA back one more week to July 24.

Push back 2FA another week

---

jetpack.php

Upgrade JP version to latest, 7.5.3
1. Try various frontend requests
1. Try REST request
1. Try `wp-admin` > `Jetpack`
1. Try CLI command
1. Verify no warnings / errors / fatals are thrown

Jetpack 7.5.3

---

rest-api/vip-endpoints.php

Apply patch on a Sandbox, make a Basic Auth'd request with a support user to that endpoint and verify that it works.

Implement vip/v1/jetpack endpoint to provide the necessary information for automated setup of ES as part of Go migrations.

---

jetpack.php

Upgrades to the latest version of Jetpack, 7.8
https://jetpack.com/2019/10/01/jetpack-78-making-jetpack-stronger-team/
Example:
1. Check JP version in footer
1. Run `wp plugin list`
1. Verify JP version
1. Run a variety of other CLI and web requests, checking for errors or unexpected behavior

Upgrade to Jetpack 7.8

---

jetpack.php

Upgrades Jetpack to 7.9
https://jetpack.com/2019/11/05/79-peek-future-jetpack-search/
https://github.com/Automattic/jetpack/releases/tag/7.9

Jetpack 7.9

---

jetpack.php

Upgrades to latest Jetpack, 7.9.1
https://github.com/Automattic/jetpack/releases/tag/7.9.1
1. Verify JP version
1. `wp plugin list`
1. Verify JP version
1. Test site functionality for any changes

Upgrade to Jetpack 7.9.1

---

files/class-vip-filesystem-stream-wrapper.php

Resolve fatal error "Too few arguments to function VIP_Filesystem_Stream_Wrapper::string_to_resource()"

---

two-factor.php

The time for enforcing 2FA has come and gone. We can simplify the logic to remove this unnecessary check.

Remove 2FA time gate

---

.deployignore

.circleci + cron-control-next
Note: no deploy necessary.

Add some more files to deployignore

---

jetpack.php

Upgrades to Jetpack 8.0
NOTE - This is actually a different branch than the 8.0 itself - https://github.com/Automattic/jetpack/tree/branch-8.sync-built - this one has some extra sync improvements that we're testing out for future versions of JP, but includes all of 8.0 too.
Example:
1. `wp plugin list` - ensure JP reports 8.0
1. Visit Jetpack -> Dashboard - ensure JP reports 8.0
1. Click around, create / edit posts, make sure everything is working as expected

Upgrade to Jetpack 8.0

---

jetpack.php

Upgrades Jetpack to 8.1
1. Ensure reported JP version is 8.1 (in mu-plugins list and in Jetpack Dashboard)
1. Perform various tasks on the site, ensure everything works normally

Update to Jetpack 8.1

---

.deployignore

No need to deploy these files.

Add some ElasticPress-related files to ignore

---

jetpack.php

Small bug-fix release for JP
https://github.com/Automattic/jetpack/releases/tag/8.1.1
1. `wp plugin list`
1. Ensure JP is reported as 8.1.1
1. Visit JP dashboard
1. Ensure reports as 8.1.1

Jetpack 8.1.1

---

two-factor.php
wpcom-vip-two-factor/set-providers.php

How often are we blocking them, for which envs and UAs.
See Slack for details.

Add stats to track blocking of 2fa API users

---

two-factor.php

Except for a small subset of sites that are transitioning.
Note: `VIP_2FA_ALLOW_API_LOGIN_ENV_IDS` will be added as part of the deploy.
- n/a This change has relevant unit tests (if applicable) (skipping, since this is transitional)
1. Apply patch.
1. Make an API request to a site with a user account that has 2fa enabled (see internal P2 for example). It should fail with a 403 (`Incorrect username or password.`)
1. Add `VIP_2FA_ALLOW_API_LOGIN_ENV_IDS` constant with the ID of the current site.
1. Repeat the request. It should pass.

Block API requests for users with 2fa enabled

---

two-factor.php

So we can narrow in on which requests will be impacted.
- n/a This change has relevant unit tests (if applicable). (temp change)
1. Make an authenticated request to either xml-rpc or REST APIs from a user with 2fa enabled on one of the bypass sites.
1. Verify that the request works but an error is logged.

Log a warning with more details about api blocks

---

elasticsearch/class-health-job.php
elasticsearch/includes/classes/class-elasticsearch.php
elasticsearch/includes/classes/class-health-job.php

Add a health check cronjob for sites using VIP Search
TBD

Add Elasticsearch health check cronjob

---

elasticsearch/includes/classes/class-health-job.php

Found a few bugs when testing out the index health check job.
Example:
1. `wp shell`
1. `do_action( 'vip_search_healthcheck' );`

Fix Search health check cron

---

two-factor.php

We've given enough notice for this.
Note: we can remove `VIP_2FA_ALLOW_API_LOGIN_ENV_IDS` as part of this deploy.
- - This change has relevant unit tests (Will look at adding some unit tests in an upcoming PR)
- - This change has relevant documentation additions / updates (if applicable).
- Apply patch.
- Make an API request to a site with a user account that has 2fa enabled (see internal P2 for example). It should fail with a 403 (Incorrect username or password.)

Block all API requests for all 2fa users

---

jetpack.php

Upgrades to JP 8.2
https://github.com/Automattic/jetpack/releases/tag/8.2
https://jetpack.com/2020/02/11/jetpack-82-blocks-help-manage-business/
Example:
1. Verify JP version is reported correctly in `wp plugin list`
1. Verify JP version is reported correctly in JP admin
1. Verify normal site behaviors all work as expected

Upgrade to Jetpack 8.2

---

jetpack.php

Bump version number in jetpack.php

---

security.php

Remove Vary: Origin override

---

elasticsearch/includes/classes/class-health-job.php
tests/elasticsearch/includes/classes/test-class-healthjob.php

Reverts Automattic/vip-go-mu-plugins#1468 to unrevert the revert for "only alert when diff is not 0" fix for ES health checking 😄

Revert "Revert "Only alert when diff is not 0""

---

README.md

README: Remove VVV testing instructions

---

jetpack.php

Upgrade JP to 8.3
https://github.com/Automattic/jetpack/releases/tag/8.3
1. `wp plugin list` - ensure JP reports as 8.3
1. Visit JP dashboard - ensure JP reports as 8.3
1. Try various site functionality

Upgrade to JP 8.3

---

two-factor.php

Reverts Automattic/vip-go-mu-plugins#1445

Revert "Limit calls to `Two_Factor_Core::is_user_using_two_factor()`"

---

000-vip-init.php
logstash/class-logger.php
logstash/logstash.php
tests/logstash/test-logger.php

Add a helper class and function to support logging to logstash
TBD

Add logstash support

---

000-vip-init.php

See p2-p9o2xV-J7
1. `curl [home_url] -I`
1. Verify `Host-Header` is returned in headers.

Add Host-Header header

---

akismet.php
akismet/_inc/akismet.css
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/setup.php

https://blog.akismet.com/2020/03/17/akismet-4-1-4-for-wordpress/

Akismet 4.1.4

---

vaultpress/vaultpress.php

Merged into Vaultpress via https://github.com/Automattic/vaultpress/pull/91.

#1539: Update Vaultpress

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

We were missing some important tests for query integration. So I added them.
2. `./bin/phpunit-docker.sh tests/search/test-class-search.php`

Added tests for ep_skip_query_integration and edited ep_skip_query_integration from tests/feedback

---

jetpack.php

Upgrades Jetpack to 8.5
1. Verify misc site functionality
1. Verify JP 8.5 is reported via `wp plugin list` and the JP dashboard

Upgrade Jetpack to 8.5

---

README.md

According to @brandon-m-skinner, "The lando env is magical".
Let's make it official.

Recommend vip-go-mu-dev for development

---

akismet.php
akismet/_inc/akismet.css
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/readme.txt

https://blog.akismet.com/2020/06/04/version-4-1-6-of-the-akismet-wordpress-plugin-is-now-available/

Akismet 4.1.6

---

README.md

README updates: mention the way to run a specific test and pass extra args to PHPUnit.

---

alloptions-limit.php

See: https://github.com/Automattic/vip-go-mu-plugins/pull/1626#issuecomment-650831789
There are some CircleCI failures due to how this is being loaded.  This should fix that.
cc @rinatkhaziev

Fix alloptions require

---

search/includes/classes/class-queue.php

Added a stat to keep track of when things are added to the queue for an index.
4. Ensure VIP Search is enabled.
5. Apply PR.
6. Set the rate limiting for indexing operations low(like 1) in `Queue::$max_indexing_op_count`.
7. Index a bunch of posts and keep track of the number added to the `wp_vip_search_index_queue` DB table.
8. Compare the number of objects queued in `wp_vip_search_index_queue` to  the `added_to_queue` stat in the StatsD output(should be something like `com.wordpress.elasticsearch.unknown.unknown.added_to_queue.200508.vip …

Record added_to_queue stat

---

lib/utils/class-alerts.php
tests/lib/utils/test-alerts.php

Change from `alerts` to `alert`.
cc @rinatkhaziev

Fix alert service endpoint

---

search/includes/classes/class-queue.php

Added a stat to keep track of when things are processed from the queue for an index.
4. Apply PR.
5. Ensure VIP Search is enabled and the `wp_vip_search_index_queue` DB table and related functionality works locally.
6. Add a bunch of entries to the `wp_vip_search_index_queue` DB table.
7. `wp shell`
8. Build an array of assoc arrays where 'job_id' is equal to the object ids of the entries you added to `wp_vip_search_index_queue`.
9. Call the `Queue::process_jobs` function on the array of assoc arrays you built in `wp shell` previously. …

Record processed_from_queue stat

---

README.md

README: Add note about lando test

---

jetpack.php

This PR upgrades Jetpack to [8.7.1](https://github.com/Automattic/jetpack/tree/8.7.1)

Upgrade Jetpack to 8.7.1

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Silencing unactionable log noise until a solution is added.

Disable health checks for more IDs

---

search/docs/versioning.md
search/docs/vip-search.md

Updating to latest version of VIP Search public docs.

Sync VIP Search public docs

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Remove all IDs from the health check deny list.

Remove health check exclusions

---

search/includes/classes/class-versioning.php
search/includes/classes/commands/class-versioncommand.php
tests/search/includes/classes/test-class-versioning.php

Add the `delete_version()` helper and the `wp vip-search index-versions delete <type> <id>` command.
1. `lando wp vip-search index-versions add post` to add a new version
1. `lando wp vip-search index-versions list post` - should see new version
1. `curl 127.0.0.1:19200/_aliases?pretty=true` to make sure the index exists on ES
1. `lando wp vip-search index-versions delete post <new_version_id>` to delete it
1. `lando wp vip-search index-versions list post` - version should be removed
1. `curl 127.0.0.1:19200/_aliases?pretty=true` index should no longer exist
1. `lando wp vip-search index-versions delete post 9999` should fail b/c version doesn't exist
1. `lando wp vip-search index-versions …

Search: Add/ delete index version command

---

search/includes/classes/class-search.php

Causing issues for BaT, reverting.

Revert ep_prepare_meta_allowed_protected_keys override

---

tests/search/test-class-search.php

Broken after a revert in https://github.com/Automattic/vip-go-mu-plugins/pull/1713
Test-only change, so just let the suite run :)

Skip currently broken tests

---

jetpack.php

Patch release for an Infinite Scroll issue.
1. `git submodule update --init`
1. Verify JP version in Jetpack Dashboard
1. Verify JP version with `wp plugin list`
1. Verify core WP behavior

Jetpack 8.8.2

---

000-vip-init.php
lib/feature/class-feature.php
tests/lib/feature/test-class-feature.php

Add a feature flag library to gate rollouts of features
Currently not used, so test suite is sufficient, but should test CLI + regular requests just to ensure the file is required from `000-vip-init.php` correctly.

Add Feature flag lib

---

search/docs/filters-actions.md
search/docs/local-development.md
search/docs/onboarding-migrations.md

Syncing public docs with latest content.

Sync latest public docs

---

lib/feature/class-feature.php

Bump up the percent of sites for which the comment type update batch jobs are running.
1. Manual testing isn't really needed

Increase the percent of sites running the comment type batch jobs

---

lib/feature/class-feature.php

Currently running on 25%, increase to 50%.

Bump comment type update job to running on 50% of sites

---

.circleci/config.yml

Updating the tests against WordPress nightly to be against PHP 7.4.

Test nightly WP against PHP 7.4

---

search/includes/classes/queue/class-cron.php

Changing the init hooks due to an unfortunate interaction with cron-control.
- N/A This change works and has been tested on a Go sandbox.

Remove sweeper hook on init. Hook on other inits.

---

jetpack.php

Upgrades JP to 8.9
https://github.com/Automattic/jetpack/releases/tag/8.9
1. `wp plugin list` - ensure JP reports at 8.9
1. Visit JP Dashboard in WP Admin - ensure JP reports at 8.9
1. Verify normal site functionality (editing/viewing)

Jetpack 8.9

---

jetpack.php

Update Jetpack to version 8.9.1
Example:
1. Go to `wp-admin`
1. Check that the Jetpack version shows version 8.9.1

Update Jetpack to version 8.9.1

---

.circleci/config.yml

The image we based our tests changed and broke some of our test runs
1. Check the circle-ci pipeline

Adds gd installation to the build pipeline

---

admin-notice/js/script.js

Removing optional chaining to fix #1866

---

admin-notice/admin-notice.php
admin-notice/class-admin-notice.php

Reverts Automattic/vip-go-mu-plugins#1868

Revert "Add admin notice for WP 5.6 RC1"

---

files/class-api-client.php

Deployed already in r1292-stacks

Hotfix: sprint => sprintf

---

alloptions-limit.php

alloptions: Don't send alerts to nagios-vip

---

search/includes/classes/class-search.php
tests/search/test-class-search.php

There are situations when a failed response from ES doesn't contain an error in the payload. In those situations, we would try to access non-defined index resulting in error.
On lando env:
1. Before applying the change
1. `lando wp elasticpress delete-index`
1. `lando wp eval '$id = wp_insert_post(["post_title" => "Test post", "post_status" => "draft"]);'`
1. See notice: `Notice: Undefined index ...`
1. Apply PR
1. `lando wp eval '$id = wp_insert_post(["post_title" => "Test post", "post_status" => "draft"]);'`
1. No notice

Adds defensive check when procesing ES response

---

search/includes/classes/commands/class-corecommand.php

* Fixes error line
* Fixes warning about non-existing index
When Investigating some versioning issues, I found these minor bugs to fix. See steps to test for more details
1. ` wp vip-search index` (stops printing warning about non-defined version key)
1. `wp vip-search index --indexables="users2" --version="1"` Prints correctly error about user2 non-known (used to fail with empty error and warning)

Fixes minor issues/warnings when using vip-search CLI

---

.github/PULL_REQUEST_TEMPLATE.md

Added a template for the Changelog Description that includes the title and a link to the PR. That way they can be copied / pasted directly into the changelog.
Updated plugin upgrade example.

Added Changelog Description template to PR template.

---

vaultpress/vaultpress.php

Reverts Automattic/vip-go-mu-plugins#1917

Revert "remove VP ping hotfix"

---

lib/proxy/ip-forward.php
lib/proxy/ip-utils.php
tests/test-lib-proxy-ip-utils.php
vip-helpers/vip-utils.php

Same as bellow
#
As part of the ongoing work on cleaning up legacy we go over files not touched in a while and make sure they still comply with our code standards. This change updates the style of IpUtils library.
Not sure really. The code is covered in unit tests pretty well so maybe no need for manual testing.

IpUtils - clearing up phpcs errors

---

search/includes/classes/commands/class-healthcommand.php

In a multisite context, if one site has VIP Search all sites have access to VIP Search. Even if they don't have an index. This is problematic as it logs false positives in our health checks.
To prevent this from happening, we need to skip trying to validate counts if an index doesn't exist.
In a multisite context, if one site has VIP Search all sites have access to VIP Search. Even if they don't have an index. This is problematic as it logs false positives in our health checks. To prevent this from happening, we now skip site / indexable combos that don't exist.
https://github.com/Automattic/vip-go-mu-plugins/pull/this-pr
1. `wp vip-search health validate-counts` in a multisite that has VIP Search but on a …

Do not validate counts if Search index doesn't exist

---

akismet.php
akismet/_inc/akismet.js
akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt

Update to Akismat 4.1.8
```
Plugin Updated: Akismet 4.1.8
We upgraded Akismet to v4.1.8 (previously 4.1.7)
This release includes two fixes:
* Fixed missing fields in submit-spam and submit-ham calls that could lead to reduced accuracy.
* Fixed usage of deprecated jQuery function.
https://github.com/Automattic/vip-go-mu-plugins/pull/1928
```

Akismet 4.1.8

---

lib/proxy/ip-forward.php
tests/bootstrap.php
vip-helpers/vip-utils.php

Follow up on https://github.com/Automattic/vip-go-mu-plugins/pull/1929 and https://github.com/Automattic/vip-go-mu-plugins/pull/1937
As the last part of phpcs cleanup, we plan to rename `iputils.php` file to adhere to our naming standards. To increase the safety of this change the previous change only introduce the new file. This change starts using the new file. The final follow-up change will remove the old file. This was done as a follow-up to be isolated change from the previous cleanup done on this file.
Not sure really. The code is covered in unit tests pretty well so maybe no need for manual testing.

Update requires for the iputils

---

search/includes/classes/class-versioning.php

Code style cleanup of `search/includes/classes/class-versioning.php`.
There are only white space changes so running test suite is probably good enough.

Clean up whitespace phpcs issues - class-versioning

---

.github/PULL_REQUEST_TEMPLATE.md

Removed PR links from the changelog examples and edited the changelog checklist item to be more inclusive.
Since the changelog generation is now automated, we've made some changes to the pull request template to reflect that. We removed links to pull requests from the examples since they're no longer needed and edited the changelog checklist item to be inclusive. The expectation is that everyone fills out a proper changelog description and this is now reflected properly in the pull request template.

Removed PR URLs from changelog examples and edited changelog checklist item to be for everyone

---

search/includes/classes/class-health-job.php
tests/search/includes/classes/test-class-healthjob.php

Another phpcs cleanup.. only 32 files left before we can enable full phpcs sweep. The file also needs renaming, but I will do that in separate PRs.
Phpcs cleanup of `class-health-job.php`.

phpcs cleanup search health job

---

search/includes/classes/class-healthjob.php

As a part of code style cleanup, we need to rename `class-health-job.php`  => `class-healthjob.php`. This is the first step introducing `class-healthjob.php` which is a full copy of  `class-health-job.php` as a new file.

Adds class-healthjob.php for renaming of class-health-job.php

---

search/includes/classes/class-search.php

This change enables compression on HTTP requests towards Elastic Search.
1. Add a debug line `var_dump(['Response headers', $response['headers'] ]);`
2. Do any ES request e.g. `wp vip-search documents get post 1`
3. See the headers - `'content-encoding'` is not there
4. Apply the PR
5.  Do any ES request e.g. `wp vip-search documents get post 1`
6. Verify `'content-encoding'` header is present

Search: Add result compression

---

search/includes/classes/class-search.php

Search loads incredibly early. In some cases, other hooks might not be attached in time to allow them to apply. By firing off `Search::apply_settings()` again on `after_setup_theme` we can hopefully address this and capture settings in a more effective way.
In some cases hooks for setting per-site values for Search settings were not getting applied. By applying Search settings much later on the `after_setup_theme` hook, we make it much easier and more reliable to capture per-site settings.
1. Setup a hook on any filter in Search::apply_settings.
2. Check the value in the Search singleton via `wp shell`. Note how it's still the default value and not the filtered value.
3. Apply PR.
4. Do 2 again. It should be …

Run Search::apply_settings again on after_setup_theme hook

---

.github/PULL_REQUEST_TEMPLATE.md

Re-wording to avoid confusion.

Revise PR template to be inline with guidelines

---

000-vip-init.php

Add support for figuring out the container type from environment variables. This is more portable to ✨ future 🦄 container 💫 platforms 🌟 than relying on a structured hostname.
@joshbetz 
Switches to the  new Environment class for determining sandbox and CLI container status, which can now come from environment variables in addition to the hostname.

Add environment variable-based container-type detection

---

alloptions-limit.php

We're triggering the alert when alloptions size is over 800KB and block the site from loading when it's over 1MB. 
Unfortunately, that approach didn't account for the fact that Memcache client automagically compresses values of they're over 20KB and the savings from storing the compressed value are more than 20% (it's a setting for Memcached pool, we use the default ones and they never change, that's why they're hardcoded.)
The changes may look cryptic, that's why there are so many code comments with links.
We have systems in place that alert us when the size of the options grows too big to fit into a Memcached server entry to prevent increased pressure on the Memcached server and limit potential performance degradation. 
We made changes to alerting logic to prevent false positives. …

ALLOPTIONS limit alert/block - account for the fact that pecl-memcache client automagically compresses the values before sending it to the server

---

search/docs/onboarding-migrations.md

Updates docs
No production change.

Instruction

---

.gitmodules
phpcs.xml.dist
vip-dashboard.php

**Please do not deploy this PR after merging.**
We are migrating `vip-dashboard` from a [standalone repository](https://github.com/Automattic/vip-dashboard) to be contained in `vip-go-mu-plugins` (this repo). 
This is the *first* of two PRs. In this one, we are getting rid of the submodule. This will result in a non-functional state for the repo, as the code will be missing. In the next PR, we will manually add the files from the `vip-dashboard` repo back to this one. 
Code will be added again in https://github.com/Automattic/vip-go-mu-plugins/pull/2079
1/2 Delete git submodule.

[1 of 2] Deleting vip-dashboard submodule

---

jetpack.php

We have rolled out Jetpack 9.8 to all VIP Go sites (except those that are pinned to a specific version).
You can find [here](https://github.com/Automattic/jetpack-production/releases/tag/9.8) the list of changes in this version.
1. Ensure the enabled version is 9.8
1. Ensure everything else keeps working

Make Jetpack 9.8 default

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

We are performing some tests on Connection Pilot with Akismet and we'd like to test with some sites that have a slightly lower site id.

Decreasing minimum site id for Connection Pilot

---

vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php

This PR fixes a logic bug with the Connection Pilot rollout code and decreases the Site ID minimum to run it. 
We also clean some noisy logs up.
Rolling out Connection Pilot autoconnection to some additional sites.

Staged rollout of Connection Pilot and logs cleanup

---

bin/phpunit-docker.sh

This PR changes the Docker image to run unit tests from `phpunit/phpunit` to a custom one hosted here: https://github.com/Automattic/phpunit-docker
**Please test it locally on your machine!**
We upgraded our unit tests engine from PHPUnit 6 to PHPUnit 7.
2. Run `bin/phpunit-docker.sh`

Upgrading to custom PHPUnit Docker image

---

.deployignore

Moving search-dev-tools babel config to ignored files
No need to publish this changelog

ignore babel config for deploy

---

wp-parsely.php

Include `global $parsely` reference to the global `Parsely` object instance that was missed in #2337. Unfortunately, I missed this line while copying the code from my dev environment and the `remove_action` and `remove_filters` lines don't perform their intended functions.
Plugin Updated: VIP Parse.ly Integration -- Hide plugin UI in some cases (take 2)
We made some behind-the-scenes changes that will help customers try Parse.ly on their sites more easily.
Same as #2337

add reference to global Parsely instance to loader

---

bin/phpunit-docker.sh

Makes it possible to run multiple arguments (previous code would enclose all in double quotes making it interpreted as a single argument)
This entry can be ignored.

Make filters passed to phpunit work

---

README.md
vip-jetpack/connection-pilot/class-jetpack-connection-controls.php

I found a couple of typos in a README and in a comment that weren't awesome to see. Fixed them here.
Internal tweaks on our docs.

Fix some typos in documentation

---

debug-bar.php

This PR updates the ElasticPress Debug bar to its latest version, `v2.1.0`.
We upgraded ElasticPress Debug Bar to 2.1.0.
2. Make sure Enterprise Search is enabled.
3. Perform a search and check its details through the Debug Bar.

Update ElasticPress Debug bar to 2.1.0

---

README.md
bin/create-release.sh

This PR adds a script for automating the release process. Instead of manually crafting the changelog, this script fetches the last PRs and automatically generates the release.
Adding internal tooling for releasing mu-plugins versions.

Adding release script

---

akismet.php
akismet/_inc/akismet.css
akismet/akismet.php
akismet/class.akismet.php
akismet/readme.txt

This PR updates Akismet to its latest version, 4.1.12.
- Fixed "Use of undefined constant" notice.
- Improved styling of alert notices.
2. Go to `wp-admin`, Akismet page. Check it correctly renders.
3. Go to plugins list and check Akismet version matches 4.1.12.

Updating Akismet to 4.1.12

---

vip-jetpack/connection-pilot/class-jetpack-connection-controls.php

We were getting a lot of failed VaultPress and Akismet connection attempts due to us flagging some Jetpack connections are good when in reality, they were only partially connected. What that meant is that the `wpcomvip` was missing the user token in WPCOM's side.
This PR adds an additional check on the procedure to evaluate the existing connection using that logic.
Improving Jetpack Connection Pilot checks for an active connection.

Adding additional checks on correct Jetpack Connection

---

search/includes/classes/queue/class-cron.php

Don't log the false returned from Queue Sweeper's schedule_batch_job because it means that the queue is empty, instead only log a WP_Error which would mean a cron event schedule failed.
#2382 introduced some logging which was intended to log unsuccessful event scheduling attempts but due to a logic error it was also logging on `FALSE` which signifies an empty queue. An empty queue is a valid state and should not be logged.
We've removed logging from Queue Sweeper when the queue is empty.

Don't log the false returned from Queue Sweeper's schedule_batch_job

---

.deployignore

`.lintstagedrc` should not be deployed
Do not deploy `.lintstagedrc`

Add .lintstagedrc into .deployignore

---

config/class-site-details-index.php

This PR just renames site details endpoint, as it was changed from `/sitedetails` to `/site-details`
We updated site details endpoint.

Update site details endpoint from /sitedetails to /site-details

---

package-lock.json
package.json

This PR takes care of Dependabot alerts and updates the JS dependencies to their latest versions.
* Update eslines from 1.1.0 to 2.0.0
* Update eslint from 5.16.0 to 7.32.0
2. Create a dummy commit with PHP files violating our code standards
3. Try to push it; observe that pre-commit/pre-push hooks work by reporting violations.

Update JavaScript dependencies

---

search/includes/classes/class-healthjob.php

Darn those butterfingers.
Fix typo of md_rand to mt_rand

Fix typo of md_rand to mt_rand

---

.circleci/config.yml

Yesterday there was a patch release of WordPress; this PR updates our Ci to use those latest revisions.
Use the latest WP revisions for CI.

Update CI to use the latest WP revisions

---

.github/ISSUE_TEMPLATE.md

Fix spelling in ISSUE_TEMPLATE.md
N/A
N/A

Fix spelling in ISSUE_TEMPLATE.md

---

search/includes/classes/class-health.php
tests/search/includes/classes/test-class-health.php

This PR adds type annotations to the files I have worked recently with so that static code analysis and code completion features work properly.
Add type annotations
N/A

Add type annotations so that static code analysis and code completion work properly

---

tests/search/includes/classes/queue/test-class-cron.php

This PR fixes unstable behavior of `Cron_Test::test_schedule_batch_job` — see #2605
Fix flaky tests.

Fix GH-2605

---

wp-cli/alloptions.php

This function was removed in #2585

Remove call to removed function

---

search/includes/classes/class-healthjob.php
tests/search/includes/classes/test-class-healthjob.php

If there is already an ongoing healthcheck job and it doesn't finish before the next one runs (i.e. it is scheduled within a minute of each other), we should not run it in parallel.
Add lock to healthcheck job to prevent parallel runs.
0) Check out PR
1) Shell in
2) `$es = new \Automattic\VIP\Search\Search();`
3) `$es->init();`
4) `$hj = new \Automattic\VIP\Search\HealthJob( $es );`
5) Enable healthchecks: `add_filter( 'enable_vip_search_healthchecks', '__return_true' );`
6) Set a lock manually: `$hj->set_healthcheck_lock();`
7) Check that `$hj->is_healthcheck_ongoing()` returns true
8) Attempt to run `$hj->check_health()` and check that it doesn't call `$hj->check_document_count_health()`.

Search: Add lock if there is already an ongoing healthcheck

---

lib/utils/class-context.php
tests/lib/environment/test-class-environment.php
tests/lib/helpers/test-environment.php
tests/lib/utils/context.php
tests/mock-constants.php

Run all Context tests in a single process.
Timings:
* before: 1.16 minutes
* after: 4.81 seconds

Refactor Context tests

---

wp-parsely-3.0/.github/workflows/deploy.yml
wp-parsely-3.0/.github/workflows/e2e-tests.yml
wp-parsely-3.0/CHANGELOG.md
wp-parsely-3.0/README.md
wp-parsely-3.0/src/class-parsely.php
wp-parsely-3.0/tests/Integration/OtherTest.php
wp-parsely-3.0/tests/Integration/TestCase.php
wp-parsely-3.0/wp-parsely.php

This PR pulls the final release of Parse.ly 3.0.
We upgraded Parse.ly from 3.0-RC2 to 3.0.0

Update Parse.ly to 3.0

---

.github/workflows/learn-github-actions.yml

Preparation for a automated release process.

github actions

---

.github/workflows/learn-github-actions.yml
.github/workflows/release-changelog.yml
bin/mark-production-changelog.js
bin/package-lock.json
bin/package.json

Adds an action. This action is however only triggerable after merge...

Changelog creator action

---

wp-parsely-3.0/CHANGELOG.md
wp-parsely-3.0/README.md
wp-parsely-3.0/src/class-parsely.php
wp-parsely-3.0/tests/Integration/OtherTest.php
wp-parsely-3.0/wp-parsely.php

This PR pulls the final release of Parse.ly 3.0.1.
We upgraded Parse.ly from 3.0.0 to 3.0.1

Update Parse.ly to 3.0.1

---

.github/workflows/e2e.yml

This PR fixes an issue where running the e2e workflow in Github actions does not install the specified version of WP. 
- [ X] This change works and has been tested locally (or has an appropriate fallback).
1. Make sure it passes in CI
I tested a manual run with these changes and used 5.9-beta2 as version in this run https://github.com/Automattic/vip-go-mu-plugins/actions/runs/1593407891

e2e:Allow specifying WP version for manual runs.

---

search/includes/classes/class-concurrency-limiter.php

Bump concurrency limit

---

000-pre-vip-config/requires.php
000-vip-init.php
001-cron.php
a8c-files.php
alloptions-limit.php
async-publish-actions.php
config/class-sync.php
files/class-api-client.php
lib/class-apc-cache-interceptor.php
logstash/class-logger.php
search/includes/classes/class-concurrency-limiter.php
search/includes/classes/class-health.php
search/includes/classes/class-search.php
search/includes/classes/queue/class-cron.php
search/includes/classes/queue/class-schema.php
security/class-private-sites.php
tests/bootstrap.php
two-factor.php
vip-helpers/vip-newrelic.php
vip-helpers/vip-notoptions-mitigation.php
vip-helpers/vip-utils.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
vip-jetpack/vip-jetpack.php
wp-cli.php

Use `Context::is_XXX()` instead of "manual" request type checks
`Context` class is now available in a single-site mode.

Use Context for request type checks

---

000-pre-vip-config/requires.php
000-vip-init.php
001-cron.php
a8c-files.php
alloptions-limit.php
async-publish-actions.php
config/class-sync.php
files/class-api-client.php
lib/class-apc-cache-interceptor.php
logstash/class-logger.php
search/includes/classes/class-concurrency-limiter.php
search/includes/classes/class-health.php
search/includes/classes/class-search.php
search/includes/classes/queue/class-cron.php
search/includes/classes/queue/class-schema.php
security/class-private-sites.php
tests/bootstrap.php
two-factor.php
vip-helpers/vip-newrelic.php
vip-helpers/vip-notoptions-mitigation.php
vip-helpers/vip-utils.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
vip-jetpack/vip-jetpack.php
wp-cli.php

Reverts Automattic/vip-go-mu-plugins#2748

Revert "Use Context for request type checks"

---

search/includes/classes/concurrency-limiter/class-object-cache-backend.php

* Add more logging;
* Return `true` if the counter cannot be incremented to allow the request to go to ES.

Add more logging

---

.github/workflows/e2e.yml

E2E workflow appears to be broken:
Trying to fix it.
Reason: https://github.com/Marak/colors.js/blob/master/lib/index.js#L16-L23
It will take some time until `vip` fixes its dependencies; this PR tries to fix the tests now.

Fix E2E workflow

---

.circleci/config.yml

5.5 => 5.5.8, 5.6 => 5.6.7, 5.7 => 5.7.5, 5.8 => 5.8.3

Update WP versions for CI

---

000-pre-vip-config/requires.php
000-vip-init.php
001-cron.php
a8c-files.php
alloptions-limit.php
async-publish-actions.php
config/class-sync.php
files/class-api-client.php
lib/class-apc-cache-interceptor.php
logstash/class-logger.php
search/includes/classes/class-concurrency-limiter.php
search/includes/classes/class-health.php
search/includes/classes/class-search.php
search/includes/classes/queue/class-cron.php
search/includes/classes/queue/class-schema.php
security/class-private-sites.php
two-factor.php
vip-helpers/vip-newrelic.php
vip-helpers/vip-notoptions-mitigation.php
vip-helpers/vip-utils.php
vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
vip-jetpack/vip-jetpack.php
wp-cli.php

Reverts Automattic/vip-go-mu-plugins#2758

Revert "Revert "Revert "Use Context for request type checks"""

---

admin-notice/README.md
admin-notice/admin-notice.php

Add admin notice for WP 5.9
WordPress 5.9 is scheduled to be released on January 25th. This change adds an admin notice to be shown on all environments running WordPress 5.8.
1) Start environment with WP 5.8 or 5.8.1
2) See the notice in the admin area

Add admin notice for WP 5.9

---

package-lock.json

* Bump @typescript-eslint/eslint-plugin from 5.7.0 to 5.9.1;
* Bump @typescript-eslint/parser from 5.7.0 to 5.9.1.

E2E: Update JS Dependencies

---

wp-parsely.php

Reverts Automattic/vip-go-mu-plugins#2772

Revert "Setting Parse.ly 3.0 as the default version"

---

wp-parsely-3.0/src/class-parsely.php

Reverts Automattic/vip-go-mu-plugins#2824
Revert to 2.6 as the default version

Revert "Fix empty name on Parse.ly 3.0"

---

wp-parsely-3.0/src/Integrations/class-amp.php
wp-parsely-3.0/src/class-parsely.php
wp-parsely.php

Reverts Automattic/vip-go-mu-plugins#2823

Revert "Fixing Parse.ly 3.0 release"

---

search/search-dev-tools/search-dev-tools.php

This PR fixes the shape of the data returned by the Search Dev Tools REST endpoint (we accidentally dropped `body` from the response).
Fix "Run Query" functionality

Fix the shape of the data returned by the REST endpoint

---

lib/feature/class-feature.php
search/includes/classes/class-search.php

Fully rollout `_search/_mget` query caching.
We've fully rolled out the search/get query caching to improve performance.

Fully roll out Enterprise Search query caching

---

search/includes/classes/class-search.php

Let's remove the logging we added for 401s in #2719 since looking at the logs, it hasn't occurred in the last 2.5 months.

Search: Remove logging for 401

---

search/includes/classes/class-concurrency-limiter.php

This PR defers the initialization of the Concurrency Limiter until the `init` event fires. This gives third-party plugins a chance to modify the limit and TTL parameters.
Defer Concurrency Limiter initialization until the `init` event fires.

Defer Concurrency Limiter initialization until 'init'

---

jetpack-10.6/CHANGELOG.md
jetpack-10.6/jetpack_vendor/i18n-map.php
jetpack-10.6/modules/search.php
jetpack-10.6/vendor/composer/jetpack_autoload_classmap.php

Pulls in this change: https://github.com/Automattic/jetpack/pull/22815

Upgrade Jetpack 10.6 to 10.6.1

---

lib/feature/class-feature.php

Continuation of #2892 which was at 25%.

Search: Roll out index re-building to 50% of non-production sites

---

search/includes/classes/class-settingshealthjob.php
search/includes/classes/class-versioningcleanupjob.php
search/includes/functions/utils.php

Sometimes data syncs can lead to weirdness with homeurls, so we should also log the application ID to avoid confusion in our alerting.

Search: Add FILES_CLIENT_SITE_ID to alerting

---

lib/feature/class-feature.php
search/includes/classes/class-versioningcleanupjob.php

Continuation of #2932 to 100%.

Search: Roll out index re-building to 100% of non-production sites

---

.github/workflows/e2e.yml

This changes the e2e tests to use a specific version of VIP cli. The latest version wasn't working so we'll hard code going forward and update over time.
Make sure e2e tests pass in CI

e2e: Move to node 14 to fix issues with VIP CLI

---

akismet.php

This PR comes after the last Akismet upgrade in #2950. Aside from upgrading the plugin's code, we need to upgrade the version number in our Akismet wrapper.

Updating Akismet version number

---

search/includes/functions/utils.php

Bugfix: Change the variable name to match the check

Search: Update variable name in vip_maybe_backfill_ep_option()

---

lib/feature/class-feature.php
search/includes/classes/class-versioningcleanupjob.php

Continuing the work of #2885, let's roll it out to 25% of production.

Search: Roll out deleting stale indexes to 25% of prod

---

search/includes/classes/class-settingshealthjob.php

Let's make the alert more explicit when re-building fails + some whitespacing changes.

Search: Make error message more explicit in build_new_index()

---

__tests__/e2e/lib/pages/published-page-page.ts
__tests__/e2e/lib/pages/published-post-page.ts

The default theme for WP changed and the selectors for some things we're testing changed as well.
This PR updates those selectors to get the tests passing again.
Make sure e2e tests pass in CI, with the exception of the Search test which is failing for unrelated issues

e2e- Fix e2e failures related to themes update

---

lib/feature/class-feature.php
search/includes/classes/class-versioningcleanupjob.php

Search: Roll out deleting stale inactive indexes to 100%

---

lib/feature/class-feature.php

Search: Roll out rebuilding indexes for 75% of non-production

---

lib/feature/class-feature.php
search/includes/classes/class-settingshealthjob.php

Search: Roll out rebuilding indexes to 100% of non-production

---

lib/feature/class-feature.php
search/includes/classes/class-settingshealthjob.php

Search: Index re-building for 10% of prod

---

search/includes/classes/class-search.php

Add alerting to see how often no origin DC is detected during mapping process.

Search: Add alerting to detect when no origin DC detected

---

lib/feature/class-feature.php
search/includes/classes/class-settingshealthjob.php

Finishing up #2998 and subsequent PRs.

Search: Roll out index re-building everywhere

---

.circleci/config.yml

Let's update our config.yml to match our current stacks.

CircleCI: Bump WP_VERSIONs

---

search/includes/functions/utils.php

Just wanting to remove the alerting since so far, it's been a false positive due to race conditions. So far, the option has been added each time.

Search: Do not alert on backfill of ep_feature_settings option

---

vip-helpers/class-wpcomvip-restrictions.php

Hotfix for CoAuthors plugin.
Add a hotfix for CoAuthor plugin hooks.

Validate parameter types in the userland, not in PHP

---

security/machine-user.php
security/password.php

Fix warnings that manifest themselves under some rare circumstances.
Related: #3059

Fix PHP warnings

---

config/class-site-details-index.php
tests/config/test-site-details-index.php

- Renaming `wporg_slug` to `slug`, as it turns out to be more than just wporg slugs since 3rd party plugins hook into the core transient.
- Sync a plugin's "marketplace" (main usefulness will be helping us tell if it's WPorg or not, but other could come in handy later on).
- Sync if there is an available update and what that new version is, via `has_update`.
- Sync the `download_link` if available.
Will remove the `wporg_slug` pieces in a separate step, once other systems are ready for the new data.
Indexes a plugin's slug, marketplace, next update version, and version download link if available.
Is kind of complicated to setup for a full end to end test on this (ping me in slack if interested). The unit tests …

SDI: Index additional plugin update data

---

akismet.php
akismet/akismet.php
akismet/class.akismet-admin.php
akismet/class.akismet.php
akismet/readme.txt
akismet/views/config.php
akismet/views/connect-jp.php
akismet/views/get.php
akismet/views/stats.php

This PR fetches the latest version of the Akismet plugin, 4.2.4.
We upgraded Akismet 4.2.2 to Akismet 4.2.4.
2. Make sure Jetpack and Akismet are enabled.
3. Check that the Akismet version is 4.2.4
4. Perform the viagra test.

Updating Akismet to 4.2.4

---

composer.json
composer.lock

Update:
* johnpbloch/wordpress-core (5.9.3 => 6.0.0)
* wp-phpunit/wp-phpunit (5.9.3 => 6.0.0)

Update PHP dev dependencies
